if(FParse::Param(FCommandLine::Get(),TEXT("LWAudio64Smoke"))){
 struct FState64{TArray<TWeakObjectPtr<UBoxComponent>> Walls;TWeakObjectPtr<UAudioComponent> Audio,Local;TWeakObjectPtr<ALWVehicle> Car;FVector Centre;double Started=0;};auto S=MakeShared<FState64>();
 Add(TEXT("64 acoustic room"),2,[this,S](ALWCharacter& P){
  P.NewGame();P.ClosePanels();P.bMenu=false;P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.bGod47=true;P.SetActorTickEnabled(false);P.World->SetActorTickEnabled(false);P.SetActorLocation(FVector(0,0,50000));S->Centre=P.Camera->GetComponentLocation();
  const FVector Positions[]={FVector(400,0,0),FVector(-400,0,0),FVector(0,400,0),FVector(0,-400,0),FVector(0,0,250),FVector(0,0,-150)};
  const FVector Extents[]={FVector(15,415,400),FVector(15,415,400),FVector(415,15,400),FVector(415,15,400),FVector(415,415,15),FVector(415,415,15)};
  for(int I=0;I<6;++I){auto* A=GetWorld()->SpawnActor<AActor>();auto* B=NewObject<UBoxComponent>(A);A->SetRootComponent(B);B->SetBoxExtent(Extents[I]);B->SetCollisionEnabled(ECollisionEnabled::QueryOnly);B->SetCollisionResponseToAllChannels(ECR_Block);B->RegisterComponent();A->SetActorLocation(S->Centre+Positions[I]);S->Walls.Add(B);}S->Started=GetWorld()->GetTimeSeconds();
 },[this](ALWCharacter& P){auto* A=GetWorld()->GetSubsystem<ULWAcoustics64>();Check(A&&A->GetRoomPreset()==2,TEXT("measured enclosed medium room reverb"));});
 V2->Steps.Last().Ready=[this,S](ALWCharacter&){return GetWorld()->GetTimeSeconds()-S->Started>=1.5;};
 Add(TEXT("64 exterior sound and local report"),1,[this,S](ALWCharacter& P){
  S->Audio=P.World->Sound(TEXT("CarEngine"),S->Centre+FVector(1000,0,0),.7f);
  S->Local=ULWAudioCatalog::PlaySlot(&P,TEXT("CarEngine"),S->Centre,.5f,1,false,P.World->Attenuation,P.World->LoudAttenuation,true);
 },[this,S](ALWCharacter& P){auto* A=S->Audio.Get();Check(A&&A->IsPlaying(),TEXT("world loop remains active"));if(A){Check(A->AttenuationOverrides.LPFFrequencyAtMin<2200,TEXT("outside sound muffled through room wall"));Check(FMath::IsNearlyEqual(A->VolumeMultiplier,.7f*ULWAudioCatalog::GetDefaultCatalog()->Slots.FindChecked(TEXT("CarEngine")).Volume,.01f),TEXT("environment does not overwrite caller volume"));}auto* L=S->Local.Get();Check(L&&!L->AttenuationOverrides.bAttenuate&&!L->AttenuationOverrides.bSpatialize,TEXT("local report retains stable positional bypass"));Check(L&&L->AttenuationOverrides.ManualReverbSendLevel>0,TEXT("local report feeds room reflections"));});
 Add(TEXT("64 doorway opens"),1,[S](ALWCharacter&){S->Walls[0]->SetCollisionEnabled(ECollisionEnabled::NoCollision);},[this,S](ALWCharacter&){Check(S->Audio.IsValid()&&S->Audio->AttenuationOverrides.LPFFrequencyAtMin>15000,TEXT("opening path restores bandwidth dynamically"));});
 Add(TEXT("64 cabin muffling"),1.5,[S,this](ALWCharacter& P){for(auto B:S->Walls)if(B.IsValid())B->SetCollisionEnabled(ECollisionEnabled::NoCollision);auto* V=GetWorld()->SpawnActor<ALWVehicle>();V->SetActorTickEnabled(false);V->SetActorLocation(P.GetActorLocation());S->Car=V;P.Vehicle=V;},[this,S](ALWCharacter&){auto* A=GetWorld()->GetSubsystem<ULWAcoustics64>();Check(A->GetRoomPreset()==0,TEXT("vehicle selects dry cabin reflections"));Check(S->Audio.IsValid()&&S->Audio->AttenuationOverrides.LPFFrequencyAtMin<2000,TEXT("exterior sound muffles inside vehicle"));});
 Add(TEXT("64 outside and cleanup"),1.5,[S](ALWCharacter& P){P.Vehicle=nullptr;},[this,S](ALWCharacter& P){Check(GetWorld()->GetSubsystem<ULWAcoustics64>()->GetRoomPreset()==-1,TEXT("outdoors removes room reverb"));Check(S->Audio.IsValid()&&S->Audio->AttenuationOverrides.LPFFrequencyAtMin>15000,TEXT("leaving cabin restores bandwidth"));if(S->Audio.IsValid())S->Audio->Stop();if(S->Local.IsValid())S->Local->Stop();for(auto B:S->Walls)if(B.IsValid())B->GetOwner()->Destroy();if(S->Car.IsValid())S->Car->Destroy();});
 return;
}
