if(FParse::Param(FCommandLine::Get(),TEXT("LWArsenal62Smoke"))){
 struct FState62{TWeakObjectPtr<ALWWorldObject> Bench;FGuid Weapon;};auto State=MakeShared<FState62>();
 Add(TEXT("62 assets and bench"),2,[this,State](ALWCharacter& P){P.NewGame();Cast<APlayerController>(P.Controller)->ConsoleCommand(TEXT("r.ScreenPercentage 100"));P.ClosePanels();P.bMenu=false;P.bSafehouse=false;P.SetMenuInput(false);P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.Inventory.Empty();auto G=LWItems::Make(TEXT("rifle"));G.Slot=TEXT("Primary");G.Chamber=1;P.Inventory.Add(G);P.ActiveWeaponId=G.Id;State->Weapon=G.Id;P.Equip(6);for(FName Id:{FName(TEXT("att_reflex")),FName(TEXT("att_brake62")),FName(TEXT("att_heavy62")),FName(TEXT("att_precision62")),FName(TEXT("att_tape62")),FName(TEXT("att_laser"))}){auto I=LWItems::Make(Id);LWItems::Place(P.Inventory,I,12,LWItems::InventoryHeight(P.Inventory));}auto* S=GetWorld()->SpawnActor<ALWWorldObject>(P.GetActorLocation()+FVector(100,0,0),FRotator::ZeroRotator);S->Configure(P.World,ELWObjectKind::Furniture,TEXT("bench62"));S->SetFurniture(TEXT("workbench"));State->Bench=S;P.OpenWorkbench39(S);auto* B=P.Workbench39.Get();Check(B&&B->Load(G.Id),TEXT("gunsmith opens weapon draft"));Check(B&&!B->SetCamo62(9),TEXT("mystic locked before challenge"));for(int W=0;W<21;W++)Check(P.World->Mesh(FName(*FString::Printf(TEXT("Mystic62_%02d"),W)))!=nullptr,TEXT("mystic replacement mesh exists"));},[this](ALWCharacter& P){CaptureV2(TEXT("Arsenal62_Gunsmith"));});
 Add(TEXT("62 attachment transactions"),1,[this](ALWCharacter& P){auto* B=P.Workbench39.Get();if(!B)return;TArray<FGuid> Mods;for(auto& I:B->Draft.Bank)if(LWItems::Def(I.Definition).Category==TEXT("Attachment"))Mods.Add(I.Id);for(int I=0;I<5;I++)Check(B->Add(Mods[I]),TEXT("install compatible attachment"));Check(!B->Add(Mods[5]),TEXT("sixth attachment rejected"));Check(B->Draft.Gun.Attachments.Num()==5,TEXT("five attachment limit"));B->Undo();Check(B->Draft.Gun.Attachments.Num()==4,TEXT("undo attachment transaction"));B->Undo(true);Check(B->Draft.Gun.Attachments.Num()==5,TEXT("redo attachment transaction"));Check(B->Apply(),TEXT("apply preserves weapon identity and ammo"));Check(P.ActiveGun()&&P.ActiveGun()->Chamber==1&&P.ActiveGun()->Attachments.Num()==5,TEXT("live inventory receives loadout"));P.Attack();Check(P.ActiveGun()->Chamber==1,TEXT("UI click cannot fire"));B->Load(P.ActiveWeaponId);B->Tab62=1;},[this](ALWCharacter& P){CaptureV2(TEXT("Arsenal62_Attachments"));});
 Add(TEXT("62 mystic challenge"),3,[this](ALWCharacter& P){auto* B=P.Workbench39.Get();if(!B)return;P.RPG.WeaponKills62.Add(TEXT("rifle"),249);LWArsenal62::Credit(&P,TEXT("rifle"),true,false);Check(LWArsenal62::Unlocked(&P,TEXT("rifle"),9),TEXT("250 kills unlock this weapon mystic"));Check(!LWArsenal62::Unlocked(&P,TEXT("smg"),9),TEXT("challenge progress does not leak to other weapons"));Check(B->SetCamo62(9),TEXT("unlocked mystic equips"));B->Tab62=2;},[this](ALWCharacter& P){CaptureV2(TEXT("Arsenal62_Mystic"));});
 Add(TEXT("62 extreme slugger"),3,[this,State](ALWCharacter& P){auto* B=P.Workbench39.Get();if(!B)return;B->Apply();P.ClosePanels();P.GiveItem(TEXT("bat"));P.RPG.WeaponKills62.Add(TEXT("bat"),250);P.OpenWorkbench39(State->Bench.Get());B=P.Workbench39.Get();for(const auto& I:P.Inventory)if(I.Definition==TEXT("bat")){B->Load(I.Id);break;}Check(B->SetCamo62(9),TEXT("Extreme Slugger equipped"));B->Tab62=2;},[this](ALWCharacter& P){CaptureV2(TEXT("Arsenal62_Slugger"));});
 Add(TEXT("62 manual save"),2,[this](ALWCharacter& P){P.ClosePanels();P.DrainSave40();P.Money=1262;P.bMenu=true;P.OpenSaves62(true);Check(P.ManualSave62(LWSaves62::Manual(20)),TEXT("manual save queued"));},[this](ALWCharacter& P){P.DrainSave40();auto* S=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromSlot(LWSaves62::Manual(20),0));Check(S&&S->Money==1262,TEXT("manual slot contains chosen snapshot"));P.OpenSaves62(false);CaptureV2(TEXT("Arsenal62_SaveMenu"));});
 Add(TEXT("62 manual restore"),2,[this](ALWCharacter& P){P.Money=1;Check(P.LoadSlot62(LWSaves62::Manual(20)),TEXT("manual slot loads"));Check(P.Money==1262,TEXT("manual load restores money"));Check(P.RPG.WeaponKills62.FindRef(TEXT("rifle"))==250,TEXT("challenge progress survives disk load"));Check(P.ActiveGun()&&P.ActiveGun()->Camo62==9,TEXT("mystic survives disk load"));Check(P.SaveSlot40()!=LWSaves62::Manual(20),TEXT("later autosaves cannot overwrite manual slot"));});
 return;
}
