void ALWGameMode::BuildCasinoSmoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,90,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWChunk> C;TWeakObjectPtr<ALWSlotMachine> Slot;TWeakObjectPtr<ALWVehicle> Car;};auto S=MakeShared<FState>();
 Add(TEXT("resort construction"),3,[this,S](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;P.Health=10000;P.World->TimeOfDay=12;LWV2Teleport(P,FVector(200000,195000,15130));P.Flashlight->SetVisibility(false);auto* C=GetWorld()->SpawnActor<ALWChunk>();S->C=C;LWGen::FSite Site;Site.Id=212121;Site.Type=21;Site.Size=LWPlaces::Size(21);Site.Position=FVector2D(200000,200000);Site.Friendly=true;C->Building(P.World,Site);C->SetActorLocation(FVector(0,0,15000));for(auto& A:C->Residents)if(A)A->AddActorWorldOffset(FVector(0,0,15000));int Slots=0,Tables=0,Beds=0,Supercars=0,Cars=0;
 for(auto& A:C->Residents){if(auto* O=Cast<ALWSlotMachine>(A)){Slots++;S->Slot=O;}if(Cast<ALWCardTable>(A))Tables++;if(auto* O=Cast<ALWWorldObject>(A))Beds+=O->UseType==TEXT("bed");if(auto* V=Cast<ALWVehicle>(A)){Cars++;Supercars+=FName(V->Spec().Id)==TEXT("supercar");}}
 Check(Slots==168,TEXT("two floors of 168 playable slots"));Check(Tables==33,TEXT("33 playable card tables including VIP"));Check(Beds>=33,TEXT("hotel rooms and VIP bed are interactive"));Check(Cars>=6&&Supercars>Cars/3,TEXT("resort parking favors supercars"));
 for(auto& Pair:C->Batches)Check(Pair.Value->GetStaticMesh()!=nullptr,TEXT("resort art resolves"));
 for(int F=0;F<7;F++){FHitResult H;FCollisionQueryParams Q;FVector At(203400,202000,15036+F*420);Check(GetWorld()->LineTraceSingleByChannel(H,At+FVector(0,0,50),At-FVector(0,0,20),ECC_Visibility,Q)&&FMath::Abs(H.ImpactPoint.Z-At.Z)<3,TEXT("all seven floors have walkable surfaces"));}
 for(int F=0;F<6;F++)for(int I=0;I<12;I++)for(int Flight=0;Flight<2;Flight++){float Z=15036+F*420+(I+1)*17.5f+(Flight?210:0);FVector At(200000+(Flight?4660:3975),202000+(Flight?-36-(I+.5f)*32:-420+(I+.5f)*32),Z);FHitResult H,Head;FCollisionQueryParams Q;Check(GetWorld()->LineTraceSingleByChannel(H,At+FVector(0,0,40),At-FVector(0,0,15),ECC_Visibility,Q)&&FMath::Abs(H.ImpactPoint.Z-Z)<3&&!GetWorld()->LineTraceSingleByChannel(Head,At+FVector(0,0,20),At+FVector(0,0,196),ECC_Visibility,Q),TEXT("resort stair tread and headroom"));}
 LWV2Teleport(P,FVector(200000,197000,15140));P.Controller->SetControlRotation(FRotator(0,90,0));P.World->TickWeather(0,&P);
 },[this](ALWCharacter&){CaptureV2(TEXT("Casino21_Entrance"));});
 Add(TEXT("slot accounting"),2.5,[this,S](ALWCharacter& P){auto* M=S->Slot.Get();LWV2Teleport(P,M->GetActorLocation()+FVector(0,-160,100));P.Controller->SetControlRotation(FRotator(0,90,0));P.Money=100;M->Use(&P);Check(P.Money==90+M->Award,TEXT("slot charges wager and credits payout once"));int Balance=P.Money;M->Use(&P);Check(P.Money==Balance,TEXT("spin cannot be double-clicked"));Check(P.World->PropStates.FindRef(M->RecordId)>0,TEXT("slot sequence persists"));},[this](ALWCharacter&){CaptureV2(TEXT("Casino21_Slots"));});
 for(int F:{0,2,3,4,6})Add(FString::Printf(TEXT("resort floor %d"),F),1.5,[S,F](ALWCharacter& P){LWV2Teleport(P,FVector(199000,202000,15135+F*420));P.Controller->SetControlRotation(FRotator(0,F==0?50:120,0));},[this,F](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Casino21_Floor%d"),F));});
 Add(TEXT("supercar"),4,[this,S](ALWCharacter& P){if(S->C.IsValid())S->C->Destroy();auto* C=GetWorld()->SpawnActor<ALWChunk>();S->C=C;C->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(6000,6000,20));LWV2Teleport(P,FVector(20550,19500,5200));FLWVehicleRecord V;V.Model=TEXT("supercar");V.VIN=FGuid::NewGuid();V.Position=FVector(20000,20000,5075);V.Unlocked=true;P.World->Vehicles.Add(TEXT("super21"),V);auto* Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("super21"),V.Position));S->Car=Car;Check(Car&&Car->Body->GetStaticMesh()==P.World->Mesh(TEXT("SupercarV21")),TEXT("supercar uses rebuilt body"));if(!Car)return;for(auto& Wheel:Car->Wheels)Check(Wheel->GetStaticMesh()==P.World->Mesh(TEXT("SuperWheelV21")),TEXT("supercar uses independent new wheels"));LWV2Teleport(P,FVector(20550,19500,5200));P.Controller->SetControlRotation(FRotator(-8,140,0));},[this](ALWCharacter&){CaptureV2(TEXT("Supercar21_Exterior"));});
 Add(TEXT("supercar cockpit"),2,[this,S](ALWCharacter& P){LWV2Teleport(P,S->Car->GetActorLocation()+FVector(0,-220,0));Check(S->Car->Enter(&P),TEXT("rebuilt supercar remains drivable"));S->Car->Record()->Hotwired=true;S->Car->Ignition();S->Car->Control(TEXT("lights"));S->Car->Control(TEXT("wipers"));Check(S->Car->EngineOn&&S->Car->Headlights&&S->Car->WipersOn,TEXT("ignition headlights and wipers remain functional"));},[this,S](ALWCharacter& P){CaptureV2(TEXT("Supercar21_Cockpit"));});
 Add(TEXT("supercar acceleration"),1.5,[S](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::W,IE_Pressed,1.f));},[this,S](ALWCharacter& P){Check(S->Car->Speed>30,TEXT("supercar accelerates under player input"));Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::W,IE_Released,0.f));});
 Add(TEXT("supercar brakes"),1.2,[](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::SpaceBar,IE_Pressed,1.f));},[this,S](ALWCharacter& P){Check(FMath::Abs(S->Car->Speed)<10,TEXT("supercar brakes to a stop"));Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::SpaceBar,IE_Released,0.f));S->Car->Exit(true);S->Car->Destroy();S->C->Destroy();});
}
