if(FParse::Param(FCommandLine::Get(),TEXT("LWCampaign77Smoke"))){
 auto Grip77=MakeShared<FVector2D>(0,0);
 auto Go77=[](ALWCharacter& P,FName Id){auto* D=ALWCampaign76::Ensure(&P);D->Pause();P.ClosePanels();D->State().Paused=false;D->State().Scene=NAME_None;D->SetActorTickEnabled(true);D->SetStage(Id);if(LWCampaign76::Stage(Id)->Site==TEXT("canada")){D->State().Values.Add(TEXT("humanitarian_permit"),1);P.RPG.Canada68.Cleared=true;}P.SetActorLocation(D->At(FVector(0,-420,92)),false,nullptr,ETeleportType::TeleportPhysics);P.World->Stream(P.GetActorLocation(),true);D->Spawn();P.Controller->SetControlRotation(FRotator(0,90,0));};
 if(FParse::Param(FCommandLine::Get(),TEXT("LWCampaign77Crowds"))){
  Add(TEXT("Crowd77 setup"),3,[](ALWCharacter& P){P.NewGame();P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.bGod47=true;ALWCampaign76::Ensure(&P)->Begin(true);});
  for(FName Stage:{FName(TEXT("meridian_inside")),FName(TEXT("resistance_exit")),FName(TEXT("final_evacuation"))}){
   if(FParse::Param(FCommandLine::Get(),TEXT("LWCampaign77Labor"))&&Stage!=TEXT("resistance_exit"))continue;
   Add(FString::Printf(TEXT("Crowd77 %s evacuation and reconstruction"),*Stage.ToString()),105,[Go77,this,Stage](ALWCharacter& P){
    Go77(P,Stage);auto* D=P.Campaign76.Get();D->Pause();D->State().Scene=NAME_None;D->State().Decisions.Add(FName(*FString::Printf(TEXT("arrived_%s"),*Stage.ToString())));D->Effects({TEXT("family_corridor"),TEXT("labor_exit_open")});
    for(auto E:D->Enemies)if(E)E->SetActorTickEnabled(false);
    P.SetActorLocation(D->At(FVector(650,-1900,92)),false,nullptr,ETeleportType::TeleportPhysics);
    V2->Observe=[this,Elapsed=0.f,Reloaded=false,Stage](ALWCharacter& Q)mutable{
     Elapsed+=Q.GetWorld()->GetDeltaSeconds();auto* R=Q.Campaign76.Get();
     if(!Reloaded&&Elapsed>25){Reloaded=true;int Before=0;for(const auto& E:R->Production->Crowd)Before+=E.Next;R->Clear();R->Spawn();for(auto E:R->Enemies)if(E)E->SetActorTickEnabled(false);int After=0;for(const auto& E:R->Production->Crowd)After+=E.Next;Check(Before>0&&After==Before,TEXT("crowd reconstruction retains individual route cursors"));
      if(Stage==TEXT("resistance_exit")&&R->Production->Crowd.Num()){FDamageEvent Damage;R->Production->Crowd.Last().Person->TakeDamage(1000,Damage,nullptr,nullptr);}
     }
    };
   },[this,Stage](ALWCharacter& P){V2->Observe={};auto* D=P.Campaign76.Get();int Survivors=0,Reached=0;for(const auto& E:D->Production->Crowd)if(E.Person&&!E.Person->bDead){Survivors++;Reached+=E.Complete;UE_LOG(LogTemp,Display,TEXT("C77_CROWD %s node=%d at=%s"),*E.Person->Person.ToString(),E.Next,*E.Person->GetActorLocation().ToString());}Check(Survivors>0&&Survivors==Reached,TEXT("every surviving civilian reaches safety after reconstruction"));Check(D->State().Values.FindRef(TEXT("crowd_clear77"))!=0,TEXT("physical evacuation releases the mission tally"));if(Stage==TEXT("resistance_exit"))Check(D->State().Values.FindRef(TEXT("civilian_losses"))>0,TEXT("a casualty is counted without blocking the survivors"));CaptureV2(*FString::Printf(TEXT("Campaign77_%s_Crowd"),*Stage.ToString()));});
  }
  for(auto& Step:V2->Steps)Step.Ready=[Frames=0](ALWCharacter&)mutable{return ++Frames>=45;};
  return;
 }
 Add(TEXT("Production77 campaign setup"),3,[](ALWCharacter& P){P.NewGame();P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.bGod47=true;P.bCrust=false;P.Flashlight->SetVisibility(false);ALWCampaign76::Ensure(&P)->Begin(true);},[this](ALWCharacter& P){Check(P.Campaign76&&P.Campaign76->Production,TEXT("production component exists"));for(FName Mesh:{FName(TEXT("CarrierHull77")),FName(TEXT("Ferry77")),FName(TEXT("Case77")),FName(TEXT("SchoolDesk77"))})Check(P.World->Mesh(Mesh)!=nullptr,*FString::Printf(TEXT("%s imported"),*Mesh.ToString()));});
 Add(TEXT("Production77 anchored heater repair"),15,[Go77](ALWCharacter& P){Go77(P,TEXT("bell_lights"));auto* D=P.Campaign76.Get();D->State().Scene=NAME_None;D->State().Decisions.Add(TEXT("arrived_bell_lights"));P.SetActorLocation(D->At(FVector(-210,-50,92)),false,nullptr,ETeleportType::TeleportPhysics);D->Use(TEXT("heater"));},[this](ALWCharacter& P){Check(P.Campaign76->State().Values.FindRef(TEXT("heater_fixed"))!=0,TEXT("real repair completes after performer reaches the prop"));CaptureV2(TEXT("Campaign77_Repair"));});
 Add(TEXT("Production77 individual medical treatment"),20,[Go77,this](ALWCharacter& P){Go77(P,TEXT("bell_attack"));auto* D=P.Campaign76.Get();D->State().Scene=NAME_None;D->Effects({TEXT("medical_ready")});for(auto& E:D->Enemies)if(E)E->SetActorTickEnabled(false);P.SetActorLocation(D->At(FVector(400,40,92)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation(FRotator(-12,45,0));Check(D->Use(TEXT("treat_lena")),TEXT("treatment can be started at the bedside"));V2->Observe=[this,Done=false,NextLog=0.f](ALWCharacter& Q)mutable{auto* R=Q.Campaign76->Production.Get();if(Q.GetWorld()->GetTimeSeconds()>NextLog){NextLog=Q.GetWorld()->GetTimeSeconds()+2;if(auto* N=R->Performer.Get())UE_LOG(LogTemp,Display,TEXT("C77_TREAT action=%s time=%.2f ready=%d actor=%s goal=%s remaining=%.1f"),*Q.Campaign76->WorkAction.ToString(),R->PerformanceTime,R->WorkReady,*N->GetActorLocation().ToString(),*N->Mark.ToString(),FVector::Dist2D(N->GetActorLocation(),N->Mark));}if(!Done&&R->Performance==TEXT("treatment")&&R->PerformanceTime>1.5f){Done=true;CaptureV2(TEXT("Campaign77_Treatment"));}};},[this](ALWCharacter& P){V2->Observe={};Check(P.Campaign76->State().Values.FindRef(TEXT("lena_treated"))!=0,TEXT("bedside treatment completes with its individual performance"));CaptureV2(TEXT("Campaign77_TreatmentEnd"));});
 Add(TEXT("Production77 restraint scene"),6,[Go77](ALWCharacter& P){Go77(P,TEXT("guard_convoy"));auto* D=P.Campaign76.Get();P.SetActorLocation(D->At(FVector(1190,345,120)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation(FRotator(-6,180,0));D->Show(TEXT("convoy_restraints"));},[this](ALWCharacter& P){auto* D=P.Campaign76.Get();auto* N=D->People.FindRef(TEXT("tomas")).Get();Check(N&&N->LifeAnimation->PerformancePose77==1,TEXT("Tomas uses restrained seating"));Check(D->Production->Cuffs&&D->Production->Cuffs->IsVisible(),TEXT("restraints are visible physical props"));CaptureV2(TEXT("Campaign77_Restraints"));});
 Add(TEXT("Production77 tracing office and case handoff"),12,[Go77,this,Grip77](ALWCharacter& P){Go77(P,TEXT("canada_investigate"));auto* D=P.Campaign76.Get();P.SetActorLocation(D->At(FVector(300,150,92)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation((D->At(FVector(70,410,140))-P.Camera->GetComponentLocation()).Rotation());D->Show(TEXT("world_records"));V2->Observe=[this,Grip77](ALWCharacter& Q){auto* R=Q.Campaign76->Production.Get();if(R->Performance==TEXT("handoff")&&R->PerformanceTime>1.1f&&R->PerformanceTime<2.8f){for(auto N:{R->Performer.Get(),R->Recipient.Get()})if(N)for(int Side=0;Side<2;Side++)if(N->LifeAnimation->HandWeights77[Side]>.95){Grip77->X=FMath::Max(Grip77->X,FVector::Dist(N->LifeAnimation->HandPosition77(Side),N->LifeAnimation->HandTargets77[Side]));Grip77->Y++;}if(Grip77->Y==2)CaptureV2(TEXT("Campaign77_Contact"));}};},[this,Grip77](ALWCharacter& P){auto* D=P.Campaign76.Get();V2->Observe={};UE_LOG(LogTemp,Display,TEXT("C77_CONTACT max_cm=%.2f samples=%.0f"),Grip77->X,Grip77->Y);Check(Grip77->Y>0&&Grip77->X<5,TEXT("animated wrists meet the case within 5cm"));Check(!D->Enemies.Num(),TEXT("Canadian tracing office remains safe"));Check(FVector::Dist2D(P.GetActorLocation(),D->At(FVector::ZeroVector))<1000,TEXT("tracing scene is inside Northbank"));Check(D->Production->Performance.IsNone(),TEXT("case performance finishes without a dialogue deadlock"));CaptureV2(TEXT("Campaign77_Tracing"));});
 Add(TEXT("Production77 canal machinery"),13,[Go77](ALWCharacter& P){Go77(P,TEXT("rome_repair"));auto* D=P.Campaign76.Get();D->Effects({TEXT("terminal_working")});P.SetActorLocation(D->At(FVector(450,-1050,160)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation(FRotator(-8,35,0));},[this](ALWCharacter& P){auto* R=P.Campaign76->Production.Get();Check(R->Mechanisms.Num()==4,TEXT("canal has animated gates gear and winch"));Check(R->MechanismPhase>.9f,TEXT("repaired terminal opens gates over time"));CaptureV2(TEXT("Campaign77_Canal"));});
 Add(TEXT("Production77 residence and school"),4,[Go77](ALWCharacter& P){Go77(P,TEXT("meridian_inside"));auto* D=P.Campaign76.Get();P.SetActorLocation(D->At(FVector(1450,-2900,92)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation(FRotator(-5,30,0));},[this](ALWCharacter& P){Check(P.Campaign76->Production->Crowd.Num()==10,TEXT("residential evacuation has individual civilians"));CaptureV2(TEXT("Campaign77_School"));});
 Add(TEXT("Production77 crowded evacuation"),100,[](ALWCharacter& P){auto* D=P.Campaign76.Get();D->Pause();D->State().Scene=NAME_None;D->Effects({TEXT("family_corridor")});P.SetActorLocation(D->At(FVector(650,-2700,92)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation(FRotator(0,90,0));},[this](ALWCharacter& P){auto* R=P.Campaign76->Production.Get();int Reached=0;for(const auto& E:R->Crowd){Reached+=E.Complete;UE_LOG(LogTemp,Display,TEXT("C77_CROWD %s node=%d at=%s"),*E.Person->Person.ToString(),E.Next,*E.Person->GetActorLocation().ToString());}Check(Reached==R->Crowd.Num(),TEXT("all ten civilians route through real doors to safety"));CaptureV2(TEXT("Campaign77_Evacuation"));});
 Add(TEXT("Production77 intact executive office"),4,[Go77](ALWCharacter& P){Go77(P,TEXT("carrier_hall"));auto* D=P.Campaign76.Get();P.SetActorLocation(D->At(FVector(0,340,282)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation((D->Carrier->GetActorTransform().TransformPosition(FVector(0,170,295))-P.Camera->GetComponentLocation()).Rotation());},[this](ALWCharacter& P){auto* D=P.Campaign76.Get();Check(D->Carrier&&D->Carrier->Body->GetStaticMesh()->GetName()==TEXT("SM_CarrierHull77"),TEXT("Carrier uses the bespoke mesh"));CaptureV2(TEXT("Campaign77_Carrier"));});
 Add(TEXT("Production77 authored damage sequence"),12,[Go77](ALWCharacter& P){Go77(P,TEXT("carrier_battle"));auto* D=P.Campaign76.Get();D->State().CarrierDamage77=0;D->Effects({TEXT("carrier_feed_cut"),TEXT("carrier_trapped"),TEXT("carrier_disabled")});D->Show(TEXT("broken_office"));P.SetActorLocation(D->At(FVector(650,-250,150)),false,nullptr,ETeleportType::TeleportPhysics);P.Controller->SetControlRotation((D->Carrier->GetActorLocation()+FVector(0,0,310)-P.Camera->GetComponentLocation()).Rotation());},[this](ALWCharacter& P){auto* D=P.Campaign76.Get();Check(D->State().CarrierDamage77>=10,TEXT("damage timeline finishes"));Check(D->CarrierShutter->GetRelativeLocation().Y<-600&&D->CarrierShutter->GetRelativeLocation().Z<60,TEXT("released office shutter falls clear of the entrance"));Check(D->Production->WreckPanels.Num()==4&&D->Production->WreckPanels[0]->IsVisible(),TEXT("authored torn panels replace released armor"));Check(D->CarrierShutter->GetCollisionEnabled()==ECollisionEnabled::NoCollision,TEXT("released shutter cannot block the stair"));CaptureV2(TEXT("Campaign77_BrokenOffice"));});
 Add(TEXT("Production77 ferry departure"),4,[Go77](ALWCharacter& P){Go77(P,TEXT("crossing_ferry"));auto* D=P.Campaign76.Get();D->Effects({TEXT("entry_route=3"),TEXT("humanitarian_permit"),TEXT("crossing_open"),TEXT("group_at_cover")});D->SetStage(TEXT("canada_arrival"));if(D->Production->Boat)P.SetActorLocation(D->Production->Boat->GetActorTransform().TransformPosition(FVector(0,-350,113)),false,nullptr,ETeleportType::TeleportPhysics);},[this](ALWCharacter& P){Check(P.Campaign76->State().Sailing77,TEXT("ferry route sails before Toronto transfer"));Check(P.RPG.Canada68.Escrow.Num()>0,TEXT("weapons are processed before crossing"));CaptureV2(TEXT("Campaign77_Ferry"));});
 Add(TEXT("Production77 moving-deck traversal"),25,[this](ALWCharacter& P){V2->Observe=[this](ALWCharacter& P2){auto* D=P2.Campaign76.Get();if(!D||!D->State().Sailing77||!D->Production->Boat)return;auto* B=D->Production->Boat.Get();const float T=D->State().FerrySeconds77;const FVector Local=B->GetActorTransform().InverseTransformPosition(P2.GetActorLocation());if(T<14&&Local.Y<130)P2.AddMovementInput(B->GetActorRightVector(),.4f);else if(T>=14&&Local.Y>-450)P2.AddMovementInput(-B->GetActorRightVector(),.4f);};},[this](ALWCharacter& P){V2->Observe={};auto* B=P.Campaign76->Production->Boat.Get();if(B){const auto Local=B->GetActorTransform().InverseTransformPosition(P.GetActorLocation());Check(FMath::Abs(Local.X)<290&&Local.Z>60&&Local.Z<220,TEXT("walking passenger remains supported while sailing"));}CaptureV2(TEXT("Campaign77_Underway"));auto* D=P.Campaign76.Get();if(D->State().Sailing77){const auto Saved=D->State();const FTransform Before=D->Production->Boat->GetActorTransform();D->Production->Clear();D->State()=Saved;D->Production->RestoreSailing();Check(D->Production->Boat&&D->Production->Boat->GetActorLocation().Equals(Before.GetLocation(),.1),TEXT("vessel reconstructs at saved journey time"));Check(D->State().FerrySeconds77==Saved.FerrySeconds77,TEXT("reconstruction does not restart the crossing"));}});
 Add(TEXT("Production77 crossing arrival"),90,[](ALWCharacter& P){},[this](ALWCharacter& P){Check(P.Campaign76->State().Values.FindRef(TEXT("ferry_landed77"))!=0,TEXT("ferry completes the continuous journey"));Check(P.Campaign76->State().Stage==TEXT("canada_arrival"),TEXT("Ontario landing connects to Toronto reception"));Check(!P.Campaign76->State().Sailing77,TEXT("travel state clears at arrival"));CaptureV2(TEXT("Campaign77_Arrival"));});
 if(FParse::Param(FCommandLine::Get(),TEXT("LWCampaign77Treatment")))V2->Steps.SetNum(3);
 for(auto& Step:V2->Steps){Step.Ready=[Frames=0](ALWCharacter&)mutable{return ++Frames>=45;};}
 return;
}
