if(FParse::Param(FCommandLine::Get(),TEXT("LWCanada68Smoke"))){
 Add(TEXT("68 passport and customs"),1,[this](ALWCharacter& P){
  P.NewGame();P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.SetActorTickEnabled(false);P.ClosePanels();P.bMenu=false;P.bSafehouse=false;P.bGod47=true;UGameplayStatics::SetGamePaused(&P,false);P.SetMenuInput(false);P.GetCharacterMovement()->DisableMovement();
  P.SetActorLocation(FVector(LWBorder51::North-1400,5500,110));P.World->Stream(P.GetActorLocation(),true);P.Money=999999;
  Check(!LWCanada68::BuyPassport(&P)&&P.Money==999999,TEXT("insufficient credits cannot buy passport"));P.Money=1000025;Check(LWCanada68::BuyPassport(&P)&&P.Money==25,TEXT("passport costs exactly one million"));Check(LWCanada68::BuyPassport(&P)&&P.Money==25,TEXT("passport cannot charge twice"));
  const auto Before=P.Inventory;Check(LWCanada68::Deposit(&P)&&LWCanada68::Authorized(&P),TEXT("customs grants entry after storing weapons"));Check(!P.Inventory.ContainsByPredicate([](const auto& I){return LWItems::Def(I.Definition).Category==TEXT("Weapon");}),TEXT("weapons removed from carried equipment"));Check(P.RPG.Canada68.Escrow.Num()>=2,TEXT("crowbar and revolver held at customs"));
  LWCanada68::Reclaim(&P);for(const auto& I:Before)Check(P.Inventory.ContainsByPredicate([&](const auto& X){return X.Id==I.Id&&X.Definition==I.Definition&&X.Cylinder==I.Cylinder&&X.Attachments.OrderIndependentCompareEqual(I.Attachments);}),TEXT("customs returns exact weapon state and identity"));Check(P.RPG.Canada68.Escrow.IsEmpty()&&!LWCanada68::Authorized(&P),TEXT("collection revokes clearance for next visit"));
  ALWBorderGuard51* G=nullptr;for(TActorIterator<ALWBorderGuard51> I(GetWorld());I;++I)if(!I->Mech51){G=*I;break;}Check(G!=nullptr,TEXT("checkpoint has a human officer"));if(G){P.SetActorLocation(G->GetActorLocation()+FVector(-140,0,0));G->Tick(.1);Check(G->Hostile51==0,TEXT("guard stays friendly in front of no-entry point"));P.Talk(G);Check(P.Speaker==G&&P.DialogueActions.Contains(TEXT("ca_deposit")),TEXT("officer offers customs through real dialogue"));P.ClosePanels();}
 },[this](ALWCharacter&){CaptureV2(TEXT("Canada68_Checkpoint"));});
 Add(TEXT("68 escrow persistence and full inventory"),.2,[this](ALWCharacter& P){
  P.ClosePanels();P.SetActorLocation(FVector(LWBorder51::North-1400,6400,110));auto Gun=LWItems::Make(TEXT("rifle"));auto Mag=LWItems::Make(TEXT("mag_rifle30"));Gun.WeaponTier=4;Gun.LegendaryModifier=TEXT("toxic");Gun.Attachments.Add(TEXT("Sight"),TEXT("reflex"));Mag.Slot=TEXT("Loaded");Mag.Rounds=17;Gun.LoadedMagazine=Mag.Id;Gun.Slot=TEXT("Primary");P.Inventory.Add(Gun);P.Inventory.Add(Mag);LWCanada68::Deposit(&P);
  auto* Save=NewObject<ULWSaveGame>();Save->RPG=P.RPG;TArray<uint8> Bytes;Check(UGameplayStatics::SaveGameToMemory(Save,Bytes),TEXT("customs can serialize through real save format"));auto* Loaded=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromMemory(Bytes));Check(Loaded&&Loaded->RPG.Canada68.Passport&&Loaded->RPG.Canada68.Escrow.ContainsByPredicate([&](const auto& E){return E.Item.Id==Gun.Id&&E.Item.LoadedMagazine==Mag.Id&&E.Item.WeaponTier==4;}),TEXT("passport and complete weapon state survive save roundtrip"));
  for(int I=0;I<200;I++){auto Kit=LWItems::Make(TEXT("medkit"),3);if(!LWItems::Place(P.Inventory,Kit,12,10))break;}LWCanada68::Reclaim(&P);Check(P.RPG.Canada68.Escrow.ContainsByPredicate([&](const auto& E){return E.Item.Id==Gun.Id;}),TEXT("full inventory leaves weapons safely in customs"));P.Inventory.Empty();LWCanada68::Reclaim(&P);Check(P.Inventory.ContainsByPredicate([&](const auto& I){return I.Id==Gun.Id&&I.LoadedMagazine==Mag.Id;})&&P.Inventory.ContainsByPredicate([&](const auto& I){return I.Id==Mag.Id&&I.Rounds==17&&I.Slot==TEXT("Loaded");}),TEXT("weapon and magazine return together without losing rounds"));
 });
 Add(TEXT("68 Canada city and premium trade"),2,[this](ALWCharacter& P){
  P.SetActorLocation(FVector(LWBorder51::North-1400,6400,110));LWCanada68::Deposit(&P);P.SetActorLocation(FVector(LWGen::CanadaCity68(),120));P.World->Stream(P.GetActorLocation(),true);P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.World->TickWeather(.1,&P);LWCanada68::Tick(P.World,&P,.1);
  int Citizens=0,Hostiles=0;ALWResident* Shop=nullptr;for(TActorIterator<ALWZombie> I(GetWorld());I;++I)if(I->GetActorLocation().X>=LWBorder51::North){if(auto* N=Cast<ALWResident>(*I)){Citizens++;if(N->NpcRole==TEXT("canada_shop68"))Shop=N;}else Hostiles++;}
  Check(Citizens>=20&&Shop,TEXT("city contains populated shops and pedestrians"));Check(Hostiles==0,TEXT("Canada has no hostile population"));
  if(Shop){P.SetActorLocation(Shop->GetActorLocation()+FVector(0,-120,0));P.Talk(Shop);Check(P.DialogueActions.Contains(TEXT("ca_trade")),TEXT("Canadian merchant is interactable"));LWCanada68::Action(&P,TEXT("ca_trade"));auto I=LWItems::Make(TEXT("medkit"));Check(LWCanada68::TradePrice(&P,I,false)==LWMods::Price(I)*2,TEXT("northern merchants pay four times ordinary resale"));Check(LWCanada68::TradePrice(&P,I,true)>LWCanada68::TradePrice(&P,I,false),TEXT("local buy and sell cannot generate free money"));auto* R=P.World->Containers.Find(P.OpenObject?P.OpenObject->RecordId:NAME_None);Check(R&&R->Items.ContainsByPredicate([](const auto& X){return X.Definition==TEXT("ca_trauma");}),TEXT("exclusive northern supplies stocked"));P.ClosePanels();}
  P.SetActorLocation(FVector(LWGen::CanadaCity68()+FVector2D(-8000,-4000),1400));P.Camera->SetWorldRotation(FRotator(-15,25,0));
 },[this](ALWCharacter& P){CaptureV2(TEXT("Canada68_Maplehaven"));UE_LOG(LogTemp,Display,TEXT("STREAM68 initial max indivisible stage %.2f ms"),P.World->StreamMaxStep68);});
 Add(TEXT("68 aircraft warning and explosion"),.4,[this](ALWCharacter& P){
  P.SetActorLocation(FVector(LWBorder51::North+1500,6400,2500));FLWVehicleRecord R;R.Model=TEXT("helicopter");R.Position=P.GetActorLocation();R.Unlocked=R.Hotwired=true;R.Health=600;P.World->Vehicles.Add(TEXT("air68"),R);auto* V=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("air68"),R.Position));Check(V!=nullptr,TEXT("aircraft available"));if(!V)return;V->SetActorLocation(R.Position);V->SetActorTickEnabled(false);P.Vehicle=V;P.RPG.Canada68.Cleared=false;P.RPG.Canada68.Passport=false;LWCanada68::Tick(P.World,&P,.1);Check(P.World->BorderAircraft68==V&&!V->Record()->Exploded,TEXT("unauthorized flight warns before firing"));V->SetActorLocation(FVector(LWBorder51::North-1000,6400,2500));P.SetActorLocation(V->GetActorLocation());LWCanada68::Tick(P.World,&P,.1);Check(!P.World->BorderAircraft68.IsValid()&&!V->Record()->Exploded,TEXT("turning south cancels interception"));V->SetActorLocation(R.Position);P.SetActorLocation(R.Position);P.RPG.Canada68.Passport=P.RPG.Canada68.Cleared=true;LWCanada68::Tick(P.World,&P,25);Check(!V->Record()->Exploded,TEXT("cleared passport holder can fly north"));P.RPG.Canada68.Passport=P.RPG.Canada68.Cleared=false;LWCanada68::Tick(P.World,&P,.1);LWCanada68::Tick(P.World,&P,21);Check(V->Record()->Exploded,TEXT("ignoring the grace period destroys aircraft"));P.Vehicle=nullptr;P.SetActorLocation(R.Position+FVector(-1000,-700,50));auto* ShotCamera=GetWorld()->SpawnActor<ACameraActor>(P.GetActorLocation(),(R.Position-P.GetActorLocation()).Rotation());Cast<APlayerController>(P.Controller)->SetViewTarget(ShotCamera);
 });
 Add(TEXT("68 explosion capture"),.25,[](ALWCharacter&){},[this](ALWCharacter& P){for(TActorIterator<ALWVehicleExplosion68> E(GetWorld());E;++E)UE_LOG(LogTemp,Display,TEXT("EFFECT68 position=%s age=%f camera=%s target=%s"),*E->GetActorLocation().ToString(),E->Age,*UGameplayStatics::GetPlayerCameraManager(&P,0)->GetCameraLocation().ToString(),*Cast<APlayerController>(P.Controller)->GetViewTarget()->GetName());CaptureV2(TEXT("Canada68_Explosion"));});
 Add(TEXT("68 staged flight loading"),12,[this](ALWCharacter& P){Cast<APlayerController>(P.Controller)->SetViewTarget(&P);P.World->StreamMaxStep68=0;P.SetActorLocation(FVector(LWBorder51::North+180000,6400,1800));P.World->SetActorTickEnabled(true);P.RPG.Canada68.Passport=P.RPG.Canada68.Cleared=true;},[this](ALWCharacter& P){Check(P.World->Chunks.Num()>5,TEXT("staged streamer populates destination"));UE_LOG(LogTemp,Display,TEXT("STREAM68 travel max indivisible stage %.2f ms / %d chunks / %d jobs"),P.World->StreamMaxStep68,P.World->Chunks.Num(),P.World->Jobs68.Num());P.World->SetActorTickEnabled(false);});
 Add(TEXT("68 continuous helicopter-speed travel"),8,[this](ALWCharacter& P){
  for(TActorIterator<ALWVehicle> V(GetWorld());V;++V)if(V->RecordId==TEXT("air68")){P.Vehicle=*V;V->SetActorLocation(P.GetActorLocation());V->Velocity57=FVector(6200,0,0);break;}
  P.World->StreamMaxStep68=0;P.World->SetActorTickEnabled(true);V2->Observe=[](ALWCharacter& Player){if(Player.Vehicle){Player.Vehicle->AddActorWorldOffset(FVector(6200,0,0)*Player.GetWorld()->GetDeltaSeconds());Player.SetActorLocation(Player.Vehicle->GetActorLocation());}};
 },[this](ALWCharacter& P){Check(P.World->LastAhead68!=P.World->LastCenter,TEXT("moving helicopter preloads chunks ahead of current position"));auto* Under=P.World->Chunks.FindRef(P.World->LastCenter).Get();Check(Under&&Under->Stage68>0,TEXT("terrain is present under fast travelling aircraft"));UE_LOG(LogTemp,Display,TEXT("STREAM68 moving flight max indivisible stage %.2f ms"),P.World->StreamMaxStep68);V2->Observe=FLWV2Action();P.Vehicle=nullptr;P.World->SetActorTickEnabled(false);});
 Add(TEXT("68 American chunk travel"),15,[this](ALWCharacter& P){P.World->StreamMaxStep68=0;P.SetActorLocation(FVector(300000,300000,2200));P.World->SetActorTickEnabled(true);},[this](ALWCharacter& P){Check(P.World->Chunks.Num()>5,TEXT("American POIs remain streamable"));UE_LOG(LogTemp,Display,TEXT("STREAM68 America max indivisible stage %.2f ms / %d chunks / %d jobs"),P.World->StreamMaxStep68,P.World->Chunks.Num(),P.World->Jobs68.Num());P.World->SetActorTickEnabled(false);});
 Add(TEXT("68 underground loads on entry"),1,[this](ALWCharacter& P){
  auto* TestChunk=GetWorld()->SpawnActor<ALWChunk>(FVector(400000,400000,0),FRotator::ZeroRotator);LWGen::FSite Site;Site.Position=FVector2D(402000,402000);Site.Id=680053;Site.Type=53;Site.Size=FVector2D(4000);TestChunk->BuildingUnderground(P.World,Site);
  ALWUndergroundDoor* Door=nullptr;for(TActorIterator<ALWUndergroundDoor> D(GetWorld());D;++D)if(!D->Exit&&D->PrepareInterior68){Door=*D;break;}
  Check(Door!=nullptr,TEXT("surface travel leaves underground interiors deferred"));if(!Door)return;P.ClosePanels();P.SetActorLocation(Door->GetActorLocation()+FVector(0,-200,95));Door->Use(&P);
  Check(!Door->PrepareInterior68&&P.GetActorLocation().Z<-8000,TEXT("entry builds underground once and moves player inside"));FHitResult Hit;FCollisionQueryParams Q(NAME_None,false,&P);Check(GetWorld()->LineTraceSingleByChannel(Hit,P.GetActorLocation(),P.GetActorLocation()-FVector(0,0,250),ECC_Visibility,Q),TEXT("underground floor collision ready before control returns"));
  const FVector SavedPosition=P.GetActorLocation();TestChunk->Destroy();auto* Reloaded=GetWorld()->SpawnActor<ALWChunk>(FVector(400000,400000,0),FRotator::ZeroRotator);Reloaded->BuildingUnderground(P.World,Site);FHitResult RestoredFloor;Check(GetWorld()->LineTraceSingleByChannel(RestoredFloor,SavedPosition,SavedPosition-FVector(0,0,250),ECC_Visibility,Q),TEXT("loading underground position reconstructs floor without using entrance"));
 });
 return;
}
