#include "LWAppearance.h"
#include "LWResident.h"
#include "LWOpening.h"
void ALWGameMode::BuildCharacters32Smoke(ALWCharacter& Initial){
 auto Add=[this](const TCHAR* Label,double Delay,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({Label,Delay,90,MoveTemp(Begin),MoveTemp(End),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};
 struct FGallery{ALWOpeningScene* Scene=nullptr;TArray<ALWZombie*> NPCs;};auto G=MakeShared<FGallery>();
 Add(TEXT("PS2 male creator"),3,[this,G](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;G->Scene=GetWorld()->SpawnActor<ALWOpeningScene>(FVector(0,0,80000),FRotator::ZeroRotator);G->Scene->World=P.World;P.OpeningScene=G->Scene;P.OpeningMode=2;P.DraftIdentity=FLWIdentity();P.DraftIdentity.Hair=2;G->Scene->Portrait(P.DraftIdentity,0);Cast<APlayerController>(P.Controller)->SetViewTarget(G->Scene);P.bMenu=true;P.SetMenuInput(true);for(auto& C:G->Scene->Pieces)Check(C&&C->GetStaticMesh(),TEXT("creator has valid model components"));},[this](ALWCharacter& P){CaptureV2(TEXT("Characters32_MaleCreator"));});
 Add(TEXT("PS2 female creator"),3,[this,G](ALWCharacter& P){P.DraftIdentity.Body=1;P.DraftIdentity.Hair=5;P.DraftIdentity.Skin=2;P.DraftIdentity.Weight=.8;P.DraftIdentity.Shoulders=.2;G->Scene->Portrait(P.DraftIdentity,0);for(auto& C:G->Scene->Pieces)Check(C&&C->GetStaticMesh(),TEXT("female morph components resolve"));},[this](ALWCharacter& P){CaptureV2(TEXT("Characters32_FemaleCreator"));});
 Add(TEXT("NPC character lineup"),4,[this,G](ALWCharacter& P){P.OpeningMode=0;P.bMenu=false;P.SetMenuInput(false);G->Scene->Clear();G->Scene->Piece(TEXT("Cube"),TEXT("Concrete"),FVector(0,0,-10),FVector(1800,1800,20));G->Scene->Light(FVector(180,-350,360),FLinearColor(1,.9,.8),38000,1400);G->Scene->Light(FVector(150,360,250),FLinearColor(.7,.8,1),24000,1200);for(int I=0;I<4;I++){FVector At=G->Scene->GetActorLocation()+FVector(0,(I-1.5f)*120,96);ALWZombie* N;if(I<2){auto* R=GetWorld()->SpawnActor<ALWResident>(At,FRotator::ZeroRotator);R->ConfigureResident(I?TEXT("story_mara"):TEXT("story_jonah"),TEXT("story"),I?TEXT("Mara Vale"):TEXT("Jonah Reed"),I);N=R;}else{N=GetWorld()->SpawnActor<ALWZombie>(At,FRotator::ZeroRotator);N->ConfigureKind(I==2?ELWEnemyKind::Raider:ELWEnemyKind::Zombie);}N->SetActorTickEnabled(false);N->GetCharacterMovement()->DisableMovement();G->NPCs.Add(N);for(auto& C:N->Parts){Check(C->GetStaticMesh()&&C->GetStaticMesh()->GetName().EndsWith(TEXT("32")),TEXT("NPC uses rebuilt model"));Check(C->GetStaticMesh()&&C->GetStaticMesh()->GetBodySetup(),TEXT("NPC supports physics collision"));}}G->Scene->From=G->Scene->To=FVector(650,-330,210);G->Scene->Focus=FVector(0,0,90);G->Scene->Camera->FieldOfView=52;G->Scene->Pose(0);},[this](ALWCharacter& P){CaptureV2(TEXT("Characters32_NPCLineup"));});
 Add(TEXT("Creature mesh and ragdoll compatibility"),3,[this,G](ALWCharacter& P){for(int I=2;I<9;I++){auto* N=GetWorld()->SpawnActor<ALWZombie>(G->Scene->GetActorLocation()+FVector(2500,I*350,160),FRotator::ZeroRotator);N->ConfigureKind(ELWEnemyKind(I));for(auto& C:N->Parts)Check(C->GetStaticMesh()&&C->GetStaticMesh()->GetName().EndsWith(TEXT("32")),TEXT("creature segment asset resolves"));N->Destroy();}FDamageEvent E;G->NPCs[3]->Die(E,&P,100,nullptr);},[this,G](ALWCharacter& P){int Simulating=0;for(auto& C:G->NPCs[3]->Parts)if(C->IsSimulatingPhysics())Simulating++;Check(Simulating==7,TEXT("seven rebuilt zombie segments simulate ragdoll"));});
 Add(TEXT("Player first person appearance"),4,[this,G](ALWCharacter& P){for(auto* N:G->NPCs)if(IsValid(N))N->Destroy();G->Scene->Destroy();P.OpeningScene=nullptr;P.OpeningMode=0;Cast<APlayerController>(P.Controller)->SetViewTarget(&P);P.EnterSafehouse();P.ToggleFlashlight();P.Identity=P.DraftIdentity;P.ApplyIdentity();P.GiveItem(TEXT("revolver"));P.Equip(3);Check(P.Arms->GetStaticMesh()&&P.Arms->GetStaticMesh()->GetName()==TEXT("SM_RightHand32"),TEXT("weapon view uses rebuilt right hand"));Check(P.LoadingHand->GetStaticMesh()&&P.LoadingHand->GetStaticMesh()->GetName()==TEXT("SM_LeftHand32"),TEXT("reload view uses rebuilt left hand"));},[this](ALWCharacter& P){CaptureV2(TEXT("Characters32_FirstPerson"));});
 Add(TEXT("Player melee appearance"),3,[this](ALWCharacter& P){P.Equip(0);Check(P.Arms->GetStaticMesh()&&P.Arms->GetStaticMesh()->GetName()==TEXT("SM_RightHand32"),TEXT("melee uses rebuilt right hand"));Check(P.LoadingHand->GetStaticMesh()&&P.LoadingHand->GetStaticMesh()->GetName()==TEXT("SM_LeftHand32"),TEXT("melee uses rebuilt left hand"));},[this](ALWCharacter& P){CaptureV2(TEXT("Characters32_Melee"));});
}
