void ALWGameMode::BuildCombat29Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,180,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};
 struct FState {TWeakObjectPtr<ALWChunk> Floor,Building;TWeakObjectPtr<ALWZombie> Enemy;TWeakObjectPtr<ALWUndergroundDoor> Entry,Exit;};auto S=MakeShared<FState>();
 Add(TEXT("combat29 fixtures"),2,[this,S](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;P.World->WeatherOverride=0;P.World->TimeOfDay=12;P.World->TickWeather(0,&P);P.Health=10000;auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Floor=C;C->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(40000,40000,20));LWV2Teleport(P,FVector(20000,20000,5090));P.Controller->SetControlRotation(FRotator::ZeroRotator);});
 for(FName Id:{TEXT("missile_launcher"),TEXT("taser")})Add(TEXT("direct ammunition transactions"),.3,[this,Id](ALWCharacter& P){P.ClosePanels();P.CancelReload();P.StopAttack();P.Inventory.Empty();auto G=LWItems::Make(Id);const auto& D=LWItems::Def(Id);G.Slot=D.EquipSlots[0];P.Inventory.Add(G);P.ActiveWeaponId=G.Id;P.Equip(D.WeaponIndex);P.AttackTimer=0;P.bUIAttackHeld=false;P.GiveItem(D.AmmoType,3);
 P.Reload();Check(P.bReloading,TEXT("loose ammunition starts direct reload"));P.UpdateReload(.2f);P.CancelReload();Check(P.AmmoCount(D.AmmoType)==3&&P.ActiveGun()->Rounds==0,TEXT("interrupted direct reload consumes nothing"));P.Reload();P.UpdateReload(4);Check(!P.bReloading&&P.ActiveGun()->Rounds==D.Capacity&&P.AmmoCount(D.AmmoType)==2,TEXT("one loose missile or battery loads full capacity"));Check(!P.ActiveGun()->LoadedMagazine.IsValid()&&P.ActiveGun()->Chamber==0,TEXT("direct loading creates no magazine or phantom chamber"));P.Reload();Check(!P.bReloading&&P.AmmoCount(D.AmmoType)==2,TEXT("loaded weapon cannot waste ammunition"));P.AttackTimer=0;int Before=P.ActiveGun()->Rounds;P.Attack();P.StopAttack();Check(P.ActiveGun()->Rounds==Before-1,TEXT("direct fire consumes one missile or battery charge"));P.SyncAmmoHUD();Check(P.Shells==Before-1,TEXT("direct ammunition HUD matches weapon"));},[this,Id](ALWCharacter&){CaptureV2(*(Id.ToString()+TEXT("29_Direct")));});
 Add(TEXT("legacy ammunition conservation"),.2,[this](ALWCharacter& P){P.ClosePanels();P.CancelReload();P.Inventory.Empty();auto G=LWItems::Make(TEXT("missile_launcher"));G.Slot=TEXT("Primary");G.Chamber=1;auto M=LWItems::Make(TEXT("rocket_tube"));M.Slot=TEXT("Loaded");M.Rounds=0;G.LoadedMagazine=M.Id;P.Inventory.Add(G);P.Inventory.Add(M);auto Spare=LWItems::Make(TEXT("rocket_tube"));Spare.Rounds=1;LWItems::Place(P.Inventory,Spare,12,10);P.GiveItem(TEXT("ammo_dart"),8);P.MigrateDirectAmmo();Check(P.FindItem(G.Id)&&P.FindItem(G.Id)->Rounds==1&&!P.FindItem(G.Id)->LoadedMagazine.IsValid(),TEXT("legacy live missile remains loaded"));Check(P.AmmoCount(TEXT("ammo_rocket"))==1&&P.AmmoCount(TEXT("battery"))==8,TEXT("legacy spare ammunition converted without loss"));Check(LWItems::ValidateEquipment(P.Inventory),TEXT("migration produces non-overlapping legal inventory"));int N=P.Inventory.Num();P.MigrateDirectAmmo();Check(N==P.Inventory.Num()&&P.AmmoCount(TEXT("battery"))==8,TEXT("migration is idempotent"));});
 Add(TEXT("fuel pump refill"),.2,[this](ALWCharacter& P){P.Inventory.Empty();auto Tank=LWItems::Make(TEXT("fuel_tank"));Tank.Rounds=7;LWItems::Place(P.Inventory,Tank,12,10);auto* Pump=P.World->SpawnObject(ELWObjectKind::FuelPump,TEXT("test29_pump"),P.GetActorLocation()+FVector(140,0,-90));Pump->bChanged=false;P.RefillCanisters(Pump);Check(P.FindItem(Tank.Id)->Rounds==100,TEXT("intact pump refills canister"));P.FindItem(Tank.Id)->Rounds=8;Pump->bChanged=true;P.RefillCanisters(Pump);Check(P.FindItem(Tank.Id)->Rounds==8,TEXT("exploded pump cannot refill"));Pump->Destroy();});
 Add(TEXT("gun bash and menu safety"),.4,[this,S](ALWCharacter& P){P.Inventory.Empty();auto G=LWItems::Make(TEXT("m4"));G.Slot=TEXT("Primary");P.Inventory.Add(G);P.ActiveWeaponId=G.Id;P.Equip(13);P.AttackTimer=0;P.Stamina=100;LWV2Teleport(P,FVector(20000,20000,5090));auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20140,20000,5090),FRotator::ZeroRotator);S->Enemy=Z;Z->EnsureLegendary();Z->SetActorTickEnabled(false);float HP=Z->Health;P.bInventory=true;P.GunBash();Check(Z->Health==HP&&P.Stamina==100,TEXT("gun bash blocked while inventory is open"));P.ClosePanels();P.GunBash();Check(Z->Health<HP&&Z->Health>=HP-8.01f,TEXT("gun bash inflicts low damage"));Check(P.Stamina==92&&P.GunBashTimer>0,TEXT("bash spends stamina and animates"));Check(P.CombatTarget==Z,TEXT("damaging enemy selects healthbar target"));},[this,S](ALWCharacter&){CaptureV2(TEXT("Combat29_Target"));});
 for(int Stars=1;Stars<=3;Stars++)Add(TEXT("legendary corpse reward"),.2,[this,Stars,S](ALWCharacter& P){P.ClosePanels();if(S->Enemy.IsValid())S->Enemy->Destroy();auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20300,20000,5090),FRotator::ZeroRotator);Z->PersistentId=290000+Stars;Z->Stars=Stars;Z->ConfigureKind(ELWEnemyKind::Raider);float Base=Z->Health;Z->EnsureLegendary();Check(Z->Health>Base*(1+Stars),TEXT("legendary stars scale health"));Check(Z->LegendaryDamage()>1&&Z->EnemyName().Contains(TEXT("LEGENDARY")),TEXT("legendary damage and display name"));P.World->Containers.Remove(FName(*FString::Printf(TEXT("corpse_%u"),Z->PersistentId)));Z->Die(FDamageEvent(),&P,10000,P.Controller);FName Key(*FString::Printf(TEXT("corpse_%u"),Z->PersistentId));auto* C=P.World->Containers.Find(Key);Check(C&&C->Items.ContainsByPredicate([](const auto& I){return LWItems::Def(I.Definition).Category==TEXT("Weapon")&&I.WeaponTier==4&&!I.LegendaryModifier.IsNone();}),TEXT("every legendary corpse guarantees legendary weapon with modifier"));Z->LootBody(&P);Check(P.OpenObject==Z->LootProxy,TEXT("dead body opens loot inventory"));P.ClosePanels();if(C){C->Items.Empty();Z->MakeCorpseLoot();Check(P.World->Containers.FindChecked(Key).Items.IsEmpty(),TEXT("searching corpse cannot duplicate loot"));auto* Save=NewObject<ULWSaveGame>();Save->WorldContainers=P.World->Containers;TArray<uint8> Bytes;UGameplayStatics::SaveGameToMemory(Save,Bytes);auto* Loaded=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromMemory(Bytes));Check(Loaded&&Loaded->WorldContainers.FindChecked(Key).Items.IsEmpty(),TEXT("empty corpse persists through serialization"));}if(Z->LootProxy)Z->LootProxy->Destroy();Z->Destroy();});
 for(int Kind=9;Kind<=11;Kind++)Add(TEXT("boss scale and behavior"),1,[this,S,Kind](ALWCharacter& P){P.ClosePanels();if(S->Enemy.IsValid())S->Enemy->Destroy();P.StopAttack();auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(23000,20000,5100),FRotator(0,180,0));S->Enemy=Z;Z->PersistentId=290100+Kind;Z->ConfigureKind(ELWEnemyKind(Kind));Z->EnsureLegendary();Z->SetActorTickEnabled(false);P.CombatTarget=Z;P.CombatTargetTime=100;Check(Z->MaximumHealth>=2200,TEXT("boss health initialized"));Check(Kind==9?FMath::IsNearlyEqual(Z->GetActorScale3D().X,3.):Kind==10?FMath::IsNearlyEqual(Z->GetActorScale3D().X,9.):Z->Parts[0]->Bounds.BoxExtent.X>500,TEXT("boss size matches requested scale"));if(Kind>=10)Check(Z->Stars>=1,TEXT("rare bosses always legendary"));if(Kind==11){Z->BossClock=0;Z->TickBoss(.1f,&P);Check(Z->BurrowPhase==1&&!Z->GetActorEnableCollision(),TEXT("worm burrows with collision disabled"));Z->TickBoss(2.1f,&P);Check(Z->BurrowPhase==2&&Z->IsHidden(),TEXT("burrowed worm hides"));float HP=Z->Health;Z->TakeDamage(100,FDamageEvent(),P.Controller,&P);Check(Z->Health==HP,TEXT("burrowed worm cannot be shot underground"));FVector Previous=P.GetActorLocation();LWV2Teleport(P,FVector(900000,900000,1000));Z->SetActorLocation(FVector(905000,900000,-1600));Z->BossClock=0;for(int Attempt=0;Attempt<12&&Z->BurrowPhase==2;Attempt++)Z->TickBoss(1.1f,&P);Check(Z->BurrowPhase==3,TEXT("worm selects a real clear random emergence position"));if(Z->BurrowPhase==3)Check(Z->BurrowDestination.Z>P.World->HeightAt(FVector2D(Z->BurrowDestination)),TEXT("emergence above terrain"));LWV2Teleport(P,Previous);Z->SetActorLocation(FVector(23000,20000,5800));Z->BurrowDestination=FVector(23000,20000,5800);Z->BurrowPhase=3;Z->BossClock=.1f;Z->TickBoss(.2f,&P);Check(Z->BurrowPhase==0&&!Z->IsHidden()&&Z->GetActorEnableCollision(),TEXT("worm emerges and restores collision"));Check(FVector::DotProduct(Z->GetActorForwardVector(),(P.GetActorLocation()-Z->GetActorLocation()).GetSafeNormal2D())>.99,TEXT("worm emerges facing its target"));}LWV2Teleport(P,FVector(19000,18500,5100));P.Controller->SetControlRotation(FRotator(Kind==10?15:3,21,0));},[this,S,Kind](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Boss29_%d"),Kind));});
 for(int Type:{53,54,55}){
 Add(TEXT("underground entrance"),1,[this,S,Type](ALWCharacter& P){if(S->Enemy.IsValid())S->Enemy->Destroy();if(S->Building.IsValid())S->Building->Destroy();auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Building=C;LWGen::FSite Site;Site.Type=Type;Site.Id=290200+Type;Site.Size=LWPlaces::Size(Type);Site.Position=FVector2D(60000,60000);C->Building(P.World,Site);S->Entry.Reset();S->Exit.Reset();for(auto A:C->Residents)if(auto* Door=Cast<ALWUndergroundDoor>(A)){if(Door->Exit)S->Exit=Door;else S->Entry=Door;}if(!RequireV2(S->Entry.IsValid()&&S->Exit.IsValid(),TEXT("underground has entrance and exit")))return;LWV2Teleport(P,S->Entry->GetActorLocation()-FVector(0,160,-100));S->Entry->Use(&P);Check(P.GetActorLocation().Z<-8000,TEXT("entrance reaches underground location"));ALWDungeon* D=nullptr;for(auto A:C->Residents)if(auto* Child=Cast<ALWChunk>(A))for(auto B:Child->Residents)if(auto* Found=Cast<ALWDungeon>(B))D=Found;if(RequireV2(D!=nullptr,TEXT("underground controller present"))){D->Tick(.5f);Check(D->WasInside,TEXT("negative-height dungeon activation works"));Check(D->Guards.Num()>10,TEXT("underground populated with guarded rooms"));Check(D->Site.Type==Type,TEXT("underground uses its own themed profile"));}FHitResult H;FCollisionQueryParams Q(NAME_None,false,&P);GetWorld()->LineTraceSingleByChannel(H,P.GetActorLocation(),P.GetActorLocation()-FVector(0,0,180),ECC_WorldStatic,Q);Check(H.bBlockingHit&&H.ImpactPoint.Z<-8000,TEXT("underground spawn has solid floor"));P.Controller->SetControlRotation(FRotator(-3,25,0));},[this,Type](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Underground29_%d"),Type));});
 Add(TEXT("underground return"),.2,[this,S](ALWCharacter& P){if(S->Exit.IsValid()){S->Exit->Use(&P);Check(P.GetActorLocation().Z>0,TEXT("exit returns player to surface"));}if(S->Building.IsValid())S->Building->Destroy();});}
 for(int Type:{20,56,57,21})Add(TEXT("tower and casino structure"),2,[this,S,Type](ALWCharacter& P){P.ClosePanels();if(S->Building.IsValid())S->Building->Destroy();auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Building=C;LWGen::FSite Site;Site.Type=Type;Site.Id=290300+Type;Site.Size=LWPlaces::Size(Type);Site.Position=FVector2D(20000,20000);Site.Floors=12;Site.AccessibleFloors=3;C->BuildingSurfaces=true;C->Building(P.World,Site);C->BuildingSurfaces=false;C->FlushSurfaces();C->SetActorLocation(FVector(0,0,5000));int Glass=0,Containers=0;ALWWorldObject* Pane=nullptr;for(auto A:C->Residents)if(IsValid(A)){A->AddActorWorldOffset(FVector(0,0,5000));if(auto* O=Cast<ALWWorldObject>(A)){if(O->Kind==ELWObjectKind::Window){Glass++;Pane=O;}Containers+=O->Kind==ELWObjectKind::Container;}}
 Check(Glass>100,TEXT("facade has individually breakable glass"));Check(Containers>20,TEXT("accessible interiors contain storage furnishings"));if(Pane){Pane->TakeDamage(100,FDamageEvent(),P.Controller,&P);Check(Pane->bChanged&&!Pane->Body->IsVisible(),TEXT("facade window breaks"));Check(P.World->PropStates.FindRef(Pane->RecordId)!=0,TEXT("broken facade window persists"));}
 if(Type!=21){FCollisionQueryParams Q(NAME_None,false,&P);int Errors=0;for(int F=0;F<12;F++){FVector A(19700,20700,5012+F*400+110);FHitResult H;GetWorld()->LineTraceSingleByChannel(H,A,A-FVector(0,0,150),ECC_WorldStatic,Q);if(!H.bBlockingHit)Errors++;}Check(Errors==0,TEXT("tower has solid decks even on inaccessible floors"));LWV2Teleport(P,Type==56?FVector(19700,19040,5118):FVector(19700,18800,5118));P.Controller->SetControlRotation(FRotator(-3,Type==56?-60:175,0));}else{LWV2Teleport(P,FVector(20000,18300,5120));P.Controller->SetControlRotation(FRotator(-3,50,0));}},[this,Type](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Interior29_%d"),Type));});
 Add(TEXT("combat29 cleanup"),.2,[S](ALWCharacter& P){P.ClosePanels();if(S->Building.IsValid())S->Building->Destroy();if(S->Floor.IsValid())S->Floor->Destroy();P.World->WeatherOverride=-1;});
}
