#include "LWInventory.h"
#include "LWGeneration.h"
#include "Misc/AutomationTest.h"
#if WITH_DEV_AUTOMATION_TESTS
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWSortTest,"LethalWorld.Inventory.SortAndQuickTransfer",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWSortTest::RunTest(const FString&){LWItems::SetCatalog(nullptr);TArray<FLWItemInstance> A,B;
 auto X=LWItems::Make(TEXT("ammo_9mm"),12),Y=LWItems::Make(TEXT("ammo_9mm"),20);LWItems::Place(A,X,12,10);LWItems::Place(A,Y,12,10);auto Pick=LWItems::Make(TEXT("lockpick"),2),Worn=LWItems::Make(TEXT("lockpick"),1);Worn.Durability=10;LWItems::Place(A,Pick,12,10);LWItems::Place(A,Worn,12,10);
 TestTrue(TEXT("sort succeeds"),LWItems::AutoSort(A,12,10));int Ammo=0,Picks=0;for(const auto& I:A){if(I.Definition==TEXT("ammo_9mm"))Ammo+=I.Count;if(I.Definition==TEXT("lockpick"))Picks++;TestTrue(TEXT("sorted footprint valid"),LWItems::Fits(A,I,I.X,I.Y,I.bRotated,12,10,I.Id));}TestEqual(TEXT("rounds conserved"),Ammo,32);TestEqual(TEXT("distinct pick condition retained"),Picks,2);TestEqual(TEXT("ammo stacks combined"),A.Num(),3);
 auto Gun=LWItems::Make(TEXT("smg")),Mag=LWItems::Make(TEXT("mag_smg30"));Mag.Slot=TEXT("Loaded");Mag.Rounds=17;Gun.LoadedMagazine=Mag.Id;LWItems::Place(A,Gun,12,10);A.Add(Mag);TestTrue(TEXT("quick transfer linked magazine"),LWItems::QuickTransfer(A,B,Gun.Id,12,10));TestTrue(TEXT("magazine identity and rounds preserved"),B.ContainsByPredicate([&](const auto& I){return I.Id==Mag.Id&&I.Rounds==17&&I.Slot==TEXT("Loaded");}));TestFalse(TEXT("magazine cannot move independently"),LWItems::QuickTransfer(B,A,Mag.Id,12,10));int Before=B.Num();TestFalse(TEXT("full target transfer fails"),LWItems::QuickTransfer(B,A,Gun.Id,1,1));TestEqual(TEXT("failed transfer keeps source intact"),B.Num(),Before);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWParcelClearanceTest,"LethalWorld.Generation.BuildingRoadClearance",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWParcelClearanceTest::RunTest(const FString&){int Sites=0;for(int Seed:{0,198706,-97})for(int Y=-3;Y<=3;Y++)for(int X=-3;X<=3;X++){TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Parcels;LWGen::Region(FIntPoint(X,Y),Seed,Roads,Parcels);for(const auto& P:Parcels){Sites++;bool Clear=true;for(const auto& R:Roads){int Steps=FMath::CeilToInt((R.B-R.A).Size()/100.);for(int I=0;I<=Steps;I++){FVector2D Q=(FMath::Lerp(R.A,R.B,double(I)/FMath::Max(1,Steps))-P.Position).GetRotated(-P.Yaw);if(FMath::Abs(Q.X)<P.Size.X*.5+R.Width*.5+80&&FMath::Abs(Q.Y)<P.Size.Y*.5+R.Width*.5+80)Clear=false;}}if(!TestTrue(TEXT("foundation and road lane do not overlap"),Clear))return false;}}TestTrue(TEXT("clearance leaves a populated world"),Sites>100);return true;}
#endif
