#include "LWConsole47.h"
#include "Engine/GameViewportClient.h"
void ALWGameMode::BuildConsole47Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Delay,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Delay,120,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){return true;}});};
 Add(TEXT("console commands"),1,[this](ALWCharacter& P){auto* C=Cast<ULWConsole47>(GetWorld()->GetGameViewport()->ViewportConsole);if(!RequireV2(C!=nullptr,TEXT("custom console installed")))return;Check(C->Execute47(TEXT("money 1")).Contains(TEXT("Start or load")),TEXT("title rejects gameplay cheats"));P.NewGame();P.EnterSafehouse();P.Inventory.Empty();P.Money=10;
 Check(C->Execute47(TEXT("money 5000")).Contains(TEXT("5010"))&&P.Money==5010,TEXT("credits granted"));C->Execute47(TEXT("money -4"));C->Execute47(TEXT("money 999999999999999999999"));Check(P.Money==5010,TEXT("invalid credit amounts rejected"));
 C->Execute47(TEXT("give medkit 3"));Check(P.CountSupply(TEXT("medkit"))==3,TEXT("items granted"));int Count=P.Inventory.Num();C->Execute47(TEXT("give not_real 1"));C->Execute47(TEXT("give medkit -1"));Check(P.Inventory.Num()==Count&&P.CountSupply(TEXT("medkit"))==3,TEXT("bad item requests do not mutate inventory"));Check(C->Execute47(TEXT("items medkit")).Contains(TEXT("medkit -")),TEXT("search lists matching IDs"));
 auto Saved=P.Inventory;P.Inventory.Empty();for(int I=0;I<120;++I){auto X=LWItems::Make(TEXT("medkit"));X.X=I%12;X.Y=I/12;P.Inventory.Add(X);}Check(C->Execute47(TEXT("give crowbar 1")).Contains(TEXT("No items added"))&&P.Inventory.Num()==120,TEXT("full inventory rejects grant atomically"));P.Inventory=Saved;
 P.Health=15;P.Stamina=3;C->Execute47(TEXT("heal"));Check(P.Health==P.MaxHealth()&&P.Stamina==P.MaxStamina(),TEXT("heal restores vitals"));int Points=P.RPG.Points;C->Execute47(TEXT("skillpoints 2"));Check(P.RPG.Points==Points+2,TEXT("perk points granted"));C->Execute47(TEXT("xp 1000"));Check(P.RPG.Level>1,TEXT("XP triggers progression"));C->Execute47(TEXT("time 0"));Check(P.World->TimeOfDay==0,TEXT("midnight accepted"));C->Execute47(TEXT("time 24"));Check(P.World->TimeOfDay==0,TEXT("invalid time rejected"));C->Execute47(TEXT("god on"));Check(P.bGod47,TEXT("god enabled"));C->Execute47(TEXT("god off"));Check(!P.bGod47,TEXT("god disabled"));
 });
 Add(TEXT("console input and display"),1,[this](ALWCharacter& P){auto* C=CastChecked<ULWConsole47>(GetWorld()->GetGameViewport()->ViewportConsole);P.bTrigger=true;C->InputKey(FInputDeviceId::CreateFromInternalId(0),EKeys::Tilde,IE_Pressed);Check(C->ConsoleActive()&&P.bConsole47&&UGameplayStatics::IsGamePaused(&P),TEXT("tilde opens console and pauses"));Check(!P.CanAct()&&!P.bTrigger,TEXT("console prevents gameplay and held fire"));C->InputKey(FInputDeviceId::CreateFromInternalId(0),EKeys::Tilde,IE_Released);C->SetInputText(TEXT("money 20"));C->InputKey(FInputDeviceId::CreateFromInternalId(0),EKeys::Enter,IE_Released);Check(P.Money==5030,TEXT("typed command executes through input"));C->ConsoleCommand(TEXT("help"));},[this](ALWCharacter&){CaptureV2(TEXT("Console47_Help"));});
 Add(TEXT("close console"),.5,[this](ALWCharacter& P){auto* C=CastChecked<ULWConsole47>(GetWorld()->GetGameViewport()->ViewportConsole);C->InputKey(FInputDeviceId::CreateFromInternalId(0),EKeys::Tilde,IE_Pressed);Check(!C->ConsoleActive()&&!P.bConsole47&&!UGameplayStatics::IsGamePaused(&P),TEXT("closing restores gameplay pause state"));P.ToggleMenu();C->FakeGotoState(FName(TEXT("Open")));C->FakeGotoState(NAME_None);Check(P.bMenu&&UGameplayStatics::IsGamePaused(&P),TEXT("console preserves existing menu pause"));P.ToggleMenu();});
}

