#include "Materials/MaterialInterface.h"
#include "LWCharacter.h"
#include "LWWeaponParts39.h"
#include "LWWeaponMods.h"
#include "LWWorld.h"
#include "Components/StaticMeshComponent.h"
#include "Components/PointLightComponent.h"
void ALWCharacter::ConfigureCustom39(){for(auto& C:CustomMeshes39)if(C)C->DestroyComponent();CustomMeshes39.Empty();const auto* G=ActiveGun();if(!G||G->Parts39.IsEmpty()||!World)return;WeaponMesh->SetStaticMesh(nullptr);WeaponMesh->SetRelativeTransform(FTransform::Identity);for(const auto& P:G->Parts39){if(LWItems::Def(P.Definition).Category==TEXT("Attachment"))continue;auto* C=NewObject<UStaticMeshComponent>(this);C->SetupAttachment(WeaponMesh);C->SetStaticMesh(World->Mesh(LWParts39::Mesh(P.Definition)));C->SetRelativeTransform(P.Transform);C->SetCollisionEnabled(ECollisionEnabled::NoCollision);C->SetCanEverAffectNavigation(false);C->SetLightingChannels(false,true,false);C->SetCastShadow(false);C->ComponentTags.Add(FName(*P.Id.ToString()));C->RegisterComponent();if(P.Tier>=2&&P.Skin>=0){auto* Finish=World->Material(FName(*FString::Printf(TEXT("WeaponSkin24_%d_%02d"),P.Tier,P.Skin)));if(Finish)for(int i=0;i<C->GetNumMaterials();++i){auto* Mat=C->GetMaterial(i);if(Mat&&!Mat->GetName().Contains(TEXT("Rubber")))C->SetMaterial(i,Finish);}}CustomMeshes39.Add(C);}const auto Barrels=LWParts39::Barrels(*G);if(Muzzle&&!Barrels.IsEmpty())Muzzle->SetRelativeLocation(Barrels[0].GetLocation());}
void ALWCharacter::UpdateCustom39(){const auto* G=ActiveGun();const bool Custom=G&&!G->Parts39.IsEmpty();const bool Visible=Custom&&CanAct()&&!(bAim&&(LWMods::Has(G,TEXT("att_scope4"))||LWMods::Has(G,TEXT("att_scope8"))));for(auto& C:CustomMeshes39)if(C)C->SetVisibility(Visible);if(!Custom)return;int PartIndex=0;for(const auto& Part:G->Parts39){if(LWItems::Def(Part.Definition).Category==TEXT("Attachment"))continue;if(!CustomMeshes39.IsValidIndex(PartIndex))break;auto* C=CustomMeshes39[PartIndex++].Get();if(!C)continue;const auto* P=&Part;FTransform T=P->Transform;const auto* D=LWParts39::Find(P->Definition);if(D&&bReloading){const float Progress=FMath::Clamp(ReloadElapsed/FMath::Max(.1f,ReloadDuration),0.f,1.f);const float Motion=FMath::Sin(Progress*PI);if(D->Group==TEXT("Barrel")&&(Weapon==8||Weapon==11))T.SetRotation((FQuat(FVector::YAxisVector,FMath::DegreesToRadians(40*Motion))*T.GetRotation()).GetNormalized());if(D->Group==TEXT("Feed")){T.AddToTranslation(Weapon==3?FVector(0,-12*Motion,0):FVector(0,0,-20*Motion));}}if(D&&D->Group==TEXT("Barrel")&&(Weapon==16||Weapon==20)&&MovingPart)T.SetRotation((MovingPart->GetRelativeRotation().Quaternion()*P->Transform.GetRotation()).GetNormalized());
 if(Weapon==18&&bReloading&&D&&D->Group==TEXT("Feed"))T=FTransform(WeaponRoot->GetComponentQuat(),WeaponRoot->GetComponentTransform().TransformPosition(P->Transform.GetLocation())).GetRelativeTransform(WeaponMesh->GetComponentTransform());
 C->SetRelativeTransform(T);if(Weapon==18&&bReloading&&D&&D->Group!=TEXT("Feed")&&ReloadElapsed>=.95f&&ReloadElapsed<=1.25f)C->SetVisibility(false);
 }if(Custom){WeaponMesh->SetVisibility(false);if(MovingPart)MovingPart->SetVisibility(false);if(SecondPart)SecondPart->SetVisibility(false);}}
