if(FParse::Param(FCommandLine::Get(),TEXT("LWDestiny71Smoke"))){
 Add(TEXT("Destiny71 setup"),1,[this](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.SetActorTickEnabled(false);P.ClosePanels();P.bMenu=false;P.bSafehouse=false;P.bGod47=true;UGameplayStatics::SetGamePaused(&P,false);P.SetMenuInput(false);P.GetCharacterMovement()->DisableMovement();P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.World->TickWeather(.1,&P);P.WeaponRoot->SetVisibility(false,true);P.Flashlight->SetVisibility(false);Cast<APlayerController>(P.Controller)->GetHUD()->bShowHUD=false;});
 Add(TEXT("Destiny71 construction"),3,[this](ALWCharacter& P){const auto* S=LWNY69::Sites().FindByPredicate([](const auto& A){return A.Type==69;});Check(S!=nullptr,TEXT("Destiny landmark exists"));if(!S)return;FLWContainerRecord Legacy;Legacy.Id=FName(*FString::Printf(TEXT("ny69_%u_000"),S->Id));Legacy.Items.Add(LWItems::Make(TEXT("medkit"),2));Legacy.Width=14;Legacy.Height=20;P.World->Containers.Add(Legacy.Id,Legacy);P.SetActorLocation(FVector(S->Position,9000));P.World->Stream(P.GetActorLocation(),true);auto* C=P.World->Chunks.FindRef(LWGen::ChunkAt(S->Position)).Get();Check(C&&C->Ready68,TEXT("landmark construction complete"));
  FCollisionQueryParams Q(NAME_None,false,&P);int Blocked=0,Unsupported=0;for(const auto& E:LWDestiny71::Data().Escalators)for(int Side:{-1,1})for(int J=1;J<53;J++){auto N=FVector2D(-E.D.Y,E.D.X);FVector A(S->Position+E.P+N*(Side*140)+E.D*(-600+(J+.5)*1200/54),24+E.Level*600+(J+1)*600.f/54+4);FHitResult H;if(GetWorld()->LineTraceSingleByChannel(H,A,A+FVector(0,0,185),ECC_Visibility,Q)){Blocked++;if(Blocked<30)UE_LOG(LogTemp,Warning,TEXT("DESTINY71 head blocked level %d step %d by %s at %s"),E.Level,J,*GetNameSafe(H.GetComponent()),*H.ImpactPoint.ToString());}if(!GetWorld()->LineTraceSingleByChannel(H,A,A-FVector(0,0,35),ECC_Visibility,Q))Unsupported++;}Check(Blocked==0,TEXT("all escalators have standing headroom"));Check(Unsupported==0,TEXT("all escalator treads have collision"));
  int Stock=0;for(TActorIterator<ALWWorldObject> O(GetWorld());O;++O)if(O->RecordId.ToString().StartsWith(TEXT("destiny71_")))Stock++;Check(Stock>150,TEXT("shops and seating have interactions"));bool Restored=false;for(const auto& Pair:P.World->Containers)if(Pair.Key.ToString().StartsWith(TEXT("destiny71_"))&&Pair.Value.Width==14&&Pair.Value.Height==20&&Pair.Value.Items.Num()==1&&Pair.Value.Items[0].Definition==TEXT("medkit")&&Pair.Value.Items[0].Count==2)Restored=true;Check(Restored,TEXT("saved stock survives the mall reconstruction"));
 });
 for(int Shot=0;Shot<5;Shot++)Add(FString::Printf(TEXT("Destiny71 view %d"),Shot),2,[this,Shot](ALWCharacter& P){const auto* S=LWNY69::Sites().FindByPredicate([](const auto& A){return A.Type==69;});if(!S)return;const auto& D=LWDestiny71::Data();FVector At,Look;
  if(Shot==0){At=FVector(-42000,-45000,30000);Look=FVector(0,0,800);}
  else if(Shot==1){auto Dir=(D.CanyonB-D.CanyonA).GetSafeNormal();At=FVector((D.CanyonA+D.CanyonB)*.5+FVector2D(-Dir.Y,Dir.X)*750,715);Look=FVector(D.CanyonB,1600);}
  else if(Shot==2){At=FVector(D.Atrium+FVector2D(-450,-300),720);Look=FVector(D.Atrium+FVector2D(2000,0),1000);}
  else if(Shot==3){At=FVector(D.Carousel+(D.Atrium-D.Carousel).GetSafeNormal()*1000,1320);Look=FVector(D.Carousel,1470);}
  else {At=FVector(D.Entries[0]+(D.Entries[0]-D.Atrium).GetSafeNormal()*4500,1600);Look=FVector(D.Entries[0],1000);}
  P.SetActorLocation(FVector(S->Position,0)+At);P.Controller->SetControlRotation((FVector(S->Position,0)+Look-P.GetPawnViewLocation()).Rotation());P.World->Sky->SetActorLocation(P.GetActorLocation());P.World->TickWeather(.1,&P);
 },[this,Shot](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Destiny71_%d"),Shot));});
 return;
}


