if(FParse::Param(FCommandLine::Get(),TEXT("LWDebug67Smoke"))){
 Add(TEXT("67 console opens menu"),1,[this](ALWCharacter& P){
  auto* C=CastChecked<ULWConsole47>(GetWorld()->GetGameViewport()->ViewportConsole);
  Check(C->Execute47(TEXT("debugmenu")).Contains(TEXT("Start or load")),TEXT("debug menu rejects title screen"));P.NewGame();P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.SetActorTickEnabled(false);P.EnterSafehouse();P.ClosePanels();P.bMenu=false;UGameplayStatics::SetGamePaused(&P,false);P.SetMenuInput(false);P.Inventory.Empty();P.Money=100;
  auto* PC=Cast<APlayerController>(P.Controller);PC->ConsoleCommand(TEXT("r.SetRes 1600x1000w"));
  P.bTrigger=true;C->FakeGotoState(TEXT("Open"));C->SetInputText(TEXT("debugmenu"));C->InputKey(FInputDeviceId::CreateFromInternalId(0),EKeys::Enter,IE_Released);
  Check(P.DebugMenu67&&P.DebugMenu67->IsOpen()&&P.bDebug67&&!C->ConsoleActive(),TEXT("typed console command opens modal menu and closes console"));Check(UGameplayStatics::IsGamePaused(&P)&&!P.CanAct()&&!P.bTrigger,TEXT("debug menu pauses world and releases fire"));
 },[this](ALWCharacter&){CaptureV2(TEXT("Debug67_Cheats"));});
 Add(TEXT("67 item search and grant"),1,[this](ALWCharacter& P){auto* M=P.DebugMenu67.Get();if(!RequireV2(M&&M->IsOpen(),TEXT("debug menu available")))return;
  M->SetSection(ELWDebugSection67::Items);for(TCHAR Ch:FString(TEXT("MEDKIT")))FSlateApplication::Get().ProcessKeyCharEvent(FCharacterEvent(Ch,FModifierKeysState(),0,false));UE_LOG(LogTemp,Display,TEXT("LW_DEBUG67 search=%s focus=%s"),*M->Search,FSlateApplication::Get().GetKeyboardFocusedWidget().IsValid()?*FSlateApplication::Get().GetKeyboardFocusedWidget()->GetTypeAsString():TEXT("none"));Check(M->Search==TEXT("MEDKIT"),TEXT("real Slate text input reaches live search"));Check(M->Visible.Num()==1&&M->Visible[0]->Id==TEXT("medkit"),TEXT("live item filtering finds only medkit"));Check(M->Select(TEXT("medkit")),TEXT("matching item can be selected"));M->Amount=3;
  TFunction<TSharedPtr<SWidget>(TSharedRef<SWidget>)> FindAction;FindAction=[&FindAction](TSharedRef<SWidget> W)->TSharedPtr<SWidget>{if(W->GetTag()==TEXT("Debug67Action"))return W;auto* Children=W->GetChildren();for(int I=0;I<Children->Num();I++)if(auto Found=FindAction(Children->GetChildAt(I)))return Found;return nullptr;};
  auto Window=GetWorld()->GetGameViewport()->GetWindow();auto Action=Window?FindAction(Window.ToSharedRef()):nullptr;Check(Action.IsValid(),TEXT("execute action is reachable in Slate widget tree"));if(Action){const FVector2D At=Action->GetCachedGeometry().GetAbsolutePosition()+Action->GetCachedGeometry().GetAbsoluteSize()*.5;TSet<FKey> Buttons;FSlateApplication::Get().ProcessMouseMoveEvent(FPointerEvent(0,At,At,Buttons,EKeys::Invalid,0,FModifierKeysState()));Buttons.Add(EKeys::LeftMouseButton);FSlateApplication::Get().ProcessMouseButtonDownEvent(Window->GetNativeWindow(),FPointerEvent(0,At,At,Buttons,EKeys::LeftMouseButton,0,FModifierKeysState()));Buttons.Empty();FSlateApplication::Get().ProcessMouseButtonUpEvent(FPointerEvent(0,At,At,Buttons,EKeys::LeftMouseButton,0,FModifierKeysState()));}
  Check(P.CountSupply(TEXT("medkit"))==3&&M->Status.Contains(TEXT("Added")),TEXT("actual Slate action button grants requested items"));Check(!P.bTrigger,TEXT("actual menu mouse click does not fire weapon"));
  M->SetSearch(TEXT("zz_no_such_entry_67"));Check(M->Visible.IsEmpty()&&!M->Selected,TEXT("empty results clear stale selection"));M->Execute();Check(P.CountSupply(TEXT("medkit"))==3,TEXT("empty selection cannot grant previous item"));M->SetSearch(TEXT(""));M->SetCategory(TEXT("Weapon"));Check(!M->Visible.IsEmpty()&&!M->Visible.ContainsByPredicate([](const auto& E){return E->Category!=TEXT("Weapon");}),TEXT("category filter narrows item list"));M->SetSort(1);Check(M->Sort==1&&!M->Descending,TEXT("sort column changes"));M->SetSort(1);Check(M->Descending,TEXT("clicking same column reverses order"));
 },[this](ALWCharacter&){CaptureV2(TEXT("Debug67_Items"));});
 Add(TEXT("67 quick cheats and modal input"),.5,[this](ALWCharacter& P){auto* M=P.DebugMenu67.Get();if(!M)return;M->SetSection(ELWDebugSection67::Cheats);M->Select(TEXT("money"));M->Amount=500;M->Execute();Check(P.Money==600,TEXT("quick credits executes"));M->Select(TEXT("heal"));P.Health=10;M->Execute();Check(P.Health==P.MaxHealth(),TEXT("quick heal executes"));M->Select(TEXT("time"));M->Amount=0;M->Execute();Check(P.World->TimeOfDay==0,TEXT("time control accepts midnight"));M->Select(TEXT("god"));const FModifierKeysState Ctrl(false,false,true,false,false,false,false,false,false);FSlateApplication::Get().ProcessKeyDownEvent(FKeyEvent(EKeys::F,Ctrl,0,false,0,0));FSlateApplication::Get().ProcessKeyDownEvent(FKeyEvent(EKeys::Enter,Ctrl,0,false,0,0));Check(P.bGod47,TEXT("Ctrl+F then Ctrl+Enter executes with search focused"));
  auto* Input=ULWPlayerInput51::Get51(&P);FInputKeyEventArgs Key;Key.Key=EKeys::LeftMouseButton;Key.Event=IE_Pressed;Key.AmountDepressed=1;Input->InputKey(Key);Check(!P.bTrigger,TEXT("menu clicks do not attack"));FSlateApplication::Get().ProcessKeyDownEvent(FKeyEvent(EKeys::Escape,FModifierKeysState(),0,false,0,0));Check(!P.bDebug67&&!P.bUIInputActive&&!UGameplayStatics::IsGamePaused(&P),TEXT("Escape from focused text input closes and restores gameplay"));
  P.ToggleMenu();ULWDebugMenu67::OpenFor(&P);M->Close();Check(P.bMenu&&P.bUIInputActive&&UGameplayStatics::IsGamePaused(&P),TEXT("closing preserves prior pause menu"));P.ToggleMenu();
 });
 Add(TEXT("67 NPC and vehicle selection"),1,[this](ALWCharacter& P){
  P.bSafehouse=false;P.SetActorLocation(FVector(-300000,-300000,180));P.SetActorRotation(FRotator::ZeroRotator);P.GetCharacterMovement()->DisableMovement();auto* Floor=GetWorld()->SpawnActor<ALWChunk>(FVector(-300000,-300000,0),FRotator::ZeroRotator);Floor->Box(P.World,TEXT("Concrete"),FVector(0,0,-50),FVector(15000,15000,100));
  auto* C=CastChecked<ULWConsole47>(GetWorld()->GetGameViewport()->ViewportConsole);C->ConsoleCommand(TEXT("debug"));Check(P.bDebug67,TEXT("debug alias opens menu"));auto* M=P.DebugMenu67.Get();M->SetSection(ELWDebugSection67::NPCs);M->SetCategory(TEXT("Friendly"));Check(M->Visible.Num()==4,TEXT("friendly NPC category complete"));M->Select(TEXT("survivor"));M->Execute();Check(M->Status.Contains(TEXT("Spawned 1 / 1")),TEXT("NPC selection spawns requested type"));
  P.SetActorRotation(FRotator(0,180,0));M->SetSection(ELWDebugSection67::Vehicles);M->Select(TEXT("dirtbike"));M->Execute();Check(M->Status.Contains(TEXT("Spawned")),TEXT("vehicle selection spawns requested model"));
 },[this](ALWCharacter&){CaptureV2(TEXT("Debug67_Vehicles"));});
 Add(TEXT("67 POI locator"),.1,[this](ALWCharacter& P){auto* M=P.DebugMenu67.Get();M->SetSection(ELWDebugSection67::POIs);M->SetSort(1);Check(M->Select(TEXT("21")),TEXT("casino POI selected by exact ID"));P.ClearWaypoint();M->Amount=5;M->Execute();Check(M->LocateRequest>0,TEXT("POI lookup starts asynchronously from menu"));},[this](ALWCharacter& P){auto* M=P.DebugMenu67.Get();Check(P.bWaypoint&&M->Status.Contains(TEXT("Waypoint set")),TEXT("asynchronous POI result appears in menu and sets waypoint"));CaptureV2(TEXT("Debug67_POIs"));});
 V2->Steps.Last().Ready=[](ALWCharacter& P){return P.DebugMenu67&&P.DebugMenu67->LocateRequest==0;};V2->Steps.Last().TimeoutSeconds=90;
 Add(TEXT("67 POI result screenshot"),.5,[](ALWCharacter&){});
 Add(TEXT("67 search cancellation and close"),.5,[this](ALWCharacter& P){auto* M=P.DebugMenu67.Get();P.ClearWaypoint();M->Amount=20;M->Execute();M->CancelSearch();Check(M->LocateRequest==0&&M->Status.Contains(TEXT("cancelled")),TEXT("location search can be cancelled"));M->Execute();M->Close();Check(!P.bDebug67&&!P.bConsole47&&!UGameplayStatics::IsGamePaused(&P)&&M->LocateRequest==0,TEXT("closing cancels outstanding lookup and restores controls"));},[this](ALWCharacter& P){Check(!P.bWaypoint,TEXT("cancelled search cannot later alter waypoint"));});
 return;
}
