void ALWGameMode::BuildDungeonSmoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,180,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};
 struct FState{TWeakObjectPtr<ALWChunk> C;TWeakObjectPtr<ALWDungeon> D;};auto State=MakeShared<FState>();
 Add(TEXT("dungeon setup"),1,[this](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;P.World->WeatherOverride=0;P.World->TimeOfDay=12;P.Health=10000;P.World->TickWeather(0,&P);P.Flashlight->SetVisibility(false);});
 for(int T=22;T<32;T++){
 Add(TEXT("build and traverse dungeon"),3,[this,State,T](ALWCharacter& P){if(State->C.IsValid())State->C->Destroy();P.ClosePanels();P.DungeonStatus.Empty();auto* C=GetWorld()->SpawnActor<ALWChunk>();State->C=C;LWGen::FSite S;S.Type=T;S.Size=LWPlaces::Size(T);S.Position=FVector2D(20000,20000);S.Id=270000+T;
 C->BuildingSurfaces=true;C->Building(P.World,S);C->BuildingSurfaces=false;C->FlushSurfaces();C->SetActorLocation(FVector(0,0,5000));for(auto A:C->Residents)if(IsValid(A)){A->AddActorWorldOffset(FVector(0,0,5000));if(auto* D=Cast<ALWDungeon>(A)){State->D=D;D->SetActorTickEnabled(false);for(auto& G:D->Guards)G.Position.Z+=5000;}}
 auto* D=State->D.Get();if(!RequireV2(D!=nullptr,TEXT("dungeon controller built")))return;const auto& Profile=LWDungeons::Profile(T);Check(D->Guards.Num()>=18,TEXT("substantial authored guard population"));Check(!D->Ready(),TEXT("end reserve starts secured"));Check(!D->Claim(&P),TEXT("cannot bypass objective requirements"));
 FCollisionQueryParams Q;Q.AddIgnoredActor(&P);int PassageFailures=0,FloorFailures=0;for(int F=0;F<Profile.Floors;F++){auto L=LWDungeons::Layout(T,S.Id,F);for(int I=0;I<L.Links.Num();I++){FVector A=D->At(LWDungeons::Room(T,F,I))+FVector(0,0,92);FHitResult Hit;if(!GetWorld()->LineTraceSingleByChannel(Hit,A,A-FVector(0,0,110),ECC_WorldStatic,Q)||FMath::Abs(Hit.ImpactPoint.Z-(A.Z-92))>2)FloorFailures++;for(int K=0;K<2;K++)if(L.Links[I]&(1<<K)){FVector B=D->At(LWDungeons::Room(T,F,I+(K==0?1:Profile.Columns)))+FVector(0,0,92);if(GetWorld()->SweepSingleByChannel(Hit,A,B,FQuat::Identity,ECC_WorldStatic,FCollisionShape::MakeCapsule(32,86),Q)&&GetWorld()->SweepSingleByChannel(Hit,A+FVector(0,0,30),B+FVector(0,0,30),FQuat::Identity,ECC_WorldStatic,FCollisionShape::MakeCapsule(32,86),Q)){PassageFailures++;UE_LOG(LogTemp,Warning,TEXT("DUNGEON_PASSAGE %d floor %d room %d hit %s"),T,F,I,*GetNameSafe(Hit.GetComponent()));}}}}
 Check(FloorFailures==0,TEXT("every dungeon room has a usable floor"));Check(PassageFailures==0,TEXT("all intended room passages clear for player capsule"));
 const float Front=-Profile.Rows*LWDungeons::Cell*.5f+LWDungeons::Apron*.5f,StairX=-Profile.Columns*LWDungeons::Cell*.5f+LWDungeons::Cell*.5f;
 int Stairs=0;for(int F=0;F<Profile.Floors-1;F++)for(int Flight=0;Flight<2;Flight++)for(int J=0;J<14;J++){float Z=36+F*500+(Flight?250:0)+(J+1)*500.f/28;FVector A=D->At(FVector(StairX+(Flight?290:-290),Flight?Front-600+(J+.5f)*30:Front-180-(J+.5f)*30,Z+90));FHitResult H;if(!GetWorld()->LineTraceSingleByChannel(H,A,A-FVector(0,0,105),ECC_WorldStatic,Q)||FMath::Abs(H.ImpactPoint.Z-(A.Z-90))>2)Stairs++;}Check(Stairs==0,TEXT("every stair tread has correct height and collision"));
 LWV2Teleport(P,D->At(LWDungeons::Room(T,0,0))+FVector(0,0,94));for(int Step=0;Step<3;Step++)D->Tick(.45f);int Active=0;for(auto& G:D->Guards)if(G.Actor.IsValid())Active++;Check(Active>0&&Active<=24,TEXT("guard director activates enemies within its budget"));P.Controller->SetControlRotation(FRotator(-4,45,0));
 },[this,T](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Dungeon27_%d_Entry"),T));});
 Add(TEXT("security and reward persistence"),2,[this,State,T](ALWCharacter& P){auto* D=State->D.Get();if(!D)return;for(int I=0;I<3;I++){Check(D->Activate(I,&P),TEXT("security control activates"));Check(!D->Activate(I,&P),TEXT("security control cannot be farmed"));}Check(!D->Ready(),TEXT("living vault guards still seal reserve"));for(auto& G:D->Guards)if(G.Warden)P.World->KilledZombies.Add(G.Id);Check(D->Ready(),TEXT("controls and defeated wardens release reserve"));int64 Money=P.Money;int XP=P.RPG.XP;Check(D->Claim(&P),TEXT("completed dungeon pays reward"));Check(P.Money==Money+LWDungeons::Credits(T)&&P.RPG.XP==XP+LWDungeons::XP(T),TEXT("correct credits and XP payout"));auto* C=P.World->Containers.Find(D->Key(TEXT("reserve")));Check(C&&C->Items.Num()>=8,TEXT("large persistent reward inventory exists"));if(C){TSet<FGuid> IDs;int Guns=0;for(const auto& I:C->Items){Check(I.Id.IsValid()&&!IDs.Contains(I.Id)&&!LWItems::Def(I.Definition).Id.IsNone()&&I.Count<=LWItems::Def(I.Definition).MaxStack,TEXT("reward items valid unique and within stack limits"));IDs.Add(I.Id);Guns+=LWItems::Def(I.Definition).Category==TEXT("Weapon");}Check(Guns==2+LWDungeons::Profile(T).Scale,TEXT("guaranteed high-tier weapon count"));C->Items.Empty();}Money=P.Money;XP=P.RPG.XP;D->Claim(&P);Check(P.Money==Money&&P.RPG.XP==XP&&C&&C->Items.IsEmpty(),TEXT("reopening cannot reroll loot or duplicate payment"));const auto& Profile=LWDungeons::Profile(T);int End=LWDungeons::Layout(T,D->Site.Id,Profile.Floors-1).End;LWV2Teleport(P,D->At(LWDungeons::Room(T,Profile.Floors-1,End))+FVector(0,-450,94));P.Controller->SetControlRotation(FRotator(-2,80,0));
 },[this,T](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Dungeon27_%d_Reserve"),T));});
 }
 Add(TEXT("dungeon cleanup"),1,[State](ALWCharacter& P){P.DungeonStatus.Empty();if(State->C.IsValid())State->C->Destroy();P.World->WeatherOverride=-1;});
}
