if(FParse::Param(FCommandLine::Get(),TEXT("LWElectric74Smoke"))){
 struct FState74{TWeakObjectPtr<ALWVehicle> Coach,Hyper;TWeakObjectPtr<ACameraActor> Camera;};auto S=MakeShared<FState74>();
 Add(TEXT("74 electric fleet"),6,[this,S](ALWCharacter& P){
  P.NewGame();P.ClosePanels();P.bMenu=false;P.bStarted=true;P.bGod47=true;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.SetActorTickEnabled(false);P.GetCharacterMovement()->DisableMovement();P.World->TimeOfDay=12;P.World->TickWeather(0,&P);P.bCrust=false;
  auto* PC=Cast<APlayerController>(P.Controller);PC->ConsoleCommand(TEXT("r.ScreenPercentage 100"));PC->ConsoleCommand(TEXT("r.SetRes 1600x1000w"));PC->ConsoleCommand(TEXT("DisableAllScreenMessages"));PC->GetHUD()->bShowHUD=false;
  for(TActorIterator<ALWVehicle> V(GetWorld());V;++V)V->Destroy();P.World->Vehicles.Empty();P.SetActorLocation(FVector(20000,23000,50300));
  auto* Floor=GetWorld()->SpawnActor<ALWChunk>();Floor->SyncCollision68=true;Floor->Box(P.World,TEXT("Concrete"),FVector(20000,20000,49990),FVector(40000,40000,20));
  for(int I=0;I<2;I++){
   FLWVehicleRecord R;R.Model=I?TEXT("apex_ev"):TEXT("solstice_rv");R.Position=FVector(20000,20000+I*1500,50075);R.VIN=FGuid::NewGuid();R.Unlocked=R.Hotwired=true;R.FuelLootInitialized=true;R.FuelLitres=0;P.World->Vehicles.Add(I?TEXT("ev74_hyper"):TEXT("ev74_coach"),R);
   auto* V=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,I?TEXT("ev74_hyper"):TEXT("ev74_coach"),R.Position));if(!RequireV2(V!=nullptr,TEXT("electric vehicle spawns")))return;V->SetActorTickEnabled(false);if(I)S->Hyper=V;else S->Coach=V;
   Check(!V->SpawnPlacementPending,TEXT("vehicle footprint fits ground"));Check(V->IsElectric74()&&V->HasFuel()&&V->Record()->FuelLitres==0,TEXT("electric power works without petrol"));Check(V->DashTarget74&&V->DashMaterial74,TEXT("live dashboard render target allocated"));Check(V->Body->GetStaticMesh()->GetName().StartsWith(TEXT("SM_EV74_")),TEXT("new custom body mesh installed"));
  }
  auto* V=S->Coach.Get();if(!V)return;Check(V->Spec().Seats==6&&V->ShadesMesh66.Num()==15,TEXT("coach preserves seating and working window shades"));Check(V->Root->GetRelativeScale3D().Y>1.1,TEXT("widened residence cabin"));
  S->Camera=GetWorld()->SpawnActor<ACameraActor>();S->Camera->GetCameraComponent()->SetFieldOfView(65);S->Camera->SetActorLocation(V->GetActorLocation()+FVector(1200,1450,650));S->Camera->SetActorRotation((V->GetActorLocation()+FVector(0,0,130)-S->Camera->GetActorLocation()).Rotation());PC->SetViewTarget(S->Camera.Get());
 },[this](ALWCharacter&){CaptureV2(TEXT("EV74_CoachExterior"));});
 Add(TEXT("74 solar and battery"),.5,[this,S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;auto* R=V->Record();P.World->CloudAmount=0;P.World->TimeOfDay=12;R->SolarHours74=(P.World->DayNumber-1)*24.+11;R->BatteryKWh74=100;V->RoofCheck74=100;V->RoofClear74=true;V->TickBattery74(0);Check(R->BatteryKWh74>107&&V->SolarKW74>8,TEXT("solar roof charges in daylight"));
  R->BatteryKWh74=100;R->SolarHours74=(P.World->DayNumber-1)*24.+20;P.World->TimeOfDay=22;V->TickBattery74(0);Check(R->BatteryKWh74==100&&V->SolarKW74==0,TEXT("night produces no solar power"));
  P.World->TimeOfDay=12;R->SolarHours74=(P.World->DayNumber-1)*24.+11;V->RoofClear74=false;V->TickBattery74(0);Check(R->BatteryKWh74==100,TEXT("covered roof does not charge"));
  V->RoofClear74=true;R->SolarHours74=(P.World->DayNumber-1)*24.+12;V->EngineOn=true;V->Speed=1500;V->Throttle=1;V->TickBattery74(10);Check(R->BatteryKWh74<100,TEXT("traction draws from battery"));
  V->WasBrake42=true;V->TickBattery74(10);Check(V->PowerKW74<0,TEXT("braking recovers charge"));V->WasBrake42=false;V->Speed=V->Throttle=0;V->EngineOn=false;R->BatteryKWh74=200;
  Check(!V->Refuel(&P)&&R->FuelLitres==0,TEXT("gas cans cannot refill electric vehicles"));
 });
 Add(TEXT("74 moving cabin invariance"),.5,[this,S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;P.SetActorLocation(V->GetActorLocation()+FVector(450,230,0));if(!RequireV2(V->Enter(&P,-2),TEXT("enter enlarged cabin")))return;
  V->CabinEye=V->CabinToActor74(FVector(-70,0,225));P.SeatYaw=180;V->CabinMove=FVector2D::ZeroVector;const FVector Start=V->GetActorLocation(),Local=V->CabinEye;float Drift=0;
  for(int I=0;I<360;I++){const float A=I*.4f;V->SetActorLocationAndRotation(Start+FVector(I*14,FMath::Sin(I*.012f)*220,0),FRotator(FMath::Sin(I*.02f)*4,A,0));V->TickCabinWalk(1.f/60);P.TickVehicleSeat();FVector Expected=V->GetActorTransform().TransformPosition(Local);Drift=FMath::Max(Drift,float(FVector::Dist(P.Camera->GetComponentLocation(),Expected)));}
  Check(Drift<.5f,TEXT("zero platform drift through translation and turning"));Check(V->CabinEye.Equals(Local,.01),TEXT("standing still preserves cabin position"));
  V->SetActorLocationAndRotation(Start,FRotator::ZeroRotator);P.SeatYaw=180;V->CabinMove=FVector2D(1,0);V->SelfDriving74=V->AutoDriving=true;V->Speed=1000;
  for(int I=0;I<360;I++)V->TickCabinWalk(1.f/60);Check(V->ActorToCabin74(V->CabinEye).X< -790,TEXT("walk entire aisle while autopilot is moving"));
  V->CabinMove=FVector2D::ZeroVector;V->CabinVelocity74=FVector::ZeroVector;Check(V->ChangeSeat(1)&&V->PlayerSeat==1,TEXT("sit in passenger seat during travel"));V->StandInCamper();Check(V->PlayerSeat==-2&&V->SelfDriving74,TEXT("stand without disengaging autonomous driving"));
  Check(!V->ChangeSeat(-1),TEXT("driver handover requires controlled stop"));V->UseCamper(&P,TEXT("entry"));Check(!V->CamperDoorOpen,TEXT("entry stays locked while moving"));V->UseCamper(&P,TEXT("slides66"));Check(!V->Record()->Slides66,TEXT("slide rooms cannot deploy during travel"));
  V->UseCamper(&P,TEXT("tv66"));Check(V->Record()->TV66==1,TEXT("TV remains usable while traveling"));V->UseCamper(&P,TEXT("faucet66"));Check(V->Record()->Faucet66,TEXT("faucet remains usable while traveling"));
  V->Control(TEXT("fridge"));Check(P.bInventory,TEXT("interior storage accessible through actual interact control in motion"));P.ClosePanels();V->Control(TEXT("dining_storage"));Check(P.bInventory,TEXT("dining storage routes through interact control"));P.ClosePanels();V->Speed=0;V->SelfDriving74=V->AutoDriving=false;V->Exit(true);
 });
 Add(TEXT("74 cabin movement rates and collision"),.5,[this,S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;P.SetActorLocation(V->GetActorLocation());if(!RequireV2(V->Enter(&P,-2),TEXT("reenter cabin")))return;
  double Dist[3];int Index=0;for(int Hz:{30,60,144}){V->CabinEye=V->CabinToActor74(FVector(-70,0,225));V->CabinVelocity74=FVector::ZeroVector;V->CabinMove=FVector2D(1,0);P.SeatYaw=180;for(int I=0;I<Hz*2;I++)V->TickCabinWalk(1.f/Hz);Dist[Index++]=V->ActorToCabin74(V->CabinEye).X;}
  Check(FMath::Abs(Dist[0]-Dist[2])<3,TEXT("30-144 fps walking distance is stable"));
  V->CabinEye=V->CabinToActor74(FVector(-470,0,225));V->CabinVelocity74=FVector::ZeroVector;P.SeatYaw=-90;for(int I=0;I<120;I++)V->TickCabinWalk(1.f/60);Check(V->ActorToCabin74(V->CabinEye).Y> -60,TEXT("kitchen collision prevents walking through cabinets"));
  V->CabinMove=FVector2D::ZeroVector;V->CabinVelocity74=FVector::ZeroVector;V->CabinEye=V->CabinToActor74(FVector(35,140,225));V->CamperDoorOpen=true;V->CamperDoorAngle=-100;V->TickCamperEntry(0);P.SeatYaw=90;V->CabinMove=FVector2D(1,0);for(int I=0;I<120&&P.Vehicle;I++){V->TickCabinWalk(1.f/60);P.TickVehicleSeat();}
  Check(!P.Vehicle&&P.GetCharacterMovement()->MovementMode==MOVE_Walking,TEXT("walking exit restores character movement"));P.GetCharacterMovement()->DisableMovement();
 });
 Add(TEXT("74 self driving without crew"),.5,[this,S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;P.ClosePanels();P.SetActorLocation(V->GetActorLocation());V->Enter(&P,-1);P.bWaypoint=false;V->ToggleSelfDrive74();Check(!V->SelfDriving74,TEXT("autopilot requires destination"));
  P.bWaypoint=true;P.Waypoint=FVector2D(V->GetActorLocation())+FVector2D(6000,0);V->ToggleSelfDrive74();Check(V->SelfDriving74&&!V->Chauffeur,TEXT("route engages without companion driver"));
  V->TickAutopilot(.016f);Check(V->AutoDriving&&V->EngineOn&&V->DrivePath.Num()>1,TEXT("autonomous route drives shared controller"));
  V->Speed=800;V->RequestDriverStop();V->TickAutopilot(.016);Check(V->StopRequested&&V->SelfDriving74&&V->Throttle==0,TEXT("stop request brakes before relinquishing control"));V->Speed=0;V->TickAutopilot(.016);Check(!V->SelfDriving74&&!V->AutoDriving&&!V->EngineOn,TEXT("stopped autopilot parks and powers down"));
  V->Record()->Slides66=true;V->SlideAlpha66=1;V->ToggleSelfDrive74();V->TickAutopilot(.016f);Check(V->SelfDriving74&&!V->EngineOn&&!V->Record()->Slides66,TEXT("autopilot retracts camp equipment before departure"));for(int I=0;I<420;I++)V->TickLuxury66(1.f/60);V->TickAutopilot(.016f);Check(V->AutoDriving&&V->EngineOn,TEXT("autopilot resumes when camping equipment stowed"));V->SelfDriving74=V->AutoDriving=false;V->EngineOn=false;V->Speed=0;V->Exit(true);
 });
 Add(TEXT("74 integrated autonomous travel"),.5,[this,S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;const FTransform Start=V->GetActorTransform();P.SetActorLocation(V->GetActorLocation());V->Enter(&P,-1);P.bWaypoint=true;P.Waypoint=FVector2D(Start.GetLocation())+FVector2D(12000,0);V->DriveGoal=P.Waypoint;V->DrivePath={FVector2D(Start.GetLocation()),P.Waypoint};V->DriveStep=1;V->DriveComplete=true;V->SelfDriving74=V->AutoDriving=true;V->StandInCamper();V->CabinEye=V->CabinToActor74(FVector(-70,0,225));P.SeatYaw=180;float Drift=0;
  for(int I=0;I<720;I++){V->CabinMove=I<160?FVector2D(1,0):FVector2D::ZeroVector;V->Tick(1.f/60);P.TickVehicleSeat();Drift=FMath::Max(Drift,float(FVector::Dist(P.Camera->GetComponentLocation(),V->GetActorTransform().TransformPosition(V->CabinEye))));}
  Check(FVector::Dist2D(Start.GetLocation(),V->GetActorLocation())>2000,TEXT("full vehicle tick propels autonomous coach"));Check(Drift<.5f&&V->ActorToCabin74(V->CabinEye).X< -400,TEXT("player walks while real driving controller moves coach"));V->Speed=0;V->StopRequested=true;V->Exit(true);Check(!V->StopRequested&&!V->SelfDriving74&&!V->AutoDriving,TEXT("forced exit releases autonomous braking for next driver"));V->SetActorTransform(Start);V->EngineOn=false;V->Steer=V->Throttle=V->SteeringAngle=0;V->StopDriveAudio();
 });
 Add(TEXT("74 interior and screen"),1,[S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;V->Record()->TV66=2;V->TickLuxury66(0);V->DrawDashboard74();auto* C=S->Camera.Get();C->GetCameraComponent()->SetFieldOfView(84);C->SetActorLocation(V->Root->GetComponentTransform().TransformPosition(FVector(-130,0,221)));C->SetActorRotation(FRotator(-4,180,0));Cast<APlayerController>(P.Controller)->SetViewTarget(C);},[this](ALWCharacter&){CaptureV2(TEXT("EV74_Residence"));});
 Add(TEXT("74 dashboard view"),1,[S](ALWCharacter& P){auto* V=S->Coach.Get();if(!V)return;P.SetActorLocation(V->GetActorLocation());V->Enter(&P,-1);V->DrawDashboard74();auto* C=S->Camera.Get();C->GetCameraComponent()->SetFieldOfView(78);C->SetActorLocation(V->GetActorTransform().TransformPosition(V->DriverEye()));C->SetActorRotation(FRotator(-18,16,0));Cast<APlayerController>(P.Controller)->SetViewTarget(C);},[this](ALWCharacter&){CaptureV2(TEXT("EV74_Dashboard"));});
 Add(TEXT("74 hypercar exterior"),1,[S](ALWCharacter& P){if(P.Vehicle)P.Vehicle->Exit(true);auto* V=S->Hyper.Get();if(!V)return;auto* C=S->Camera.Get();C->GetCameraComponent()->SetFieldOfView(58);C->SetActorLocation(V->GetActorLocation()+FVector(630,740,290));C->SetActorRotation((V->GetActorLocation()+FVector(0,0,25)-C->GetActorLocation()).Rotation());},[this](ALWCharacter&){CaptureV2(TEXT("EV74_HyperExterior"));});
 Add(TEXT("74 hypercar cockpit"),1,[this,S](ALWCharacter& P){auto* V=S->Hyper.Get();if(!V)return;P.SetActorLocation(V->GetActorLocation());Check(V->Enter(&P,-1),TEXT("enter hypercar"));V->Ignition();Check(V->EngineOn,TEXT("hypercar starts with battery and zero petrol"));V->TickElectricAudio74(.05f,false,.5f);Check(V->DriveAudio.Num()==5&&IsValid(V->DriveAudio[0]),TEXT("electric motor audio loads"));V->DrawDashboard74();auto* C=S->Camera.Get();C->GetCameraComponent()->SetFieldOfView(84);C->SetActorLocation(V->GetActorTransform().TransformPosition(V->DriverEye()));C->SetActorRotation(FRotator(-12,15,0));Cast<APlayerController>(P.Controller)->SetViewTarget(C);},[this](ALWCharacter&){CaptureV2(TEXT("EV74_HyperCockpit"));});
 Add(TEXT("74 cleanup and compatibility"),.5,[this,S](ALWCharacter& P){if(P.Vehicle){P.Vehicle->Speed=0;P.Vehicle->Exit(true);}CollectGarbage(RF_NoFlags);for(auto V:{S->Coach,S->Hyper})if(V.IsValid()){V->Headlights=true;V->Tick(.016);Check(V->Headlamps.Num()==2&&IsValid(V->Headlamps[0]),TEXT("lights survive exit and garbage collection"));Check(V->Record()->VIN.IsValid(),TEXT("persistent vehicle identity remains intact"));}P.SetActorTickEnabled(true);P.World->SetActorTickEnabled(true);});
 Add(TEXT("74 finished exterior"),1,[S](ALWCharacter& P){auto* V=S->Coach.Get();auto* C=S->Camera.Get();if(!V||!C)return;C->GetCameraComponent()->SetFieldOfView(65);C->SetActorLocation(V->GetActorLocation()+FVector(1200,1450,650));C->SetActorRotation((V->GetActorLocation()+FVector(0,0,130)-C->GetActorLocation()).Rotation());Cast<APlayerController>(P.Controller)->SetViewTarget(C);},[this](ALWCharacter&){CaptureV2(TEXT("EV74_CoachExterior"));});
 return;
}
