#include "LWVoice44.h"
#include "LWZombie.h"
#include "LWWorld.h"
#include "LWCharacter.h"
#include "LWResident.h"
#include "LWWeaponMods.h"
#include "LWLootTable.h"
#include "Components/CapsuleComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMeshActor.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Engine/World.h"
#include "Engine/StaticMesh.h"
#include "Kismet/GameplayStatics.h"
FString ALWZombie::EnemyName()const{static const TCHAR* Names[]={TEXT("ZOMBIE"),TEXT("RAIDER"),TEXT("RABID DOG"),TEXT("MANNEQUIN"),TEXT("MUTATED MOOSE"),TEXT("TITAN"),TEXT("DEATHCLAW"),TEXT("GIANT SCORPION"),TEXT("ZOMBIE KAREN"),TEXT("BEHEMOTH"),TEXT("COLOSSUS"),TEXT("WORLD EATER")};FString N=CustomName.IsEmpty()?FString(Names[FMath::Clamp(int(Kind),0,11)]):CustomName;if(Stars){N=TEXT("LEGENDARY ")+N+TEXT(" ");for(int I=0;I<Stars;I++)N+=TEXT("*");}return N;}
void ALWZombie::EnsureLegendary(){if(LegendaryInitialized||!World)return;LegendaryInitialized=true;if(Cast<ALWResident>(this))return;uint32 H=LWGen::Hash(int32(PersistentId),int(Kind),World->Seed,29001)%1000;if(Stars==0&&PersistentId)Stars=H<5?3:H<20?2:H<60?1:0;if(Kind==ELWEnemyKind::Colossus||Kind==ELWEnemyKind::WorldEater)Stars=FMath::Max(1,Stars);Stars=FMath::Clamp(Stars,0,3);Health*=1.f+Stars*1.25f;MaximumHealth=Health;}
void ALWZombie::MakeCorpseLoot(){if(!World||!bDead)return;if(CorpseRecord.IsNone())CorpseRecord=PersistentId?FName(*FString::Printf(TEXT("corpse_%u"),PersistentId)):FName(*(TEXT("corpse_")+FGuid::NewGuid().ToString()));const FName Id=CorpseRecord;if(!World->Containers.Contains(Id)){FLWContainerRecord C;C.Id=Id;C.Context=TEXT("corpse");C.Unlocked=true;C.bDropped=true;C.Width=12;C.Height=12;C.Position=GetActorLocation();FCollisionQueryParams Q(NAME_None,false,this);FHitResult H;if(GetWorld()->LineTraceSingleByChannel(H,C.Position,C.Position-FVector(0,0,10000),ECC_WorldStatic,Q))C.Position=H.ImpactPoint+FVector(0,0,12);FRandomStream R(PersistentId^uint32(World->Seed)^29002);int Serial=0;auto Add=[&](FName Name,int Count,int Tier=-1){const auto& D=LWItems::Def(Name);if(D.Id.IsNone())return;while(Count>0){int N=FMath::Min(Count,D.MaxStack);Count-=N;auto I=LWItems::Make(Name,N);I.Id=FGuid::NewDeterministicGuid(Id.ToString()+FString::FromInt(Serial++));if(Tier>=0){I.WeaponTier=Tier;LWMods::RollFinish(I,R);}LWItems::Place(C.Items,I,C.Width,C.Height);}};
 Add(Kind==ELWEnemyKind::Raider?TEXT("ammo_556"):TEXT("scrap"),Kind==ELWEnemyKind::Raider?R.RandRange(8,25):R.RandRange(1,3));if(R.FRand()<.5f)Add(TEXT("medkit"),1);if(Stars){const FName Guns[]={TEXT("m4"),TEXT("rifle"),TEXT("sniper"),TEXT("lmg"),TEXT("doublebarrel"),TEXT("desert_eagle"),TEXT("missile_launcher"),TEXT("minigun")};Add(Guns[R.RandRange(0,Stars==3?7:5)],1,4);Add(TEXT("medkit"),Stars*2);Add(TEXT("ammo_556"),30*Stars);Add(TEXT("lockpick"),Stars*3);if(Stars==3)Add(TEXT("att_scope8"),1);}World->Containers.Add(Id,C);}
 auto& C=World->Containers.FindChecked(Id);if(!IsValid(LootProxy)){LootProxy=World->SpawnObject(ELWObjectKind::Container,Id,C.Position);if(auto* Chunk=World->Chunks.FindRef(LWGen::ChunkAt(FVector2D(C.Position))).Get())Chunk->Residents.Add(LootProxy);}if(auto* P=Cast<ALWCharacter>(UGameplayStatics::GetPlayerPawn(this,0)))P->PersistWorldChange();}
void ALWZombie::LootBody(ALWCharacter* P){if(!bDead||!P||!P->CanAct())return;MakeCorpseLoot();if(LootProxy){LootProxy->SetActorLocation(Parts[0]->GetComponentLocation());P->OpenContainer(LootProxy);}}
void ALWZombie::ConfigureBoss(){if(!World)return;const auto Requested=Kind;if(Requested!=ELWEnemyKind::WorldEater){Kind=ELWEnemyKind::Titan;ConfigureCreature();Kind=Requested;const float Scale=Kind==ELWEnemyKind::Colossus?9:3;SetActorScale3D(FVector(Scale));AddActorWorldOffset(FVector(0,0,152*(Scale-1)));Health=Kind==ELWEnemyKind::Colossus?9000:2200;GetCharacterMovement()->MaxStepHeight=80;}
 else{GetCapsuleComponent()->SetCapsuleSize(550,650);AddActorWorldOffset(FVector(0,0,562));Health=12000;for(int I=0;I<7;I++){Parts[I]->SetStaticMesh(World->Mesh(TEXT("Sphere")));Parts[I]->SetMaterial(0,World->Material(TEXT("Skin")));Parts[I]->SetRelativeLocation(FVector(600-I*700,0,100-I*85));Parts[I]->SetRelativeScale3D(FVector(16-I*.9f,12-I*.55f,12-I*.55f));}for(int I=7;I<14;I++){auto* S=NewObject<UStaticMeshComponent>(this);S->SetupAttachment(RootComponent);S->SetStaticMesh(World->Mesh(TEXT("Sphere")));S->SetMaterial(0,World->Material(TEXT("Skin")));S->SetRelativeLocation(FVector(600-I*700,0,(8-(I-7)*.6f)*37.5f-720));S->SetRelativeScale3D(FVector(8,8-(I-7)*.6f,8-(I-7)*.6f));S->SetCollisionEnabled(ECollisionEnabled::NoCollision);S->RegisterComponent();S->AttachToComponent(Parts[6],FAttachmentTransformRules::KeepWorldTransform);}auto* Mouth=NewObject<UStaticMeshComponent>(this);Mouth->SetupAttachment(RootComponent);Mouth->SetStaticMesh(World->Mesh(TEXT("Sphere")));Mouth->SetMaterial(0,World->Material(TEXT("Steel")));Mouth->SetRelativeLocation(FVector(1410,0,100));Mouth->SetRelativeScale3D(FVector(.6,8.5,8.5));Mouth->SetCollisionEnabled(ECollisionEnabled::NoCollision);Mouth->RegisterComponent();Mouth->AttachToComponent(Parts[0],FAttachmentTransformRules::KeepWorldTransform);
 for(int I=0;I<12;I++){float A=I*PI/6;auto* Tooth=NewObject<UStaticMeshComponent>(this);Tooth->SetupAttachment(RootComponent);Tooth->SetStaticMesh(LoadObject<UStaticMesh>(nullptr,TEXT("/Engine/BasicShapes/Cone.Cone")));Tooth->SetMaterial(0,World->Material(TEXT("Bone")));Tooth->SetRelativeLocation(FVector(1300,FMath::Cos(A)*420,FMath::Sin(A)*420+100));Tooth->SetRelativeRotation(FRotator(-90,0,0));Tooth->SetRelativeScale3D(FVector(1.7,1.7,4));Tooth->SetCollisionEnabled(ECollisionEnabled::NoCollision);Tooth->RegisterComponent();Tooth->AttachToComponent(Parts[0],FAttachmentTransformRules::KeepWorldTransform);}}
 GetCapsuleComponent()->SetCollisionResponseToChannel(ECC_Visibility,ECR_Block);Home=GetActorLocation();Interest=Home;BossClock=10;MaximumHealth=Health;}
void ALWZombie::TickBoss(float Dt,ALWCharacter* P){if(!P||P->bSafehouse||ALWWorld::IsSafePosition(P->GetActorLocation()))return;const bool Worm=Kind==ELWEnemyKind::WorldEater;const float Dist=FVector::Dist2D(P->GetActorLocation(),GetActorLocation());if(Dist>18000)return;
 DecisionClock-=Dt;ContactMemory=FMath::Max(0.f,ContactMemory-Dt);Alert=FMath::Max(0.f,Alert-Dt);
 if(DecisionClock<=0){DecisionClock=.4f;FHitResult Sight;FCollisionQueryParams SQ(NAME_None,false,this);HasVisual=Dist<FMath::Max(6000.f,World->VisibilityRange)&&(!GetWorld()->LineTraceSingleByChannel(Sight,GetActorLocation(),P->GetActorLocation(),ECC_Visibility,SQ)||Sight.GetActor()==P);if(HasVisual){Interest=P->GetActorLocation();ContactMemory=12;Alert=14;}}
 if(Alert<=0){GetCharacterMovement()->StopMovementImmediately();return;}
 if(HasVisual&&TickCarAttack49(Dt,P))return;
 BossClock-=Dt;AttackCooldown-=Dt;Stagger=FMath::Max(0.f,Stagger-Dt);if(Stagger>0)return;
 if(!Worm){const float T=GetWorld()->GetTimeSeconds(),Moving=FMath::Clamp(GetVelocity().Size2D()/300.f,0.,1.);for(int Limb=3;Limb<7;Limb++)if(!Missing(Limb)){float Angle=FMath::Sin(T*3.2f+(Limb%2)*PI)*22*Moving;if(Limb<5&&AttackWindup>0)Angle=-100*FMath::Sin(FMath::Clamp(AttackWindup/1.8f,0.f,1.f)*PI*.5f);Parts[Limb]->SetRelativeRotation(FRotator(Angle,0,0));}}
 if(Worm){if(BurrowPhase==0&&BossClock<=0){BurrowPhase=1;BossClock=2;BurrowOrigin=GetActorLocation();GetCharacterMovement()->DisableMovement();SetActorEnableCollision(false);World->Sound(LWVoice44::Enemy(Kind),BurrowOrigin,1);}
 if(BurrowPhase==1){SetActorLocation(BurrowOrigin-FVector(0,0,(1-FMath::Max(0.f,BossClock)/2)*2400));if(BossClock<=0){BurrowPhase=2;BossClock=3;SetActorHiddenInGame(true);}return;}
 if(BurrowPhase==2){if(BossClock>0)return;FRandomStream R(PersistentId+int(GetWorld()->GetTimeSeconds()*10));bool Found=false;for(int I=0;I<24;I++){float A=R.FRand()*2*PI;FVector Candidate=P->GetActorLocation()+FVector(FMath::Cos(A),FMath::Sin(A),0)*R.FRandRange(1150,2300);Candidate.Z=World->HeightAt(FVector2D(Candidate))+720;TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;LWGen::Gather(FVector2D(Candidate),World->Seed,Roads,Sites);if(Sites.ContainsByPredicate([&](const auto& S){return FVector2D::Distance(S.Position,FVector2D(Candidate))<S.Size.Size()*.5+2200;})||LWStory::Reserved(FVector2D(Candidate),2200)||ALWWorld::IsSafePosition(Candidate))continue;FCollisionQueryParams Q(NAME_None,false,this);if(GetWorld()->OverlapBlockingTestByChannel(Candidate,FQuat::Identity,ECC_Pawn,FCollisionShape::MakeCapsule(650,700),Q))continue;BurrowDestination=Candidate;Found=true;break;}if(!Found){BossClock=1;return;}BurrowPhase=3;BossClock=2;auto* Dust=GetWorld()->SpawnActor<AStaticMeshActor>();Dust->SetMobility(EComponentMobility::Movable);Dust->GetStaticMeshComponent()->SetStaticMesh(World->Mesh(TEXT("Sphere")));Dust->GetStaticMeshComponent()->SetMaterial(0,World->Material(TEXT("Rust")));Dust->GetStaticMeshComponent()->SetCollisionEnabled(ECollisionEnabled::NoCollision);Dust->SetActorLocation(BurrowDestination-FVector(0,0,620));Dust->SetActorScale3D(FVector(15,15,.7));Dust->SetLifeSpan(3);World->Sound(LWVoice44::Enemy(Kind),BurrowDestination,1);return;}
 if(BurrowPhase==3){if(BossClock<=0){SetActorLocation(BurrowDestination);SetActorRotation((P->GetActorLocation()-BurrowDestination).GetSafeNormal2D().Rotation());SetActorHiddenInGame(false);SetActorEnableCollision(true);GetCharacterMovement()->SetMovementMode(MOVE_Walking);BurrowPhase=0;BossClock=14;AttackCooldown=1;}return;}}
 if(Worm){const float T=GetWorld()->GetTimeSeconds();for(int Segment=0;Segment<7;Segment++){FVector V=Parts[Segment]->GetRelativeLocation();V.Y=FMath::Sin(T*1.7f-Segment*.5f)*100;Parts[Segment]->SetRelativeLocation(V);}}
 const float Reach=Worm?1700:Kind==ELWEnemyKind::Colossus?2100:750;FCollisionQueryParams Q(NAME_None,false,this);FHitResult H;bool See=!GetWorld()->LineTraceSingleByChannel(H,GetActorLocation(),P->GetActorLocation(),ECC_Visibility,Q)||H.GetActor()==P;
 if(AttackWindup>0){AttackWindup-=Dt;GetCharacterMovement()->StopMovementImmediately();if(AttackWindup<=0){if(Dist<Reach&&See&&FVector::DotProduct(GetActorForwardVector(),(P->GetActorLocation()-GetActorLocation()).GetSafeNormal2D())>.35f){UGameplayStatics::ApplyDamage(P,(Worm?55:Kind==ELWEnemyKind::Colossus?65:35)*LegendaryDamage(),nullptr,this,nullptr);P->LaunchCharacter((P->GetActorLocation()-GetActorLocation()).GetSafeNormal2D()*500+FVector(0,0,260),false,false);P->CombatTarget=this;P->CombatTargetTime=8;}World->Sound(TEXT("GiantSlam54"),GetActorLocation(),.9f,.8f);P->GroundImpact54(GetActorLocation(),1.7f,Kind==ELWEnemyKind::Colossus?6500:3000);AttackCooldown=3.2f+FMath::FRandRange(0.f,1.7f);}return;}
 if(HasVisual&&Dist<Reach&&See&&AttackCooldown<=0){AttackWindup=Worm?1.3f:1.8f;World->Sound(LWVoice44::Enemy(Kind),GetActorLocation(),.9f);return;}
 if(!Worm&&Dist>Reach*.8f){FVector D=(Interest-GetActorLocation()).GetSafeNormal2D();GetCharacterMovement()->MaxWalkSpeed=Kind==ELWEnemyKind::Colossus?420:330;GetCharacterMovement()->MaxWalkSpeed*=InjurySpeed();FCollisionQueryParams M=Q;M.AddIgnoredActor(P);if(GetWorld()->SweepSingleByChannel(H,GetActorLocation(),GetActorLocation()+D*450,FQuat::Identity,ECC_WorldStatic,FCollisionShape::MakeSphere(GetCapsuleComponent()->GetScaledCapsuleRadius()),M))D=FVector(-D.Y,D.X,0)*(PersistentId%2?1:-1);if(!CrossesSafehouse(GetActorLocation(),GetActorLocation()+D*500))AddMovementInput(D,1,true);SetActorRotation(FMath::RInterpTo(GetActorRotation(),D.Rotation(),Dt,1.5f));}}

