// Generated from Data/Encounters.json.
{ FLWEncounterDefinition D; D.Id=TEXT("last_canteen"); D.Title=TEXT("The Last Canteen"); D.Task=ELWEncounterTask::Aid; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("A dehydrated courier is hiding beneath a torn awning. Her sealed satchel is marked for a clinic."); D.Outcome=TEXT("She marks the next courier stop on her route and promises to remember you."); D.CostItem=TEXT("water"); D.Cost=2; D.RewardItem=TEXT("medkit"); D.RewardCount=1; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("field_surgery"); D.Title=TEXT("No More Bandages"); D.Task=ELWEncounterTask::Aid; D.Setting=ELWEncounterSetting::Medical; D.Intro=TEXT("A roadside medic has a patient on a folding cot and nothing left to stop the bleeding."); D.Outcome=TEXT("The patient stabilizes. The medic packs a field kit for you."); D.CostItem=TEXT("medkit"); D.Cost=1; D.RewardItem=TEXT("ammo_12g"); D.RewardCount=12; D.NearPOI=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("cold_supper"); D.Title=TEXT("Cold Supper"); D.Task=ELWEncounterTask::Aid; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("Two exhausted walkers split an empty tin beside a dead cooking fire."); D.Outcome=TEXT("They share a route through the next district and a little of their ammunition."); D.CostItem=TEXT("food"); D.Cost=2; D.RewardItem=TEXT("ammo_9mm"); D.RewardCount=24; D.Hours=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("filter_rot"); D.Title=TEXT("The Bitter Well"); D.Task=ELWEncounterTask::Aid; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A water carrier says the emergency filter has clogged. The last clean bottles are reserved for children."); D.Outcome=TEXT("The carrier gets the clean-water run moving again."); D.CostItem=TEXT("scrap"); D.Cost=3; D.RewardItem=TEXT("water"); D.RewardCount=4; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("courier_return"); D.Title=TEXT("A Debt on the Road"); D.Task=ELWEncounterTask::Aid; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("The courier you helped recognizes you. She has returned from the clinic with supplies to spare."); D.Outcome=TEXT("She presses the supplies into your hands. Some debts travel farther than people."); D.Prerequisite=TEXT("last_canteen"); D.RewardItem=TEXT("medkit"); D.RewardCount=2; D.Credits=80; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("storm_blankets"); D.Title=TEXT("Waiting Out the Rain"); D.Task=ELWEncounterTask::Aid; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("Stranded walkers are shivering beside soaked bedrolls. They need food before continuing."); D.Outcome=TEXT("The walkers leave a dry ammunition pouch as thanks."); D.Weather=1; D.CostItem=TEXT("food"); D.Cost=2; D.RewardItem=TEXT("ammo_357"); D.RewardCount=18; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("broken_axle"); D.Title=TEXT("Broken Axle"); D.Task=ELWEncounterTask::Repair; D.Setting=ELWEncounterSetting::Motor; D.Intro=TEXT("A scavenger has jacked up a van on timber blocks. A broken bracket is all that keeps him here."); D.Outcome=TEXT("The repair holds. He pays you from his delivery money."); D.CostItem=TEXT("scrap"); D.Cost=3; D.WorkSeconds=28; D.RewardItem=TEXT("water"); D.RewardCount=2; D.Credits=90; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("relay_repair"); D.Title=TEXT("Dead Air"); D.Task=ELWEncounterTask::Repair; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("An isolated relay repeats a distress fragment. A technician points to a burned contactor."); D.Outcome=TEXT("The relay wakes up. Somewhere down the road, a second station answers."); D.CostItem=TEXT("scrap"); D.Cost=4; D.WorkSeconds=35; D.RewardItem=TEXT("ammo_9mm"); D.RewardCount=30; D.Cue=TEXT("RadioStatic"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("refrigerated_cargo"); D.Title=TEXT("The Warm Medicine"); D.Task=ELWEncounterTask::Repair; D.Setting=ELWEncounterSetting::Medical; D.Intro=TEXT("A delivery driver is losing a refrigerator full of medicine. The cooling unit has seized."); D.Outcome=TEXT("Cold air returns to the cases. The driver hands over a preserved medical pack."); D.CostItem=TEXT("scrap"); D.Cost=5; D.WorkSeconds=40; D.RewardItem=TEXT("medkit"); D.RewardCount=3; D.NearPOI=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("pump_restart"); D.Title=TEXT("Water Under Pressure"); D.Task=ELWEncounterTask::Repair; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A hand-painted sign promises clean water, but the roadside pump has fallen silent."); D.Outcome=TEXT("The pump starts. The operator fills bottles for the next travelers."); D.CostItem=TEXT("scrap"); D.Cost=2; D.WorkSeconds=22; D.RewardItem=TEXT("water"); D.RewardCount=5; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("flooded_generator"); D.Title=TEXT("Ground Fault"); D.Task=ELWEncounterTask::Repair; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("Rainwater has drowned a camp generator. Its owner has disconnected it, but needs help rebuilding the starter."); D.Outcome=TEXT("The lamps come back on under the awning."); D.CostItem=TEXT("scrap"); D.Cost=4; D.Weather=1; D.WorkSeconds=32; D.RewardItem=TEXT("food"); D.RewardCount=3; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("ammo_broker"); D.Title=TEXT("Last Box of Shells"); D.Task=ELWEncounterTask::Trade; D.Setting=ELWEncounterSetting::Supply; D.Intro=TEXT("A cautious broker offers a sealed box of shotgun shells. He will only trade in the open."); D.Outcome=TEXT("The broker counts your credits twice, then slides over the box."); D.Cost=90; D.RewardItem=TEXT("ammo_12g"); D.RewardCount=24; D.Credits=0; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("night_pharmacy"); D.Title=TEXT("Night Pharmacy"); D.Task=ELWEncounterTask::Trade; D.Setting=ELWEncounterSetting::Medical; D.Intro=TEXT("A lantern-lit medical seller has opened for the graveyard shift. No names, no questions."); D.Outcome=TEXT("The seller wraps your medicine in clean paper."); D.Cost=110; D.RewardItem=TEXT("medkit"); D.RewardCount=2; D.Credits=0; D.Hours=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("locksmith"); D.Title=TEXT("The Traveling Locksmith"); D.Task=ELWEncounterTask::Trade; D.Setting=ELWEncounterSetting::Motor; D.Intro=TEXT("A locksmith trades carefully made picks from a roll of tools spread across his bonnet."); D.Outcome=TEXT("He demonstrates the tension wrench before handing you the roll."); D.Cost=70; D.RewardItem=TEXT("lockpick"); D.RewardCount=6; D.Credits=0; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("ration_exchange"); D.Title=TEXT("Ration Exchange"); D.Task=ELWEncounterTask::Trade; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("A cook is offering preserved meals in exchange for clean water."); D.Outcome=TEXT("The cook gives you freshly packed traveling rations."); D.CostItem=TEXT("water"); D.Cost=3; D.RewardItem=TEXT("food"); D.RewardCount=5; D.Credits=0; D.Hours=1; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("scrap_buyback"); D.Title=TEXT("Weight in Metal"); D.Task=ELWEncounterTask::Trade; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A repair caravan has run out of usable metal. Its quartermaster is paying for scrap."); D.Outcome=TEXT("Your scrap disappears into organized bins; the quartermaster pays the agreed rate."); D.CostItem=TEXT("scrap"); D.Cost=8; D.RewardItem=TEXT("water"); D.RewardCount=1; D.Credits=140; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("relay_hold"); D.Title=TEXT("Keep the Signal Alive"); D.Task=ELWEncounterTask::Defense; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("The repaired relay is transmitting a convoy route. Its operator needs you to hold the perimeter until the burst finishes."); D.Outcome=TEXT("The convoy receives the route. The operator records your call sign."); D.Prerequisite=TEXT("relay_repair"); D.Enemies=4; D.EnemyKind=1; D.WorkSeconds=65; D.MinLevel=3; D.RewardItem=TEXT("ammo_556"); D.RewardCount=45; D.Credits=160; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("camp_siege"); D.Title=TEXT("Firelight Siege"); D.Task=ELWEncounterTask::Defense; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("A camp cook is banging a pan as infected shapes approach the fire. Someone must keep them outside the camp."); D.Outcome=TEXT("The fire stays lit. The camp shares what it can spare."); D.Enemies=5; D.WorkSeconds=50; D.Hours=2; D.RewardItem=TEXT("food"); D.RewardCount=5; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("clinic_evac"); D.Title=TEXT("The Last Stretcher"); D.Task=ELWEncounterTask::Defense; D.Setting=ELWEncounterSetting::Medical; D.Intro=TEXT("The medic you supplied is moving patients. The evacuation cannot leave until the road is clear."); D.Outcome=TEXT("The last patient gets away. A crate of reserve medicine remains for you."); D.Prerequisite=TEXT("field_surgery"); D.Enemies=5; D.WorkSeconds=60; D.RewardItem=TEXT("medkit"); D.RewardCount=3; D.Credits=120; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("caravan_rearguard"); D.Title=TEXT("Rear Guard"); D.Task=ELWEncounterTask::Defense; D.Setting=ELWEncounterSetting::Checkpoint; D.Intro=TEXT("A supply convoy is retreating behind a barricade. Raiders are searching for a weak point."); D.Outcome=TEXT("The convoy escapes the district and leaves its emergency pay chest."); D.Enemies=4; D.EnemyKind=1; D.WorkSeconds=70; D.MinLevel=4; D.RewardItem=TEXT("ammo_762"); D.RewardCount=30; D.Credits=180; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("caged_scout"); D.Title=TEXT("The Caged Scout"); D.Task=ELWEncounterTask::Rescue; D.Setting=ELWEncounterSetting::Checkpoint; D.Intro=TEXT("A scout is trapped behind a makeshift barricade. The guards are close enough to hear a raised voice."); D.Outcome=TEXT("With the guards gone, the scout cuts through the restraints and shares recovered ammunition."); D.Enemies=3; D.EnemyKind=1; D.MinLevel=2; D.RewardItem=TEXT("ammo_556"); D.RewardCount=30; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("dogged_runner"); D.Title=TEXT("Cornered Runner"); D.Task=ELWEncounterTask::Rescue; D.Setting=ELWEncounterSetting::Motor; D.Intro=TEXT("A runner is balancing on a wreck while rabid dogs circle below."); D.Outcome=TEXT("The runner climbs down and offers a spare medical kit."); D.Enemies=4; D.EnemyKind=2; D.RewardItem=TEXT("medkit"); D.RewardCount=1; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("buried_technician"); D.Title=TEXT("Under the Machinery"); D.Task=ELWEncounterTask::Rescue; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A technician is pinned behind collapsed equipment. Infected workers are drawn to his calls."); D.Outcome=TEXT("The technician limps free and hands you the maintenance locker contents."); D.Enemies=4; D.RewardItem=TEXT("scrap"); D.RewardCount=8; D.NearPOI=13; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("motel_escape"); D.Title=TEXT("No Vacancy"); D.Task=ELWEncounterTask::Rescue; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("A motel guest escaped through a window but cannot get past the infected on the access road."); D.Outcome=TEXT("The guest recovers a hidden travel bag and shares its supplies."); D.Enemies=3; D.RewardItem=TEXT("water"); D.RewardCount=3; D.NearPOI=1; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("postal_cache"); D.Title=TEXT("Undelivered"); D.Task=ELWEncounterTask::Cache; D.Setting=ELWEncounterSetting::Supply; D.Intro=TEXT("A battered postal case sits beside an overturned handcart. Its delivery log ends months ago."); D.Outcome=TEXT("Inside are supplies addressed to a district that no longer answers."); D.RewardItem=TEXT("food"); D.RewardCount=3; D.CostItem=TEXT("lockpick"); D.Cost=1; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("police_dead_drop"); D.Title=TEXT("Blue Tape"); D.Task=ELWEncounterTask::Cache; D.Setting=ELWEncounterSetting::Checkpoint; D.Intro=TEXT("Blue tape marks a locked evidence case beneath an abandoned roadside checkpoint."); D.Outcome=TEXT("The case contains ammunition and an old emergency authorization."); D.CostItem=TEXT("lockpick"); D.Cost=2; D.MinLevel=3; D.RewardItem=TEXT("ammo_357"); D.RewardCount=36; D.NearPOI=17; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("storm_drain"); D.Title=TEXT("What the Rain Revealed"); D.Task=ELWEncounterTask::Cache; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("Runoff has stripped the soil from a sealed supply drum. Its latch is packed with rust."); D.Outcome=TEXT("The seal kept the contents dry through years underground."); D.Weather=1; D.CostItem=TEXT("scrap"); D.Cost=1; D.RewardItem=TEXT("ammo_762"); D.RewardCount=24; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("scout_stash"); D.Title=TEXT("The Scout's Promise"); D.Task=ELWEncounterTask::Cache; D.Setting=ELWEncounterSetting::Supply; D.Intro=TEXT("The scout you rescued left a trail mark and a cache exactly where promised."); D.Outcome=TEXT("A note reads: I do not forget who came back for me."); D.Prerequisite=TEXT("caged_scout"); D.RewardItem=TEXT("medkit"); D.RewardCount=2; D.Credits=120; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("false_distress"); D.Title=TEXT("A Voice Too Calm"); D.Task=ELWEncounterTask::Ambush; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("A distress loop plays from a receiver. No one answers your calls, but fresh bootprints surround the station."); D.Outcome=TEXT("The transmission goes silent. You recover the bait supplies."); D.Enemies=3; D.EnemyKind=1; D.MinLevel=2; D.RewardItem=TEXT("ammo_556"); D.RewardCount=30; D.Cue=TEXT("RadioStatic"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("baited_trunk"); D.Title=TEXT("Open Invitation"); D.Task=ELWEncounterTask::Ambush; D.Setting=ELWEncounterSetting::Motor; D.Intro=TEXT("A wreck has its cargo lid propped open. The neatly arranged supplies look untouched."); D.Outcome=TEXT("The ambushers will not be using this wreck again."); D.Enemies=3; D.EnemyKind=1; D.RewardItem=TEXT("food"); D.RewardCount=4; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("hunters_whistle"); D.Title=TEXT("The Whistle"); D.Task=ELWEncounterTask::Ambush; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("A whistle sounds twice beyond a deserted campsite. Something moves in the brush."); D.Outcome=TEXT("The pack disperses. You find the hunters' abandoned supplies."); D.Enemies=5; D.EnemyKind=2; D.RewardItem=TEXT("ammo_12g"); D.RewardCount=18; D.Cue=TEXT("DogGrowl"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("silent_procession"); D.Title=TEXT("Silent Procession"); D.Task=ELWEncounterTask::Ambush; D.Setting=ELWEncounterSetting::Grave; D.Intro=TEXT("Clothes and luggage lie in a careful line along the verge. The figures beyond them have stopped moving."); D.Outcome=TEXT("The procession ends at a pile of discarded rations."); D.Enemies=6; D.Hours=2; D.MinLevel=3; D.RewardItem=TEXT("food"); D.RewardCount=4; D.Cue=TEXT("ZombieVoice"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("lost_surveyor"); D.Title=TEXT("Lost Surveyor"); D.Task=ELWEncounterTask::Escort; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("A surveyor has lost her bearings in the fog. She needs someone to walk her to the next road marker."); D.Outcome=TEXT("She reaches the marker and gives you a copy of her supply coordinates."); D.RewardItem=TEXT("scrap"); D.RewardCount=6; D.WorkSeconds=45; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("walking_wounded"); D.Title=TEXT("Walking Wounded"); D.Task=ELWEncounterTask::Escort; D.Setting=ELWEncounterSetting::Medical; D.Intro=TEXT("An injured traveler can walk, but only slowly. The next safe pull-off is a short distance down the road."); D.Outcome=TEXT("The traveler reaches the rendezvous and offers a keepsake pouch."); D.RewardItem=TEXT("medkit"); D.RewardCount=1; D.WorkSeconds=60; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("last_bus_passenger"); D.Title=TEXT("The Last Passenger"); D.Task=ELWEncounterTask::Escort; D.Setting=ELWEncounterSetting::Motor; D.Intro=TEXT("A stranded passenger refuses to spend another night beside the dead bus."); D.Outcome=TEXT("At the rendezvous, the passenger finally throws away the old bus ticket."); D.RewardItem=TEXT("water"); D.RewardCount=4; D.Hours=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("technician_home"); D.Title=TEXT("A Second Chance"); D.Task=ELWEncounterTask::Escort; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("The technician you rescued is ready to move his tools. He asks you to walk the exposed stretch with him."); D.Outcome=TEXT("He reaches his pickup point and pays for the escort."); D.Prerequisite=TEXT("buried_technician"); D.RewardItem=TEXT("scrap"); D.RewardCount=10; D.Credits=130; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("alpha_pack"); D.Title=TEXT("The Alpha Pack"); D.Task=ELWEncounterTask::Hunt; D.Setting=ELWEncounterSetting::Grave; D.Intro=TEXT("A traveler points out a feeding ground. The largest dogs have been stalking this road for days."); D.Outcome=TEXT("The road falls quiet. The traveler releases the promised bounty."); D.Enemies=6; D.EnemyKind=2; D.MinLevel=3; D.RewardItem=TEXT("ammo_12g"); D.RewardCount=24; D.Credits=150; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("road_snipers"); D.Title=TEXT("Long Shadows"); D.Task=ELWEncounterTask::Hunt; D.Setting=ELWEncounterSetting::Checkpoint; D.Intro=TEXT("Spent brass litters a lookout. Raiders have been firing on anyone crossing the next stretch."); D.Outcome=TEXT("The lookout is clear. You recover their ammunition reserve."); D.Enemies=4; D.EnemyKind=1; D.MinLevel=4; D.RewardItem=TEXT("ammo_762"); D.RewardCount=40; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("infected_shift"); D.Title=TEXT("End of Shift"); D.Task=ELWEncounterTask::Hunt; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("Infected workers keep returning to the same maintenance stop. A scavenger offers a bounty for clearing it."); D.Outcome=TEXT("The scavenger can finally retrieve the crew's tools."); D.Enemies=7; D.MinLevel=3; D.RewardItem=TEXT("scrap"); D.RewardCount=12; D.NearPOI=13; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("numbers_station"); D.Title=TEXT("Numbers at Midnight"); D.Task=ELWEncounterTask::Signal; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("A receiver repeats groups of numbers under a wash of static. Holding the frequency may reveal the whole message."); D.Outcome=TEXT("The final numbers identify a relief cache. The operator releases its supplies."); D.Hours=2; D.WorkSeconds=40; D.RewardItem=TEXT("ammo_357"); D.RewardCount=24; D.Cue=TEXT("RadioStatic"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("convoy_reply"); D.Title=TEXT("A Reply at Last"); D.Task=ELWEncounterTask::Signal; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("The convoy you helped is on the air. They need a relay operator to acknowledge their arrival."); D.Outcome=TEXT("Their safe-arrival code comes through. They authorize a supply payment."); D.Prerequisite=TEXT("relay_hold"); D.WorkSeconds=30; D.RewardItem=TEXT("medkit"); D.RewardCount=2; D.Credits=180; D.Cue=TEXT("RadioStatic"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("weather_balloon"); D.Title=TEXT("Fallen Weather Station"); D.Task=ELWEncounterTask::Signal; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A weather instrument has landed in the ditch. Its recorder still has enough power for one download."); D.Outcome=TEXT("The recording yields a route advisory and an emergency maintenance kit."); D.Weather=1; D.WorkSeconds=35; D.RewardItem=TEXT("scrap"); D.RewardCount=8; D.Cue=TEXT("RadioStatic"); Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("roadside_shrine"); D.Title=TEXT("Names on Tin"); D.Task=ELWEncounterTask::Memorial; D.Setting=ELWEncounterSetting::Grave; D.Intro=TEXT("Names are scratched into scraps of tin. A caretaker asks you to stay for a moment while he reads them."); D.Outcome=TEXT("The caretaker thanks you for listening and shares a wrapped meal."); D.WorkSeconds=18; D.RewardItem=TEXT("food"); D.RewardCount=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("birthday"); D.Title=TEXT("One More Birthday"); D.Task=ELWEncounterTask::Memorial; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("A lone traveler has put a candle on an unopened ration. Today would have been his daughter's birthday."); D.Outcome=TEXT("You sit through the silence together. He gives you a small medical pouch."); D.WorkSeconds=22; D.RewardItem=TEXT("medkit"); D.RewardCount=1; D.Hours=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("empty_boots"); D.Title=TEXT("A Pair of Boots"); D.Task=ELWEncounterTask::Memorial; D.Setting=ELWEncounterSetting::Grave; D.Intro=TEXT("A pair of boots sits beside a freshly filled grave. A friend is waiting for the courage to leave."); D.Outcome=TEXT("After a few quiet minutes, the traveler picks up the empty pack and heads on."); D.WorkSeconds=25; D.RewardItem=TEXT("water"); D.RewardCount=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("chemical_spill"); D.Title=TEXT("Yellow Water"); D.Task=ELWEncounterTask::Hazard; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A ruptured chemical drum is leaking across the verge. A warning lamp marks the contaminated ground."); D.Outcome=TEXT("You isolate the leaking drum and recover the sealed clean supplies."); D.CostItem=TEXT("scrap"); D.Cost=3; D.WorkSeconds=25; D.RewardItem=TEXT("medkit"); D.RewardCount=2; D.MinLevel=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("arcing_cable"); D.Title=TEXT("Live Wire"); D.Task=ELWEncounterTask::Hazard; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("A fallen cable spits light into rainwater. The cutoff box is reachable from the dry shoulder."); D.Outcome=TEXT("The circuit goes dead. The recovery case is safe to open."); D.Weather=1; D.CostItem=TEXT("scrap"); D.Cost=2; D.WorkSeconds=20; D.RewardItem=TEXT("scrap"); D.RewardCount=9; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("steam_main"); D.Title=TEXT("Pressure Leak"); D.Task=ELWEncounterTask::Hazard; D.Setting=ELWEncounterSetting::Utility; D.Intro=TEXT("A buried steam line has split beneath a maintenance hatch. The pressure valve is jammed."); D.Outcome=TEXT("The steam thins. An old service kit remains inside the hatch."); D.CostItem=TEXT("scrap"); D.Cost=2; D.WorkSeconds=30; D.RewardItem=TEXT("lockpick"); D.RewardCount=4; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("burning_supply"); D.Title=TEXT("Heat in the Drums"); D.Task=ELWEncounterTask::Hazard; D.Setting=ELWEncounterSetting::Supply; D.Intro=TEXT("A stack of supply drums has begun to smoke. Clean water could cool the hottest one before it ruptures."); D.Outcome=TEXT("The drums cool enough to recover the undamaged cargo."); D.CostItem=TEXT("water"); D.Cost=3; D.WorkSeconds=20; D.RewardItem=TEXT("ammo_556"); D.RewardCount=45; D.MinLevel=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("stripped_engine"); D.Title=TEXT("The Engine Picker"); D.Task=ELWEncounterTask::Salvage; D.Setting=ELWEncounterSetting::Motor; D.Intro=TEXT("A mechanic has exposed an engine block. The remaining parts will take patience to separate."); D.Outcome=TEXT("The useful components come free without breaking."); D.WorkSeconds=35; D.RewardItem=TEXT("scrap"); D.RewardCount=10; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("collapsed_shelter"); D.Title=TEXT("Under the Canvas"); D.Task=ELWEncounterTask::Salvage; D.Setting=ELWEncounterSetting::Camp; D.Intro=TEXT("An old roadside shelter has folded over its supply chest. The frame must be lifted clear."); D.Outcome=TEXT("The frame gives way, revealing a dry chest."); D.WorkSeconds=28; D.RewardItem=TEXT("food"); D.RewardCount=4; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("furniture_delivery"); D.Title=TEXT("Flat-Pack Apocalypse"); D.Task=ELWEncounterTask::Salvage; D.Setting=ELWEncounterSetting::Supply; D.Intro=TEXT("A furniture delivery has scattered sealed tool packs along the verge. A collector is sorting what survived."); D.Outcome=TEXT("You assemble a useful set from the broken cartons."); D.WorkSeconds=32; D.RewardItem=TEXT("scrap"); D.RewardCount=8; D.NearPOI=12; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("toll_collectors"); D.Title=TEXT("Private Road"); D.Task=ELWEncounterTask::Toll; D.Setting=ELWEncounterSetting::Checkpoint; D.Intro=TEXT("Armed collectors demand a road fee. Their barricade does not actually block the whole road."); D.Outcome=TEXT("The collectors pocket the payment and agree to leave you alone."); D.Enemies=3; D.EnemyKind=1; D.Cost=100; D.Credits=0; D.RewardItem=TEXT("water"); D.RewardCount=1; D.MinLevel=2; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("false_quarantine"); D.Title=TEXT("Quarantine Fee"); D.Task=ELWEncounterTask::Toll; D.Setting=ELWEncounterSetting::Medical; D.Intro=TEXT("Men wearing borrowed medical bands demand payment for a nonexistent inspection."); D.Outcome=TEXT("They wave you through without getting any closer."); D.Enemies=4; D.EnemyKind=1; D.Cost=140; D.Credits=0; D.RewardItem=TEXT("medkit"); D.RewardCount=1; D.MinLevel=3; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("road_counter"); D.Title=TEXT("Counting the Living"); D.Task=ELWEncounterTask::Survey; D.Setting=ELWEncounterSetting::Checkpoint; D.Intro=TEXT("A volunteer is counting travelers for the settlements. He asks you to watch the road while he repairs his tally board."); D.Outcome=TEXT("The count continues. He shares the supplies assigned to this shift."); D.WorkSeconds=30; D.RewardItem=TEXT("food"); D.RewardCount=3; D.Hours=1; Events.Add(MoveTemp(D)); }
{ FLWEncounterDefinition D; D.Id=TEXT("meteor_watch"); D.Title=TEXT("The Falling Lights"); D.Task=ELWEncounterTask::Survey; D.Setting=ELWEncounterSetting::Radio; D.Intro=TEXT("A stargazer has set up an improvised observation station. She asks you to keep watch during a brief recording."); D.Outcome=TEXT("The recording finishes. For once, the lights overhead belong to something distant."); D.WorkSeconds=45; D.RewardItem=TEXT("ammo_357"); D.RewardCount=18; D.Hours=2; Events.Add(MoveTemp(D)); }
