if(FParse::Param(FCommandLine::Get(),TEXT("LWUpdate54Smoke"))){
 struct F54{TWeakObjectPtr<ALWChunk> Floor,Obstacle;TWeakObjectPtr<ALWWorldObject> Box;TWeakObjectPtr<ALWZombie> Enemy;FVector Start;FGuid Mag;};auto S=MakeShared<F54>();
 auto Add=[this](FString Name,double Delay,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({Name,Delay,120,MoveTemp(Begin),MoveTemp(End),[](ALWCharacter&){return true;}});};
 Add(TEXT("54 test arena"),2,[this,S](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.LeaveSafehouse();P.Health=10000;P.ClosePanels();auto* F=GetWorld()->SpawnActor<ALWChunk>();S->Floor=F;F->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(9000,9000,20));LWV2Teleport(P,FVector(20000,20000,5090));P.Controller->SetControlRotation(FRotator::ZeroRotator);P.GetCharacterMovement()->SetMovementMode(MOVE_Walking);P.World->TimeOfDay=12;P.World->TickWeather(0,&P);});
 Add(TEXT("54 prone and crawl"),.5,[this](ALWCharacter& P){P.ToggleProne54();Check(P.Prone54,TEXT("prone input enters crawl stance"));},[this](ALWCharacter& P){Check(P.GetCapsuleComponent()->GetScaledCapsuleHalfHeight()<34,TEXT("prone has a physically shorter collision capsule"));Check(P.GetCharacterMovement()->MaxWalkSpeedCrouched==95,TEXT("crawl speed is applied"));Check(P.Camera->GetRelativeLocation().Z<30,TEXT("camera settles into prone eye height"));});
 Add(TEXT("54 obstructed stance"),.4,[this,S](ALWCharacter& P){auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Obstacle=C;const float Floor=P.GetActorLocation().Z-P.GetCapsuleComponent()->GetScaledCapsuleHalfHeight();C->Box(P.World,TEXT("Concrete"),FVector(20000,20000,Floor+115),FVector(240,240,20));Check(!P.Stand54()&&P.Prone54,TEXT("cannot stand through a low ceiling"));C->Destroy();S->Obstacle.Reset();Check(P.Stand54(),TEXT("can stand after obstruction is removed"));});
 Add(TEXT("54 slide"),.35,[this,S](ALWCharacter& P){P.Stamina=100;P.GetCharacterMovement()->Velocity=FVector(610,0,0);P.bSprint=true;P.StartCrouch();Check(P.Sliding54&&P.Stamina<=82,TEXT("sprint crouch starts stamina-costed slide"));S->Start=P.GetActorLocation();},[this,S](ALWCharacter& P){Check(P.GetActorLocation().X>S->Start.X+30,TEXT("slide travels through character movement"));P.StopCrouch();});
 Add(TEXT("54 slide recovery"),1.3,[](ALWCharacter&){},[this](ALWCharacter& P){Check(!P.Sliding54,TEXT("slide ends without indefinite momentum"));Check(P.GetCharacterMovement()->GroundFriction==8,TEXT("normal friction is restored"));});
 Add(TEXT("54 low vault"),1.1,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(20000,20000,5090));P.SetActorRotation(FRotator::ZeroRotator);P.Controller->SetControlRotation(FRotator::ZeroRotator);P.Stamina=100;auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Obstacle=C;C->Box(P.World,TEXT("Concrete"),FVector(20100,20000,5040),FVector(70,280,80));Check(P.TryTraverse54(),TEXT("low obstacle accepts a vault"));Check(!P.CanAct(),TEXT("firing is blocked while hands are vaulting"));},[this,S](ALWCharacter& P){Check(!P.Traversing54&&P.GetActorLocation().X>20130,TEXT("vault crosses the obstacle and releases movement"));Check(P.GetActorLocation().Z<5110&&P.GetActorLocation().Z>5070,TEXT("vault lands on real supporting ground"));if(S->Obstacle.IsValid())S->Obstacle->Destroy();});
 Add(TEXT("54 high climb"),1.5,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(21000,20000,5090));P.Stamina=100;auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Obstacle=C;C->Box(P.World,TEXT("Concrete"),FVector(21130,20000,5087.5),FVector(170,280,175));Check(P.TryTraverse54(),TEXT("high ledge accepts a climb"));},[this,S](ALWCharacter& P){Check(!P.Traversing54&&P.GetActorLocation().Z>5240,TEXT("climb finishes standing on ledge"));if(S->Obstacle.IsValid())S->Obstacle->Destroy();});
 Add(TEXT("54 blocked vault"),.3,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(20000,20000,5090));auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Obstacle=C;C->Box(P.World,TEXT("Concrete"),FVector(20100,20000,5040),FVector(70,280,80));C->Box(P.World,TEXT("Concrete"),FVector(20100,20000,5220),FVector(500,500,20));Check(!P.TryTraverse54(),TEXT("vault rejects blocked overhead route"));C->Destroy();});
 Add(TEXT("54 quick container"),.5,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(20000,20000,5090));P.GetCharacterMovement()->StopMovementImmediately();P.Controller->SetControlRotation(FRotator::ZeroRotator);P.Camera->SetWorldRotation(FRotator::ZeroRotator);P.Inventory.Empty();P.ActiveWeaponId.Invalidate();FLWContainerRecord R;R.Id=TEXT("smoke_quick54");R.Unlocked=true;R.Position=FVector(20220,20000,5140);auto Ammo=LWItems::Make(TEXT("ammo_357"),15);LWItems::Place(R.Items,Ammo,12,12);auto Gun=LWItems::Make(TEXT("rifle")),Mag=LWItems::Make(TEXT("mag_rifle30"));Mag.Slot=TEXT("Loaded");Mag.Rounds=17;Gun.LoadedMagazine=Mag.Id;S->Mag=Mag.Id;LWItems::Place(R.Items,Gun,12,12);R.Items.Add(Mag);P.World->Containers.Add(R.Id,R);S->Box=P.World->SpawnObject(ELWObjectKind::Container,R.Id,R.Position);},[this,S](ALWCharacter& P){Check(P.QuickContainer54()==S->Box.Get(),TEXT("unlocked looked-at container opens quick list"));Check(P.TakeQuick54(),TEXT("quick take transfers selected stack"));Check(P.CountSupply(TEXT("ammo_357"))==15&&!P.bInventory,TEXT("quick take keeps gameplay active and conserves items"));CaptureV2(TEXT("Gameplay54_QuickLoot"));});
 Add(TEXT("54 locks and ownership"),.3,[this,S](ALWCharacter& P){auto& R=P.World->Containers.FindChecked(S->Box->RecordId);R.LockTier=2;R.Unlocked=false;Check(!P.QuickContainer54()&&!P.TakeQuick54(true),TEXT("quick loot cannot bypass lock"));R.Unlocked=true;Check(P.TakeQuick54(true),TEXT("take all works on unlocked container"));Check(R.Items.IsEmpty()&&P.Inventory.ContainsByPredicate([&](const auto& I){return I.Id==S->Mag&&I.Rounds==17&&I.Slot==TEXT("Loaded");}),TEXT("take all preserves loaded magazine identity and ammunition"));P.OpenContainer(S->Box.Get());Check(P.TakeAll54()==0,TEXT("empty take all is safe"));P.ClosePanels();S->Box->Kind=ELWObjectKind::Trader;Check(!P.QuickContainer54(),TEXT("traders cannot be quick-looted for free"));S->Box->Kind=ELWObjectKind::Container;
 auto& Items=R.Items;auto Scrap=LWItems::Make(TEXT("scrap"),3);LWItems::Place(Items,Scrap,12,12);P.Inventory.Empty();for(int Y=0;Y<10;Y+=2)for(int X=0;X<12;++X){auto I=LWItems::Make(TEXT("lockpick"),1);I.X=X;I.Y=Y;I.Durability=1+X+Y*12;P.Inventory.Add(I);}const int Before=Items.Num();P.OpenContainer(S->Box.Get());Check(P.TakeAll54()==0&&Items.Num()==Before,TEXT("full inventory leaves uncollected items in container"));P.ClosePanels();S->Box->Destroy();});
 Add(TEXT("54 enemy reactions"),.3,[this,S](ALWCharacter& P){P.Inventory.Empty();auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20800,20080,5090),FRotator(0,180,0));Z->ConfigureKind(ELWEnemyKind::Raider);Z->PersistentId=54001;Z->SetActorTickEnabled(false);Z->GetCharacterMovement()->DisableMovement();S->Enemy=Z;ALWZombie::SuppressAlong54(&P,P.GetActorLocation()+FVector(0,0,30),P.GetActorLocation()+FVector(1600,0,30));Check(Z->Suppression54>0&&Z->Alert>0,TEXT("nearby gunfire causes suppression and investigation"));Z->HasVisual=false;Z->Interest=FVector(20500,20400,5090);Z->TacticalGoal=Z->Interest;Z->ContactMemory=8;const FVector Remembered=Z->Interest;Z->ReactTactics54(.1f,&P);Check(Z->Interest==Remembered,TEXT("lost contact does not reveal player position"));float Before=Z->Suppression54;Z->ReactTactics54(1,&P);Check(Z->Suppression54<Before,TEXT("suppression recovers with time"));P.GetCharacterMovement()->Velocity=FVector(0,0,0);float Standing=P.Spread54();P.Prone54=true;Check(P.Spread54()<Standing,TEXT("prone stabilizes weapon spread"));P.Prone54=false;P.RecoilBloom54=.7f;Check(P.Spread54()>Standing,TEXT("sustained fire increases spread"));P.GroundImpact54(P.GetActorLocation(),1,1000);Check(P.Rumble54>0,TEXT("nearby heavy impact creates camera response"));P.Rumble54=0;P.GroundImpact54(P.GetActorLocation()+FVector(5000,0,0),1,1000);Check(P.Rumble54==0,TEXT("distant heavy impact does not shake camera"));Z->Destroy();});
 Add(TEXT("54 hostile obstacle route"),10,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(21300,21000,5090));P.SetActorRotation(FRotator(0,180,0));P.Controller->SetControlRotation(FRotator(0,180,0));auto* C=GetWorld()->SpawnActor<ALWChunk>();S->Obstacle=C;C->Box(P.World,TEXT("Concrete"),FVector(20650,21000,5150),FVector(70,650,300));auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20000,21000,5090),FRotator::ZeroRotator);Z->PersistentId=54002;TestEnemy=Z;Z->Interest=P.GetActorLocation();Z->Alert=20;Z->ContactMemory=10;S->Enemy=Z;},[this,S](ALWCharacter& P){auto* Z=S->Enemy.Get();if(Z)UE_LOG(LogTemp,Display,TEXT("NAV54_FINAL at=%s path=%d alert=%.2f visual=%d"),*Z->GetActorLocation().ToString(),Z->Path.Num(),Z->Alert,Z->HasVisual);Check(Z&&Z->GetActorLocation().X>20700,TEXT("hostile actually routes around a blocking wall"));Check(Z&&Z->GetActorLocation().Z>5070,TEXT("hostile route retains floor support"));if(Z)Z->Destroy();if(S->Obstacle.IsValid())S->Obstacle->Destroy();});
 Add(TEXT("54 deathclaw charge pose"),1,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(20000,20000,5090));P.Controller->SetControlRotation(FRotator(0,0,0));auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20500,20000,5090),FRotator(0,180,0));Z->ConfigureKind(ELWEnemyKind::Deathclaw);TestEnemy=Z;Z->SetActorTickEnabled(false);Z->GetCharacterMovement()->SetComponentTickEnabled(false);Z->GetCharacterMovement()->Velocity=FVector(-850,0,0);Z->CreatureCharge=1;S->Enemy=Z;},[this,S](ALWCharacter& P){auto* Z=S->Enemy.Get();Check(Z&&Z->Parts[3]->GetRelativeLocation().Z<0&&Z->Parts[0]->GetRelativeRotation().Pitch< -40,TEXT("charging deathclaw lowers forelimbs into four-limbed pose"));CaptureV2(TEXT("Gameplay54_Deathclaw"));if(Z)Z->SetLifeSpan(.2f);});
 Add(TEXT("54 giant ground contacts"),.2,[this](ALWCharacter& P){auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20500,20000,5090),FRotator::ZeroRotator);Z->ConfigureKind(ELWEnemyKind::Titan);Z->SetActorTickEnabled(false);Z->GetCharacterMovement()->SetComponentTickEnabled(false);Z->GetCharacterMovement()->SetMovementMode(MOVE_Walking);Z->GetCharacterMovement()->Velocity=FVector(230,0,0);P.Rumble54=0;Z->CreatureFootfall54(PI*1.1f,&P);Check(P.Rumble54>0,TEXT("actual titan ground contact triggers rumble"));float Before=P.Rumble54;Z->CreatureFootfall54(PI*1.1f,&P);Check(P.Rumble54==Before,TEXT("same gait beat cannot emit duplicate footfall"));Z->Destroy();});
 Add(TEXT("54 prone save setup"),.4,[this](ALWCharacter& P){LWV2Teleport(P,FVector(20000,20000,5090));P.ToggleProne54();});
 Add(TEXT("54 prone save round trip"),.5,[this,S](ALWCharacter& P){auto* Snapshot=P.MakeProgressSnapshot37();Check(Snapshot->PlayerStance54==2,TEXT("snapshot records prone stance"));S->Start=P.GetActorLocation();TArray<uint8> Data;UGameplayStatics::SaveGameToMemory(Snapshot,Data);auto* Copy=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromMemory(Data));Check(Copy&&Copy->PlayerStance54==2,TEXT("stance survives save serialization"));if(Copy)P.ApplyProgressSnapshot37(Copy);},[this,S](ALWCharacter& P){Check(P.Prone54&&P.bIsCrouched&&P.GetCapsuleComponent()->GetScaledCapsuleHalfHeight()==32,TEXT("loading restores low stance collision"));Check(FMath::Abs(P.GetActorLocation().Z-S->Start.Z)<8,TEXT("prone reload preserves floor height"));P.Stand54();});
 Add(TEXT("54 finish"),.3,[this](ALWCharacter& P){for(FName Slot:{TEXT("Slide54"),TEXT("TitanStep54"),TEXT("ColossusStep54"),TEXT("DeathclawCharge54")}){FLWResolvedAudioSlot R;Check(ULWAudioCatalog::ResolveDefaultSlot(Slot,R)&&R.Sound,TEXT("new action audio slots have playable fallback sources"));}UE_LOG(LogTemp,Display,TEXT("GAMEPLAY54_DONE failures=%d"),TestFailures);});
 return;
}
