#include "LWBlood40.h"
#include "LWThreatAwareness.h"
void ALWGameMode::BuildGameplay40Smoke(ALWCharacter& Initial){
 struct FState{TWeakObjectPtr<ALWZombie> Enemy;int Saves=0;int64 Money=0;};auto S=MakeShared<FState>();
 auto Add=[this](const TCHAR* N,double Delay,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({N,Delay,120,MoveTemp(Begin),MoveTemp(End),[](ALWCharacter&){return true;}});};
 Add(TEXT("setup"),2,[this,S](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;P.ClosePanels();P.LeaveSafehouse();LWV2Teleport(P,FVector(20000,20000,5110));auto* F=GetWorld()->SpawnActor<ALWChunk>();F->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(8000,8000,20));P.World->EnableEncounters=false;P.Controller->SetControlRotation(FRotator::ZeroRotator);P.Camera->SetWorldRotation(FRotator::ZeroRotator);P.Health=50;P.GiveItem(TEXT("medkit"),2);});
 Add(TEXT("Quick heal"),.5,[this](ALWCharacter& P){const int Before=P.CountSupply(TEXT("medkit"));P.QuickHeal40();Check(P.Health==P.MaxHealth()&&P.CountSupply(TEXT("medkit"))==Before-1,TEXT("H heals and consumes exactly one medkit"));P.QuickHeal40();Check(P.CountSupply(TEXT("medkit"))==Before-1,TEXT("full health does not waste a medkit"));P.Health=40;P.bInventory=true;P.SetMenuInput(true);P.QuickHeal40();Check(P.Health==40,TEXT("heal blocked while UI open"));P.ClosePanels();P.QuickHeal40();Check(P.CountSupply(TEXT("medkit"))==Before-2,TEXT("second kit usable after leaving UI"));P.Health=30;P.QuickHeal40();Check(P.Health==30,TEXT("no kit cannot heal"));P.Health=100;});
 Add(TEXT("Corner lean clearance"),1,[this](ALWCharacter& P){P.GetCharacterMovement()->SetMovementMode(MOVE_Walking);P.LeanLeftStart40();P.TickLean40(.2);Check(P.LeanPivot40->GetRelativeLocation().Y<-30,TEXT("left lean offsets camera"));P.LeanLeftStop40();P.LeanRightStart40();P.TickLean40(.2);Check(P.LeanPivot40->GetRelativeLocation().Y>30,TEXT("right lean offsets camera"));const FVector Head=P.GetActorLocation()+FVector(0,0,66);auto* Wall=GetWorld()->SpawnActor<ALWChunk>();Wall->Box(P.World,TEXT("Concrete"),Head+FVector(0,27,0),FVector(150,8,160));P.TickLean40(.1);Check(P.LeanPivot40->GetRelativeLocation().Y<20,TEXT("camera clearance prevents wall clipping"));Wall->Destroy();P.bInventory=true;P.SetMenuInput(true);P.TickLean40(.2);Check(P.LeanPivot40->GetRelativeLocation().IsNearlyZero(1),TEXT("lean clears in menus"));P.ClosePanels();},[this](ALWCharacter& P){CaptureV2(TEXT("Gameplay40_Lean"));});
 Add(TEXT("Event save batching"),.5,[this,S](ALWCharacter& P){P.SaveProgress();P.DrainSave40();S->Saves=P.AutoSaves40;const double Start=FPlatformTime::Seconds();for(int i=0;i<1000;++i)P.PersistWorldChange();const double Ms=(FPlatformTime::Seconds()-Start)*1000;UE_LOG(LogTemp,Display,TEXT("LW40_EVENT_SAVE_REQUESTS count=1000 ms=%.3f"),Ms);Check(P.AutoSaves40==S->Saves&&P.SaveDirty40,TEXT("1000 gameplay writes coalesce without a snapshot"));Check(Ms<30,TEXT("event save requests do not block for disk I/O"));P.bReloading=true;P.TickSave40(4);Check(P.AutoSaves40==S->Saves,TEXT("automatic snapshot deferred during reload"));P.bReloading=false;P.World->CombatMusicHold=0;P.HurtFlash=0;P.AttackTimer=0;P.bTrigger=false;P.TickSave40(.1);Check(P.AutoSaves40==S->Saves+1,TEXT("one snapshot after event burst"));P.Money+=17;S->Money=P.Money;P.SaveProgress();P.LoadProgress();Check(P.Money==S->Money,TEXT("manual save waits for earlier writer and preserves latest state"));});
 Add(TEXT("Combat music engagement"),1,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(20000,20000,5110));auto* Z=GetWorld()->SpawnActor<ALWZombie>(P.GetActorLocation()+FVector(650,0,0),FRotator::ZeroRotator);Z->World=P.World;Z->SetActorTickEnabled(false);Z->Alert=20;Z->Interest=P.GetActorLocation();S->Enemy=Z;P.World->MusicScan40=0;P.World->Tick(.25);Check(P.World->MusicState==TEXT("CombatMusic"),TEXT("visible engaged threat starts combat music"));Z->SetActorLocation(Z->GetActorLocation()+FVector(0,0,400));P.World->MusicScan40=0;P.World->Tick(.25);Check(!P.World->MusicThreat40&&P.World->CombatMusicHold>0,TEXT("other floor cannot refresh combat but brief hold prevents churn"));},[this,S](ALWCharacter& P){if(auto* Z=S->Enemy.Get()){Z->Alert=0;}P.World->CombatMusicHold=.01;P.World->MusicScan40=0;P.World->Tick(.25);Check(P.World->MusicState==TEXT("ExploreMusic"),TEXT("combat releases after threat hold expires"));});
 Add(TEXT("Batched blood"),2,[this,S](ALWCharacter& P){if(auto* Z=S->Enemy.Get()){Z->SetActorLocation(P.GetActorLocation()+FVector(500,0,0));FDamageEvent E;Z->BloodTime=-10;Z->BloodHit(E,&P,35);Check(P.World->BloodEffects40.Num()>0,TEXT("blood effect tracked without world actor scan"));if(auto* B=Cast<ALWBlood40>(P.World->BloodEffects40.Last().Get())){Check(B->Mesh->GetInstanceCount()>=8,TEXT("blood uses batched instances"));Check(!B->Mesh->IsSimulatingPhysics(),TEXT("droplets do not create rigid bodies"));}UGameplayStatics::ApplyDamage(Z,100000,P.Controller,&P,nullptr);Check(Z->bDead,TEXT("enemy death still ragdolls"));}},[this](ALWCharacter& P){CaptureV2(TEXT("Gameplay40_Combat"));});
 Add(TEXT("Blood settling regression"),.1,[this](ALWCharacter& P){
  const FVector Ground(50000,50000,10000);
  auto* Floor=GetWorld()->SpawnActor<ALWChunk>();Floor->Box(P.World,TEXT("Concrete"),Ground-FVector(0,0,10),FVector(2000,2000,20));
  auto* Body=GetWorld()->SpawnActor<AActor>();auto* Plate=NewObject<UStaticMeshComponent>(Body);Body->SetRootComponent(Plate);Body->AddInstanceComponent(Plate);
  Plate->SetStaticMesh(LoadObject<UStaticMesh>(nullptr,TEXT("/Engine/BasicShapes/Cube.Cube")));Plate->SetCollisionEnabled(ECollisionEnabled::QueryOnly);Plate->SetCollisionObjectType(ECC_PhysicsBody);Plate->SetCollisionResponseToAllChannels(ECR_Block);Plate->RegisterComponent();Plate->SetWorldLocation(Ground+FVector(0,0,100));Plate->SetWorldScale3D(FVector(3,3,.2));
  auto* B=GetWorld()->SpawnActor<ALWBlood40>();B->Init(P.World,Ground+FVector(0,0,200),FVector::ForwardVector,35);
  bool Grounded=B->Mesh->GetInstanceCount()==13;
  for(int i=8;i<B->Mesh->GetInstanceCount();++i){FTransform T;B->Mesh->GetInstanceTransform(i,T,true);Grounded&=FMath::Abs(T.GetLocation().Z-Ground.Z)<2;}
  Check(Grounded,TEXT("blood stains ignore ragdoll collision and land on floor"));
  for(int i=0;i<30;++i)B->Tick(.05);
  bool Settled=true;for(int i=0;i<8;++i){FTransform T;B->Mesh->GetInstanceTransform(i,T,true);Settled&=B->Velocities[i].IsNearlyZero()&&FMath::Abs(T.GetLocation().Z-Ground.Z)<2&&T.GetScale3D().Z<.01;}
  Check(Settled,TEXT("droplets land and flatten on the floor"));
  auto* High=GetWorld()->SpawnActor<ALWBlood40>();High->Init(P.World,Ground+FVector(0,0,10000),FVector::ForwardVector,35);
  for(int i=0;i<32;++i)High->Tick(.05);
  Check(High->IsActorTickEnabled()&&!High->Velocities[0].IsNearlyZero(),TEXT("airborne droplets keep falling after old 1.5 second cutoff"));
  for(int i=0;i<52;++i)High->Tick(.05);
  bool Hidden=true;for(int i=0;i<8;++i){FTransform T;High->Mesh->GetInstanceTransform(i,T,true);Hidden&=T.GetScale3D().IsNearlyZero();}
  Check(Hidden&&!High->IsActorTickEnabled(),TEXT("expired airborne droplets disappear instead of freezing"));
  B->Destroy();High->Destroy();Body->Destroy();Floor->Destroy();
 });
 Add(TEXT("flush"),2,[](ALWCharacter& P){});
}
