#include "LWGarage45.h"
namespace LWGarage45 {
const TArray<FMod>& Mods(){static const TArray<FMod> All=[](){TArray<FMod> A;
 const TCHAR* Slots[]={TEXT("engine"),TEXT("gearbox"),TEXT("brakes"),TEXT("tires"),TEXT("suspension"),TEXT("armor"),TEXT("tank"),TEXT("cargo"),TEXT("lighting"),TEXT("cooling")};
 const TCHAR* Stats[]={TEXT("power"),TEXT("speed"),TEXT("brake"),TEXT("grip"),TEXT("clearance"),TEXT("armor"),TEXT("tank"),TEXT("cargo"),TEXT("light"),TEXT("economy")};
 const TCHAR* Names[]={TEXT("Ported intake"),TEXT("Forged internals"),TEXT("Supercharger kit"),TEXT("Close-ratio gearbox"),TEXT("Six-speed conversion"),TEXT("Race transmission"),TEXT("Vented brake rotors"),TEXT("Four-piston calipers"),TEXT("Carbon ceramic brakes"),TEXT("All-season tires"),TEXT("All-terrain tires"),TEXT("Competition tires"),TEXT("Heavy-duty springs"),TEXT("Adjustable coilovers"),TEXT("Long-travel suspension"),TEXT("Door reinforcement"),TEXT("Composite plating"),TEXT("Ballistic armor"),TEXT("Auxiliary fuel cell"),TEXT("Extended-range tank"),TEXT("Expedition fuel system"),TEXT("Cargo organizers"),TEXT("Deep cargo drawers"),TEXT("Expedition cargo racks"),TEXT("Halogen upgrade"),TEXT("LED driving lights"),TEXT("High-output light bar"),TEXT("High-flow radiator"),TEXT("Efficient fuel mapping"),TEXT("Thermal management kit")};
 for(int I=0;I<30;++I){int G=I/3,T=I%3+1;float V=G==4?T*12:G==7?T*2:G==8?T*.5f:T*.12f;A.Add({FName(*FString::Printf(TEXT("mod45_%02d"),I)),Slots[G],Stats[G],Names[I],TEXT(""),350+T*350,V});}
 const TCHAR* Names2[]={TEXT("Coach solar roof"),TEXT("Coach economy computer"),TEXT("Coach towing package"),TEXT("Coach reinforced body"),TEXT("Coach pantry conversion"),TEXT("Coach luggage expansion"),TEXT("Coach perimeter lights"),TEXT("Coach underbody protection"),TEXT("Police pursuit calibration"),TEXT("Police reinforced pushbar"),TEXT("Police scene lights"),TEXT("Police long-range fuel cell"),TEXT("Bus armored panels"),TEXT("Bus luggage conversion"),TEXT("Bus mountain gearing"),TEXT("Bus air-brake upgrade"),TEXT("Bike trail gearing"),TEXT("Bike knobby tires"),TEXT("Supercar active aero"),TEXT("Supercar overboost")};
 const TCHAR* Stats2[]={TEXT("economy"),TEXT("economy"),TEXT("power"),TEXT("armor"),TEXT("cargo"),TEXT("cargo"),TEXT("light"),TEXT("armor"),TEXT("speed"),TEXT("armor"),TEXT("light"),TEXT("tank"),TEXT("armor"),TEXT("cargo"),TEXT("power"),TEXT("brake"),TEXT("power"),TEXT("grip"),TEXT("grip"),TEXT("power")};
 for(int I=0;I<20;++I){FString Model=I<8?TEXT("rv"):I<12?TEXT("police"):I<16?TEXT("bus"):I<18?TEXT("dirtbike"):TEXT("supercar");FName Id(*FString::Printf(TEXT("mod45_%02d"),I+30));A.Add({Id,Id,Stats2[I],Names2[I],Model,1400+I*75,FString(Stats2[I])==TEXT("cargo")?2.f:.20f});}return A;}();return All;}
bool Compatible(const FMod& M,FName Model){return M.Models.IsEmpty()||M.Models==Model.ToString();}
float Stat(const FLWVehicleRecord* R,FName Key){float Sum=0;if(R)for(const auto& M:Mods())if(M.Stat==Key&&R->Mods45.Contains(M.Id)&&Compatible(M,R->Model))Sum+=M.Value;return Sum;}
int FreeBay(const TMap<FName,FLWVehicleRecord>& Cars,FName Model){bool Used[10]={};for(const auto& P:Cars)if(P.Value.Owned45&&P.Value.GarageBay45>=0)for(int I=0;I<Bays(P.Value.Model);++I){int B=P.Value.GarageBay45+I;if(B>=0&&B<10)Used[B]=true;}int Size=Bays(Model);for(int B=0;B<10;++B){if(B/5!=(B+Size-1)/5)continue;bool Free=true;for(int I=0;I<Size;++I)Free&=!Used[B+I];if(Free)return B;}return -1;}
}
