#include "Misc/CommandLine.h"
#include "Misc/Parse.h"
#include "LWGraphics33.h"
#include "LWLighting.h"
#include "DLSSLibrary.h"
#include "StreamlineLibraryDLSSG.h"
#include "StreamlineLibraryReflex.h"
#include "GameFramework/GameUserSettings.h"
#include "HAL/IConsoleManager.h"
#include "Misc/ConfigCacheIni.h"
#include "RHI.h"
namespace LWGraphics33 {
namespace {
int Preset=2,Up=1,FG=0,Reflex=1,Pool=1024,Radius=2,LOD=1,Shadow=1;float ManualScale58=0;bool RR=false,Fog=true,Contact=true,Grass=true;FString Status;
const TCHAR* Presets[]={TEXT("MINIMUM"),TEXT("LOW / LAPTOP"),TEXT("BALANCED"),TEXT("HIGH"),TEXT("ULTRA"),TEXT("CINEMATIC")};
const TCHAR* Ups[]={TEXT("MANUAL SCALE"),TEXT("TSR"),TEXT("DLSS QUALITY"),TEXT("DLSS BALANCED"),TEXT("DLSS PERFORMANCE"),TEXT("DLSS ULTRA PERFORMANCE"),TEXT("DLAA")};
const UDLSSMode Modes[]={UDLSSMode::Off,UDLSSMode::Off,UDLSSMode::Quality,UDLSSMode::Balanced,UDLSSMode::Performance,UDLSSMode::UltraPerformance,UDLSSMode::DLAA};
const EStreamlineDLSSGMode Frames[]={EStreamlineDLSSGMode::Off,EStreamlineDLSSGMode::On2X,EStreamlineDLSSGMode::On3X,EStreamlineDLSSGMode::On4X,EStreamlineDLSSGMode::On5X,EStreamlineDLSSGMode::On6X,EStreamlineDLSSGMode::OnDynamic};
const TCHAR* FrameNames[]={TEXT("OFF"),TEXT("2X"),TEXT("3X"),TEXT("4X"),TEXT("5X"),TEXT("6X"),TEXT("DYNAMIC")};
void CVar58(const TCHAR* N,float V){if(auto* C=IConsoleManager::Get().FindConsoleVariable(N))if(!(C->GetFlags()&ECVF_ReadOnly))C->Set(V,ECVF_SetByCode);}
void Config58(bool Save){const TCHAR* S=TEXT("LWGraphics58");if(Save)GConfig->SetFloat(S,TEXT("ManualScale"),ManualScale58,GGameUserSettingsIni);else GConfig->GetFloat(S,TEXT("ManualScale"),ManualScale58,GGameUserSettingsIni);ManualScale58=FMath::Clamp(ManualScale58,0.f,150.f);auto I=[&](const TCHAR* N,int& V){if(Save)GConfig->SetInt(S,N,V,GGameUserSettingsIni);else GConfig->GetInt(S,N,V,GGameUserSettingsIni);};auto B=[&](const TCHAR* N,bool& V){if(Save)GConfig->SetBool(S,N,V,GGameUserSettingsIni);else GConfig->GetBool(S,N,V,GGameUserSettingsIni);};I(TEXT("Preset"),Preset);I(TEXT("Upscaler"),Up);I(TEXT("FrameGeneration"),FG);I(TEXT("Reflex"),Reflex);I(TEXT("Pool"),Pool);I(TEXT("Radius"),Radius);I(TEXT("LOD"),LOD);I(TEXT("ShadowMethod"),Shadow);B(TEXT("RR"),RR);B(TEXT("Fog"),Fog);B(TEXT("Contact"),Contact);B(TEXT("Grass"),Grass);if(Save)GConfig->Flush(false,GGameUserSettingsIni);}
}
void Custom58(int I){Preset=-1;if(I==14)Up=0;Config58(true);}
int Radius58(){return Radius;}FString Status58(){return Status;}
void Apply58(){auto* S=UGameUserSettings::GetGameUserSettings();if(!S)return;Status.Empty();if(Preset>=0){CVar58(TEXT("r.BloomQuality"),Preset==0?0:5);CVar58(TEXT("r.MotionBlurQuality"),0);CVar58(TEXT("r.AmbientOcclusionLevels"),Preset<2?0:-1);CVar58(TEXT("r.MaxAnisotropy"),Preset<2?2:Preset==2?8:16);if(Preset==0)CVar58(TEXT("r.AntiAliasingMethod"),1);}CVar58(TEXT("r.VolumetricFog"),Fog);CVar58(TEXT("r.ContactShadows"),Contact);CVar58(TEXT("foliage.DensityScale"),Grass);CVar58(TEXT("grass.DensityScale"),Grass);CVar58(TEXT("r.ViewDistanceScale"),LOD==0?.45f:LOD==1?1:1.8f);CVar58(TEXT("r.StaticMeshLODDistanceScale"),LOD==0?2.5f:LOD==1?1:.6f);CVar58(TEXT("r.Streaming.UseFixedPoolSize"),1);CVar58(TEXT("r.Streaming.LimitPoolSizeToVRAM"),1);CVar58(TEXT("r.Streaming.PoolSize"),Pool);CVar58(TEXT("r.Shadow.Virtual.Enable"),Shadow==2&&GMaxRHIFeatureLevel>=ERHIFeatureLevel::SM6);CVar58(TEXT("r.ShadowQuality"),Shadow?FMath::Max(1,S->GetShadowQuality()+2):0);
 bool DLSS=Up>=2&&UDLSSLibrary::IsDLSSSupported()&&UDLSSLibrary::IsDLSSModeSupported(Modes[Up]);if(Up>=2&&!DLSS)Status=TEXT("DLSS unavailable; using TSR. ");UDLSSLibrary::EnableDLSS(DLSS);float Scale=FMath::Clamp(ManualScale58>0?ManualScale58:S->ScalabilityQuality.ResolutionQuality,35.f,150.f);if(DLSS){bool Supported=false,Fixed=false;float Min=0,Max=100,Sharp=0;UDLSSLibrary::GetDLSSModeInformation(Modes[Up],FVector2D(S->GetScreenResolution()),Supported,Scale,Fixed,Min,Max,Sharp);}if(Up)CVar58(TEXT("r.AntiAliasingMethod"),4);CVar58(TEXT("r.ScreenPercentage"),Scale);
 UDLSSLibrary::EnableDLSSRR(RR&&DLSS&&LWLighting::Mode()==2&&UDLSSLibrary::IsDLSSRRSupported());bool CanFG=UStreamlineLibraryDLSSG::IsDLSSGSupported()&&UStreamlineLibraryDLSSG::IsDLSSGModeSupported(Frames[FG]);if(FG&&!CanFG)Status+=TEXT("Frame generation unavailable; disabled. ");if(FG&&CanFG&&!UStreamlineLibraryDLSSG::GetDLSSGIsVsyncSupportAvailable()){S->SetVSyncEnabled(false);CVar58(TEXT("r.VSync"),0);}if(UStreamlineLibraryReflex::IsReflexSupported())UStreamlineLibraryReflex::SetReflexMode(FG&&CanFG?EStreamlineReflexMode::Enabled:Reflex==2?EStreamlineReflexMode::Boost:Reflex==1?EStreamlineReflexMode::Enabled:EStreamlineReflexMode::Off);if(UStreamlineLibraryDLSSG::IsDLSSGSupported()){for(const TCHAR* N:{TEXT("r.Streamline.DLSSG.Enable"),TEXT("r.Streamline.DLSSG.FramesToGenerate")})if(auto* C=IConsoleManager::Get().FindConsoleVariable(N))C->Set(C->GetInt(),ECVF_SetByCode);UStreamlineLibraryDLSSG::SetDLSSGMode(CanFG?Frames[FG]:EStreamlineDLSSGMode::Off);}if(Status.IsEmpty())Status=TEXT("Applied. Minimum reduces draw distance and effects; cinematic is demanding.");
}
void Load58(){Config58(false);Preset=FMath::Clamp(Preset,-1,5);Up=FMath::Clamp(Up,0,6);FG=FMath::Clamp(FG,0,6);Reflex=FMath::Clamp(Reflex,0,2);Pool=FMath::Clamp(Pool,256,8192);Radius=FMath::Clamp(Radius,1,4);LOD=FMath::Clamp(LOD,0,2);Shadow=FMath::Clamp(Shadow,0,2);if(FParse::Param(FCommandLine::Get(),TEXT("LWLowSpec58")))Preset58(0);else Apply58();}
void Preset58(int I){auto* S=UGameUserSettings::GetGameUserSettings();if(!S)return;Preset=FMath::Clamp(I,0,5);ManualScale58=0;S->SetOverallScalabilityLevel(FMath::Clamp(Preset-1,0,4));const float Scales[]={40,60,75,85,100,100};const int Pools[]={256,512,1024,2048,4096,6144};S->SetResolutionScaleValueEx(Scales[Preset]);S->SetFrameRateLimit(Preset==0?30:Preset==1?40:Preset<4?60:0);S->SetDynamicResolutionEnabled(false);Pool=Pools[Preset];Radius=Preset<2?1:Preset<4?2:3;LOD=Preset<2?0:Preset<4?1:2;Fog=Contact=Grass=Preset>=2;Up=Preset==0?0:1;FG=0;RR=false;Shadow=Preset==0?0:Preset>=4?2:1;S->ApplyNonResolutionSettings();LWLighting::Apply(Preset<2?0:Preset>=4?2:1,true);CVar58(TEXT("r.AntiAliasingMethod"),Preset==0?1:4);CVar58(TEXT("r.MotionBlurQuality"),0);CVar58(TEXT("t.MaxFPS"),S->GetFrameRateLimit());Apply58();S->SaveSettings();Config58(true);}
void Change58(int I){if(I==11){auto* S=UGameUserSettings::GetGameUserSettings();float V=ManualScale58>0?ManualScale58:S->ScalabilityQuality.ResolutionQuality;ManualScale58=V>=149?35:FMath::Min(150.f,V+5);Preset=-1;Apply58();Config58(true);return;}if(I==10){Preset58((Preset+1)%6);return;}if(I==21||I>=34){Preset58(I==21?2:I==34?0:I==35?4:5);return;}Preset=-1;if(I==23){for(int N=0;N<7;N++){Up=(Up+1)%7;if(Up<2||(UDLSSLibrary::IsDLSSSupported()&&UDLSSLibrary::IsDLSSModeSupported(Modes[Up])))break;}}if(I==24){for(int N=0;N<7;N++){FG=(FG+1)%7;if(!FG||(UStreamlineLibraryDLSSG::IsDLSSGSupported()&&UStreamlineLibraryDLSSG::IsDLSSGModeSupported(Frames[FG])))break;}}if(I==25)Reflex=(Reflex+1)%3;if(I==26)RR=!RR;if(I==27)Pool=Pool>=8192?256:Pool*2;if(I==28)Radius=Radius>=4?1:Radius+1;if(I==29)LOD=(LOD+1)%3;if(I==30)Fog=!Fog;if(I==31)Contact=!Contact;if(I==32)Grass=!Grass;if(I==33)Shadow=(Shadow+1)%3;Apply58();Config58(true);}
FString Label58(int I){switch(I){case 11:return FString::Printf(TEXT("MANUAL RENDER SCALE: %.0f%%"),ManualScale58>0?ManualScale58:UGameUserSettings::GetGameUserSettings()->ScalabilityQuality.ResolutionQuality);case 10:return FString(TEXT("PRESET: "))+(Preset<0?TEXT("CUSTOM"):Presets[Preset]);case 23:return FString(TEXT("UPSCALER: "))+Ups[Up]+(!UDLSSLibrary::IsDLSSSupported()?TEXT(" / DLSS UNAVAILABLE"):TEXT(""));case 24:return FString(TEXT("FRAME GENERATION: "))+(UStreamlineLibraryDLSSG::IsDLSSGSupported()?FrameNames[FG]:TEXT("UNAVAILABLE"));case 25:return FString(TEXT("REFLEX: "))+(!UStreamlineLibraryReflex::IsReflexSupported()?TEXT("UNAVAILABLE"):Reflex==0?TEXT("OFF"):Reflex==1?TEXT("ON"):TEXT("ON + BOOST"));case 26:return FString(TEXT("RAY RECONSTRUCTION: "))+(!UDLSSLibrary::IsDLSSRRSupported()?TEXT("UNAVAILABLE"):RR?TEXT("ON / DLSS + RT REQUIRED"):TEXT("OFF"));case 27:return FString::Printf(TEXT("TEXTURE BUDGET: %d MB"),Pool);case 28:return FString::Printf(TEXT("STREAMING RADIUS: %d CHUNKS"),Radius);case 29:return FString(TEXT("MESH DETAIL: "))+(LOD==0?TEXT("PERFORMANCE"):LOD==1?TEXT("BALANCED"):TEXT("EXTENDED"));case 30:return Fog?TEXT("VOLUMETRIC FOG: ON"):TEXT("VOLUMETRIC FOG: OFF");case 31:return Contact?TEXT("CONTACT SHADOWS: ON"):TEXT("CONTACT SHADOWS: OFF");case 32:return Grass?TEXT("GROUND COVER: ON"):TEXT("GROUND COVER: OFF");case 33:return FString(TEXT("SHADOW METHOD: "))+(Shadow==0?TEXT("OFF"):Shadow==1?TEXT("STANDARD"):TEXT("VIRTUAL / DX12 SM6"));case 34:return TEXT("APPLY MINIMUM LAPTOP PRESET");case 35:return TEXT("APPLY ULTRA PRESET");case 36:return TEXT("APPLY CINEMATIC PRESET");}return TEXT("");}
}
