void ALWGameMode::BuildImpactSmoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,90,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWChunk> C;TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWZombie> Z;TWeakObjectPtr<ALWZombie> Injured,Head;FVector CrawlStart;};auto S=MakeShared<FState>();
 Add(TEXT("impact fixtures"),4,[this,S](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;LWV2Teleport(P,FVector(20000,19500,5200));P.Health=10000;P.World->TimeOfDay=12;P.World->TickWeather(10,&P);auto* C=GetWorld()->SpawnActor<ALWChunk>();S->C=C;C->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(6000,6000,20));FLWVehicleRecord R;R.Model=TEXT("sedan");R.VIN=FGuid::NewGuid();R.Position=FVector(20000,20000,5075);R.Unlocked=true;P.World->Vehicles.Add(TEXT("impact22"),R);S->Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("impact22"),R.Position));Check(S->Car.IsValid(),TEXT("impact car spawned"));Check(P.World->Material(TEXT("Blood22"))!=nullptr,TEXT("blood material imported"));});
 if(FParse::Param(FCommandLine::Get(),TEXT("LWInjurySmoke"))){
 Add(TEXT("rarity and live injuries"),1,[this,S](ALWCharacter& P){
  TSet<FColor> Colors;for(int I=0;I<5;I++)Colors.Add(LWMods::TierColor(I).ToFColor(true));Check(Colors.Num()==5,TEXT("five distinct rarity colors"));
  auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(21000,20000,5090),FRotator::ZeroRotator);S->Injured=Z;Z->PersistentId=1;Z->ConfigureKind(ELWEnemyKind::Raider);Z->Health=1000;Z->SetActorTickEnabled(false);
  auto Hit=[&](int Part){FPointDamageEvent E;E.ShotDirection=FVector(1,0,0);E.HitInfo.Component=Z->Parts[Part];E.HitInfo.ImpactPoint=Z->Parts[Part]->Bounds.Origin;Z->TakeDamage(60,E,P.Controller,&P);};
  Hit(5);Z->TickInjuries(.01f,&P);Check(!Z->bDead&&Z->Missing(5)&&!Z->bCrawling&&Z->InjurySpeed()<.5f,TEXT("one leg injury produces live hobble"));
  Hit(3);Check(Z->CanUseGun()&&Z->InjuryAttackDelay()>1,TEXT("support arm loss slows attacks without disabling trigger hand"));
  Hit(4);Check(!Z->CanUseGun()&&!Z->Gun->IsVisible(),TEXT("trigger arm loss prevents firearm use"));
  float HP=Z->Health;Hit(4);Check(Z->Health==HP,TEXT("detached limb hit cannot damage living owner"));
  Hit(6);Z->TickInjuries(.01f,&P);Check(Z->bCrawling&&Z->GetCapsuleComponent()->GetScaledCapsuleHalfHeight()<50,TEXT("both legs lost produces low crawl posture"));
  Check(Z->Parts[5]->IsSimulatingPhysics()&&Z->Parts[5]->GetAttachParent()==nullptr,TEXT("detached live limb simulates independently"));
  auto* Head=GetWorld()->SpawnActor<ALWZombie>(FVector(21100,20600,5090),FRotator::ZeroRotator);S->Head=Head;TestEnemy=Head;FPointDamageEvent E;E.ShotDirection=FVector(1,0,0);E.HitInfo.Component=Head->Parts[1];E.HitInfo.ImpactPoint=Head->Parts[1]->Bounds.Origin;Head->TakeDamage(60,E,P.Controller,&P);Check(!Head->bDead&&Head->HeadlessTime>=3&&Head->HeadlessTime<=10,TEXT("head loss starts a live 3 to 10 second death timer"));Head->TickInjuries(.01f,&P);Check(Head->GetCharacterMovement()->MaxWalkSpeed>=350,TEXT("headless enemy runs before collapse"));
 });
 Add(TEXT("vehicle deformation"),.5,[this,S](ALWCharacter& P){auto* Car=S->Car.Get();Check(Car->Body->GetStaticMesh()->bAllowCPUAccess,TEXT("vehicle geometry supports cooked dent deformation"));Car->AddDent(Car->Body->GetComponentTransform().TransformPosition(FVector(150,85,65)),FVector(0,-1,0),80);
 Check(Car->DentedBody&&Car->DentedBody->GetNumSections()>0&&!Car->Body->IsVisible(),TEXT("dented geometry replaces original shell"));bool Changed=false;
 if(Car->DentedBody)for(int Section=0;Section<Car->DentedBody->GetNumSections();Section++){auto* Mesh=Car->DentedBody->GetProcMeshSection(Section);if(Mesh)for(int I=0;I<Mesh->ProcVertexBuffer.Num();I++)if(!Mesh->ProcVertexBuffer[I].Position.Equals(Car->DentOriginal[Section][I],.01))Changed=true;}
 Check(Changed,TEXT("impact deforms actual mesh vertices"));FLWVehicleRecord Copy=*Car->Record();Copy.Position+=FVector(0,900,0);P.World->Vehicles.Add(TEXT("dent_reload23"),Copy);auto* Reload=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("dent_reload23"),Copy.Position));Check(Reload&&Reload->DentedBody&&Reload->Record()->Dents.Num()==Copy.Dents.Num(),TEXT("reloaded vehicle reconstructs saved dents"));if(Reload)Reload->Destroy();
 for(int I=0;I<30;I++)Car->AddDent(Car->GetActorLocation()+FVector(I*19-250,(I%2?1:-1)*90,20),FVector(0,I%2?-1:1,0),10);Check(Car->Record()->Dents.Num()<=12,TEXT("dent history is bounded"));
 });
 Add(TEXT("rarity colors visual"),1,[](ALWCharacter& P){P.ClosePanels();P.Inventory.Empty();P.ActiveWeaponId.Invalidate();for(int I=0;I<5;I++){auto G=LWItems::Make(TEXT("smg"));G.WeaponTier=I;LWItems::Place(P.Inventory,G,12,10);}P.ToggleInventory();},[this](ALWCharacter&){CaptureV2(TEXT("Injury23_Rarities"));});
 Add(TEXT("dent visual"),1,[S](ALWCharacter& P){P.ClosePanels();P.Flashlight->SetVisibility(false);S->Car->RebuildDents();FVector At(20450,20400,5160),Target(20100,20030,5070);LWV2Teleport(P,At);P.Controller->SetControlRotation((Target-(At+FVector(0,0,60))).Rotation());},[this](ALWCharacter&){CaptureV2(TEXT("Injury23_Dents"));});
 Add(TEXT("headless collapse"),11,[](ALWCharacter&){},[this,S](ALWCharacter&){Check(S->Head->bDead&&S->Head->Parts[0]->IsSimulatingPhysics(),TEXT("headless enemy collapses on timeout"));S->Head->Destroy();TestEnemy=nullptr;});
 Add(TEXT("live crawler locomotion"),2,[this,S](ALWCharacter& P){auto* Z=S->Injured.Get();TestEnemy=Z;Z->SetActorTickEnabled(true);Z->GetCharacterMovement()->SetMovementMode(MOVE_Walking);S->CrawlStart=Z->GetActorLocation();LWV2Teleport(P,Z->GetActorLocation()+FVector(0,-550,90));P.Controller->SetControlRotation(FRotator(-18,90,0));},[this,S](ALWCharacter&){Check(FVector::Dist2D(S->CrawlStart,S->Injured->GetActorLocation())>10,TEXT("injured enemy actually crawls toward player"));CaptureV2(TEXT("Injury23_Crawler"));});
 Add(TEXT("injury cleanup"),.2,[this,S](ALWCharacter&){TestEnemy=nullptr;S->Injured->Destroy();});
 }
 Add(TEXT("roadkill"),.5,[this,S](ALWCharacter& P){auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20300,20000,5090),FRotator::ZeroRotator);S->Z=Z;Z->SetActorTickEnabled(false);auto* Car=S->Car.Get();Car->Driver=&P;Car->Speed=1800;Car->Tick(.05f);Check(Car->GetActorLocation().X>20040,TEXT("car advances through pedestrian"));Check(Z->bDead,TEXT("high speed impact kills enemy"));Check(Z->SeveredMask!=0,TEXT("high energy impact severs a limb"));Check(Z->Parts[0]->IsSimulatingPhysics(),TEXT("impact produces ragdoll"));Check(Car->Speed<1800,TEXT("collision transfers momentum"));Car->Driver=nullptr;Car->Speed=0;},[this](ALWCharacter&){CaptureV2(TEXT("Impact22_Gore"));});
 Add(TEXT("settle ragdoll"),2,[](ALWCharacter&){});
 Add(TEXT("corpse damage"),.2,[this,S](ALWCharacter& P){auto* Z=S->Z.Get();int Before=Z->SeveredMask;FPointDamageEvent E;E.ShotDirection=FVector(1,0,0);E.HitInfo.ImpactPoint=Z->Parts[1]->Bounds.Origin;Z->TakeDamage(100,E,P.Controller,&P);Check(Z->SeveredMask!=Before,TEXT("corpse can lose another limb"));});
 Add(TEXT("gore closeup"),1,[this,S](ALWCharacter& P){FVector Target=S->Z->Parts[0]->Bounds.Origin;FVector At=Target+FVector(0,-350,150);LWV2Teleport(P,At);P.Controller->SetControlRotation((Target-(At+FVector(0,0,60))).Rotation());P.WeaponRoot->SetVisibility(false,true);
 auto* A=GetWorld()->SpawnActor<AActor>();auto* L=NewObject<USpotLightComponent>(A);A->SetRootComponent(L);L->RegisterComponent();L->SetWorldLocation(Target+FVector(0,-200,500));L->SetWorldRotation((Target-L->GetComponentLocation()).Rotation());L->SetIntensity(150000);L->SetAttenuationRadius(1600);L->SetOuterConeAngle(80);L->SetCastShadows(false);A->SetLifeSpan(8);
 },[this](ALWCharacter&){CaptureV2(TEXT("Impact22_GoreCloseup"));});
 if(FParse::Param(FCommandLine::Get(),TEXT("LWInjurySmoke")))Add(TEXT("car strikes existing ragdoll"),.2,[this,S](ALWCharacter&){auto* Z=S->Z.Get();FVector At=Z->Parts[0]->Bounds.Origin;for(auto& Part:Z->Parts){Part->SetPhysicsLinearVelocity(FVector::ZeroVector);Part->PutAllRigidBodiesToSleep();}auto* Car=S->Car.Get();Car->SetActorLocation(FVector(At.X-350,At.Y,At.Z+60));Car->Speed=1400;Car->HitPedestrians(FVector(At.X+150,At.Y,At.Z+60),FRotator::ZeroRotator);Check(FMath::IsNearlyEqual(Car->ImpactTimes.FindRef(Z),GetWorld()->GetTimeSeconds(),.01f),TEXT("second vehicle contact registered on corpse"));Car->Speed=0;},[this,S](ALWCharacter&){Check(S->Z->Parts[0]->GetPhysicsLinearVelocity().Size()>20,TEXT("car wakes and accelerates an existing corpse"));});
 Add(TEXT("survivor and passenger impacts"),.2,[this,S](ALWCharacter& P){
 auto* Car=S->Car.Get();Car->SetActorLocation(FVector(20000,20000,5075));auto* N=GetWorld()->SpawnActor<ALWResident>(FVector(20300,20000,5090),FRotator::ZeroRotator);N->ConfigureResident(TEXT("impactcivilian"),TEXT("civilian"),TEXT("Test"),0);N->SetActorTickEnabled(false);Car->Driver=&P;Car->Speed=1800;N->Riding=Car;Car->HitPedestrians(FVector(20500,20000,5075),FRotator::ZeroRotator);Check(N->Health==150,TEXT("riding NPC immune to own vehicle"));N->Riding=nullptr;Car->HitPedestrians(FVector(20500,20000,5075),FRotator::ZeroRotator);Check(N->DownTime>0&&!N->bDead,TEXT("civilian downed by impact and remains recoverable"));N->Destroy();Car->Driver=nullptr;
 auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(19700,20000,5090),FRotator::ZeroRotator);Z->SetActorTickEnabled(false);Car->Speed=-400;Car->HitPedestrians(FVector(19500,20000,5075),FRotator::ZeroRotator);float HP=Z->Health;Check(HP<100&&HP>0,TEXT("reverse moderate impact wounds"));Car->HitPedestrians(FVector(19500,20000,5075),FRotator::ZeroRotator);Check(Z->Health==HP,TEXT("contact cooldown prevents frame repeated damage"));Z->Destroy();Car->Speed=0;
 });
 Add(TEXT("low speed and occlusion"),.2,[this,S](ALWCharacter& P){auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20300,20000,5090),FRotator::ZeroRotator);Z->SetActorTickEnabled(false);auto* Car=S->Car.Get();Car->SetActorLocation(FVector(20000,20000,5075));Car->Speed=80;Car->HitPedestrians(FVector(20500,20000,5075),FRotator::ZeroRotator);Check(Z->Health==100,TEXT("parking speed causes no damage"));S->C->Box(P.World,TEXT("Concrete"),FVector(20230,20000,5150),FVector(30,800,300));Car->Speed=1800;Car->HitPedestrians(FVector(20500,20000,5075),FRotator::ZeroRotator);Check(Z->Health==100,TEXT("wall shields pedestrian"));Car->Speed=0;Z->Destroy();});
 Add(TEXT("cleanup"),.2,[S](ALWCharacter&){if(S->Z.IsValid())S->Z->Destroy();S->Car->Destroy();S->C->Destroy();});
}
