#include "LWGeneration.h"
#include "LWRPG.h"
#include "Misc/AutomationTest.h"
#if WITH_DEV_AUTOMATION_TESTS
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWLandmarkPlacement,"LethalWorld.Landmarks.UniqueReservations",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWLandmarkPlacement::RunTest(const FString&){for(int Seed:{1,42,198706,999999}){TSet<FIntPoint> Owners;TSet<uint32> IDs;for(int I=0;I<20;I++){const auto R=LWGen::UniqueRegion(I,Seed);TestFalse(TEXT("one exclusive owner per landmark"),Owners.Contains(R));Owners.Add(R);LWGen::FSite Expected;TestTrue(TEXT("reservation exists"),LWGen::SpecialSite(R,Seed,Expected));TestEqual(TEXT("correct landmark type"),Expected.Type,33+I);TestFalse(TEXT("unique site identity"),IDs.Contains(Expected.Id));IDs.Add(Expected.Id);
 TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;for(int Y=-1;Y<=1;Y++)for(int X=-1;X<=1;X++)LWGen::Region(R+FIntPoint(X,Y),Seed,Roads,Sites);int Found=0;for(const auto& S:Sites)if(S.Type==33+I){Found++;TestTrue(TEXT("stable location"),S.Position.Equals(Expected.Position));TestFalse(TEXT("roads clear exclusive footprint"),Roads.ContainsByPredicate([&](const auto& Road){return LWGen::RoadOverlaps(S,Road);}));TestFalse(TEXT("ordinary plots do not overlap"),Sites.ContainsByPredicate([&](const auto& Other){return Other.Id!=S.Id&&LWGen::ParcelsOverlap(S,Other);}));}TestEqual(TEXT("exactly one landmark across neighboring regions"),Found,1);
 }}return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWAirportRarity,"LethalWorld.Landmarks.AirportRarity",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWAirportRarity::RunTest(const FString&){int Count=0,Checked=0;for(int Y=-100;Y<=100;Y++)for(int X=-100;X<=100;X++)if(LWGen::AirportHere({X,Y},198706)){Count++;if(Checked++<5){TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;LWGen::Gather(FVector2D(X*LWGen::RegionSize,Y*LWGen::RegionSize),198706,Roads,Sites);const auto* S=Sites.FindByPredicate([](const auto& A){return A.Type==32;});TestNotNull(TEXT("eligible airport survives filtering"),S);if(S){TestTrue(TEXT("massive airport footprint"),S->Size.X>=30000&&S->Size.Y>=22000);TestFalse(TEXT("runways clear regional roads"),Roads.ContainsByPredicate([&](const auto& R){return LWGen::RoadOverlaps(*S,R);}));}}}AddInfo(FString::Printf(TEXT("Airports in 40401 regions: %d"),Count));TestTrue(TEXT("highly rare airport frequency"),Count>25&&Count<130);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWStaminaPerks,"LethalWorld.RPG.MaximumStamina",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWStaminaPerks::RunTest(const FString&){FLWRPGState S;S.Points=20;TestTrue(TEXT("conditioning available immediately"),LWRPG::Buy(S,TEXT("stamina_conditioning")));TestEqual(TEXT("rank adds ten stamina"),LWRPG::Stat(S,TEXT("stamina")),10.f);TestFalse(TEXT("reserve level gate"),LWRPG::Buy(S,TEXT("stamina_reserve")));S.Level=50;S.Attributes[2]=5;for(int I=0;I<4;I++)TestTrue(TEXT("conditioning rank"),LWRPG::Buy(S,TEXT("stamina_conditioning")));for(int I=0;I<3;I++)TestTrue(TEXT("reserve rank"),LWRPG::Buy(S,TEXT("stamina_reserve")));TestEqual(TEXT("new perks add 125 maximum stamina"),LWRPG::Stat(S,TEXT("stamina")),125.f);TestFalse(TEXT("conditioning capped"),LWRPG::Buy(S,TEXT("stamina_conditioning")));TestFalse(TEXT("reserve capped"),LWRPG::Buy(S,TEXT("stamina_reserve")));return true;}
#endif
