void ALWGameMode::BuildLandmarks28Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,180,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};struct FState{TWeakObjectPtr<ALWChunk> C;TWeakObjectPtr<ALWResident> N;};auto State=MakeShared<FState>();
 Add(TEXT("landmark fixtures"),1,[this,State](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;P.World->WeatherOverride=0;P.World->TimeOfDay=12;P.Health=10000;P.World->TickWeather(0,&P);auto* C=GetWorld()->SpawnActor<ALWChunk>();State->C=C;C->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(2000,2000,20));LWV2Teleport(P,FVector(20000,20000,5090));P.Controller->SetControlRotation(FRotator(0,0,0));auto* N=GetWorld()->SpawnActor<ALWResident>(FVector(20220,20000,5090),FRotator(0,180,0));State->N=N;N->ConfigureResident(TEXT("test28"),TEXT("warden"),TEXT("Casey Ward"),0);N->SetActorTickEnabled(false);});
 Add(TEXT("resident camera interaction"),1,[this,State](ALWCharacter& P){auto* N=State->N.Get();FHitResult H;FCollisionQueryParams Q;Q.AddIgnoredActor(&P);const FVector A=P.Camera->GetComponentLocation();GetWorld()->LineTraceSingleByChannel(H,A,A+P.Camera->GetForwardVector()*330,ECC_Visibility,Q);Check(H.GetActor()==N,TEXT("camera visibility trace hits rebuilt resident"));Check(P.ResidentFocus==N,TEXT("normal focus tick selects resident"));P.Interact();Check(P.Speaker==N&&P.RPGPanel==4&&P.DialogueActions.Num()>0,TEXT("normal interact opens branching conversation"));P.ClosePanels();if(N)N->Destroy();if(State->C.IsValid())State->C->Destroy();});
 for(int T=33;T<53;T++)Add(TEXT("landmark activity and persistence"),1,[this,State,T](ALWCharacter& P){P.ClosePanels();if(State->C.IsValid())State->C->Destroy();auto* C=GetWorld()->SpawnActor<ALWChunk>();State->C=C;LWGen::FSite S;S.Type=T;S.Size=LWPlaces::Size(T);S.Position=FVector2D(20000,20000);S.Id=280000+T;C->BuildingSurfaces=true;C->Building(P.World,S);C->BuildingSurfaces=false;C->FlushSurfaces();C->SetActorLocation(FVector(0,0,5000));ALWLandmark* A=nullptr;int Devices=0;for(auto O:C->Residents)if(IsValid(O)){O->AddActorWorldOffset(FVector(0,0,5000));if(auto* L=Cast<ALWLandmark>(O)){A=L;L->SetActorTickEnabled(false);}Devices+=Cast<ALWLandmarkDevice>(O)!=nullptr;}if(!RequireV2(A!=nullptr,TEXT("landmark controller exists")))return;Check(Devices>=3,TEXT("three physical objectives built"));const auto& D=LWLandmarks::Get(T);
 Check(!A->Activate(2,0,&P)&&A->Stage()==0,TEXT("cannot skip to reward"));A->Activate(0,0,&P);Check(A->Stage()==1,TEXT("first clue starts tracked quest"));FName Supply=D.Mechanic==1?TEXT("water"):D.Mechanic==5?TEXT("scrap"):TEXT("lockpick");if(D.Mechanic==1||D.Mechanic==3||D.Mechanic==5){auto I=LWItems::Make(Supply,3);LWItems::Place(P.Inventory,I,12,10);}
 if(D.Mechanic==2){A->Activate(1,(T+1)%3,&P);A->Activate(1,T%3,&P);A->Activate(1,(T+2)%3,&P);}else A->Activate(1,0,&P);Check(A->Stage()==2,TEXT("site-specific requirement advances quest"));if(A->GuardCount()){A->Tick(.4f);Check(A->Guards.ContainsByPredicate([](const auto& G){return IsValid(G);}),TEXT("challenge actually spawns enemies"));Check(!A->Activate(2,0,&P),TEXT("living threats prevent reward"));for(int I=0;I<A->GuardCount();I++)P.World->KilledZombies.Add(A->GuardId(I));}
 auto Money=P.Money;Check(A->Activate(2,0,&P)&&A->Stage()==3,TEXT("completed activity pays once"));Check(P.Money==Money+1500,TEXT("landmark payout"));auto* Reward=P.World->Containers.Find(A->Key(TEXT("reserve")));Check(Reward&&Reward->Items.ContainsByPredicate([&](const auto& I){return I.Definition==FName(D.Weapon)&&I.WeaponTier==4;}),TEXT("signature legendary reward exists"));if(Reward)Reward->Items.Empty();Money=P.Money;A->Activate(2,0,&P);Check(P.Money==Money&&Reward&&Reward->Items.IsEmpty(),TEXT("reopening cannot refill or duplicate money"));auto* Reload=GetWorld()->SpawnActor<ALWLandmark>();Reload->World=P.World;Reload->Site=S;Check(Reload->Stage()==3,TEXT("controller recreation retains completion"));Reload->MakeReward();Check(Reward&&Reward->Items.IsEmpty(),TEXT("controller recreation cannot regenerate loot"));Reload->Destroy();LWV2Teleport(P,FVector(20000,20000-S.Size.Y*.5+800,5120));P.Controller->SetControlRotation(FRotator(-3,T==36?0:70,0));},[this,T](ALWCharacter&){if(T==33||T==36||T==40||T==44||T==46||T==50)CaptureV2(*FString::Printf(TEXT("Landmark28_%d"),T));});
 Add(TEXT("airport decks and stairs"),3,[this,State](ALWCharacter& P){if(State->C.IsValid())State->C->Destroy();P.World->PropStates.Remove(TEXT("weather_crown_until"));auto* C=GetWorld()->SpawnActor<ALWChunk>();State->C=C;LWGen::FSite S;S.Type=32;S.Size=LWPlaces::Size(32);S.Position=FVector2D(20000,20000);S.Id=280032;C->BuildingSurfaces=true;C->Building(P.World,S);C->BuildingSurfaces=false;C->FlushSurfaces();C->SetActorLocation(FVector(0,0,5000));for(auto O:C->Residents)if(IsValid(O))O->AddActorWorldOffset(FVector(0,0,5000));Check(C->Residents.Num()>80,TEXT("airport has many usable storage furnishings"));Check(C->MajorBounds.IsInside(S.Position+FVector2D(14000,10000)),TEXT("airport remains loaded across its entire footprint"));FCollisionQueryParams Q;Q.AddIgnoredActor(&P);int Errors=0;for(int F=0;F<3;F++){FVector A(20000,15000,5000+28+F*520+90);FHitResult H;if(!GetWorld()->LineTraceSingleByChannel(H,A,A-FVector(0,0,110),ECC_WorldStatic,Q)||FMath::Abs(H.ImpactPoint.Z-(A.Z-90))>2)Errors++;}Check(Errors==0,TEXT("all terminal decks have solid walkable floors"));Errors=0;for(int F=0;F<2;F++)for(int J=0;J<32;J++){FVector A(13100,16500+J*45,5000+28+F*520+(J+1)*520.f/32+90);FHitResult H;if(!GetWorld()->LineTraceSingleByChannel(H,A,A-FVector(0,0,110),ECC_WorldStatic,Q)||FMath::Abs(H.ImpactPoint.Z-(A.Z-90))>2)Errors++;}Check(Errors==0,TEXT("all airport stair treads have correct collision height"));LWV2Teleport(P,FVector(20000,11500,5300));P.Controller->SetControlRotation(FRotator(6,90,0));},[this](ALWCharacter&){CaptureV2(TEXT("Airport28_Entry"));});
 Add(TEXT("airport overview"),2,[](ALWCharacter& P){LWV2Teleport(P,FVector(20000,31500,6900));P.GetCharacterMovement()->DisableMovement();P.Controller->SetControlRotation(FRotator(-13,-90,0));},[this](ALWCharacter&){CaptureV2(TEXT("Airport28_Apron"));});
 Add(TEXT("landmark cleanup"),.2,[State](ALWCharacter& P){P.ClosePanels();if(State->C.IsValid())State->C->Destroy();P.GetCharacterMovement()->SetMovementMode(MOVE_Walking);P.World->WeatherOverride=-1;P.World->PropStates.Remove(TEXT("weather_crown_until"));});
}

