if(FParse::Param(FCommandLine::Get(),TEXT("LWSettlement82Smoke"))){
 struct FState82{FVector Center=FVector(-1200000,-1200000,0);FName Claim,Foundation,Wall,Door,Window,Bed,Station,Lot,Car;TWeakObjectPtr<ACameraActor> View;int Scrap=0;float Ruggedness=1;};auto S=MakeShared<FState82>();
 auto HUD=[](ALWCharacter& P){return Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());};
 auto Click=[this,HUD](ALWCharacter& P,FName Id){auto* H=HUD(P);const auto* C=H->Controls55.FindByPredicate([&](const auto& X){return X.Id==Id;});if(!RequireV2(C!=nullptr,*FString::Printf(TEXT("82 control %s exists"),*Id.ToString())))return;auto* V=GetWorld()->GetGameViewport()->GetGameViewport();auto W=V->GetViewportWidget().Pin();if(!W)return;const auto G=W->GetCachedGeometry();const FVector2D Point=G.LocalToAbsolute(C->Center*H->Scale+H->Origin55);TSet<FKey> Keys{EKeys::LeftMouseButton};FPointerEvent D(0,0,Point,Point,Keys,EKeys::LeftMouseButton,0,FModifierKeysState());V->OnMouseButtonDown(G,D);Keys.Empty();FPointerEvent U(0,0,Point,Point,Keys,EKeys::LeftMouseButton,0,FModifierKeysState());V->OnMouseButtonUp(G,U);};
 auto Put=[this](ALWCharacter& P,FName Type,FVector At,float Yaw=0,FName Parent=NAME_None){auto* M=P.Settlement82.Get();M->SelectedCatalog=LWBuilding82::Catalog().IndexOfByPredicate([&](const auto& D){return D.Id==Type;});M->Moving=NAME_None;M->Support=Parent;M->Placement=FTransform(FRotator(0,Yaw,0),At);M->Valid=true;bool OK=M->Place();Check(OK,*FString::Printf(TEXT("82 construct %s: %s"),*Type.ToString(),*M->Message));return OK?M->State()->Pieces.Last().Id:NAME_None;};
 Add(TEXT("82 isolated settlement fixture"),1,[this,S](ALWCharacter& P){P.NewGame();P.EndOpening(true);P.ClosePanels();if(P.Campaign76){P.Campaign76->Pause();P.RPG.Campaign76.Paused=true;}P.bStoryLocked=false;P.bStarted=true;P.bMenu=false;P.bGod47=true;P.bSafehouse=false;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.SetActorTickEnabled(false);P.GetCharacterMovement()->DisableMovement();P.bCrust=false;P.World->TimeOfDay=12;P.World->TickWeather(0,&P);P.SetActorLocation(S->Center+FVector(0,-600,100));S->Ruggedness=LWGen::Ruggedness;LWGen::Ruggedness=0;P.Inventory.Empty();P.GiveItem(TEXT("settlement_flag"));P.GiveItem(TEXT("scrap"),240);S->View=GetWorld()->SpawnActor<ACameraActor>();S->View->GetCameraComponent()->SetFieldOfView(72);auto* Floor=GetWorld()->SpawnActor<ALWChunk>();Floor->SyncCollision68=true;Floor->Box(P.World,TEXT("Earth"),S->Center-FVector(0,0,10),FVector(22000,22000,20));ALWSettlement82::Ensure(&P);P.SetMenuInput(false);},[this,S](ALWCharacter& P){auto* M=P.Settlement82.Get();Check(M->BeginClaim(),TEXT("82 flag starts claim preview"));FString Why;Check(!M->ValidateClaim(S->Center+FVector(0,0,1000),Why),TEXT("82 floating flag rejected"));Check(M->ClaimAt(S->Center),*FString::Printf(TEXT("82 valid flag claims ground: %s"),*M->Message));S->Claim=M->Selected;Check(P.CountSupply(TEXT("settlement_flag"))==0&&P.RPG.Claims82.Num()==1,TEXT("82 exactly one flag consumed"));Check(!M->ClaimAt(S->Center),TEXT("82 overlapping claim rejected"));M->State()->Scrap=10000;});
 Add(TEXT("82 management single click"),.5,[](ALWCharacter&){},[this,HUD,Click](ALWCharacter& P){Check(P.RPGPanel==7&&HUD(P)->Controls55.ContainsByPredicate([](const auto& C){return C.Id==TEXT("tab_6");}),TEXT("82 settlements tab integrated"));Click(P,TEXT("s82_deposit"));Check(P.CountSupply(TEXT("scrap"))==0&&P.Settlement82->State()->Scrap==10240&&!P.bTrigger,TEXT("82 one click deposits scrap without firing"));});
 Add(TEXT("82 enter catalog"),.5,[Click](ALWCharacter& P){Click(P,TEXT("s82_begin"));},[this,HUD](ALWCharacter& P){Check(P.SettlementBuild82&&P.Settlement82->Palette&&P.IsUIOpen()&&!P.CanAct(),TEXT("82 build camera owns controls and blocks combat"));Check(HUD(P)->Controls55.Num()>12,TEXT("82 catalog and finish controls rendered"));CaptureV2(TEXT("Settlement82_Catalog"));});
 Add(TEXT("82 structural construction"),.8,[this,S,Put,HUD](ALWCharacter& P){auto* M=P.Settlement82.Get();M->SetPalette(false);TMap<FIntPoint,FName> Bases;TArray<FName> Fronts;
  for(int Y=0;Y<3;Y++)for(int X=0;X<3;X++){auto Id=Put(P,TEXT("foundation"),S->Center+FVector(X*400,800+Y*400,30));Bases.Add({X,Y},Id);}S->Foundation=Bases.FindRef({0,0});
  for(int X=0;X<3;X++){auto Id=Put(P,X==1?TEXT("door"):TEXT("window"),S->Center+FVector(X*400,600,30),0,Bases.FindRef({X,0}));Fronts.Add(Id);if(X==1)S->Door=Id;else S->Window=Id;auto Back=Put(P,TEXT("wall"),S->Center+FVector(X*400,1800,30),180,Bases.FindRef({X,2}));if(X==0)S->Wall=Back;}
  for(int Y=0;Y<3;Y++){Put(P,TEXT("wall"),S->Center+FVector(-200,800+Y*400,30),-90,Bases.FindRef({0,Y}));Put(P,TEXT("window"),S->Center+FVector(1000,800+Y*400,30),90,Bases.FindRef({2,Y}));}
  S->Bed=Put(P,TEXT("bed"),S->Center+FVector(0,1550,32),0,Bases.FindRef({0,2}));Put(P,TEXT("bed"),S->Center+FVector(220,1550,32),0,Bases.FindRef({1,2}));
  Put(P,TEXT("table"),S->Center+FVector(680,1200,32),0,Bases.FindRef({2,1}));Put(P,TEXT("chair"),S->Center+FVector(680,1050,32),0,Bases.FindRef({2,1}));Put(P,TEXT("locker"),S->Center+FVector(870,1620,32),0,Bases.FindRef({2,2}));Put(P,TEXT("ham"),S->Center+FVector(0,1050,32),0,Bases.FindRef({0,1}));Put(P,TEXT("lamp"),S->Center+FVector(80,1300,32),0,Bases.FindRef({0,1}));
  S->Station=Put(P,TEXT("scavenge"),S->Center+FVector(-1200,900,2));Put(P,TEXT("farm"),S->Center+FVector(-1200,1400,2));Put(P,TEXT("sell"),S->Center+FVector(-1200,2000,2));Put(P,TEXT("contracts"),S->Center+FVector(-1200,2450,2));
  auto Stair=Put(P,TEXT("stairs"),S->Center+FVector(1600,900,2));Put(P,TEXT("floor"),S->Center+FVector(1600,1300,322),0,Stair);
  for(int X=0;X<3;X++){FName Parent=Fronts[X];for(int Y=0;Y<3;Y++)Parent=Put(P,TEXT("roof"),S->Center+FVector(X*400,800+Y*400,350),0,Parent);}
  S->Lot=Put(P,TEXT("parking"),S->Center+FVector(0,-2500,18));
  FString Why;Check(!M->Validate(*LWBuilding82::Find(TEXT("floor")),FTransform(S->Center+FVector(2200,0,500)),NAME_None,NAME_None,Why),TEXT("82 unsupported floating floor rejected"));Check(!M->Validate(*LWBuilding82::Find(TEXT("foundation")),FTransform(S->Center+FVector(7000,0,30)),NAME_None,NAME_None,Why),TEXT("82 outside boundary rejected"));
  M->Moving=S->Foundation;Check(!M->Dismantle(),TEXT("82 foundation with attached walls cannot be removed"));M->Moving=NAME_None;
  const int Before=M->State()->Scrap;M->State()->Scrap=0;M->SelectedCatalog=LWBuilding82::Catalog().IndexOfByPredicate([](const auto& D){return D.Id==TEXT("crate");});M->Placement=FTransform(S->Center+FVector(2500,1700,2));M->Support=NAME_None;M->Valid=true;Check(!M->Place()&&M->State()->Scrap==0,TEXT("82 unaffordable build cannot consume or create"));M->State()->Scrap=Before;
  M->Moving=S->Wall;M->Outside=0;M->OutsideColor=1;M->Inside=2;M->InsideColor=3;Check(M->Paint(),TEXT("82 independent face finishes applied"));M->Moving=NAME_None;
  M->Close();P.ClosePanels();S->View->SetActorLocation(S->Center+FVector(2400,-300,1550));S->View->SetActorRotation((S->Center+FVector(0,800,70)-S->View->GetActorLocation()).Rotation());Cast<APlayerController>(P.Controller)->SetViewTarget(S->View.Get());HUD(P)->bShowHUD=false;
 },[this](ALWCharacter&){CaptureV2(TEXT("Settlement82_Construction"));});
 Add(TEXT("82 furnished interior"),.7,[S](ALWCharacter& P){S->View->SetActorLocation(S->Center+FVector(400,710,200));S->View->SetActorRotation((S->Center+FVector(340,1540,120)-S->View->GetActorLocation()).Rotation());},[this](ALWCharacter&){CaptureV2(TEXT("Settlement82_Interior"));});
 Add(TEXT("82 doors glass and collision"),.9,[this,S](ALWCharacter& P){auto* M=P.Settlement82.Get();auto* Door=M->Actors.FindRef(S->Door).Get();Check(Door&&Door->CanCompanionOpenDoor(),TEXT("82 settlement door participates in companion navigation"));if(Door)Door->Use(&P);auto* Window=M->Actors.FindRef(S->Window).Get();if(Window){FDamageEvent E;Window->TakeDamage(20,E,P.Controller,&P);Check(Window->bChanged&&!Window->Body->IsVisible(),TEXT("82 window glass breaks independently of its wall"));}},[this,S](ALWCharacter& P){auto* Door=P.Settlement82->Actors.FindRef(S->Door).Get();Check(Door&&Door->DoorAngle>85,TEXT("82 door animates open"));});
 Add(TEXT("82 recruitment and assignments"),1,[this,S,HUD](ALWCharacter& P){auto* M=P.Settlement82.Get();Check(!M->Assign(TEXT("missing"),S->Station),TEXT("82 invalid resident assignment rejected"));M->State()->RecruitmentSeconds=479;M->Economy(2);Check(M->State()->Residents.Num()==1,TEXT("82 HAM radio attracts first resident"));Check(M->Recruit(S->Claim),TEXT("82 second free bed accepts a resident"));Check(!M->Recruit(S->Claim)&&M->State()->Residents.Num()==2,TEXT("82 bed capacity prevents overpopulation"));auto N=M->State()->Residents[0].Id;Check(M->Assign(N,S->Station),TEXT("82 resident assigned to scrap station"));Check(!M->Assign(M->State()->Residents[1].Id,S->Station),TEXT("82 station cannot be double-booked"));int Scrap=M->State()->Scrap;M->State()->WorkSeconds=299;M->Economy(2);Check(M->State()->Scrap==Scrap+20,TEXT("82 assigned worker produces scrap"));Check(M->Crew(N,true),TEXT("82 resident becomes companion without hiring fee"));Scrap=M->State()->Scrap;M->Economy(300);Check(M->State()->Scrap==Scrap,TEXT("82 companion away from home does not also work"));Check(M->Crew(N,false),TEXT("82 companion returns to settlement"));M->BeginBuild(0);M->Moving=S->Bed;Check(!M->Dismantle(),TEXT("82 occupied bed allowance cannot be dismantled"));M->Close();M->Open(S->Claim);M->Panel=1;M->SelectedResident=N;HUD(P)->bShowHUD=true;},[this](ALWCharacter&){CaptureV2(TEXT("Settlement82_Residents"));});
 Add(TEXT("82 parking ownership and cargo"),1,[this,S](ALWCharacter& P){auto* M=P.Settlement82.Get();M->Selected=S->Claim;const auto* Lot=M->State()->Pieces.FindByPredicate([&](const auto& X){return X.Id==S->Lot;});if(!RequireV2(Lot!=nullptr,TEXT("82 parking lot exists")))return;
  FLWVehicleRecord R;R.Model=TEXT("sedan");R.VIN=FGuid::NewGuid();R.Position=M->Bay(*Lot,0,1);R.Rotation=FRotator(0,90,0);R.Unlocked=R.Hotwired=true;S->Car=TEXT("settlement82_smokecar");P.World->Vehicles.Add(S->Car,R);auto* Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,S->Car,R.Position,R.Rotation));if(!RequireV2(Car!=nullptr,TEXT("82 vehicle spawned")))return;Car->SetActorTickEnabled(false);Car->SpawnPlacementPending=false;P.SetActorLocation(Car->GetActorLocation()+FVector(350,0,20));Check(M->Park(Car,S->Lot),*FString::Printf(TEXT("82 register parked vehicle: %s"),*M->Message));auto* Saved=Car->Record();Check(Saved->Owned45&&Saved->GarageBay45==-1&&Saved->HomeParking82==S->Lot,TEXT("82 independent insured parking ownership"));
  auto& Cargo=P.World->Containers.FindChecked(S->Car);Cargo.Items.Empty();auto Medkit82=LWItems::Make(TEXT("medkit"),2);LWItems::Place(Cargo.Items,Medkit82,Cargo.Width,Cargo.Height);Saved->Mods45.Add(TEXT("mod45_02"));Saved->Paint45=4;Saved->Exploded=true;Saved->Health=0;Saved->Replacement45=1;
  P.SetActorLocation(S->Center+FVector(0,-300,100));auto* Obstruction=GetWorld()->SpawnActor<ALWChunk>();Obstruction->SyncCollision68=true;Obstruction->Box(P.World,TEXT("Concrete"),R.Position+FVector(0,0,70),FVector(100,100,100));M->TickParking(2);Check(P.World->Vehicles[S->Car].Exploded,TEXT("82 occupied parking defers replacement"));Obstruction->Destroy();M->TickParking(2);const auto& V=P.World->Vehicles.FindChecked(S->Car);Check(!V.Exploded&&V.Health==200&&V.VIN==R.VIN&&V.Mods45.Contains(TEXT("mod45_02"))&&V.Paint45==4,TEXT("82 destruction restores same vehicle identity and upgrades"));Check(P.World->Containers[S->Car].Items[0].Count==2,TEXT("82 replacement preserves cargo"));M->BeginBuild(0);M->Moving=S->Lot;Check(!M->Dismantle(),TEXT("82 insured parking cannot be dismantled"));M->Close();M->Open(S->Claim);M->Panel=2;M->SelectedLot=S->Lot;
 },[this](ALWCharacter&){CaptureV2(TEXT("Settlement82_Parking"));});
 Add(TEXT("82 placement move and dismantle transactions"),.5,[this,S](ALWCharacter& P){auto* M=P.Settlement82.Get();M->Selected=S->Claim;M->BeginBuild(0);M->SetPalette(false);M->Snap=true;M->Aim(S->Center+FVector(1200,800,30),FVector::UpVector);Check(M->Valid&&!M->Support.IsNone(),*FString::Printf(TEXT("82 preview chooses adjacent foundation support: %s"),*M->Message));int Before=M->State()->Pieces.Num(),Scrap=M->Scrap();M->WaitClick=false;M->Input(EKeys::LeftMouseButton,true);M->Input(EKeys::LeftMouseButton,false);Check(M->State()->Pieces.Num()==Before+1&&M->Scrap()==Scrap-16,TEXT("82 placement input commits exactly one charged foundation"));if(M->State()->Pieces.Num()==Before+1){M->Moving=M->State()->Pieces.Last().Id;Check(M->Dismantle(),TEXT("82 unused foundation dismantles"));}
  M->SelectedCatalog=LWBuilding82::Catalog().IndexOfByPredicate([](const auto& D){return D.Id==TEXT("crate");});M->Aim(S->Center+FVector(2200,1700,0),FVector::UpVector);if(!RequireV2(M->Place(),TEXT("82 loose crate placed on ground")))return;FName Crate=M->State()->Pieces.Last().Id;auto Item=LWItems::Make(TEXT("medkit"),1);auto& Store=P.World->Containers.FindChecked(Crate);LWItems::Place(Store.Items,Item,Store.Width,Store.Height);M->Moving=Crate;Check(!M->Dismantle(),TEXT("82 full storage cannot be dismantled"));Scrap=M->Scrap();M->Aim(S->Center+FVector(2500,1700,0),FVector::UpVector);Check(M->Place()&&M->Scrap()==Scrap&&P.World->Containers[Crate].Items.Num()==1,TEXT("82 moving preserves storage identity and contents without charging"));M->Moving=Crate;P.World->Containers[Crate].Items.Empty();Check(M->Dismantle()&&M->Scrap()==Scrap+4&&!P.World->Containers.Contains(Crate),TEXT("82 empty storage dismantles and refunds half its cost"));M->Close();
 },[](ALWCharacter&){});
 Add(TEXT("82 save and streaming restoration"),1,[this,S](ALWCharacter& P){auto* M=P.Settlement82.Get();P.ClosePanels();P.DrainSave40();auto* Save=P.MakeProgressSnapshot37();TArray<uint8> Bytes;Check(UGameplayStatics::SaveGameToMemory(Save,Bytes),TEXT("82 complete gameplay snapshot serializes"));auto* Round=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromMemory(Bytes));if(!RequireV2(Round!=nullptr,TEXT("82 gameplay snapshot deserializes")))return;int Pieces=M->State()->Pieces.Num();Check(Round->RPG.Claims82.FindChecked(S->Claim).Pieces.Num()==Pieces,TEXT("82 all building pieces saved"));Check(Round->RPG.Claims82[S->Claim].Residents.Num()==2&&Round->Vehicles[S->Car].HomeParking82==S->Lot,TEXT("82 residents and parking saved"));
  M->Reset();P.RPG=Round->RPG;P.World->PropStates=Round->PropStates;P.World->Containers=Round->WorldContainers;P.World->Vehicles=Round->Vehicles;M->Selected=S->Claim;M->Stream();Check(M->Queue.Num()==Pieces+1&&M->Actors.IsEmpty(),TEXT("82 streaming rebuild is queued instead of synchronous"));
 },[this,S](ALWCharacter& P){auto* M=P.Settlement82.Get();Check(M->Queue.IsEmpty()&&M->Actors.Contains(S->Door),TEXT("82 budgeted rebuild completes"));Check(M->Actors.FindRef(S->Window).Get()&&M->Actors[S->Window]->bChanged,TEXT("82 broken window state survives rebuild"));Check(M->Actors.FindRef(S->Door).Get()&&M->Actors[S->Door]->bChanged,TEXT("82 open door state survives rebuild"));});
 V2->Steps.Last().Ready=[](ALWCharacter& P){return P.Settlement82&&P.Settlement82->Queue.IsEmpty();};
 Add(TEXT("82 closing and cleanup"),.5,[this,S,HUD](ALWCharacter& P){auto* M=P.Settlement82.Get();M->Open(S->Claim);HUD(P)->bShowHUD=true;},[this,S,HUD](ALWCharacter& P){Check(HUD(P)->UIKey55(EKeys::Right),TEXT("82 tab UI supports keyboard navigation"));P.ClosePanels();Check(!P.IsUIOpen()&&!P.SettlementBuild82,TEXT("82 closing restores gameplay input"));LWGen::Ruggedness=S->Ruggedness;CaptureV2(TEXT("Settlement82_Completed"));});
 return;
}
