#include "LWChapter52.h"
#include "Engine/StaticMesh.h"
#include "LWVoice44.h"
#include "LWDialogue59.h"
#include "LWStory.h"
#include "LWCharacter.h"
#include "LWWorld.h"
#include "LWAudioCatalog.h"
#include "LWVehicle.h"
#include "Camera/CameraComponent.h"
#include "Components/PointLightComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/AudioComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/PlayerController.h"
#include "Engine/World.h"
#include "Engine/DamageEvents.h"
#include "Kismet/GameplayStatics.h"
#include "EngineUtils.h"

const TArray<LWStory::FMission>& LWStory::Missions(){static const TArray<FMission> M={
 {TEXT("1. The Morning After"),TEXT("Wake up in Shelter 01."),-1,TEXT(""),0},
 {TEXT("1. The Morning After"),TEXT("Sweep the bunker radio for a signal."),-1,TEXT("radio"),0},
 {TEXT("1. The Morning After"),TEXT("Leave the bunker and survey the surface."),0,TEXT(""),0},
 {TEXT("2. A Voice on the Road"),TEXT("Meet Mara at Mile Nine Rest Stop."),0,TEXT("mara"),0},
 {TEXT("2. A Voice on the Road"),TEXT("Pack Mara's emergency supplies."),0,TEXT("supplies"),0},
 {TEXT("2. A Voice on the Road"),TEXT("Clear the infected around the rest stop."),0,TEXT(""),3},
 {TEXT("3. A Place at the Table"),TEXT("Travel with Mara to Mercy Crossing."),1,TEXT(""),0},
 {TEXT("3. A Place at the Table"),TEXT("Meet Jonah Reed at the communal kitchen."),1,TEXT("jonah"),0},
 {TEXT("4. The Price of Shelter"),TEXT("Defend Mercy Crossing from the Cinder Choir."),1,TEXT(""),6},
 {TEXT("5. Names in the Ash"),TEXT("Find Jonah's evacuation note in the burned communal kitchen."),1,TEXT("ashes"),0},
 {TEXT("5. Names in the Ash"),TEXT("Treat the wounded survivor, open the pharmacy, and recover a trauma kit."),2,TEXT("trauma"),5},
 {TEXT("6. Paper Trail"),TEXT("Infiltrate the toll offices and recover the stamped transfer ledger."),3,TEXT("ledger"),6},
 {TEXT("7. Dead Air"),TEXT("Restore Relay Six: activate the generator and transmitter."),4,TEXT("relay"),5},
 {TEXT("8. A Witness Worth Saving"),TEXT("Meet Inez at Dry Creek's maintenance shelter."),5,TEXT("inez"),0},
 {TEXT("8. A Witness Worth Saving"),TEXT("Track the dispatcher through the freight yard and recover his manifest."),5,TEXT("manifest"),7},
 {TEXT("9. The Kennels"),TEXT("Find the warden in his office and take his cell keys."),6,TEXT("key"),8},
 {TEXT("9. The Kennels"),TEXT("Unlock Mara's cell."),6,TEXT("rescue"),0},
 {TEXT("10. No One Left Behind"),TEXT("Regroup with Mara in the prison infirmary."),6,TEXT("mara_plan"),0},
 {TEXT("11. The Ash Crown"),TEXT("Destroy the foundry defense feeds and clear a path into the furnace hall."),7,TEXT("breach"),8},
 {TEXT("11. The Ash Crown"),TEXT("Defeat Silas Rusk in the furnace hall."),7,TEXT(""),4},
 {TEXT("12. Liberty's Welcome"),TEXT("Answer Captain Voss's demand."),7,TEXT(""),0},
 {TEXT("13. Model Citizens"),TEXT("Find a loose fastener under your cell bunk."),8,TEXT("fastener"),0},
 {TEXT("13. Model Citizens"),TEXT("Short the cell lock at the service breaker."),8,TEXT("breaker"),0},
 {TEXT("14. Property of the State"),TEXT("Recover your confiscated equipment from evidence storage."),8,TEXT("gear"),3},
 {TEXT("14. Property of the State"),TEXT("Secure the detention wing and release the settlers using the cell controls."),8,TEXT("free"),5},
 {TEXT("15. The People Outside"),TEXT("Fight with the settlers through the muster yard."),8,TEXT(""),10},
 {TEXT("16. A Republic of One"),TEXT("Destroy the command relays and defeat Director Mercer."),8,TEXT(""),5},
 {TEXT("17. The Gates Stay Open"),TEXT("Witness Liberty's Heroes surrender."),8,TEXT(""),0},
 {TEXT("17. The Gates Stay Open"),TEXT("Accept the settlers' vote at the command desk."),8,TEXT("charter"),0},
 {TEXT("Chapter 1 Complete"),TEXT("Fort Resolute is your settlement. Speak to Jonah to manage it."),8,TEXT(""),0}};return M;}
FLWStoryState& ALWStoryDirector::State()const{return Player->RPG.Story;}
ALWStoryDirector::ALWStoryDirector(){PrimaryActorTick.bCanEverTick=true;RootComponent=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));Camera=CreateDefaultSubobject<UCameraComponent>(TEXT("StoryCamera"));Camera->SetupAttachment(RootComponent);Camera->FieldOfView=68;SceneLight=CreateDefaultSubobject<UPointLightComponent>(TEXT("CinematicFill"));SceneLight->SetupAttachment(Camera);SceneLight->SetRelativeLocation(FVector(30,0,35));SceneLight->SetIntensity(90000);SceneLight->SetAttenuationRadius(2000);SceneLight->SetCastShadows(false);SceneLight->SetVisibility(false);}
ALWStoryDirector* ALWStoryDirector::Ensure(ALWCharacter* P){if(!P||!P->World)return nullptr;if(!IsValid(P->Story)){auto* D=P->GetWorld()->SpawnActor<ALWStoryDirector>();D->Player=P;D->World=P->World;P->Story=D;}return P->Story;}
FVector ALWStoryDirector::At(int32 I,FVector Local)const{return FVector(LWStory::Site(I),30)+Local;}
FVector ALWStoryDirector::Target()const{const auto& M=LWStory::Missions()[FMath::Clamp(State().Stage,0,29)];for(auto& N:Nodes)if(IsValid(N)&&Available(N->Action))return N->GetActorLocation();if(FCString::Strlen(M.Action))for(auto& N:Nodes)if(IsValid(N)&&N->Action==M.Action)return N->GetActorLocation();for(auto& E:Enemies)if(IsValid(E)&&!E->bDead)return E->GetActorLocation();if(State().Stage==3||State().Stage==7||State().Stage==13||State().Stage==17){const FName Who=State().Stage==7?TEXT("story_jonah"):State().Stage==13?TEXT("story_inez"):TEXT("story_mara");if(auto* N=People.FindRef(Who).Get())return N->GetActorLocation();}return M.Site<0?ALWWorld::BunkerSpawn():At(M.Site,FVector(0,-2300,100));}
// Chapter 1 is retired. Retain the director type only for legacy references.
void ALWStoryDirector::Start(bool Fresh){ClearActors();State().Enabled=false;Player->bStoryLocked=false;InScene=Choosing=Failed=false;SetActorTickEnabled(false);}
void ALWStoryDirector::Route(){Player->SetWaypoint(FVector2D(Target()));}
void ALWStoryDirector::ClearActors(bool All){if(SceneAudio){SceneAudio->Stop();SceneAudio->DestroyComponent();SceneAudio=nullptr;}if(Transport)Transport->DestroyComponent();Transport=nullptr;for(auto& F:Fire)if(F)F->DestroyComponent();Fire.Empty();for(auto& A:Actors)if(IsValid(A))A->Destroy();Actors.Empty();Enemies.Empty();People.Empty();Nodes.Empty();if(All){for(auto& S:Sites)if(IsValid(S.Value))S.Value->Destroy();Sites.Empty();SiteRevisions38.Empty();}}
void ALWStoryDirector::EndPlay(const EEndPlayReason::Type R){ClearActors();if(Player){Player->bStoryLocked=false;if(auto* PC=Cast<APlayerController>(Player->Controller))PC->SetViewTarget(Player);}Super::EndPlay(R);}
void ALWStoryDirector::Advance(){auto& S=State();if(S.Stage>=29)return;if(!S.Paid.Contains(S.Stage)){S.Paid.Add(S.Stage);Player->GainXP(S.Stage<8?60:180);if(S.Stage>=9)Player->Money+=35;}S.Stage++;if(S.Stage>=LWStory::Complete)Player->MissionRecovery37.Remove(TEXT("chapter1"));S.SceneFinished=false;S.BossWave=0;Player->ClosePanels();Choosing=false;Applied=-1;ApplyStage();Player->RequestSave40();}
void ALWStoryDirector::ApplyStage(){int S=State().Stage;if(Applied==S)return;Applied=S;CombatGrace52=GetWorld()->GetTimeSeconds()+4;ClearActors(false);Player->bStoryLocked=false;InScene=Choosing=Failed=false;Shots.Empty();ShotIndex=0;ShotTime=0;
 int I=LWStory::Missions()[S].Site;if(I>=0)BuildSite(I);if(S==0||S==1)Node(TEXT("radio"),TEXT("Sweep the radio dial"),ALWWorld::BunkerSpawn()+FVector(230,-150,-40),TEXT("RadioV4"));
 SpawnStage();if(S==6)if(auto* N=People.FindRef(TEXT("story_mara")).Get())N->SetActorLocation(Player->GetActorLocation()-Player->GetActorForwardVector()*250);if(S!=0&&S!=29)Route();Player->Notify(FString(LWStory::Missions()[S].Title)+TEXT("\n")+LWStory::Missions()[S].Objective,7);
 Player->CaptureMission37(TEXT("chapter1"));
 if((S==0||S==20||S==26||S==27)&&!State().SceneFinished)Scene(S);else if(S==20){Conversation=TEXT("20");FinishScene();if(State().Flags.Contains(TEXT("execution_ending"))){Conversation=TEXT("-2");FinishScene();}}
}
int32 ALWStoryDirector::Remaining()const{int N=0;for(auto& E:Enemies)if(IsValid(E)&&!E->bDead)N++;return N;}
bool ALWStoryDirector::Available(FName A)const{const int S=State().Stage;const auto& M=LWStory::Missions()[S];if(Locked()||Player->Health<=0)return false;if(A==TEXT("shield_a")||A==TEXT("shield_b"))return S==26&&!State().Flags.Contains(A);if(A==TEXT("triage")||A==TEXT("pharmacy"))return S==10&&!State().Flags.Contains(A);if(A==TEXT("trauma")&&(!State().Flags.Contains(TEXT("triage"))||!State().Flags.Contains(TEXT("pharmacy"))))return false;if(A==TEXT("key")||A==TEXT("manifest")){if(S!=(A==TEXT("key")?15:14))return false;for(auto& E:Enemies)if(IsValid(E)&&E->EncounterIndex52==0&&!E->bDead)return false;return true;}if(A==TEXT("relay_a")||A==TEXT("relay_b"))return S==12&&!State().Flags.Contains(A);if(A==TEXT("breach_a")||A==TEXT("breach_b"))return S==18&&!State().Flags.Contains(A);return A==M.Action&&(S==11||M.Enemies==0||Remaining()==0);}
void ALWStoryNode::Use(ALWCharacter* P){if(!LWChapter52::Destructible(Action)&&Director&&P==Director->Player&&FVector::Dist(P->GetActorLocation(),GetActorLocation())<400)Director->Activate(Action);}
FString ALWStoryNode::Prompt()const{return Director&&Director->Available(Action)?(LWChapter52::Destructible(Action)?TEXT("DESTROY: "):TEXT("[E] "))+Label:FString();}
void ALWStoryPerson::Tick(float Dt){if(NpcRole!=TEXT("story")){Super::Tick(Dt);return;}ACharacter::Tick(Dt);FireTime=FMath::Max(0.f,FireTime-Dt);if(GetVelocity().Size2D()>20&&Parts.Num()>=7){float Swing=FMath::Sin(GetWorld()->GetTimeSeconds()*9)*22;Parts[5]->SetRelativeRotation(FRotator(Swing,0,0));Parts[6]->SetRelativeRotation(FRotator(-Swing,0,0));}SubtitleTime=FMath::Max(0.f,SubtitleTime-Dt);if(DownTime>0){DownTime-=Dt;if(DownTime<=0)Health=150;} }
ALWStoryPerson* ALWStoryDirector::Person(FName Id,const FString& Name,FVector Pos,int V){if(State().Stage==29&&Player->RPG.Crew.ContainsByPredicate([&](const auto& C){return C.Id==Id;}))return nullptr;if(auto* N=People.FindRef(Id).Get();IsValid(N))return N;FActorSpawnParameters Params;Params.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* N=GetWorld()->SpawnActor<ALWStoryPerson>(Pos,FRotator(0,-90,0),Params);if(!N)return nullptr;N->ConfigureResident(Id,TEXT("story"),Name,V);if(N->Gun)N->Gun->SetVisibility(State().Stage>=25&&State().Stage<=26);N->ChatterTime=99999;People.Add(Id,N);Actors.Add(N);return N;}
ALWStoryNode* ALWStoryDirector::Node(FName A,const FString& L,FVector Pos,FName Mesh){auto* N=GetWorld()->SpawnActor<ALWStoryNode>(Pos,FRotator::ZeroRotator);if(!N)return nullptr;N->Configure(World,ELWObjectKind::Sign,FName(*(TEXT("chapter1_")+A.ToString())));N->Body->SetStaticMesh(World->Mesh(Mesh));N->Director=this;N->Action=A;N->Label=L;N->Body->SetCollisionProfileName(TEXT("BlockAll"));Actors.Add(N);Nodes.Add(N);return N;}
ALWStoryEnemy* ALWStoryDirector::Enemy(int Index,FVector Pos,bool Armor,int Boss){uint32 Id=LWStory::EnemyId(State().Stage,Index);if(World->KilledZombies.Contains(Id))return nullptr;FActorSpawnParameters Params;Params.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;auto* N=GetWorld()->SpawnActor<ALWStoryEnemy>(Pos,FRotator(0,-90,0),Params);if(!N)return nullptr;N->Director=this;N->Boss=Boss;N->EncounterIndex52=Index;N->PersistentId=Id;N->ConfigureKind(State().Stage==5?ELWEnemyKind::Zombie:ELWEnemyKind::Raider);N->Stars=Boss?3:0;N->LegendaryInitialized=!Boss;if(Boss)N->EnsureLegendary();else N->MaximumHealth=N->Health;if(Boss)N->Health=N->MaximumHealth=Boss==2?2400:1100;N->Home=Pos;N->Interest=Pos;N->Alert=0;N->AttackCooldown=1.5f;N->CustomName=Boss==1?TEXT("Silas Rusk"):Boss==2?TEXT("Director Elias Mercer"):Armor?TEXT("Liberty's Heroes Trooper"):TEXT("Cinder Choir Raider");if(Armor)for(auto& Part:N->Parts)if(Part&&Part->GetStaticMesh())for(int Slot=0;Slot<Part->GetNumMaterials();Slot++)if(Part->GetMaterialSlotNames()[Slot].ToString().Contains(TEXT("Cloth")))Part->SetMaterial(Slot,World->Material(TEXT("Armor32")));Actors.Add(N);Enemies.Add(N);return N;}
float ALWStoryEnemy::TakeDamage(float D,const FDamageEvent& E,AController* I,AActor* C){if(Director&&Director->InScene)return 0;if(Boss&&Director){if(Boss==2&&(!Director->State().Flags.Contains(TEXT("shield_a"))||!Director->State().Flags.Contains(TEXT("shield_b")))){Director->Player->Notify(TEXT("Mercer's command armor is powered by the two relays."));return 0;}FDamageEvent Plain;if(Boss==1&&Health-D<=100){Health=100;Director->State().Flags.Add(TEXT("rusk_kneels"));return 0;}return Super::TakeDamage(FMath::Min(D,350.f),Plain,I,C);}return Super::TakeDamage(D,E,I,C);}
void ALWStoryDirector::SpawnStage(){const int S=State().Stage;const auto& M=LWStory::Missions()[S];const int I=M.Site;if(I<0)return;
 if(S==3||S==4||S==5||S==6||S==7||S==8||S==16||S==17||S>=24){auto* N=Person(TEXT("story_mara"),TEXT("Mara Vale"),At(I,FVector(-250,-2350,100)),1);if(N&&S==16)N->SetActorLocation(At(I,FVector(1600,3400,100)));}
 if(S==7||S==8||S>=24)Person(TEXT("story_jonah"),TEXT("Jonah Reed"),At(I,FVector(250,-2100,100)),0);
 if(S==13)Person(TEXT("story_inez"),TEXT("Inez Soto"),At(I,FVector(0,-2200,100)),2);
 if(S==20){Person(TEXT("story_voss"),TEXT("Captain Adrienne Voss"),At(I,FVector(0,700,100)),2);for(int K=0;K<4;K++){auto* N=Person(FName(*FString::Printf(TEXT("hero_%d"),K)),TEXT("Liberty's Heroes"),At(I,FVector((K-1.5f)*180,350,100)));if(N){if(N->Gun)N->Gun->SetVisibility(true);for(auto& Part:N->Parts)if(Part&&Part->GetStaticMesh())for(int Slot=0;Slot<Part->GetNumMaterials();Slot++)if(Part->GetMaterialSlotNames()[Slot].ToString().Contains(TEXT("Cloth")))Part->SetMaterial(Slot,World->Material(TEXT("Armor32")));}}}
 const auto Posts=LWChapter52::Posts(I,S);TArray<FVector> UsedPosts;for(int K=0;K<M.Enemies;K++){FVector Pos=At(I,Posts[K%Posts.Num()]);auto Clear=[&](FVector V){return FVector::Dist2D(V,Player->GetActorLocation())>=900&&!UsedPosts.ContainsByPredicate([&](FVector U){return FVector::Dist2D(U,V)<180;});};if(!Clear(Pos)){for(const FVector& Alternative:Posts)if(Clear(At(I,Alternative))){Pos=At(I,Alternative);break;}}if(!Clear(Pos))Pos=At(I,FVector(-3700+K*240,-3300,110));UsedPosts.Add(Pos);Enemy(K,Pos,S>=21,(S==19&&K==0)?1:(S==26&&K==0)?2:0);}
 if(S==26){Node(TEXT("shield_a"),TEXT("Destroy west command relay"),Objective52(TEXT("shield_a")),TEXT("Generator"));Node(TEXT("shield_b"),TEXT("Destroy east command relay"),Objective52(TEXT("shield_b")),TEXT("Generator"));}
 else if(S==12||S==18){FString Prefix=S==12?TEXT("relay"):TEXT("breach");Node(FName(*(Prefix+TEXT("_a"))),S==12?TEXT("Start the relay generator"):TEXT("Disable west defense relay"),Objective52(FName(*(Prefix+TEXT("_a")))),TEXT("Generator"));Node(FName(*(Prefix+TEXT("_b"))),S==12?TEXT("Align the transmitter"):TEXT("Disable east defense relay"),Objective52(FName(*(Prefix+TEXT("_b")))),S==12?TEXT("RelayConsole52"):TEXT("Generator"));}
 else if(FCString::Strlen(M.Action)&&FString(M.Action)!=TEXT("mara")&&FString(M.Action)!=TEXT("jonah")&&FString(M.Action)!=TEXT("inez")&&FString(M.Action)!=TEXT("mara_plan")){
 Node(M.Action,M.Objective,Objective52(M.Action),LWChapter52::Prop(M.Action));}
 if(S==10){auto* Patient=Person(TEXT("story_tessa"),TEXT("Tessa Ward"),At(2,FVector(-2450,0,110)),2);if(Patient){Patient->Health=State().Flags.Contains(TEXT("triage"))?150:30;Patient->Say(State().Flags.Contains(TEXT("triage"))?TEXT("The pharmacy cabinet. Please take what you need."):TEXT("Over here. I cannot stop the bleeding."));}Node(TEXT("triage"),TEXT("Dress the survivor's wounds"),Objective52(TEXT("triage")),TEXT("MedicalCase52"));Node(TEXT("pharmacy"),TEXT("Release the pharmacy cabinet latch"),Objective52(TEXT("pharmacy")),TEXT("EvidenceCabinetV18"));}
 if(S==26&&State().BossWave>0)for(int K=20;K<24;K++)Enemy(K,At(8,FVector((K%2?1:-1)*2700,2300+(K%2)*500,110)),true);
 if(S==7||S==8||S>=24){Person(TEXT("story_elsie"),TEXT("Elsie Park"),At(I,FVector(-650,-2700,100)),2);Person(TEXT("story_tomas"),TEXT("Tomas Bell"),At(I,FVector(650,-2700,100)),0);if(S>=24)Person(TEXT("story_inez"),TEXT("Inez Soto"),At(I,FVector(900,-2450,100)),2);}
 if(S>=24&&S<=26){int K=0;for(auto& Pair:People){auto* N=Pair.Value.Get();if(N){N->SetActorLocation(At(8,FVector(3350,-2350+K*320,110)));K++;}}}
 if(S==7)if(auto* N=People.FindRef(TEXT("story_jonah")).Get())N->SetActorLocation(At(1,FVector(-2300,200,110)));
 if(S==13)if(auto* N=People.FindRef(TEXT("story_inez")).Get())N->SetActorLocation(At(5,FVector(-2700,-1500,110)));
 if(S==17)if(auto* N=People.FindRef(TEXT("story_mara")).Get())N->SetActorLocation(At(6,FVector(-2500,100,110)));
 if(S==29){if(auto* Mara=People.FindRef(TEXT("story_mara")).Get()){Mara->NpcRole=TEXT("recruit");Mara->SettlementId=TEXT("fort_resolute");}auto* J=Person(TEXT("story_jonah"),TEXT("Jonah Reed"),At(I,FVector(250,-2100,100)));if(J){J->NpcRole=TEXT("warden");J->SettlementId=TEXT("fort_resolute");}for(auto& Pair:People){auto* N=Pair.Value.Get();if(!N)continue;N->SettlementId=TEXT("fort_resolute");if(Pair.Key==TEXT("story_elsie"))N->NpcRole=TEXT("merchant");if(Pair.Key==TEXT("story_tomas"))N->NpcRole=TEXT("medic");if(Pair.Key==TEXT("story_inez"))N->NpcRole=TEXT("recruit");}}
}
void ALWStoryDirector::SpeakTo(ALWResident* N){if(!N||Locked())return;FName A=N->ResidentId==TEXT("story_mara")?(State().Stage==17?TEXT("mara_plan"):TEXT("mara")):N->ResidentId==TEXT("story_jonah")?TEXT("jonah"):TEXT("inez");if(!Available(A)){N->Say(State().Stage>=24?TEXT("We came back for you. Keep moving!"):TEXT("I'm here. Finish what we started."));return;}Conversation=A;Choosing=true;Player->ClosePanels();Player->bStoryLocked=true;Player->SetMenuInput(true);VoiceName=N->DisplayName;Choices={TEXT("Tell me what happened."),TEXT("I'm ready. Let's do this."),TEXT("Give me a moment.")};
 Speech=A==TEXT("mara")?TEXT("Easy. I'm Mara. I used to patch up highway crews. No rescue broadcasts, no deliveries, no cavalry. Take clean water, keep a bandage dry, and check your magazine before trouble finds you. There's a place called Mercy Crossing. We keep the gates open."):A==TEXT("jonah")?TEXT("Mara says you came out of Shelter 01. I'm Jonah. That generator powers a clinic and twelve families' cookers. We vote on work, share water, and bury our own. Rusk calls that a tax base. We refused his collection yesterday."):A==TEXT("inez")?TEXT("I drove their transfers. Rusk keeps people at the Kennels until somebody pays. The people who can't pay go to men in silver armor. Mara got marked MEDICAL. She's alive. I need you to make that mean something."):TEXT("Rusk sold us. The silver soldiers wanted medics, mechanics, anyone useful. Jonah got people out of the fire, but the next transfer leaves tonight. The foundry relays protect Rusk's furnace hall. Shut them down. We end the trade here.");N->Say(Speech);}
void ALWStoryDirector::Choose(int I){if(Failed){if(I==0){Failed=false;State().Flags.Remove(TEXT("execution_ending"));State().SceneFinished=true;Choosing=true;Choices={TEXT("Surrender my weapons and follow."),TEXT("Refuse. They will take me by force.")};Speech=TEXT("Captain Voss waits for your answer.");Player->bStoryLocked=true;Player->SetMenuInput(true);}return;}if(!Choosing||!Choices.IsValidIndex(I))return;
 if(State().Stage==20){Choosing=false;Player->SetMenuInput(false);if(I==0){State().Flags.Add(TEXT("surrendered"));Scene(-2);}else{State().Flags.Add(TEXT("resisted"));Confiscate();Advance();Scene(-3);}return;}
 if(Choices[I].StartsWith(TEXT("Tell me"))){Speech+=TEXT("\n\nThe roads still connect the towns. What has broken is trust. Follow the evidence, keep supplies in reserve, and don't confuse a uniform with a promise.");if(ULWDialogue59::Available())ULWDialogue59::Channel(this)->Say(ULWDialogueCatalog59::StoryIdentity(VoiceName),false,TEXT("The roads still connect the towns. What has broken is trust. Follow the evidence, keep supplies in reserve, and don't confuse a uniform with a promise."),true);Choices.RemoveAt(0);Conversation=FName(*(Conversation.ToString()+TEXT("_heard")));return;}
 // After the optional question, indices shift; action depends on the selected label.
 bool Go=Choices[I].StartsWith(TEXT("I'm ready"));Choosing=false;Player->bStoryLocked=false;Player->SetMenuInput(false);if(Go)Advance();}
bool ALWStoryDirector::Activate(FName A){if(!Available(A))return false;const int S=State().Stage;
 if(A==TEXT("radio")){Scene(1);return true;}
 if(A==TEXT("triage")||A==TEXT("pharmacy")){State().Flags.Add(A);if(A==TEXT("triage"))if(auto* Patient=People.FindRef(TEXT("story_tessa")).Get()){Patient->Health=150;Patient->Say(TEXT("Thank you. The trauma supplies are in the pharmacy. The raiders left their paperwork there, too."));}World->Sound(TEXT("Click"),Objective52(A));Player->Notify(A==TEXT("triage")?TEXT("The bleeding stops. She points toward the pharmacy."):TEXT("The pharmacy is open. Take the sealed trauma supplies."),5);Player->CaptureMission37(TEXT("chapter1"),true);Player->RequestSave40();Route();return true;}
 if(A==TEXT("rescue"))State().Flags.Add(TEXT("mara_cell_open52"));if(A==TEXT("free"))State().Flags.Add(TEXT("settler_cells_open52"));
 if(A==TEXT("supplies")){Player->GiveItem(TEXT("water"),2);Player->GiveItem(TEXT("food"),2);Player->GiveItem(TEXT("medkit"),1);}
 if(A==TEXT("relay_a")||A==TEXT("relay_b")||A==TEXT("breach_a")||A==TEXT("breach_b")||A==TEXT("shield_a")||A==TEXT("shield_b")){State().Flags.Add(A);World->Sound(TEXT("Click"),Target());Player->RequestSave40();if((S==12&&State().Flags.Contains(TEXT("relay_a"))&&State().Flags.Contains(TEXT("relay_b")))||(S==18&&State().Flags.Contains(TEXT("breach_a"))&&State().Flags.Contains(TEXT("breach_b"))&&Remaining()==0)){Scene(S);}return true;}
 if(A==TEXT("gear"))RecoverGear();if(A==TEXT("charter")){Claim();Advance();return true;}if(S==21||S==22){World->Sound(TEXT("Click"),Player->GetActorLocation());Advance();return true;}Scene(S);return true;}
void ALWStoryDirector::Confiscate(){auto& S=State();if(S.GearHeld)return;Player->CancelReload();S.Confiscated=Player->Inventory;S.ConfiscatedWeapon=Player->ActiveWeaponId;S.GearHeld=true;Player->Inventory.Empty();Player->ActiveWeaponId.Invalidate();Player->Weapon=-1;Player->WeaponRoot->SetVisibility(false,true);for(auto& C:Player->RPG.Crew)C.Following=false;Player->RequestSave40();}
void ALWStoryDirector::RecoverGear(){auto& S=State();if(!S.GearHeld)return;auto Found=Player->Inventory;Player->Inventory=S.Confiscated;Player->ActiveWeaponId=S.ConfiscatedWeapon;S.Confiscated.Empty();S.GearHeld=false;for(auto V:Found){V.Slot=NAME_None;if(!LWItems::Place(Player->Inventory,V,12,LWItems::InventoryHeight(Player->Inventory)))World->DropGear(Player->GetActorLocation(),{V});}if(Player->ActiveGun())Player->Equip(LWItems::Def(Player->ActiveGun()->Definition).WeaponIndex);Player->RequestSave40();}
void ALWStoryDirector::RestorePrison(){BuildSite(8);Player->SetActorLocation(At(8,FVector(-2500,-2200,110)),false,nullptr,ETeleportType::TeleportPhysics);Player->GetCharacterMovement()->SetMovementMode(MOVE_Walking);Player->Health=Player->MaxHealth();Player->bDeadSaved=false;}
void ALWStoryDirector::Claim(){if(State().Flags.Contains(TEXT("fort_liberated")))return;auto& R=Player->RPG.Settlements.FindOrAdd(TEXT("fort_resolute"));R.Name=TEXT("Fort Resolute");R.Center=At(8,FVector(0,-1800,100));R.Size=2;R.Reputation=100;R.Member=R.Leader=true;R.LastEconomyHour=Player->WorldHour();Player->RPG.Respawn.Enabled=true;Player->RPG.Respawn.Vehicle=NAME_None;Player->RPG.Respawn.Position=R.Center;Player->RPG.Respawn.Name=R.Name;Player->Money+=1500;State().Flags.Add(TEXT("fort_liberated"));}
void ALWStoryDirector::Tick(float Dt){Super::Tick(Dt);if(!Player||!World||!Player->bStarted||Player->bMenu||Player->OpeningMode||!State().Enabled)return;if(Player->Health<=0)return;if(Applied!=State().Stage)ApplyStage();
 if(InScene){AnimateScene(Dt);Player->bTrigger=Player->bAim=Player->bSprint=false;Player->GetCharacterMovement()->StopMovementImmediately();ShotTime+=Dt;auto& B=Shots[ShotIndex];float T=FMath::Clamp(ShotTime/B.Duration,0.f,1.f);FVector P=FMath::Lerp(B.From,B.To,FMath::SmoothStep(0.f,1.f,T));SceneLight->SetIntensity(FMath::Clamp(float(FVector::DistSquared(P,B.Look)*.05),4000.f,90000.f));Camera->SetWorldLocation(P);Camera->SetWorldRotation((B.Look-P).Rotation());if(ShotTime>=B.Duration&&!(ULWDialogue59::Available()&&ULWDialogue59::Channel(this)->Busy())){ShotTime=0;ShotIndex++;if(!Shots.IsValidIndex(ShotIndex)){FinishScene();return;}Speech=Shots[ShotIndex].Line;VoiceName=Shots[ShotIndex].Speaker;if(ULWDialogue59::Available())ULWDialogue59::Channel(this)->Say(ULWDialogueCatalog59::StoryIdentity(VoiceName),false,Speech,true);else World->Sound(LWVoice44::Story(VoiceName),Camera->GetComponentLocation(),.4f);}return;}
 if(Locked())return;const int S=State().Stage;const int Area=LWStory::Missions()[S].Site;float Step=Dt;
 if(Area>=0&&FVector::Dist2D(Player->GetActorLocation(),At(Area))<4800)Player->DiscoverPlace(0xEF320000u+Area,At(Area,FVector(0,-4200,100)),LWStory::SiteName(Area));
 for(auto& Pair:People){auto* N=Pair.Value.Get();if(!IsValid(N)||N->DownTime>0)continue;if(S==5||S==8||(S==6&&Pair.Key==TEXT("story_mara"))||(S>=25&&S<27)){if(S==6){if(N->Riding){if(Player->Vehicle==N->Riding)continue;N->LeaveVehicle();}if(Player->Vehicle&&Player->Vehicle->HasFreeCompanionSeat()&&Player->Vehicle->Board(N))continue;if(FVector::Dist2D(Player->GetActorLocation(),Target())<1800&&FVector::Dist2D(N->GetActorLocation(),Player->GetActorLocation())>6500){FVector Arrival=At(1,FVector(-700,-3700,120));FRotator R=FRotator::ZeroRotator; if(GetWorld()->FindTeleportSpot(N,Arrival,R)){N->SetActorLocation(Arrival);N->ResetCompanionNavigation();Player->Notify(TEXT("Mara reached Mercy Crossing. Meet her at the gate."));}}}if((S==5||S==8||S>=25)&&N->TickCompanionThreat(Step,Player))continue;FVector Goal=Player->GetActorLocation()-Player->GetActorForwardVector()*220+FVector(Pair.Key==TEXT("story_mara")?-100:100,0,0);if(FVector::Dist2D(N->GetActorLocation(),Player->GetActorLocation())>250)N->NavigateCompanion(Goal,400,Step);}}
 Clock+=Dt;if(Clock<.25f)return;Clock=0;for(int I=0;I<9;I++){float Distance=FVector::Dist2D(Player->GetActorLocation(),At(I));if(Distance<18000)BuildSite(I);else if(I!=Area&&Distance>26000){if(auto* C=Sites.FindRef(I).Get())C->Destroy();Sites.Remove(I);}}
 if(S==2&&!ALWWorld::IsSafePosition(Player->GetActorLocation())&&Player->GetActorLocation().Z>-100)Advance();
 else if(S==6&&FVector::Dist2D(Player->GetActorLocation(),Target())<1300){auto* Mara=People.FindRef(TEXT("story_mara")).Get();if(Mara&&FVector::Dist2D(Mara->GetActorLocation(),Player->GetActorLocation())<900)Advance();}
 else if((S==5||S==8||S==25)&&Remaining()==0){if(S==8)Scene(8);else Advance();}
 else if(S==18&&Remaining()==0&&State().Flags.Contains(TEXT("breach_a"))&&State().Flags.Contains(TEXT("breach_b")))Scene(18);
 else if(S==19&&State().Flags.Contains(TEXT("rusk_kneels"))&&Remaining()<=1)Advance();
 else if(S==26){auto* Boss=Enemies.FindByPredicate([](const auto& N){return IsValid(N)&&N->Boss==2&&!N->bDead;});if(Boss&&(*Boss)->Health<(*Boss)->MaximumHealth*.55f&&State().BossWave==0){State().BossWave=1;for(int K=20;K<24;K++)Enemy(K,At(8,FVector((K%2?1:-1)*2700,2300+(K%2)*500,110)),true);Player->RequestSave40();}if(Remaining()==0)Advance();}
}
