#include "LWStory.h"
void ALWGameMode::BuildStory31Smoke(ALWCharacter& Initial){
 auto Add=[this](FString Name,double Wait,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({Name,Wait,120,MoveTemp(Begin),MoveTemp(End),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};
 struct FState{TArray<FGuid> Gear;};auto S=MakeShared<FState>();
 auto Kill=[](ALWStoryDirector* D,ALWCharacter& P){FDamageEvent E;auto Targets=D->Enemies;for(auto& N:Targets)if(IsValid(N))for(int Hit=0;Hit<40&&!N->bDead;Hit++){N->TakeDamage(500,E,P.Controller,&P);if(N->Boss==1&&N->Health<=100)break;}};
 Add(TEXT("Legacy chapter relocation is single-pass"),.5,[this](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=true;P.RPG.Story.Stage=3;P.RPG.Story.LayoutVersion52=0;LWV2Teleport(P,FVector(8000,10000,120));auto* D=ALWStoryDirector::Ensure(&P);D->Migrate52();Check(FVector::Dist2D(P.GetActorLocation(),D->At(0))<5000,TEXT("legacy diner save relocates once, not again via nearby old settlement"));Check(P.RPG.Story.LayoutVersion52==52,TEXT("layout migration is versioned"));FVector Once=P.GetActorLocation();D->Migrate52();Check(P.GetActorLocation().Equals(Once),TEXT("layout migration is idempotent"));});
 Add(TEXT("Chapter 1 new-game awakening"),2,[this,S](ALWCharacter& P){P.NewGame();P.RPG.Story=FLWStoryState();P.RPG.Story.Enabled=true;P.World->EnableEncounters=false;P.Health=10000;auto* D=ALWStoryDirector::Ensure(&P);D->Start(false);Check(D->InScene&&P.bStoryLocked,TEXT("chapter begins with live bunker camera and input lock"));P.SwitchTab(0);Check(!P.bInventory&&!P.CanAct(),TEXT("cutscene blocks inventory shortcuts and attacks"));for(auto& I:P.Inventory)S->Gear.Add(I.Id);CaptureV2(TEXT("Story31_00_Wake"));},[this](ALWCharacter& P){P.Story->FinishScene();Check(P.RPG.Story.Stage==1&&!P.bStoryLocked,TEXT("wake scene hands control back at radio objective"));});
 for(int Stage=1;Stage<=28;Stage++){
 Add(FString::Printf(TEXT("Chapter 1 checkpoint %d"),Stage),Stage==6?2:1.5,[this,S,Stage,Kill](ALWCharacter& P){auto* D=P.Story.Get();Check(D&&P.RPG.Story.Stage==Stage,*FString::Printf(TEXT("checkpoint %d reached through previous objective"),Stage));if(!D)return;if(P.RPG.Story.Stage!=Stage){P.RPG.Story.Stage=Stage;D->Applied=-1;D->ApplyStage();}P.Health=10000;
  if(Stage==20){S->Gear.Empty();for(const auto& Item:P.Inventory)S->Gear.Add(Item.Id);if(D->InScene)D->FinishScene();Check(D->Choosing&&P.bStoryLocked,TEXT("armored ultimatum owns player input"));D->Choose(0);Check(D->InScene,TEXT("surrender plays execution"));D->FinishScene();Check(D->Failed&&P.RPG.Story.Stage==20,TEXT("fatal ending retains ultimatum retry checkpoint"));D->Choose(0);D->Choose(1);if(D->InScene)D->FinishScene();Check(P.RPG.Story.GearHeld&&P.Inventory.IsEmpty()&&P.RPG.Story.Confiscated.Num()==S->Gear.Num(),TEXT("refusal confiscates exact gear once"));P.SaveProgress();P.LoadProgress();D=ALWStoryDirector::Ensure(&P);D->Start(false);Check(P.RPG.Story.Stage==21&&P.RPG.Story.GearHeld&&P.Inventory.IsEmpty(),TEXT("prison checkpoint reload preserves escrow and empty inventory"));CaptureV2(TEXT("Story31_21_Cell"));return;}
  if(Stage==26&&D->InScene)D->FinishScene();
  if(Stage==27){Check(D->InScene,TEXT("boss defeat starts surrender cutscene"));CaptureV2(TEXT("Story31_27_Surrender"));return;}
  if(Stage==2){LWV2Teleport(P,D->At(0,FVector(0,-2500,120)));return;}
  if(Stage==6){LWV2Teleport(P,D->Target());if(auto* N=D->People.FindRef(TEXT("story_mara")).Get())N->SetActorLocation(P.GetActorLocation()+FVector(350,0,0));return;}
  if(Stage==3||Stage==7||Stage==13||Stage==17){auto* N=D->People.FindRef(Stage==7?TEXT("story_jonah"):Stage==13?TEXT("story_inez"):TEXT("story_mara")).Get();Check(IsValid(N),TEXT("required named story character exists"));if(N){LWV2Teleport(P,N->GetActorLocation()+FVector(0,-180,0));P.Talk(N);Check(D->Choosing&&P.bStoryLocked,TEXT("story dialogue captures UI input"));D->Choose(1);}return;}
  if(Stage==26){auto* Boss=D->Enemies.FindByPredicate([](const auto& N){return N&&N->Boss==2;});if(Boss){float H=(*Boss)->Health;FDamageEvent E;(*Boss)->TakeDamage(500,E,P.Controller,&P);Check((*Boss)->Health==H,TEXT("Mercer armor requires relays"));}D->Activate(TEXT("shield_a"));D->Activate(TEXT("shield_b"));}
  if(Stage==10){Check(!D->Available(TEXT("trauma")),TEXT("medical supplies require triage and pharmacy access"));D->Activate(TEXT("triage"));D->Activate(TEXT("pharmacy"));}
  const auto& M=LWStory::Missions()[Stage];if(M.Enemies){Check(D->Remaining()>=M.Enemies,TEXT("authored encounter has required live enemies"));Kill(D,P);}
  if(Stage==12||Stage==18){if(Stage==12)D->Activate(TEXT("relay_a"));else for(auto& N:D->Nodes)if(N&&N->Action==TEXT("breach_a")){float Before=N->Durability52;N->Use(&P);Check(N->Durability52==Before,TEXT("defense feed must be destroyed, not activated"));FDamageEvent E;N->TakeDamage(150,E,P.Controller,&P);}Check(P.RPG.Story.Stage==Stage,TEXT("single relay cannot skip paired objective"));if(Stage==12)D->Activate(TEXT("relay_b"));else for(auto& N:D->Nodes)if(N&&N->Action==TEXT("breach_b")){FDamageEvent E;N->TakeDamage(150,E,P.Controller,&P);}}
  else if(FCString::Strlen(M.Action)){ALWStoryNode* Node=nullptr;for(auto& N:D->Nodes)if(N&&N->Action==M.Action){Node=N;break;}Check(Node!=nullptr,TEXT("objective has real world interaction"));if(Node){LWV2Teleport(P,Node->GetActorLocation()+FVector(0,-150,80));Node->Use(&P);}}
  if(Stage==23){Check(!P.RPG.Story.GearHeld,TEXT("equipment released from escrow"));for(FGuid Id:S->Gear)Check(P.Inventory.ContainsByPredicate([&](const auto& V){return V.Id==Id;}),TEXT("original item GUID restored"));int Count=P.Inventory.Num();D->RecoverGear();Check(P.Inventory.Num()==Count,TEXT("gear recovery cannot duplicate items"));}
  if(Stage==8){D->Tick(.3f);CaptureV2(TEXT("Story31_08_Abduction"));}if(Stage==16)CaptureV2(TEXT("Story31_16_Rescue"));if(Stage==26)CaptureV2(TEXT("Story31_26_CommandCourt"));
 },[this,Stage](ALWCharacter& P){auto* D=P.Story.Get();if(!D)return;if(D->InScene&&P.RPG.Story.Stage==Stage){D->FinishScene();}Check(P.RPG.Story.Stage==Stage+1,*FString::Printf(TEXT("checkpoint %d completes to %d"),Stage,Stage+1));});
 V2->Steps.Last().Ready=[Stage](ALWCharacter& P){
#if WITH_EDITOR
  if(GShaderCompilingManager&&GShaderCompilingManager->IsCompiling())return false;
#endif
  if(Stage==2||Stage==5||Stage==6||Stage==19||Stage==25||Stage==26)return P.RPG.Story.Stage>Stage;
  if(Stage==8)return P.Story&&P.Story->InScene;
  return true;
 };
 }
 Add(TEXT("fortress leadership and chapter persistence"),1,[this](ALWCharacter& P){auto* R=P.RPG.Settlements.Find(TEXT("fort_resolute"));Check(P.RPG.Story.Stage==29&&R&&R->Leader&&R->Member&&R->Reputation==100,TEXT("fortress awarded as governed settlement"));Check(P.RPG.Respawn.Enabled&&P.RPG.Respawn.Name==TEXT("Fort Resolute"),TEXT("fortress becomes respawn point"));Check(P.RPG.Story.Paid.Num()==29,TEXT("all objectives rewarded exactly once"));P.SaveProgress();CaptureV2(TEXT("Story31_29_Fortress"));UE_LOG(LogTemp,Display,TEXT("STORY31_DONE failures=%d"),TestFailures);});
 Add(TEXT("Settler rescue handover under normal combat health"),3,[this,Kill](ALWCharacter& P){auto* D=P.Story.Get();P.ClosePanels();P.bSafehouse=false;P.bGod47=false;P.Health=P.MaxHealth();P.RPG.Story.Enabled=true;P.RPG.Story.Stage=24;P.RPG.Story.SceneFinished=false;P.RPG.Story.Flags.Remove(TEXT("settler_cells_open52"));for(int S0=24;S0<=26;S0++)for(int K=0;K<64;K++)P.World->KilledZombies.Remove(LWStory::EnemyId(S0,K));LWV2Teleport(P,D->At(8,FVector(2600,-1850,150)));D->Applied=-1;D->ApplyStage();Kill(D,P);Check(D->Activate(TEXT("free")),TEXT("settler release works after detention guards defeated"));D->FinishScene();Check(P.RPG.Story.Stage==25&&!P.bStoryLocked,TEXT("rescue cutscene returns control at breakout"));Check(D->Remaining()==10,TEXT("breakout still has a full encounter"));for(auto& E:D->Enemies)if(E){Check(E->Stars==0,TEXT("ordinary troopers do not carry legendary damage multipliers"));Check(FVector::Dist2D(E->GetActorLocation(),P.GetActorLocation())>=850,TEXT("handover enemies do not spawn directly on the player"));}FDamageEvent Hit;const float H=P.Health;P.TakeDamage(10000,Hit,nullptr,D->Enemies[0]);Check(P.Health==H,TEXT("handover grace prevents lethal first-frame hit"));D->SafeRecovery52();P.CaptureMission37(TEXT("chapter1"),true);CaptureV2(TEXT("Story52_Detention"));},[this](ALWCharacter& P){Check(P.Health>0&&P.CanAct(),TEXT("rescued player remains alive and controllable through handover"));for(auto& Pair:P.Story->People)if(auto* N=Pair.Value.Get())Check(N->Gun&&N->Gun->IsVisible(),TEXT("released settlers are armed for breakout"));});
 Add(TEXT("Rescue death checkpoint recovers behind cover"),2,[this](ALWCharacter& P){P.FinishCheckpoints43(true);P.Health=0;P.HandleDeath();Check(P.RecoverMission37(0),TEXT("rescue checkpoint can be retried"));Check(P.RPG.Story.Stage==25&&P.Health>=P.MaxHealth()*.75f,TEXT("retry restores breakout stage and survivable health"));Check(FVector::Dist2D(P.GetActorLocation(),P.Story->At(8,FVector(3300,-2600,110)))<150,TEXT("retry relocates to detention recovery aisle"));Check(P.World->GetWorld()->GetTimeSeconds()<P.Story->CombatGrace52,TEXT("checkpoint retry grants fresh handover protection"));});
 for(int Site=0;Site<9;Site++)Add(*FString::Printf(TEXT("Inspect chapter site %d"),Site),2,[this,Site](ALWCharacter& P){auto* D=P.Story.Get();D->ClearActors(false);D->SetActorTickEnabled(false);P.bGod47=true;P.bSafehouse=false;D->BuildSite(Site);LWV2Teleport(P,D->At(Site,FVector(0,-5700,3200)));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);if(auto* PC=Cast<APlayerController>(P.Controller))PC->SetControlRotation(FRotator(-28,90,0));P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.World->Sky->SetActorLocation(P.GetActorLocation());P.World->TickWeather(.016f,&P);},[this,Site](ALWCharacter& P){CaptureV2(*FString::Printf(TEXT("Story52_Site%d"),Site));if(Site==8)UE_LOG(LogTemp,Display,TEXT("STORY52_DONE failures=%d"),TestFailures);});

}
