if(FParse::Param(FCommandLine::Get(),TEXT("LWSyracuse73Smoke"))){
 Add(TEXT("Syracuse73 setup"),1,[this](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.SetActorTickEnabled(false);P.ClosePanels();P.bMenu=false;P.bSafehouse=false;P.bGod47=true;UGameplayStatics::SetGamePaused(&P,false);P.SetMenuInput(false);P.GetCharacterMovement()->DisableMovement();P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.World->TickWeather(.1,&P);P.WeaponRoot->SetVisibility(false,true);P.Flashlight->SetVisibility(false);Cast<APlayerController>(P.Controller)->GetHUD()->bShowHUD=false;});
 for(int Type:{72,76,74,71,73,75,77,70}){
  Add(FString::Printf(TEXT("Syracuse73 construct %d"),Type),2,[this,Type](ALWCharacter& P){const auto* S=LWNY69::Sites().FindByPredicate([&](const auto& A){return A.Type==Type;});Check(S!=nullptr,TEXT("Syracuse landmark exists"));if(!S)return;P.SetActorLocation(FVector(S->Position,9000));P.World->Stream(P.GetActorLocation(),true);auto* C=P.World->Chunks.FindRef(LWGen::ChunkAt(S->Position)).Get();Check(C&&C->Ready68,TEXT("Syracuse construction complete"));
   if(Type==72||Type==74||Type==76){FCollisionQueryParams Q(NAME_None,false,&P);auto At=[&](FVector V){return FVector(S->Position,24)+FRotator(0,S->Yaw,0).RotateVector(V);};FHitResult H;const float Y=S->Size.Y*.5-(Type==72?0:60);Check(!GetWorld()->SweepSingleByChannel(H,At(FVector(0,-Y-120,100)),At(FVector(0,-Y+120,100)),FQuat::Identity,ECC_Pawn,FCollisionShape::MakeCapsule(28,80),Q),TEXT("Front entrance capsule clearance"));Check(GetWorld()->LineTraceSingleByChannel(H,At(FVector(0,0,200)),At(FVector(0,0,-30)),ECC_Visibility,Q),TEXT("Auditorium or arena floor collision"));int Blocked=0;const float X=S->Size.X*.5-(Type==72?0:60),Top=Type==74?1088:513;const int Steps=Type==72?22:FMath::RoundToInt(Top/16);for(int I=0;I<Steps;I++){FVector Foot(X-(Type==72?150:350),-Y+(Type==72?80:400)+(I+.5)*(Type==72?34:27),(I+1)*16+18);FHitResult Hit;if(GetWorld()->LineTraceSingleByChannel(Hit,At(Foot),At(Foot+FVector(0,0,180)),ECC_Visibility,Q)){Blocked++;UE_LOG(LogTemp,Warning,TEXT("SYR73 stair headroom type=%d step=%d component=%s"),Type,I,*GetNameSafe(Hit.GetComponent()));}}Check(Blocked==0,TEXT("Upper level stair headroom"));if(Type==76){int ClubBlocked=0;for(int I=0;I<28;I++){FVector Foot(X-650,-Y*.6+(I+.5)*28,Top+(I+1)*15+18);FHitResult Hit;if(GetWorld()->LineTraceSingleByChannel(Hit,At(Foot),At(Foot+FVector(0,0,180)),ECC_Visibility,Q))ClubBlocked++;}Check(ClubBlocked==0,TEXT("War Memorial club stair headroom"));}}
  });
  for(int View=0;View<2;View++)Add(FString::Printf(TEXT("Syracuse73 view %d/%d"),Type,View),2,[this,Type,View](ALWCharacter& P){const auto* S=LWNY69::Sites().FindByPredicate([&](const auto& A){return A.Type==Type;});if(!S)return;const float X=S->Size.X*.5,Y=S->Size.Y*.5;FVector At,Look;
   if(View==0){At=FVector(-X*.8,-Y-3500,Type==70?40000:1600);Look=FVector(0,0,Type==74?1600:650);}
   else if(Type==72){At=FVector(0,-Y+1850,300);Look=FVector(0,Y-1100,420);}
   else if(Type==74||Type==76){At=FVector(0,-Y+400,220);Look=FVector(0,0,450);}
   else{At=FVector(-X*.4,-Y*.4,Type==70?26000:Type==77?1800:3000);Look=FVector(0,0,400);}
   auto T=[&](FVector V){return FVector(S->Position,24)+FRotator(0,S->Yaw,0).RotateVector(V);};P.SetActorLocation(T(At));P.Controller->SetControlRotation((T(Look)-P.GetPawnViewLocation()).Rotation());P.World->Sky->SetActorLocation(P.GetActorLocation());P.World->TickWeather(.1,&P);
  },[this,Type,View](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Syracuse73_%d_%d"),Type,View));});
 }
 return;
}
