{0,TEXT("Ashline Medic"),TEXT("Last Responders"),0,TEXT("health"),1.000000f,TEXT("Ashline Medic: a legend preserved by the survivors of the American collapse.")},
{1,TEXT("Red Crossroads"),TEXT("Last Responders"),0,TEXT("health"),1.000000f,TEXT("Red Crossroads: a legend preserved by the survivors of the American collapse.")},
{2,TEXT("The Last Ambulance"),TEXT("Last Responders"),0,TEXT("health"),1.000000f,TEXT("The Last Ambulance: a legend preserved by the survivors of the American collapse.")},
{3,TEXT("Triage Angel"),TEXT("Last Responders"),0,TEXT("health"),1.000000f,TEXT("Triage Angel: a legend preserved by the survivors of the American collapse.")},
{4,TEXT("Blood Bank"),TEXT("Last Responders"),0,TEXT("health"),1.000000f,TEXT("Blood Bank: a legend preserved by the survivors of the American collapse.")},
{5,TEXT("Midnight Surgeon"),TEXT("Last Responders"),1,TEXT("health"),1.500000f,TEXT("Midnight Surgeon: a legend preserved by the survivors of the American collapse.")},
{6,TEXT("Mercy Under Fire"),TEXT("Last Responders"),1,TEXT("health"),1.500000f,TEXT("Mercy Under Fire: a legend preserved by the survivors of the American collapse.")},
{7,TEXT("Shelter Nurse"),TEXT("Last Responders"),2,TEXT("health"),2.000000f,TEXT("Shelter Nurse: a legend preserved by the survivors of the American collapse.")},
{8,TEXT("Heart of Steel"),TEXT("Last Responders"),3,TEXT("health"),2.500000f,TEXT("Heart of Steel: a legend preserved by the survivors of the American collapse.")},
{9,TEXT("The Immortal Responder"),TEXT("Last Responders"),4,TEXT("health"),3.000000f,TEXT("The Immortal Responder: a legend preserved by the survivors of the American collapse.")},
{10,TEXT("Highway Drifter"),TEXT("Roadside Legends"),0,TEXT("stamina"),1.000000f,TEXT("Highway Drifter: a legend preserved by the survivors of the American collapse.")},
{11,TEXT("Bootleg Courier"),TEXT("Roadside Legends"),0,TEXT("stamina"),1.000000f,TEXT("Bootleg Courier: a legend preserved by the survivors of the American collapse.")},
{12,TEXT("Rustbelt Runner"),TEXT("Roadside Legends"),0,TEXT("stamina"),1.000000f,TEXT("Rustbelt Runner: a legend preserved by the survivors of the American collapse.")},
{13,TEXT("Midnight Cyclist"),TEXT("Roadside Legends"),0,TEXT("stamina"),1.000000f,TEXT("Midnight Cyclist: a legend preserved by the survivors of the American collapse.")},
{14,TEXT("Bridge Jumper"),TEXT("Roadside Legends"),0,TEXT("stamina"),1.000000f,TEXT("Bridge Jumper: a legend preserved by the survivors of the American collapse.")},
{15,TEXT("Dust Trail Scout"),TEXT("Roadside Legends"),1,TEXT("stamina"),1.500000f,TEXT("Dust Trail Scout: a legend preserved by the survivors of the American collapse.")},
{16,TEXT("The Long Haul"),TEXT("Roadside Legends"),1,TEXT("stamina"),1.500000f,TEXT("The Long Haul: a legend preserved by the survivors of the American collapse.")},
{17,TEXT("Storm Chaser"),TEXT("Roadside Legends"),2,TEXT("stamina"),2.000000f,TEXT("Storm Chaser: a legend preserved by the survivors of the American collapse.")},
{18,TEXT("Marathon Ghost"),TEXT("Roadside Legends"),3,TEXT("stamina"),2.500000f,TEXT("Marathon Ghost: a legend preserved by the survivors of the American collapse.")},
{19,TEXT("The Endless Road"),TEXT("Roadside Legends"),4,TEXT("stamina"),3.000000f,TEXT("The Endless Road: a legend preserved by the survivors of the American collapse.")},
{20,TEXT("Tin Can Marksman"),TEXT("Wasteland Arsenal"),0,TEXT("gun"),0.005000f,TEXT("Tin Can Marksman: a legend preserved by the survivors of the American collapse.")},
{21,TEXT("Rooftop Sentinel"),TEXT("Wasteland Arsenal"),0,TEXT("gun"),0.005000f,TEXT("Rooftop Sentinel: a legend preserved by the survivors of the American collapse.")},
{22,TEXT("Brass Collector"),TEXT("Wasteland Arsenal"),0,TEXT("gun"),0.005000f,TEXT("Brass Collector: a legend preserved by the survivors of the American collapse.")},
{23,TEXT("Trench Defender"),TEXT("Wasteland Arsenal"),0,TEXT("gun"),0.005000f,TEXT("Trench Defender: a legend preserved by the survivors of the American collapse.")},
{24,TEXT("Railway Rifleman"),TEXT("Wasteland Arsenal"),0,TEXT("gun"),0.005000f,TEXT("Railway Rifleman: a legend preserved by the survivors of the American collapse.")},
{25,TEXT("The Gunsmith"),TEXT("Wasteland Arsenal"),1,TEXT("gun"),0.007500f,TEXT("The Gunsmith: a legend preserved by the survivors of the American collapse.")},
{26,TEXT("Smokehouse Duelist"),TEXT("Wasteland Arsenal"),1,TEXT("gun"),0.007500f,TEXT("Smokehouse Duelist: a legend preserved by the survivors of the American collapse.")},
{27,TEXT("Tower Sniper"),TEXT("Wasteland Arsenal"),2,TEXT("gun"),0.010000f,TEXT("Tower Sniper: a legend preserved by the survivors of the American collapse.")},
{28,TEXT("Last Stand Marshal"),TEXT("Wasteland Arsenal"),3,TEXT("gun"),0.012500f,TEXT("Last Stand Marshal: a legend preserved by the survivors of the American collapse.")},
{29,TEXT("The Peacebreaker"),TEXT("Wasteland Arsenal"),4,TEXT("gun"),0.015000f,TEXT("The Peacebreaker: a legend preserved by the survivors of the American collapse.")},
{30,TEXT("Crowbar King"),TEXT("Iron Fists"),0,TEXT("melee"),0.006000f,TEXT("Crowbar King: a legend preserved by the survivors of the American collapse.")},
{31,TEXT("Concrete Boxer"),TEXT("Iron Fists"),0,TEXT("melee"),0.006000f,TEXT("Concrete Boxer: a legend preserved by the survivors of the American collapse.")},
{32,TEXT("Scrapyard Bruiser"),TEXT("Iron Fists"),0,TEXT("melee"),0.006000f,TEXT("Scrapyard Bruiser: a legend preserved by the survivors of the American collapse.")},
{33,TEXT("Batting Champion"),TEXT("Iron Fists"),0,TEXT("melee"),0.006000f,TEXT("Batting Champion: a legend preserved by the survivors of the American collapse.")},
{34,TEXT("The Door Breaker"),TEXT("Iron Fists"),0,TEXT("melee"),0.006000f,TEXT("The Door Breaker: a legend preserved by the survivors of the American collapse.")},
{35,TEXT("Foundry Brawler"),TEXT("Iron Fists"),1,TEXT("melee"),0.009000f,TEXT("Foundry Brawler: a legend preserved by the survivors of the American collapse.")},
{36,TEXT("Sledgehammer Saint"),TEXT("Iron Fists"),1,TEXT("melee"),0.009000f,TEXT("Sledgehammer Saint: a legend preserved by the survivors of the American collapse.")},
{37,TEXT("Chain Gang Rebel"),TEXT("Iron Fists"),2,TEXT("melee"),0.012000f,TEXT("Chain Gang Rebel: a legend preserved by the survivors of the American collapse.")},
{38,TEXT("The Iron Wrestler"),TEXT("Iron Fists"),3,TEXT("melee"),0.015000f,TEXT("The Iron Wrestler: a legend preserved by the survivors of the American collapse.")},
{39,TEXT("Knuckles of Liberty"),TEXT("Iron Fists"),4,TEXT("melee"),0.018000f,TEXT("Knuckles of Liberty: a legend preserved by the survivors of the American collapse.")},
{40,TEXT("Barricade Guard"),TEXT("Night Watch"),0,TEXT("armor"),0.003000f,TEXT("Barricade Guard: a legend preserved by the survivors of the American collapse.")},
{41,TEXT("Steel Umbrella"),TEXT("Night Watch"),0,TEXT("armor"),0.003000f,TEXT("Steel Umbrella: a legend preserved by the survivors of the American collapse.")},
{42,TEXT("The Riot Shield"),TEXT("Night Watch"),0,TEXT("armor"),0.003000f,TEXT("The Riot Shield: a legend preserved by the survivors of the American collapse.")},
{43,TEXT("Welded Survivor"),TEXT("Night Watch"),0,TEXT("armor"),0.003000f,TEXT("Welded Survivor: a legend preserved by the survivors of the American collapse.")},
{44,TEXT("The Watchtower"),TEXT("Night Watch"),0,TEXT("armor"),0.003000f,TEXT("The Watchtower: a legend preserved by the survivors of the American collapse.")},
{45,TEXT("Armored Pilgrim"),TEXT("Night Watch"),1,TEXT("armor"),0.004500f,TEXT("Armored Pilgrim: a legend preserved by the survivors of the American collapse.")},
{46,TEXT("Blast Door Warden"),TEXT("Night Watch"),1,TEXT("armor"),0.004500f,TEXT("Blast Door Warden: a legend preserved by the survivors of the American collapse.")},
{47,TEXT("Broken Tanker"),TEXT("Night Watch"),2,TEXT("armor"),0.006000f,TEXT("Broken Tanker: a legend preserved by the survivors of the American collapse.")},
{48,TEXT("Citadel Defender"),TEXT("Night Watch"),3,TEXT("armor"),0.007500f,TEXT("Citadel Defender: a legend preserved by the survivors of the American collapse.")},
{49,TEXT("The Unbroken Wall"),TEXT("Night Watch"),4,TEXT("armor"),0.009000f,TEXT("The Unbroken Wall: a legend preserved by the survivors of the American collapse.")},
{50,TEXT("Library Lantern"),TEXT("Forbidden Knowledge"),0,TEXT("xp"),0.005000f,TEXT("Library Lantern: a legend preserved by the survivors of the American collapse.")},
{51,TEXT("The Mapmaker"),TEXT("Forbidden Knowledge"),0,TEXT("xp"),0.005000f,TEXT("The Mapmaker: a legend preserved by the survivors of the American collapse.")},
{52,TEXT("Radio Scholar"),TEXT("Forbidden Knowledge"),0,TEXT("xp"),0.005000f,TEXT("Radio Scholar: a legend preserved by the survivors of the American collapse.")},
{53,TEXT("Basement Archivist"),TEXT("Forbidden Knowledge"),0,TEXT("xp"),0.005000f,TEXT("Basement Archivist: a legend preserved by the survivors of the American collapse.")},
{54,TEXT("Forgotten Classroom"),TEXT("Forbidden Knowledge"),0,TEXT("xp"),0.005000f,TEXT("Forgotten Classroom: a legend preserved by the survivors of the American collapse.")},
{55,TEXT("The Vault Historian"),TEXT("Forbidden Knowledge"),1,TEXT("xp"),0.007500f,TEXT("The Vault Historian: a legend preserved by the survivors of the American collapse.")},
{56,TEXT("Signal Decoder"),TEXT("Forbidden Knowledge"),1,TEXT("xp"),0.007500f,TEXT("Signal Decoder: a legend preserved by the survivors of the American collapse.")},
{57,TEXT("The Wandering Professor"),TEXT("Forbidden Knowledge"),2,TEXT("xp"),0.010000f,TEXT("The Wandering Professor: a legend preserved by the survivors of the American collapse.")},
{58,TEXT("Book of Ashes"),TEXT("Forbidden Knowledge"),3,TEXT("xp"),0.012500f,TEXT("Book of Ashes: a legend preserved by the survivors of the American collapse.")},
{59,TEXT("The Last Enlightenment"),TEXT("Forbidden Knowledge"),4,TEXT("xp"),0.015000f,TEXT("The Last Enlightenment: a legend preserved by the survivors of the American collapse.")},
{60,TEXT("Bottlecap Broker"),TEXT("Dust Market"),0,TEXT("barter"),0.003000f,TEXT("Bottlecap Broker: a legend preserved by the survivors of the American collapse.")},
{61,TEXT("Neon Pawnbroker"),TEXT("Dust Market"),0,TEXT("barter"),0.003000f,TEXT("Neon Pawnbroker: a legend preserved by the survivors of the American collapse.")},
{62,TEXT("The Robot Trader"),TEXT("Dust Market"),0,TEXT("barter"),0.003000f,TEXT("The Robot Trader: a legend preserved by the survivors of the American collapse.")},
{63,TEXT("Caravan Accountant"),TEXT("Dust Market"),0,TEXT("barter"),0.003000f,TEXT("Caravan Accountant: a legend preserved by the survivors of the American collapse.")},
{64,TEXT("Junkyard Jeweler"),TEXT("Dust Market"),0,TEXT("barter"),0.003000f,TEXT("Junkyard Jeweler: a legend preserved by the survivors of the American collapse.")},
{65,TEXT("The Night Auction"),TEXT("Dust Market"),1,TEXT("barter"),0.004500f,TEXT("The Night Auction: a legend preserved by the survivors of the American collapse.")},
{66,TEXT("Golden Glovebox"),TEXT("Dust Market"),1,TEXT("barter"),0.004500f,TEXT("Golden Glovebox: a legend preserved by the survivors of the American collapse.")},
{67,TEXT("Merchant of Echoes"),TEXT("Dust Market"),2,TEXT("barter"),0.006000f,TEXT("Merchant of Echoes: a legend preserved by the survivors of the American collapse.")},
{68,TEXT("The Credit Baron"),TEXT("Dust Market"),3,TEXT("barter"),0.007500f,TEXT("The Credit Baron: a legend preserved by the survivors of the American collapse.")},
{69,TEXT("Fortune of the Wastes"),TEXT("Dust Market"),4,TEXT("barter"),0.009000f,TEXT("Fortune of the Wastes: a legend preserved by the survivors of the American collapse.")},
{70,TEXT("Bandage Botanist"),TEXT("Fieldcraft"),0,TEXT("healing"),0.008000f,TEXT("Bandage Botanist: a legend preserved by the survivors of the American collapse.")},
{71,TEXT("Rainwater Remedy"),TEXT("Fieldcraft"),0,TEXT("healing"),0.008000f,TEXT("Rainwater Remedy: a legend preserved by the survivors of the American collapse.")},
{72,TEXT("The Stitch Kit"),TEXT("Fieldcraft"),0,TEXT("healing"),0.008000f,TEXT("The Stitch Kit: a legend preserved by the survivors of the American collapse.")},
{73,TEXT("Wildflower Tonic"),TEXT("Fieldcraft"),0,TEXT("healing"),0.008000f,TEXT("Wildflower Tonic: a legend preserved by the survivors of the American collapse.")},
{74,TEXT("The Field Hospital"),TEXT("Fieldcraft"),0,TEXT("healing"),0.008000f,TEXT("The Field Hospital: a legend preserved by the survivors of the American collapse.")},
{75,TEXT("Mushroom Apothecary"),TEXT("Fieldcraft"),1,TEXT("healing"),0.012000f,TEXT("Mushroom Apothecary: a legend preserved by the survivors of the American collapse.")},
{76,TEXT("Suture Master"),TEXT("Fieldcraft"),1,TEXT("healing"),0.012000f,TEXT("Suture Master: a legend preserved by the survivors of the American collapse.")},
{77,TEXT("The Greenhouse Doctor"),TEXT("Fieldcraft"),2,TEXT("healing"),0.016000f,TEXT("The Greenhouse Doctor: a legend preserved by the survivors of the American collapse.")},
{78,TEXT("Phoenix Medicine"),TEXT("Fieldcraft"),3,TEXT("healing"),0.020000f,TEXT("Phoenix Medicine: a legend preserved by the survivors of the American collapse.")},
{79,TEXT("The Second Sunrise"),TEXT("Fieldcraft"),4,TEXT("healing"),0.024000f,TEXT("The Second Sunrise: a legend preserved by the survivors of the American collapse.")},
{80,TEXT("Pocket Mechanic"),TEXT("Quick Hands"),0,TEXT("reload"),0.004000f,TEXT("Pocket Mechanic: a legend preserved by the survivors of the American collapse.")},
{81,TEXT("Magazine Juggler"),TEXT("Quick Hands"),0,TEXT("reload"),0.004000f,TEXT("Magazine Juggler: a legend preserved by the survivors of the American collapse.")},
{82,TEXT("The Brass Dancer"),TEXT("Quick Hands"),0,TEXT("reload"),0.004000f,TEXT("The Brass Dancer: a legend preserved by the survivors of the American collapse.")},
{83,TEXT("Workbench Wizard"),TEXT("Quick Hands"),0,TEXT("reload"),0.004000f,TEXT("Workbench Wizard: a legend preserved by the survivors of the American collapse.")},
{84,TEXT("Speedloader Sally"),TEXT("Quick Hands"),0,TEXT("reload"),0.004000f,TEXT("Speedloader Sally: a legend preserved by the survivors of the American collapse.")},
{85,TEXT("The Clockwork Soldier"),TEXT("Quick Hands"),1,TEXT("reload"),0.006000f,TEXT("The Clockwork Soldier: a legend preserved by the survivors of the American collapse.")},
{86,TEXT("Belt Feed Bandit"),TEXT("Quick Hands"),1,TEXT("reload"),0.006000f,TEXT("Belt Feed Bandit: a legend preserved by the survivors of the American collapse.")},
{87,TEXT("The Lightning Loader"),TEXT("Quick Hands"),2,TEXT("reload"),0.008000f,TEXT("The Lightning Loader: a legend preserved by the survivors of the American collapse.")},
{88,TEXT("Hands of Mercury"),TEXT("Quick Hands"),3,TEXT("reload"),0.010000f,TEXT("Hands of Mercury: a legend preserved by the survivors of the American collapse.")},
{89,TEXT("The Final Chamber"),TEXT("Quick Hands"),4,TEXT("reload"),0.012000f,TEXT("The Final Chamber: a legend preserved by the survivors of the American collapse.")},
{90,TEXT("Campfire Keeper"),TEXT("Trailblazers"),0,TEXT("recovery"),0.008000f,TEXT("Campfire Keeper: a legend preserved by the survivors of the American collapse.")},
{91,TEXT("Quiet River"),TEXT("Trailblazers"),0,TEXT("recovery"),0.008000f,TEXT("Quiet River: a legend preserved by the survivors of the American collapse.")},
{92,TEXT("The Sleeping Giant"),TEXT("Trailblazers"),0,TEXT("recovery"),0.008000f,TEXT("The Sleeping Giant: a legend preserved by the survivors of the American collapse.")},
{93,TEXT("Coffee at Dawn"),TEXT("Trailblazers"),0,TEXT("recovery"),0.008000f,TEXT("Coffee at Dawn: a legend preserved by the survivors of the American collapse.")},
{94,TEXT("The Rest Stop"),TEXT("Trailblazers"),0,TEXT("recovery"),0.008000f,TEXT("The Rest Stop: a legend preserved by the survivors of the American collapse.")},
{95,TEXT("Mountain Refuge"),TEXT("Trailblazers"),1,TEXT("recovery"),0.012000f,TEXT("Mountain Refuge: a legend preserved by the survivors of the American collapse.")},
{96,TEXT("Warm Hearth"),TEXT("Trailblazers"),1,TEXT("recovery"),0.012000f,TEXT("Warm Hearth: a legend preserved by the survivors of the American collapse.")},
{97,TEXT("The Oasis Keeper"),TEXT("Trailblazers"),2,TEXT("recovery"),0.016000f,TEXT("The Oasis Keeper: a legend preserved by the survivors of the American collapse.")},
{98,TEXT("Spirit of the Trail"),TEXT("Trailblazers"),3,TEXT("recovery"),0.020000f,TEXT("Spirit of the Trail: a legend preserved by the survivors of the American collapse.")},
{99,TEXT("The Eternal Campfire"),TEXT("Trailblazers"),4,TEXT("recovery"),0.024000f,TEXT("The Eternal Campfire: a legend preserved by the survivors of the American collapse.")},
