void ALWGameMode::BuildUIClickSmoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWResident> NPC;FGuid Gun;float HP=0;};auto S=MakeShared<FState>();
 Add(TEXT("UI attack setup"),.5,[this,S](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;P.Health=10000;P.Inventory.Empty();auto G=LWItems::Make(TEXT("rifle"));G.Slot=TEXT("Primary");G.Chamber=1;P.Inventory.Add(G);S->Gun=G.Id;P.ActiveWeaponId=G.Id;P.Equip(6);P.AttackTimer=0;P.ReleaseAttackInput();auto* N=GetWorld()->SpawnActor<ALWResident>(P.GetActorLocation()+FVector(200,0,0),FRotator::ZeroRotator);N->ConfigureResident(TEXT("ui_click_npc"),TEXT("warden"),TEXT("TEST WARDEN"),0);N->SettlementId=TEXT("ui_click_town");N->SetActorTickEnabled(false);N->GetCharacterMovement()->DisableMovement();S->NPC=N;S->HP=N->Health;P.Controller->SetControlRotation((N->GetActorLocation()-P.GetActorLocation()).Rotation());});
 Add(TEXT("UI first then attack binding"),.1,[this,S](ALWCharacter& P){P.Talk(S->NPC.Get());Check(P.RPGPanel==4&&P.Speaker==S->NPC.Get(),TEXT("dialogue opens"));P.bTrigger=true;P.SetMenuInput(true);Check(!P.bTrigger,TEXT("opening UI cancels automatic fire"));auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());if(!RequireV2(H!=nullptr,TEXT("HUD available")))return;H->NotifyHitBoxClick(TEXT("rpg_close"));Check(!P.IsUIOpen(),TEXT("dialogue close button returns to gameplay"));P.Attack();Check(P.FindItem(S->Gun)->Chamber==1&&!P.bTrigger,TEXT("closing dialogue click cannot fire"));Check(S->NPC->Health==S->HP&&!S->NPC->IsTownHostile(),TEXT("dialogue partner remains unharmed and friendly"));P.ReleaseAttackInput();P.Attack();Check(P.FindItem(S->Gun)->Chamber==1,TEXT("same-frame release cannot leak the UI press"));});
 Add(TEXT("attack binding before UI callback"),.1,[this,S](ALWCharacter& P){P.Talk(S->NPC.Get());P.Attack();Check(P.FindItem(S->Gun)->Chamber==1,TEXT("attack blocked while dialogue is open"));P.ClosePanels();P.Attack();Check(P.FindItem(S->Gun)->Chamber==1,TEXT("blocked press stays blocked after dialogue closes"));P.ReleaseAttackInput();});
 Add(TEXT("all modal panels"),.1,[this,S](ALWCharacter& P){for(int Mode=0;Mode<8;Mode++){P.ClosePanels();P.bMenu=Mode==0;P.bSettings=Mode==1;P.bInventory=Mode==2;P.bMap=Mode==3;P.RPGPanel=Mode==4?5:0;P.bWorldSetup=Mode==5;P.OpeningMode=Mode==6?2:0;if(Mode==7)P.Speaker=S->NPC.Get();P.Attack();Check(P.FindItem(S->Gun)->Chamber==1&&!P.bTrigger,TEXT("modal panel blocks firing"));P.bMenu=P.bSettings=P.bWorldSetup=false;P.OpeningMode=0;P.ClosePanels();P.ReleaseAttackInput();}P.SetMenuInput(true);P.Attack();P.SetMenuInput(false);P.Attack();Check(P.FindItem(S->Gun)->Chamber==1,TEXT("input-mode transition retains press ownership"));P.ReleaseAttackInput();});
 Add(TEXT("held UI click cannot resume fire"),.15,[this,S](ALWCharacter& P){P.ConsumeUIAttack();P.ClosePanels();},[this,S](ALWCharacter& P){P.Attack();Check(P.FindItem(S->Gun)->Chamber==1,TEXT("holding a UI click into later frames cannot shoot"));P.ReleaseAttackInput();});
 Add(TEXT("fresh gameplay click fires"),.2,[](ALWCharacter& P){},[this,S](ALWCharacter& P){P.Controller->SetControlRotation(FRotator(70,180,0));P.Camera->SetWorldRotation(FRotator(70,180,0));P.Attack();Check(P.FindItem(S->Gun)->Chamber!=1,TEXT("fresh press after release fires normally"));P.ReleaseAttackInput();if(S->NPC.IsValid())S->NPC->Destroy();});
}
