#include "LWBunker45.h"
void ALWGameMode::BuildUI46Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Delay,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({N,Delay,180,MoveTemp(Begin),MoveTemp(End),[](ALWCharacter&){return true;}});};
 #include "LWUpdate56Smoke.inl"
 if(FParse::Param(FCommandLine::Get(),TEXT("LWUI55Smoke"))){
  auto HUD=[](ALWCharacter& P){return Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());};
  Add(TEXT("UI55 title"),1,[this,HUD](ALWCharacter& P){auto* H=HUD(P);Check(H&&H->UIFont55&&H->Backdrop55&&H->Surface55,TEXT("UI assets and readable font loaded"));},[this,HUD](ALWCharacter& P){auto* H=HUD(P);auto* Box=H->GetHitBoxAtCoordinates(FVector2D(180,437)*H->Scale+H->Origin55,true);Check(Box&&Box->GetName()==TEXT("Start"),TEXT("scaled and centered button hit test matches rendered position"));CaptureV2(TEXT("UI55_Title"));});
  Add(TEXT("UI55 focus navigation"),.4,[this,HUD](ALWCharacter& P){auto* H=HUD(P);H->Focus55=TEXT("Start");Check(H->UIKey55(EKeys::Down)&&H->Focus55==TEXT("New"),TEXT("directional focus chooses neighboring button"));H->Focus55=TEXT("Settings");Check(H->UIKey55(EKeys::Enter),TEXT("keyboard confirm consumed"));},[this](ALWCharacter& P){Check(P.bSettings&&!P.bTrigger,TEXT("settings opens without firing"));CaptureV2(TEXT("UI55_Settings"));});
  Add(TEXT("UI55 accessibility"),.4,[this,HUD](ALWCharacter& P){auto* H=HUD(P);H->ReducedMotion55=true;H->HighContrast55=true;},[this,HUD](ALWCharacter& P){auto* H=HUD(P);Check(H->Animate55(TEXT("test55"),1)==1,TEXT("reduced motion snaps to target"));CaptureV2(TEXT("UI55_Contrast"));H->ReducedMotion55=H->HighContrast55=false;});
  Add(TEXT("UI55 gameplay setup"),1,[](ALWCharacter& P){P.bSettings=false;P.NewGame();P.World->EnableEncounters=false;P.Health=10000;P.EnterSafehouse();P.ClosePanels();},[this](ALWCharacter&){CaptureV2(TEXT("UI55_HUD"));});
  Add(TEXT("UI55 inventory"),.7,[](ALWCharacter& P){P.SwitchTab(0);},[this,HUD](ALWCharacter& P){Check(P.bInventory&&!P.bTrigger,TEXT("inventory owns input"));CaptureV2(TEXT("UI55_Inventory"));});
  Add(TEXT("UI55 map"),.7,[](ALWCharacter& P){P.SwitchTab(1);},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Map"));});
  Add(TEXT("UI55 skills"),.7,[](ALWCharacter& P){P.SwitchTab(2);},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Skills"));});
  Add(TEXT("UI55 contracts"),.7,[](ALWCharacter& P){P.SwitchTab(3);},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Contracts"));});
  Add(TEXT("UI55 crew pagination"),.7,[](ALWCharacter& P){P.SwitchTab(4);P.RPG.Crew.Empty();for(int I=0;I<24;++I){FLWCrewRecord R;R.Id=FName(*FString::Printf(TEXT("ui55_%d"),I));R.Name=FString::Printf(TEXT("Survivor %02d"),I+1);P.RPG.Crew.Add(R);}},[this,HUD](ALWCharacter& P){auto* H=HUD(P);int Rows=0;for(auto& C:H->Controls55)if(C.Id.ToString().StartsWith(TEXT("crew_")))Rows++;Check(Rows==9,TEXT("large crews are paginated rather than overflowing"));H->NotifyHitBoxClick(TEXT("crewpage55_next"));Check(H->CrewPage55==1,TEXT("crew next page"));CaptureV2(TEXT("UI55_Crew"));});
  Add(TEXT("UI55 collection"),.7,[](ALWCharacter& P){P.SwitchTab(5);},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Collection"));});
  Add(TEXT("UI55 cards"),.7,[](ALWCharacter& P){P.ClosePanels();P.RPGPanel=5;P.Cards.Start(0,20,55);P.SetMenuInput(true);},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Cards"));});
  Add(TEXT("UI55 terminal"),.7,[](ALWCharacter& P){P.ClosePanels();P.BunkerManager45->Open(0);},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Terminal"));});
  Add(TEXT("UI55 terminal input"),.3,[this](ALWCharacter& P){auto* B=P.BunkerManager45.Get();B->Focus46=TEXT("base_tab_0");B->Navigate46(FVector2D(1,0));Check(B->Focus46==TEXT("base_tab_1"),TEXT("terminal retains directional navigation"));B->Close();});
  Add(TEXT("UI55 dialogue"),.7,[](ALWCharacter& P){FActorSpawnParameters Spawn;Spawn.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* N=P.GetWorld()->SpawnActor<ALWResident>(P.GetActorLocation()+FVector(250,0,0),FRotator::ZeroRotator,Spawn);N->ConfigureResident(TEXT("ui55_npc"),TEXT("warden"),TEXT("MARA VALE"),0);N->SetActorTickEnabled(false);P.Talk(N);P.DialogueText=TEXT("The roads are getting dangerous. We could use someone who knows how to survive out there.");P.DialogueChoices={TEXT("Tell me about this settlement."),TEXT("Do you have any work?"),TEXT("I should get going.")};},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Dialogue"));});
  Add(TEXT("UI55 security"),.7,[this](ALWCharacter& P){P.ClosePanels();P.GiveItem(TEXT("lockpick"),2);FActorSpawnParameters Spawn;Spawn.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* O=P.GetWorld()->SpawnActor<ALWWorldObject>(P.GetActorLocation()+FVector(150,0,0),FRotator::ZeroRotator,Spawn);O->Kind=ELWObjectKind::Container;O->RecordId=TEXT("ui55_lock");auto& R=P.World->Containers.FindOrAdd(O->RecordId);R.LockTier=2;R.Unlocked=false;Check(P.StartLockpick(O),TEXT("lockpick screen opens on a real locked container"));},[this](ALWCharacter& P){Check(P.SecurityMode==1,TEXT("lockpick screen remains active for rendering"));CaptureV2(TEXT("UI55_Lock"));});

  Add(TEXT("UI55 workbench"),.8,[](ALWCharacter& P){P.SecurityMode=0;P.ClosePanels();FActorSpawnParameters Spawn;Spawn.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* S=P.GetWorld()->SpawnActor<ALWWorldObject>(P.GetActorLocation()+FVector(250,0,0),FRotator::ZeroRotator,Spawn);P.OpenWorkbench39(S);if(P.Workbench39)for(const auto& I:P.Inventory)if(I.Definition==TEXT("revolver")){P.Workbench39->Load(I.Id);break;}},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Workbench"));});
  Add(TEXT("UI55 creator"),1,[](ALWCharacter& P){P.CloseWorkbench39();P.BeginOpening();P.OpeningClick(TEXT("intro_skip"));},[this](ALWCharacter&){CaptureV2(TEXT("UI55_Creator"));});
  Add(TEXT("UI55 finish"),.2,[](ALWCharacter& P){P.EndOpening(false);});
  return;
 }
 Add(TEXT("title does not generate world"),2,[this](ALWCharacter& P){Check(!P.bStarted&&P.World->Chunks.IsEmpty()&&P.World->BunkerParts.IsEmpty(),TEXT("title has no generated world or bunker"));},[this](ALWCharacter& P){CaptureV2(TEXT("UI46_Title_A"));});
 Add(TEXT("animated title"),2,[](ALWCharacter&){},[this](ALWCharacter& P){Check(P.World->Chunks.IsEmpty(),TEXT("idle title does not stream chunks"));CaptureV2(TEXT("UI46_Title_B"));});
 BuildBunker45Smoke(Initial);
 Add(TEXT("terminal housing and loadout"),2,[this](ALWCharacter& P){P.EnterSafehouse();P.ClosePanels();P.Inventory.Empty();for(FName D:{FName(TEXT("shotgun")),FName(TEXT("sniper")),FName(TEXT("revolver")),FName(TEXT("crowbar")),FName(TEXT("rig")),FName(TEXT("m4"))}){auto I=LWItems::Make(D);P.Inventory.Add(I);}const FName Slots[]={TEXT("Primary"),TEXT("Secondary"),TEXT("Sidearm"),TEXT("Melee"),TEXT("Rig"),TEXT("RigPrimary")};for(int I=0;I<6;++I)P.Inventory[I].Slot=Slots[I];P.GiveItem(TEXT("medkit"),3);P.EquipShotgun();P.Sensitivity=.3f;P.SetActorLocation(ALWBunker45::Center()+FVector(-1550,340,115));P.Controller->SetControlRotation(FRotator(0,180,0));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);ALWWorldObject* Term=nullptr;for(AActor* A:P.BunkerManager45->Built)if(auto* O=Cast<ALWWorldObject>(A))if(O->RecordId==TEXT("bunker_terminal45"))Term=O;if(RequireV2(Term!=nullptr,TEXT("wall terminal exists"))){Check(Term->Body->Bounds.BoxExtent.Y<40&&Term->Body->Bounds.BoxExtent.Z<45,TEXT("terminal housing is compact"));Check(FMath::Abs(Term->GetActorLocation().X-(ALWBunker45::Center().X-1885))<1,TEXT("terminal back is flush with wall"));}Check(P.CountSupply(TEXT("medkit"))==3,TEXT("medkit HUD count uses usable inventory kits"));},[this](ALWCharacter& P){CaptureV2(TEXT("UI46_TerminalAndSlots"));});
 Add(TEXT("open terminal"),.5,[](ALWCharacter& P){P.BunkerManager45->Open(0);});
 Add(TEXT("terminal arrow navigation"),.5,[this](ALWCharacter& P){auto* B=P.BunkerManager45.Get();B->Focus46=TEXT("base_tab_0");Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::Right,IE_Pressed,1.));},[this](ALWCharacter& P){auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(EKeys::Right,IE_Released,0.));Check(P.BunkerManager45->Focus46==TEXT("base_tab_1"),TEXT("right arrow selects next terminal category"));PC->InputKey(FInputKeyParams(EKeys::Enter,IE_Pressed,1.));});
 Add(TEXT("terminal confirm"),.5,[](ALWCharacter&){},[this](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::Enter,IE_Released,0.));Check(P.BaseUI45&&P.BunkerManager45->Tab==1,TEXT("enter activates terminal selection without closing or attacking"));Check(!P.bTrigger,TEXT("terminal navigation does not fire weapon"));CaptureV2(TEXT("UI46_TerminalMenu"));});
 Add(TEXT("build mouse look"),.5,[this](ALWCharacter& P){auto* B=P.BunkerManager45.Get();B->BeginEdit();B->BuildCamera->SetWorldRotation(FRotator::ZeroRotator);auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(EKeys::MouseX,10.,.016f,1));PC->InputKey(FInputKeyParams(EKeys::MouseY,10.,.016f,1));},[this](ALWCharacter& P){auto R=P.BunkerManager45->BuildCamera->GetComponentRotation();UE_LOG(LogTemp,Display,TEXT("UI46 look yaw=%.3f pitch=%.3f"),R.Yaw,R.Pitch);Check(R.Yaw>0&&R.Pitch>0,TEXT("positive mouse motion looks right and up"));Check(R.Yaw>.1f,TEXT("build look uses responsive sensitivity"));P.BunkerManager45->Close();});
}

