if(FParse::Param(FCommandLine::Get(),TEXT("LWController58Smoke"))){
 auto Pad=[](ALWCharacter& P,FKey Key,EInputEvent Event,float Value=1.f){auto* K=ULWPlayerInput51::Get51(&P);FInputKeyEventArgs E;E.Key=Key;E.Event=Event;E.AmountDepressed=Value;K->InputKey(E);};
 auto HUD=[](ALWCharacter& P){return Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());};
 Add(TEXT("controller title navigation"),.5,[this,Pad,HUD](ALWCharacter& P){auto* H=HUD(P);H->Focus55=TEXT("Start");Pad(P,EKeys::Gamepad_DPad_Down,IE_Pressed);Check(H->Focus55!=TEXT("Start"),TEXT("D-pad moves menu focus"));H->Focus55=TEXT("Settings");H->Keyboard55=true;Pad(P,EKeys::Gamepad_FaceButton_Bottom,IE_Pressed);Pad(P,EKeys::Gamepad_FaceButton_Bottom,IE_Released);Check(P.bSettings&&!P.bTrigger,TEXT("controller opens settings without attacking"));},[this](ALWCharacter&){CaptureV2(TEXT("Controller58_Settings"));});
 Add(TEXT("minimum graphics preset"),.5,[this,HUD](ALWCharacter& P){HUD(P)->GraphicsPage=3;LWGraphics33::Preset58(0);Check(LWGraphics33::Radius58()==1,TEXT("minimum reduces streamed world radius"));Check(IConsoleManager::Get().FindConsoleVariable(TEXT("r.ShadowQuality"))->GetInt()==0,TEXT("minimum disables dynamic shadows"));Check(IConsoleManager::Get().FindConsoleVariable(TEXT("r.VolumetricFog"))->GetInt()==0,TEXT("minimum disables volumetric fog"));Check(IConsoleManager::Get().FindConsoleVariable(TEXT("r.ScreenPercentage"))->GetFloat()<=50,TEXT("minimum lowers render resolution"));},[this](ALWCharacter&){CaptureV2(TEXT("Controller58_Graphics"));});
 Add(TEXT("balanced and NVIDIA capability"),.5,[this,HUD](ALWCharacter& P){LWGraphics33::Preset58(2);LWGraphics33::Change(23);LWGraphics33::Change(24);Check(!LWGraphics33::Label(23).IsEmpty()&&!LWGraphics33::Label(24).IsEmpty(),TEXT("upscaler and frame generation report state"));UE_LOG(LogTemp,Display,TEXT("LW58_GPU %s | %s | %s"),*LWGraphics33::Label(23),*LWGraphics33::Label(24),*LWGraphics33::Status58());if(UDLSSLibrary::IsDLSSSupported())Check(UDLSSLibrary::IsDLSSEnabled(),TEXT("DLSS is actually enabled in the renderer"));if(UStreamlineLibraryDLSSG::IsDLSSGSupported())Check(UStreamlineLibraryDLSSG::GetDLSSGMode()!=EStreamlineDLSSGMode::Off,TEXT("frame generation mode is actually enabled"));HUD(P)->GraphicsPage=4;},[this](ALWCharacter&){CaptureV2(TEXT("Controller58_Options"));});
 Add(TEXT("controller world setup"),.5,[](ALWCharacter& P){LWGraphics33::Preset58(2);P.bSettings=false;P.NewGame();P.World->EnableEncounters=false;P.Health=10000;P.EnterSafehouse();P.ClosePanels();});
 Add(TEXT("analog locomotion"),.35,[Pad](ALWCharacter& P){Pad(P,EKeys::Gamepad_LeftY,IE_Axis,.8f);Pad(P,EKeys::Gamepad_RightX,IE_Axis,.5f);},[this,Pad](ALWCharacter& P){Check(P.InputForward54>.5f,TEXT("left stick produces analog movement"));Pad(P,EKeys::Gamepad_LeftY,IE_Axis,0);Pad(P,EKeys::Gamepad_RightX,IE_Axis,0);});
 Add(TEXT("stick dead zone"),.15,[Pad](ALWCharacter& P){Pad(P,EKeys::Gamepad_LeftY,IE_Axis,.03f);},[this,Pad](ALWCharacter& P){Check(FMath::Abs(P.InputForward54)<.01f,TEXT("dead zone prevents movement drift"));Pad(P,EKeys::Gamepad_LeftY,IE_Axis,0);});
 Add(TEXT("controller crouch"),.2,[Pad](ALWCharacter& P){Pad(P,EKeys::Gamepad_FaceButton_Right,IE_Pressed);},[this,Pad](ALWCharacter& P){Check(P.bIsCrouched,TEXT("B crouches"));Pad(P,EKeys::Gamepad_FaceButton_Right,IE_Released);});
 Add(TEXT("inventory controller cursor"),.3,[Pad](ALWCharacter& P){Pad(P,EKeys::Gamepad_Special_Left,IE_Pressed);Pad(P,EKeys::Gamepad_LeftX,IE_Axis,.6f);},[this,Pad](ALWCharacter& P){Check(P.bInventory&&!P.bTrigger,TEXT("view opens inventory safely"));Check(ULWPlayerInput51::Get51(&P)->Controller58,TEXT("gamepad glyph mode active"));Pad(P,EKeys::Gamepad_LeftX,IE_Axis,0);CaptureV2(TEXT("Controller58_Inventory"));});
 Add(TEXT("controller drag pickup"),.2,[Pad,HUD](ALWCharacter& P){auto Item=LWItems::Make(TEXT("ammo_357"),7);Item.X=Item.Y=0;P.Inventory.Add(Item);auto* H=HUD(P);H->Keyboard55=false;auto* PC=Cast<APlayerController>(P.Controller);PC->SetMouseLocation(int(344*H->Scale+H->Origin55.X),int(160*H->Scale+H->Origin55.Y));Pad(P,EKeys::Gamepad_FaceButton_Bottom,IE_Pressed);},[this,HUD](ALWCharacter& P){Check(HUD(P)->DragId.IsValid(),TEXT("A holds an inventory item for dragging"));});
 Add(TEXT("controller drag drop"),.2,[Pad,HUD](ALWCharacter& P){auto* H=HUD(P);Cast<APlayerController>(P.Controller)->SetMouseLocation(int(440*H->Scale+H->Origin55.X),int(224*H->Scale+H->Origin55.Y));Pad(P,EKeys::Gamepad_FaceButton_Bottom,IE_Released);},[this,HUD,Pad](ALWCharacter& P){Check(!HUD(P)->DragId.IsValid(),TEXT("releasing A completes drag"));Check(P.Inventory.ContainsByPredicate([](const auto& I){return I.Definition==TEXT("ammo_357")&&I.X==3&&I.Y==2&&I.Count==7;}),TEXT("controller moves item without losing its stack"));Pad(P,EKeys::Gamepad_LeftShoulder,IE_Pressed);});
 Add(TEXT("controller held modifier"),.2,[](ALWCharacter&){},[this,Pad](ALWCharacter& P){Check(ULWPlayerInput51::Get51(&P)->IsPressed(EKeys::LeftShift),TEXT("LB holds quick-transfer modifier across frames"));Pad(P,EKeys::Gamepad_LeftShoulder,IE_Released);});
 Add(TEXT("release and disconnect"),.2,[this,Pad](ALWCharacter& P){P.ClosePanels();Pad(P,EKeys::Gamepad_RightTrigger,IE_Pressed);auto* K=ULWPlayerInput51::Get51(&P);K->FlushPressedKeys();Check(K->Held58.IsEmpty()&&K->Axes58.IsEmpty(),TEXT("flush clears controller axes and held actions"));},[this](ALWCharacter& P){Check(!P.bTrigger,TEXT("flushed trigger cannot keep firing"));});
 Add(TEXT("controller text entry"),.2,[this,Pad](ALWCharacter& P){P.NameEditing=true;P.DraftIdentity.Name=TEXT("TEST");auto* K=ULWPlayerInput51::Get51(&P);K->TextCell58=0;Pad(P,EKeys::Gamepad_FaceButton_Bottom,IE_Pressed);Check(P.DraftIdentity.Name==TEXT("TESTA"),TEXT("on-screen keyboard enters letters"));Pad(P,EKeys::Gamepad_FaceButton_Left,IE_Pressed);Check(P.DraftIdentity.Name==TEXT("TEST"),TEXT("controller deletes characters"));Pad(P,EKeys::Gamepad_FaceButton_Right,IE_Pressed);Check(!P.NameEditing,TEXT("controller finishes text entry"));});
 return;
}
