if(FParse::Param(FCommandLine::Get(),TEXT("LWUpdate78Smoke"))){
 auto HUD=[](ALWCharacter& P){return Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());};
 Add(TEXT("78 title input and layout"),1,[](ALWCharacter&){},[this,HUD](ALWCharacter& P){auto* H=HUD(P);Check(H&&H->Backdrop55&&H->Backdrop55->GetName()==TEXT("T_Menu78"),TEXT("new generated backdrop loaded"));int VX=0,VY=0;Cast<APlayerController>(P.Controller)->GetViewportSize(VX,VY);for(const auto& C:H->Controls55){Check(C.Center.X>=0&&C.Center.X<=VX/H->Scale&&C.Center.Y<720,TEXT("menu control within viewport"));auto* Box=H->GetHitBoxAtCoordinates(C.Center*H->Scale+H->Origin55,true);Check(Box&&Box->GetName()==C.Id,TEXT("menu visual and click target agree"));}CaptureV2(TEXT("Update78_Title"));});
 for(int Section=0;Section<7;Section++)Add(FString::Printf(TEXT("78 settings %d"),Section),.4,[HUD,Section](ALWCharacter& P){if(!P.bSettings)HUD(P)->NotifyHitBoxClick(TEXT("Settings"));HUD(P)->NotifyHitBoxClick(FName(*FString::Printf(TEXT("settings78_%d"),Section)));},[this,HUD,Section](ALWCharacter& P){auto* H=HUD(P);Check(P.bSettings&&!P.bTrigger,TEXT("settings retains UI input ownership"));Check(H->Controls55.Num()>8,TEXT("settings page exposes controls"));CaptureV2(*FString::Printf(TEXT("Update78_Settings%d"),Section));});
 Add(TEXT("78 new survivor setup"),.5,[HUD](ALWCharacter& P){HUD(P)->NotifyHitBoxClick(TEXT("Settings"));P.BeginWorldSetup();},[this](ALWCharacter&){CaptureV2(TEXT("Update78_NewSurvivor"));});
 Add(TEXT("78 actual creation handoff"),1,[](ALWCharacter& P){P.WorldSetupClick(TEXT("createworld"));P.bGod47=true;P.EndOpening(true);P.World->EnableEncounters=false;},[this](ALWCharacter& P){Check(P.RPG.Campaign76.Started&&P.Campaign76&&P.Campaign76->SceneOpen,TEXT("new survivor reaches opening conversation"));auto* PC=Cast<APlayerController>(P.Controller);Check(PC->bShowMouseCursor&&P.bUIInputActive,TEXT("opening dialogue has visible active mouse"));Check(GetWorld()->GetGameViewport()->GetMouseCaptureMode()==EMouseCaptureMode::CaptureDuringMouseDown,TEXT("opening conversation forwards clicks without permanent mouse capture"));P.SetMenuInput(false);Check(PC->bShowMouseCursor,TEXT("late gameplay handoff cannot steal dialogue cursor"));CaptureV2(TEXT("Update78_Opening"));});
 Add(TEXT("78 click conversation"),.5,[this,HUD](ALWCharacter& P){auto* D=P.Campaign76.Get();D->BeatWait=0;auto* H=HUD(P);auto* Box=H->GetHitBoxAtCoordinates(FVector2D(1090,664)*H->Scale+H->Origin55,true);Check(Box&&Box->GetName()==TEXT("c76_next"),TEXT("opening continue button is mouse hit-testable"));const int Before=D->State().Beat;H->NotifyHitBoxClick(TEXT("c76_next"));Check(D->State().Beat>Before,TEXT("mouse UI action advances conversation"));Check(!P.bTrigger,TEXT("dialogue click cannot fire equipped weapon"));D->Pause();D->State().Paused=true;P.bStoryLocked=false;P.SetMenuInput(false);},[this](ALWCharacter& P){CaptureV2(TEXT("Update78_HUD"));});
 for(int Tab=0;Tab<6;Tab++)Add(FString::Printf(TEXT("78 survivor tab %d"),Tab),.5,[Tab](ALWCharacter& P){P.SwitchTab(Tab);},[this,HUD,Tab](ALWCharacter& P){int Tabs=0;for(const auto& C:HUD(P)->Controls55)Tabs+=C.Id.ToString().StartsWith(TEXT("tab_"));Check(Tabs==6,TEXT("all survivor tabs preserved"));CaptureV2(*FString::Printf(TEXT("Update78_Tab%d"),Tab));});
 Add(TEXT("78 mounted signs"),2,[this](ALWCharacter& P){P.ClosePanels();P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.World->TickWeather(.1,&P);P.SetActorLocation(P.Campaign76->At(FVector(0,-1150,92)));P.Controller->SetControlRotation(FRotator(0,90,0));},[this](ALWCharacter& P){int Floating=0,Mounted=0;for(TObjectIterator<ULWWorldTextComponent> I;I;++I)if(I->GetWorld()==GetWorld()&&!Cast<ALWSlotMachine>(I->GetOwner()))Floating+=I->IsVisible();for(TObjectIterator<UStaticMeshComponent> I;I;++I)if(I->GetWorld()==GetWorld()&&I->ComponentHasTag(TEXT("MountedSign78")))Mounted++;Check(Floating==0,TEXT("POI glyph labels never float in world"));Check(Mounted>0,TEXT("physical painted signs were attached to supported surfaces"));CaptureV2(TEXT("Update78_Signs"));});
 Add(TEXT("78 exterior approach"),1,[](ALWCharacter& P){P.SetActorLocation(P.Campaign76->At(FVector(0,-1900,180)));P.Controller->SetControlRotation(FRotator(-6,180,0));},[this](ALWCharacter& P){CaptureV2(TEXT("Update78_Approach"));});
 Add(TEXT("78 wilderness stops"),3,[this](ALWCharacter& P){for(const auto& Pair:P.World->Containers)if(Pair.Key.ToString().StartsWith(TEXT("wild78_"))){const FVector At=Pair.Value.Position;P.SetActorLocation(At+FVector(-450,-650,240));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);P.Controller->SetControlRotation((At+FVector(0,0,70)-P.GetActorLocation()).Rotation());break;}},[this](ALWCharacter& P){int Stops=0;for(const auto& Pair:P.World->Containers)if(Pair.Key.ToString().StartsWith(TEXT("wild78_"))){Stops++;Check(Pair.Value.Unlocked&&Pair.Value.LockTier==0,TEXT("wilderness supplies remain accessible"));}Check(Stops>0,TEXT("wilderness scenes generated with persistent loot records"));CaptureV2(TEXT("Update78_Camp"));});
 Add(TEXT("78 pause"),.5,[](ALWCharacter& P){P.ToggleMenu();},[this,HUD](ALWCharacter& P){Check(HUD(P)->Origin55.X==0,TEXT("pause remains full width"));CaptureV2(TEXT("Update78_Pause"));});
 for(auto& Step:V2->Steps){Step.TimeoutSeconds=180;Step.Ready=[Frames=0](ALWCharacter&)mutable{return ++Frames>=30;};}
 return;
}
