if(FParse::Param(FCommandLine::Get(),TEXT("LWUpdate56Smoke"))){
 Add(TEXT("56 full width title"),1,[](ALWCharacter&){},[this](ALWCharacter& P){auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());Check(H&&H->Origin55.X==0,TEXT("title uses full ultrawide viewport"));CaptureV2(TEXT("UI56_Title"));});
 Add(TEXT("56 bindings"),.5,[this](ALWCharacter& P){auto* K=ULWPlayerInput51::Get51(&P);K->Load51();for(auto Pair:TArray<TPair<FKey,FKey>>{{EKeys::Q,EKeys::Q},{EKeys::E,EKeys::C},{EKeys::C,EKeys::LeftControl},{EKeys::F,EKeys::E},{EKeys::H,EKeys::F},{EKeys::M,EKeys::Tab},{EKeys::LeftControl,EKeys::H}})Check(K->Translate51(Pair.Key)==Pair.Value,TEXT("physical control resolves to intended action"));P.NewGame();P.World->EnableEncounters=false;P.EnterSafehouse();P.ClosePanels();P.Health=10000;});
 Add(TEXT("56 crouch press"),.5,[](ALWCharacter& P){P.StartCrouch();P.StopCrouch();},[this](ALWCharacter& P){Check(P.bIsCrouched&&!P.Prone54,TEXT("tap crouch persists after release"));});
 Add(TEXT("56 crouch hold"),.6,[](ALWCharacter& P){P.StartCrouch();},[this](ALWCharacter& P){Check(P.Prone54,TEXT("holding crouch enters prone"));P.StopCrouch();});
 Add(TEXT("56 prone release"),.3,[](ALWCharacter&){},[this](ALWCharacter& P){Check(P.Prone54,TEXT("prone persists after release"));P.Stand54();});
 Add(TEXT("56 map key opens map"),.3,[](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::M,IE_Pressed,1.f));},[this](ALWCharacter& P){Check(P.bMap&&!P.bInventory,TEXT("M opens map rather than inventory"));Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::M,IE_Released,0.f));});
 Add(TEXT("56 map key closes map"),.3,[](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::M,IE_Pressed,1.f));},[this](ALWCharacter& P){Check(!P.bMap&&!P.IsUIOpen(),TEXT("M closes map and releases UI input"));Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::M,IE_Released,0.f));});
 Add(TEXT("56 recovery bag"),.4,[this](ALWCharacter& P){FName Id(TEXT("test56_bag"));auto& R=P.World->Containers.FindOrAdd(Id);R.Id=Id;R.bDropped=true;R.Unlocked=true;FActorSpawnParameters S;S.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* O=GetWorld()->SpawnActor<ALWWorldObject>(P.GetActorLocation(),FRotator::ZeroRotator,S);O->Configure(P.World,ELWObjectKind::Container,Id);Check(O->Body->GetCollisionObjectType()==ECC_PhysicsBody,TEXT("bags are excluded from vehicle terrain probes"));Check(O->Body->GetCollisionEnabled()==ECollisionEnabled::QueryOnly&&O->Body->GetCollisionResponseToChannel(ECC_Pawn)==ECR_Ignore&&O->Body->GetCollisionResponseToChannel(ECC_Vehicle)==ECR_Ignore,TEXT("loot bags do not block people or vehicles"));Check(O->Body->GetCollisionResponseToChannel(ECC_Visibility)==ECR_Block,TEXT("loot bags remain selectable"));O->Destroy();});
 Add(TEXT("56 subtitles"),.6,[](ALWCharacter& P){FActorSpawnParameters S;S.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* N=P.GetWorld()->SpawnActor<ALWResident>(P.GetActorLocation()+FVector(150,0,0),FRotator::ZeroRotator,S);N->ConfigureResident(TEXT("subtitle56"),TEXT("wanderer"),TEXT("MARA VALE"),0);N->Say(TEXT("Keep your eyes on the road. We should reach the settlement before nightfall."));N->SetActorTickEnabled(false);},[this](ALWCharacter&){CaptureV2(TEXT("UI56_Subtitles"));});
 Add(TEXT("56 pause"),.7,[](ALWCharacter& P){P.bMenu=true;P.SetMenuInput(true);},[this](ALWCharacter& P){auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());Check(H->Origin55.X==0,TEXT("pause uses full ultrawide viewport"));CaptureV2(TEXT("UI56_Pause"));});
 Add(TEXT("56 RV"),1,[](ALWCharacter& P){P.bMenu=false;P.ClosePanels();FName Id(TEXT("rv56"));auto& R=P.World->Vehicles.FindOrAdd(Id);R.Model=TEXT("rv");R.Position=P.GetActorLocation()+FVector(0,0,10000);FActorSpawnParameters S;S.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* V=P.GetWorld()->SpawnActor<ALWVehicle>(R.Position,FRotator::ZeroRotator,S);V->World=P.World;V->RecordId=Id;V->InitializeVehicle();V->SetActorTickEnabled(false);auto* Camera=P.GetWorld()->SpawnActor<ACameraActor>();Camera->SetActorLocation(V->Root->GetComponentTransform().TransformPosition(FVector(-120,0,190)));Camera->SetActorRotation(FRotator(-16,0,0));Camera->GetCameraComponent()->bConstrainAspectRatio=false;Cast<APlayerController>(P.Controller)->SetViewTarget(Camera);},[this](ALWCharacter&){CaptureV2(TEXT("UI56_RV"));});
 return;
}
