// Runtime validation uses the existing isolated V17 save harness.
if(FParse::Param(FCommandLine::Get(),TEXT("LWUpdate51Smoke"))){
 auto Add=[this](FString N,double D,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,D,120,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};
 Add(TEXT("painted menu"),2,[](ALWCharacter& P){P.bStarted=false;P.bMenu=true;P.OpeningMode=0;P.bWorldSetup=false;P.World->SetActorTickEnabled(false);},[this](ALWCharacter& P){auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());Check(H&&H->MenuDistant51&&H->MenuForeground51,TEXT("both painted menu layers loaded"));CaptureV2(TEXT("Update51_Menu"));});
 Add(TEXT("keybinding screen"),1,[this](ALWCharacter& P){P.bSettings=true;auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());H->KeysPage51=0;auto* K=ULWPlayerInput51::Get51(&P);Check(K!=nullptr,TEXT("custom input class active"));if(K){K->Load51();Check(K->Bindings.Num()>=35,TEXT("movement combat and vehicle bindings available"));}},[this](ALWCharacter&){CaptureV2(TEXT("Update51_Keys"));});
 Add(TEXT("border scene"),3,[this](ALWCharacter& P){P.bSettings=false;P.NewGame();P.RPG.Story.Enabled=false;P.ClosePanels();P.LeaveSafehouse();P.World->SetActorTickEnabled(false);P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.bCrust=false;P.Health=10000;for(TActorIterator<ALWZombie> I(GetWorld());I;++I)I->Destroy();
 for(int X=99;X<=101;++X)for(int Y=0;Y<=1;++Y){auto* C=GetWorld()->SpawnActor<ALWChunk>(FVector(X*12800.,Y*12800.,0),FRotator::ZeroRotator);C->Coordinate={X,Y};C->Generate(P.World);}
 LWV2Teleport(P,FVector(LWBorder51::North-3300,6400,95));P.Controller->SetControlRotation(FRotator(-1,0,0));if(P.World->Sky)P.World->Sky->SetActorLocation(P.GetActorLocation());P.World->TickWeather(.016f,&P);
 },[this](ALWCharacter& P){int Count=0;for(TActorIterator<ALWBorderGuard51> I(GetWorld());I;++I){++Count;Check(I->Hostile51==0,TEXT("checkpoint approach is neutral"));Check(I->Parts[0]->GetStaticMesh()!=nullptr,TEXT("guard body asset loaded"));}Check(Count==6,TEXT("two streamed checkpoints create six guards"));CaptureV2(TEXT("Update51_Border"));});
 Add(TEXT("fence blocks passage"),.2,[this](ALWCharacter& P){FHitResult H;FCollisionQueryParams Q(NAME_None,false,&P);bool Block=GetWorld()->LineTraceSingleByChannel(H,FVector(LWBorder51::North-200,7000,450),FVector(LWBorder51::North+200,7000,450),ECC_Visibility,Q);Check(Block,TEXT("fence blocks line of sight and passage"));LWV2Teleport(P,FVector(LWBorder51::Warning+100,6400,95));},[this](ALWCharacter&){bool Alarm=false;for(TActorIterator<ALWBorderGuard51> I(GetWorld());I;++I)Alarm|=I->Hostile51>0;Check(Alarm,TEXT("crossing no-entry line alerts guards"));});
 Add(TEXT("retreat and provocation"),.2,[this](ALWCharacter& P){LWV2Teleport(P,FVector(LWBorder51::Warning-2500,6400,95));for(TActorIterator<ALWBorderGuard51> I(GetWorld());I;++I){I->Hostile51=0;I->Fire51=99;}for(TActorIterator<ALWBorderGuard51> I(GetWorld());I;++I){FDamageEvent E;I->TakeDamage(1,E,P.GetController(),&P);break;}for(TActorIterator<ALWBorderGuard51> I(GetWorld());I;++I)Check(I->Hostile51>0,TEXT("attacking guard alerts local squad"));LWV2Teleport(P,FVector(LWBorder51::North+500,6400,100));LWBorder51::Enforce(P.World,&P);Check(P.GetActorLocation().X<LWBorder51::North,TEXT("boundary backstop prevents crossing by teleport or high speed"));});
 auto SavedKeys51=MakeShared<TArray<ULWPlayerInput51::FBinding>>();
 Add(TEXT("input remapping press"),.3,[this,SavedKeys51](ALWCharacter& P){P.ClosePanels();auto* K=ULWPlayerInput51::Get51(&P);if(!RequireV2(K!=nullptr,TEXT("live remapping input object exists")))return;K->Load51();*SavedKeys51=K->Bindings;for(auto& B:K->Bindings)B.Physical=B.Logical;int Forward=K->Bindings.IndexOfByPredicate([](const auto& B){return B.Logical==EKeys::W;});K->Assign51(Forward,EKeys::P);FInputKeyEventArgs E;E.Key=EKeys::P;E.Event=IE_Pressed;E.AmountDepressed=1;K->InputKey(E);},[this](ALWCharacter& P){auto* K=ULWPlayerInput51::Get51(&P);if(!K)return;Check(K->IsPressed(EKeys::W),TEXT("custom movement press reaches logical input"));P.bSettings=true;FInputKeyEventArgs E;E.Key=EKeys::P;E.Event=IE_Released;E.AmountDepressed=0;K->InputKey(E);});
 Add(TEXT("input remapping release and UI capture"),.2,[this,SavedKeys51](ALWCharacter& P){auto* K=ULWPlayerInput51::Get51(&P);if(!K)return;Check(!K->IsPressed(EKeys::W),TEXT("opening UI while held still releases remapped movement"));K->Capture=0;K->CaptureFrame=0;FInputKeyEventArgs E;E.Key=EKeys::Escape;E.Event=IE_Pressed;E.AmountDepressed=1;K->InputKey(E);Check(K->Capture==-1,TEXT("Escape cancels capture"));Check(P.bSettings,TEXT("capture cancel does not also close settings"));E.Event=IE_Released;K->InputKey(E);P.StopAttack();int Ammo=P.Shells;E.Key=EKeys::LeftMouseButton;E.Event=IE_Pressed;K->InputKey(E);P.Attack();Check(!P.bTrigger&&P.Shells==Ammo,TEXT("menu click cannot fire weapon"));E.Event=IE_Released;K->InputKey(E);P.bSettings=false;K->Bindings=*SavedKeys51;});
 Add(TEXT("creature animation safety"),.2,[this](ALWCharacter& P){LWV2Teleport(P,FVector(30000,30000,5000));for(int Type=0;Type<12;++Type){auto* Z=GetWorld()->SpawnActor<ALWZombie>(P.GetActorLocation()+FVector(600,Type*50,0),FRotator::ZeroRotator);Z->PersistentId=51000+Type;Z->ConfigureKind(ELWEnemyKind(Type));Z->SetActorTickEnabled(false);Z->bAggressive=true;Z->LifeAnimation->TickComponent(.05f,LEVELTICK_All,nullptr);Check(!Z->LifeAnimation->AnimationState.IsEmpty(),TEXT("NPC type has active animation state"));Z->bDead=true;auto Rot=Z->Parts[3]->GetRelativeRotation();Z->LifeAnimation->TickComponent(.05f,LEVELTICK_All,nullptr);Check(Z->Parts[3]->GetRelativeRotation().Equals(Rot),TEXT("cosmetic animation does not overwrite dead-body physics"));Z->Destroy();}});
 return;
}
