if(FParse::Param(FCommandLine::Get(),TEXT("LWUpdate80Smoke"))){
 struct FState80{TWeakObjectPtr<ALWVehicle> RV;TWeakObjectPtr<ACameraActor> Camera;TWeakObjectPtr<UAudioComponent> Exterior;TArray<ULWPlayerInput51::FBinding> Bindings;};auto S=MakeShared<FState80>();
 auto HUD=[](ALWCharacter& P){return Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());};
 auto Click=[this,HUD](ALWCharacter& P,FName Id){
  auto* H=HUD(P);const auto* C=H->Controls55.FindByPredicate([&](const auto& Item){return Item.Id==Id;});
  if(!RequireV2(C!=nullptr,*FString::Printf(TEXT("button exists: %s"),*Id.ToString())))return;
  auto* V=GetWorld()->GetGameViewport()->GetGameViewport();auto W=V->GetViewportWidget().Pin();if(!W)return;
  const FGeometry& G=W->GetCachedGeometry();const FVector2D Local=C->Center*H->Scale+H->Origin55;
  auto* Hit=H->GetHitBoxAtCoordinates(Local,true);Check(Hit&&Hit->GetName()==Id,TEXT("topmost hitbox matches button"));
  const FVector2D Point=G.LocalToAbsolute(Local);TSet<FKey> Keys;Keys.Add(EKeys::LeftMouseButton);
  FPointerEvent Down(0,0,Point,Point,Keys,EKeys::LeftMouseButton,0,FModifierKeysState());V->OnMouseButtonDown(G,Down);
  Keys.Empty();FPointerEvent Up(0,0,Point,Point,Keys,EKeys::LeftMouseButton,0,FModifierKeysState());V->OnMouseButtonUp(G,Up);
 };
 auto Key=[](ALWCharacter& P,FKey K){auto* PC=Cast<APlayerController>(P.Controller);FInputKeyEventArgs E;E.Key=K;E.Event=IE_Pressed;E.AmountDepressed=1;PC->InputKey(E);E.Event=IE_Released;E.AmountDepressed=0;PC->InputKey(E);};
 Add(TEXT("80 first mouse press"),.5,[this](ALWCharacter& P){P.SetMenuInput(true);},[this,Click](ALWCharacter& P){Click(P,TEXT("Settings"));Check(P.bSettings&&!P.bTrigger,TEXT("single viewport click opens settings without firing"));});
 Add(TEXT("80 settings back click"),.5,[](ALWCharacter&){},[this,Click](ALWCharacter& P){Click(P,TEXT("Settings"));Check(!P.bSettings,TEXT("single click returns from settings"));});
 Add(TEXT("80 isolated game"),1,[this,S](ALWCharacter& P){
  P.NewGame();P.EndOpening(true);P.ClosePanels();if(P.Campaign76){P.Campaign76->Pause();P.RPG.Campaign76.Paused=true;}P.bStoryLocked=false;P.bMenu=false;P.bStarted=true;P.bGod47=true;P.World->EnableEncounters=false;P.World->SetActorTickEnabled(false);P.GetCharacterMovement()->DisableMovement();P.World->TimeOfDay=12;P.World->TickWeather(0,&P);P.bCrust=false;P.bSafehouse=false;P.SetActorHiddenInGame(true);P.SetActorLocation(FVector(20000,20000,50300));P.SetMenuInput(false);
  auto* K=ULWPlayerInput51::Get51(&P);K->Load51();S->Bindings=K->Bindings;K->Reset51();
  auto* Floor=GetWorld()->SpawnActor<ALWChunk>();Floor->SyncCollision68=true;Floor->Box(P.World,TEXT("Concrete"),FVector(20000,20000,49990),FVector(16000,16000,20));S->Camera=GetWorld()->SpawnActor<ACameraActor>();S->Camera->GetCameraComponent()->SetFieldOfView(86);
  P.DrainSave40();P.Money=8080;P.OpenSaves62(true);Check(P.ManualSave62(LWSaves62::Manual(1)),TEXT("initial manual save accepted"));P.DrainSave40();P.SavePanel62=0;P.ToggleMenu();
 },[this](ALWCharacter& P){Check(P.bMenu,TEXT("pause menu available"));});
 Add(TEXT("80 pause save button"),.5,[Click](ALWCharacter& P){Click(P,TEXT("Save62"));},[this](ALWCharacter& P){Check(P.SavePanel62==1,TEXT("pause save button opens save slots"));});
 Add(TEXT("80 overwrite target"),.5,[Click](ALWCharacter& P){Click(P,TEXT("save62_slot1"));},[this,HUD](ALWCharacter& P){Check(!P.SaveConfirm62.IsEmpty(),TEXT("existing save opens confirmation"));Check(HUD(P)->Controls55.Num()==2,TEXT("modal owns mouse and keyboard controls"));CaptureV2(TEXT("Update80_SaveConfirmation"));});
 Add(TEXT("80 confirm click saves while paused"),1,[Click](ALWCharacter& P){P.Money=8181;Click(P,TEXT("save62_confirm"));},[this](ALWCharacter& P){P.DrainSave40();auto* Save=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromSlot(LWSaves62::Manual(1),0));Check(Save&&Save->Money==8181,TEXT("one confirmation click writes chosen slot"));Check(P.SaveConfirm62.IsEmpty()&&P.SaveMessage62==TEXT("Save complete."),TEXT("save result is visible"));});
 Add(TEXT("80 queue behind autosave"),1,[this](ALWCharacter& P){P.DrainSave40();P.Money=8282;P.SaveProgress();P.StartSave43();Check(P.SaveWrite40.IsValid(),TEXT("autosave writer active"));P.Money=8383;Check(P.ManualSave62(LWSaves62::Manual(2))&&P.PendingSave62==LWSaves62::Manual(2),TEXT("manual request queues behind active autosave"));},[this](ALWCharacter& P){P.DrainSave40();auto* Save=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromSlot(LWSaves62::Manual(2),0));Check(Save&&Save->Money==8383,TEXT("queued manual snapshot reaches its own slot"));P.SavePanel62=0;P.ToggleMenu();});
 for(int Electric=0;Electric<2;Electric++){
  Add(FString::Printf(TEXT("80 coach %d setup"),Electric),1,[this,S,Electric](ALWCharacter& P){
   if(P.Vehicle)P.Vehicle->Exit(true);if(S->RV.IsValid())S->RV->Destroy();P.ClosePanels();P.bMenu=false;UGameplayStatics::SetGamePaused(&P,false);P.SetMenuInput(false);P.SetActorTickEnabled(false);
   FLWVehicleRecord R;R.Model=Electric?TEXT("solstice_rv"):TEXT("rv");R.Position=FVector(20000,20000,50075);R.VIN=FGuid::NewGuid();R.Unlocked=R.Hotwired=true;R.FuelLitres=70;R.FuelLootInitialized=true;R.CabinLights66=true;
   const FName ID=Electric?TEXT("rv80_electric"):TEXT("rv80_diesel");P.World->Vehicles.Add(ID,R);auto* V=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,ID,R.Position));S->RV=V;if(!RequireV2(V!=nullptr,TEXT("coach spawned")))return;V->SetActorTickEnabled(false);V->SpawnPlacementPending=false;V->SetActorHiddenInGame(false);P.SetActorLocation(V->GetActorLocation());Check(V->Enter(&P,-1),TEXT("driver can enter repaired coach"));
   Check(V->ShadesMesh66.Num()==15,TEXT("fifteen independently controlled window blinds"));Check(V->SlideSeals80.Num()==2,TEXT("both telescoping slide seals installed"));
   int Panes=0;bool Left=false,Right=false,Firewall=false;for(auto& C:V->Details){if(C->ComponentHasTag(TEXT("CoachGlazing80"))){Panes++;auto Bounds=C->GetStaticMesh()->GetBoundingBox().TransformBy(C->GetRelativeTransform());Left|=Bounds.IsInside(FVector(35,-123,250));Right|=Bounds.IsInside(FVector(105,123,250));}Firewall|=C->GetStaticMesh()&&C->GetStaticMesh()->GetName()==TEXT("SM_RV80_Joinery");}
   Check(Panes==13&&Left&&Right,TEXT("glass covers former gaps on both cockpit sides"));Check(Firewall,TEXT("lower dashboard and doorway joinery installed"));
   if(!Electric){Check(V->GaugeNeedles42.Num()==4&&V->GaugeNeedles42[0]->GetRelativeLocation().X<120,TEXT("instruments sit in front of dashboard fascia"));V->Speed=1000;V->TickInstruments42(.1f);Check(V->GaugeNeedles42[0]->GetRelativeRotation().Roll>-130,TEXT("speed needle responds"));V->Speed=0;}
   Cast<APlayerController>(P.Controller)->SetViewTarget(S->Camera.Get());Cast<APlayerController>(P.Controller)->GetHUD()->bShowHUD=false;S->Camera->SetActorLocation(V->Root->GetComponentTransform().TransformPosition(FVector(-40,0,222)));S->Camera->SetActorRotation(V->GetActorRotation()+FRotator(-15,0,0));
  },[this,Electric](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Update80_Cockpit%d"),Electric));});
  Add(FString::Printf(TEXT("80 coach %d engine acoustics"),Electric),1.5,[S](ALWCharacter& P){auto* V=S->RV.Get();V->EngineOn=true;for(int I=0;I<40;I++)V->TickDriveAudio(.05,false,.4);S->Exterior=P.World->Sound(TEXT("CarEngine"),V->GetActorLocation()+FVector(1000,0,0));},[this,S](ALWCharacter& P){auto* V=S->RV.Get();auto* A=V->DriveAudio.IsEmpty()?nullptr:V->DriveAudio[0].Get();Check(A&&A->VolumeMultiplier>.05f&&!A->AttenuationOverrides.bAttenuate&&A->AttenuationOverrides.LPFFrequencyAtMin>=4500,TEXT("own engine retains gain and cabin bandwidth without distance loss"));Check(S->Exterior.IsValid()&&S->Exterior->AttenuationOverrides.bAttenuate&&S->Exterior->AttenuationOverrides.LPFFrequencyAtMin<3000,TEXT("outside engine retains distance attenuation and cabin muffling"));if(S->Exterior.IsValid())S->Exterior->Stop();});
  Add(FString::Printf(TEXT("80 coach %d keyboard wipers"),Electric),.5,[S,Key](ALWCharacter& P){P.SetActorTickEnabled(true);S->RV->WipersOn=false;Key(P,EKeys::V);},[this,S](ALWCharacter& P){Check(S->RV->WipersOn,TEXT("V toggles wipers through input binding"));});
  Add(FString::Printf(TEXT("80 coach %d rebound wipers"),Electric),.5,[S,Key](ALWCharacter& P){auto* K=ULWPlayerInput51::Get51(&P);int I=K->Bindings.IndexOfByPredicate([](const auto& B){return B.Logical==EKeys::V;});K->Assign51(I,EKeys::F8);Key(P,EKeys::F8);},[this,S](ALWCharacter& P){Check(!S->RV->WipersOn,TEXT("rebound key toggles same wiper action"));auto* K=ULWPlayerInput51::Get51(&P);int I=K->Bindings.IndexOfByPredicate([](const auto& B){return B.Logical==EKeys::V;});K->Assign51(I,EKeys::V);});
  Add(FString::Printf(TEXT("80 coach %d controller wipers"),Electric),.5,[Key](ALWCharacter& P){auto* PC=Cast<APlayerController>(P.Controller);FInputKeyEventArgs E;E.Key=EKeys::Gamepad_LeftShoulder;E.Event=IE_Pressed;E.AmountDepressed=1;PC->InputKey(E);Key(P,EKeys::Gamepad_FaceButton_Left);E.Event=IE_Released;E.AmountDepressed=0;PC->InputKey(E);},[this,S](ALWCharacter& P){Check(S->RV->WipersOn,TEXT("controller LB plus X toggles wipers"));});
  Add(FString::Printf(TEXT("80 coach %d sound and slides"),Electric),1,[this,S,Electric](ALWCharacter& P){auto* V=S->RV.Get();V->EngineOn=true;V->Speed=0;for(int I=0;I<40;I++)V->TickDriveAudio(.05,false,.3);auto* Idle=V->DriveAudio.IsEmpty()?nullptr:V->DriveAudio[0].Get();Check(Idle&&Idle->IsPlaying(),TEXT("engine loop plays"));const float Before=V->EngineRPM;V->Speed=1100;for(int I=0;I<30;I++)V->TickDriveAudio(.05,false,1);Check(V->DriveAudio[0]==Idle,TEXT("acceleration keeps seamless engine instance"));if(!Electric)Check(V->EngineRPM>Before,TEXT("engine revs rise under throttle"));V->EngineOn=false;V->Speed=0;V->WipersOn=true;for(int I=0;I<30;I++)V->TickDriveAudio(.05,false,0);Check(V->DriveAudio[Electric?3:6]&&V->DriveAudio[Electric?3:6]->VolumeMultiplier>0,TEXT("wiper audio remains audible with ignition off"));V->Record()->Slides66=true;for(int I=0;I<140;I++)V->TickLuxury66(.05);Check(V->SlideSeals80[0]->IsVisible()&&V->SlideSeals80[0]->GetRelativeScale3D().Y>.99f,TEXT("deployed slides extend continuous return panels"));
   S->Camera->SetActorLocation(V->Root->GetComponentTransform().TransformPosition(FVector(-210,0,221)));S->Camera->SetActorRotation(V->GetActorRotation()+FRotator(0,-75,0));
  },[this,Electric](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Update80_WindowSlide%d"),Electric));});
  Add(FString::Printf(TEXT("80 coach %d vehicle save"),Electric),.5,[this,S,Key,Electric](ALWCharacter& P){auto* V=S->RV.Get();V->Record()->Slides66=false;for(int I=0;I<140;I++)V->TickLuxury66(.05);Check(!V->SlideSeals80[0]->IsVisible(),TEXT("slide returns retract without narrowing aisle"));P.ToggleMenu();P.OpenSaves62(true);Check(P.SavePanel62==1,TEXT("save panel opens while seated"));V->WipersOn=false;Key(P,EKeys::V);Check(P.ManualSave62(LWSaves62::Manual(3+Electric)),TEXT("manual save accepted in vehicle"));},[this,S,Electric](ALWCharacter& P){P.DrainSave40();auto* Save=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromSlot(LWSaves62::Manual(3+Electric),0));Check(Save&&Save->SeatedVehicle==S->RV->RecordId,TEXT("manual save preserves occupied vehicle"));Check(!S->RV->WipersOn&&!P.bTrigger,TEXT("menu input cannot toggle wipers or fire"));P.SavePanel62=0;P.ToggleMenu();});
 }
 Add(TEXT("80 restore settings and exit"),.4,[S](ALWCharacter& P){if(P.Vehicle)P.Vehicle->Exit(true);auto* K=ULWPlayerInput51::Get51(&P);K->Bindings=S->Bindings;K->Save51();Cast<APlayerController>(P.Controller)->SetViewTarget(&P);},[this](ALWCharacter&){Check(true,TEXT("coach enter and exit completed without crash"));});
 for(auto& Step:V2->Steps){Step.TimeoutSeconds=180;Step.Ready=[Frames=0](ALWCharacter&)mutable{return ++Frames>=20;};}
 return;
}
