if(FParse::Param(FCommandLine::Get(),TEXT("LWExpansion57Smoke"))){
 struct F57{TWeakObjectPtr<ALWChunk> POI;TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWResident> NPC;TWeakObjectPtr<ALWZombie> Target;};auto S=MakeShared<F57>();
 Add(TEXT("expansion57 setup"),1,[](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;P.ClosePanels();P.LeaveSafehouse();P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.World->TickWeather(0,&P);if(P.World->AmbientLight)P.World->AmbientLight->GetLightComponent()->SetIntensity(1.2f);P.World->SetActorTickEnabled(false);P.bCrust=false;P.Health=10000;for(TActorIterator<ALWZombie> I(P.GetWorld());I;++I)I->Destroy();for(TActorIterator<ALWVehicle> I(P.GetWorld());I;++I)I->Destroy();P.World->Vehicles.Empty();auto* F=P.GetWorld()->SpawnActor<ALWChunk>();F->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(30000,30000,20));for(TActorIterator<ADirectionalLight> I(P.GetWorld());I;++I){I->SetActorRotation(FRotator(-55,-40,0));I->GetLightComponent()->SetIntensity(5);}});
 for(FName Model:{FName(TEXT("apc")),FName(TEXT("armoredtruck")),FName(TEXT("technical")),FName(TEXT("helicopter"))}){
 Add(Model.ToString()+TEXT(" exterior"),1,[this,S,Model](ALWCharacter& P){if(S->Car.IsValid()){S->Car->Exit(true);S->Car->Destroy();}P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);const FVector At(20000,20000,5075);FLWVehicleRecord R;R.VIN=FGuid::NewGuid();R.Model=Model;R.Position=At;R.Unlocked=R.Hotwired=true;R.FuelLitres=100;FName Id(*(TEXT("test57_")+Model.ToString()));P.World->Vehicles.Add(Id,R);auto* C=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,At));S->Car=C;if(!RequireV2(C!=nullptr,TEXT("new vehicle spawned")))return;C->SetActorTickEnabled(false);C->SpawnPlacementPending=false;C->SetActorHiddenInGame(false);C->SetActorEnableCollision(true);C->SetActorLocation(At);Check(C->Body->GetStaticMesh()&&C->Body->GetStaticMesh()->GetName()==TEXT("SM_Vehicle42_")+Model.ToString(),TEXT("custom body asset active"));Check(C->GaugeNeedles42.Num()==4,TEXT("instrument needles present"));FVector Eye=At+FVector(900,-1100,600),Look=At+FVector(0,0,70);LWV2Teleport(P,Eye-FVector(0,0,66));P.Controller->SetControlRotation((Look-Eye).Rotation());},[this,Model](ALWCharacter&){CaptureV2(*(TEXT("Expansion57_")+Model.ToString()));});
 Add(Model.ToString()+TEXT(" cockpit"),.6,[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;LWV2Teleport(P,C->GetActorLocation()+FVector(0,-300,20));Check(C->Enter(&P,-1),TEXT("driver seat enters"));P.SeatYaw=0;P.SeatPitch=0;P.TickVehicleSeat();for(int I=0;I<3;I++){const TCHAR* Suffix[]={TEXT("Idle"),TEXT("Low"),TEXT("High")};FLWResolvedAudioSlot A;Check(P.World->AudioCatalog->ResolveSlot(FName(*(FString(TEXT("Vehicle42_"))+C->Spec().Id+TEXT("_")+Suffix[I])),A,false)&&A.Sound&&A.Settings.bLoop,TEXT("generated engine loop resolves"));}},[this,Model](ALWCharacter&){CaptureV2(*(TEXT("Expansion57_Cockpit_")+Model.ToString()));});
 if(Model==TEXT("apc")||Model==TEXT("technical")){
 Add(TEXT("companion turret targeting"),.6,[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;P.bWaypoint=false;FActorSpawnParameters Params;Params.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* N=GetWorld()->SpawnActor<ALWResident>(C->GetActorLocation()+FVector(0,200,0),FRotator::ZeroRotator,Params);N->SetActorTickEnabled(false);S->NPC=N;Check(C->Board(N),TEXT("companion boards gunner seat"));Check(C->Passengers.IsValidIndex(0)&&C->Passengers[0]==N,TEXT("first companion operates turret"));const FVector At=C->Turret57->GetComponentLocation()+FVector(0,2200,0);auto* Z=GetWorld()->SpawnActor<ALWZombie>(At,FRotator::ZeroRotator,Params);Z->Health=10000;Z->SetActorTickEnabled(false);S->Target=Z;const int Before=C->Record()->TurretRounds57;for(int I=0;I<40;I++)C->TickTurret57(.05f);Check(C->Record()->TurretRounds57<Before,TEXT("companion fires mounted weapon without player trigger"));Check(Z->Health<10000,TEXT("mounted fire hits enemy"));C->Record()->TurretRounds57=0;auto& Cargo=P.World->Containers.FindChecked(C->RecordId);Cargo.Items.Empty();auto Ammo=LWItems::Make(FName(C->Spec().Id)==TEXT("apc")?TEXT("ammo_30mm"):TEXT("ammo_762"),10);Cargo.Items.Add(Ammo);C->ReloadClock57=0;C->ReloadTurret57();Check(C->Record()->TurretRounds57==10&&Cargo.Items.IsEmpty(),TEXT("reload consumes cargo ammo exactly"));Z->Destroy();N->LeaveVehicle();N->Destroy();});
 Add(TEXT("turret respects UI capture"),.2,[this,S](ALWCharacter& P){auto* C=S->Car.Get();C->ChangeSeat(0);P.ClosePanels();P.ReleaseAttackInput();P.Attack();Check(C->TurretTrigger57,TEXT("gunner primary fire captured"));P.bInventory=true;P.Attack();Check(!C->TurretTrigger57,TEXT("inventory click cancels turret fire"));P.ClosePanels();P.ReleaseAttackInput();});
 }
 if(Model==TEXT("helicopter"))Add(TEXT("flight and landing"),.2,[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;C->EngineOn=true;C->RotorSpeed57=1;const FVector Start=C->GetActorLocation();C->Velocity57=FVector(0,0,1000);for(int I=0;I<25;I++)C->TickFlight57(.05f);Check(C->GetActorLocation().Z>Start.Z+300,TEXT("flight controller moves vertically without snapping to terrain"));Check(!C->Exit(false),TEXT("cannot exit above ground"));C->EngineOn=false;for(int I=0;I<240;I++)C->TickFlight57(.05f);Check(C->Altitude57<130,TEXT("unpowered helicopter descends and lands"));C->Velocity57=FVector::ZeroVector;C->Speed=0;C->Exit(true);});
 }
 for(int Kind=12;Kind<=14;Kind++)Add(FString::Printf(TEXT("enemy57 %d"),Kind),.8,[this,S,Kind](ALWCharacter& P){if(S->Car.IsValid()){S->Car->Exit(true);S->Car->Destroy();S->Car.Reset();}if(S->Target.IsValid())S->Target->Destroy();FActorSpawnParameters A;A.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20000,20000,5100),FRotator::ZeroRotator,A);S->Target=Z;Z->ConfigureKind(ELWEnemyKind(Kind));Z->SetActorLocation(FVector(20000,20000,Kind==12?5250:5100));Z->SetActorTickEnabled(false);Check(Z->Health>100&&Z->Parts[0]->GetStaticMesh()->GetName().EndsWith(TEXT("57")),TEXT("new enemy mesh and stats configured"));LWV2Teleport(P,FVector(20400,19500,5190));P.Controller->SetControlRotation((Z->GetActorLocation()-P.Camera->GetComponentLocation()).Rotation());Z->Tick57(.05f,&P);Check(Z->EnemyName().Contains(Kind==12?TEXT("HORNET"):Kind==13?TEXT("BEAR"):TEXT("ROGUE")),TEXT("correct enemy HUD identity"));FLWResolvedAudioSlot V;Check(P.World->AudioCatalog->ResolveSlot(Kind==12?TEXT("Hornet57"):Kind==13?TEXT("Bear57"):TEXT("Rogue57"),V,false)&&V.Sound,TEXT("enemy ElevenLabs voice resolves"));},[this,Kind](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Expansion57_Enemy%d"),Kind));});
 Add(TEXT("new POI generation"),.1,[this](ALWCharacter& P){bool Found[4]={};for(int X=-4;X<=4;X++)for(int Y=-4;Y<=4;Y++){TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;LWGen::Region({X,Y},P.World->Seed,Roads,Sites);for(const auto& Site:Sites)if(Site.Type>=64&&Site.Type<68)Found[Site.Type-64]=true;}for(int I=0;I<4;I++)Check(Found[I],*FString::Printf(TEXT("POI %d appears in generated world"),64+I));});
 for(int Type=64;Type<68;Type++){
 Add(FString::Printf(TEXT("POI57 layout %d"),Type),1,[this,S,Type](ALWCharacter& P){if(S->Target.IsValid())S->Target->Destroy();if(S->POI.IsValid())S->POI->Destroy();for(TActorIterator<ALWVehicle> I(GetWorld());I;++I)I->Destroy();P.World->Vehicles.Empty();LWV2Teleport(P,FVector(60000,60000,700));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);LWGen::FSite Site;Site.Position=FVector2D(60000,60000);Site.Type=Type;Site.Id=57000+Type;Site.Size=LWPlaces::Size(Type);auto* C=GetWorld()->SpawnActor<ALWChunk>();S->POI=C;LWExpansion57::Build(C,P.World,Site);Check(C->Residents.Num()>10,TEXT("POI has interactable content"));if(Type==64)for(TActorIterator<ALWVehicle> I(GetWorld());I;++I)Check(!I->SpawnPlacementPending,TEXT("base vehicle pads are clear"));const FVector Eye=FVector(60000,60000,1000)+FVector(Site.Size.X*.60,-Site.Size.Y*.65,2200);LWV2Teleport(P,Eye-FVector(0,0,66));P.Controller->SetControlRotation((FVector(60000,60000,50)-Eye).Rotation());},[this,Type](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Expansion57_POI%d"),Type));});
 Add(TEXT("POI57 interior"),.7,[this,Type](ALWCharacter& P){const FVector Eye=FVector(60000,60000,175)+FVector(Type==64?-3100:0,Type==64?-2200:Type==65?-2100:Type==66?-3100:-2200,0);LWV2Teleport(P,Eye-FVector(0,0,66));P.Controller->SetControlRotation(FRotator(0,90,0));},[this,Type](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Expansion57_Interior%d"),Type));});
 }
 return;
}
