#include "Misc/AutomationTest.h"
#include "LWGeneration.h"
#include "LWPlayerInput51.h"
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWBorder51Test,"LethalWorld.Update51.NorthernBoundary",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWBorder51Test::RunTest(const FString&){
 for(int Seed:{198706,7,123456})for(int Y=-3;Y<=3;++Y)for(int X=24;X<=27;++X){TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;LWGen::Region({X,Y},Seed,Roads,Sites);for(const auto& S:Sites)TestTrue(TEXT("Full POI footprint remains south of border reserve"),S.Position.X+S.Size.Size()*.5<=LWBorder51::Strip-1000);for(const auto& R:Roads)TestTrue(TEXT("Roads do not enter Canada"),R.A.X<=LWBorder51::Warning&&R.B.X<=LWBorder51::Warning);}
 TArray<LWGen::FRoad> R;TArray<LWGen::FSite> S;for(double Y:{-12800.,0.,6400.,12800.}){TestEqual(TEXT("Fence foundation flat across chunk boundaries"),LWGen::Height({LWBorder51::North,Y},R,S),0.f);TestTrue(TEXT("Terrain joins at southern strip"),FMath::Abs(LWGen::Height({LWBorder51::Strip-.1,Y},R,S)-LWGen::Height({LWBorder51::Strip+.1,Y},R,S))<1.f);}
 TestFalse(TEXT("Approach is neutral"),LWBorder51::Restricted(LWBorder51::Warning-1));TestTrue(TEXT("Crossing is restricted"),LWBorder51::Restricted(LWBorder51::Warning+1));return true;
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWKeys51Test,"LethalWorld.Update51.Keybindings",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWKeys51Test::RunTest(const FString&){auto* K=NewObject<ULWPlayerInput51>();K->Load51();for(auto& B:K->Bindings)B.Physical=B.Logical;int Fire=K->Bindings.IndexOfByPredicate([](const auto& B){return B.Logical==EKeys::LeftMouseButton;});TestTrue(TEXT("Fire binding exists"),Fire>=0);TestTrue(TEXT("Rebind attack to unused key"),K->Assign51(Fire,EKeys::P));TestTrue(TEXT("New key fires"),K->Translate51(EKeys::P)==EKeys::LeftMouseButton);TestFalse(TEXT("Former fire key no longer fires"),K->Translate51(EKeys::LeftMouseButton).IsValid());TestTrue(TEXT("Conflicts swap"),K->Assign51(Fire,EKeys::R));TestTrue(TEXT("R fires after swap"),K->Translate51(EKeys::R)==EKeys::LeftMouseButton);TestTrue(TEXT("Old physical key now reloads"),K->Translate51(EKeys::P)==EKeys::R);TestFalse(TEXT("Escape is reserved"),K->Assign51(Fire,EKeys::Escape));TestFalse(TEXT("Mouse axes cannot be bound to actions"),K->Assign51(Fire,EKeys::MouseX));TSet<FKey> Used;for(const auto& B:K->Bindings){TestFalse(TEXT("No duplicate physical bindings"),Used.Contains(B.Physical));Used.Add(B.Physical);}return true;}
