if(FParse::Param(FCommandLine::Get(),TEXT("LWUpdate60Smoke"))){
 auto Key=[](ALWCharacter& P,FKey K,EInputEvent E){FInputKeyEventArgs A;A.Key=K;A.Event=E;A.AmountDepressed=E==IE_Released?0:1;ULWPlayerInput51::Get51(&P)->InputKey(A);};
 Add(TEXT("input setup"),.5,[](ALWCharacter& P){P.NewGame();P.bGod47=true;P.RPG.Story.Enabled=false;P.World->SetActorTickEnabled(false);P.EnterSafehouse();P.ClosePanels();auto* K=ULWPlayerInput51::Get51(&P);K->Reset51();});
 Add(TEXT("Tab inventory"),.2,[Key](ALWCharacter& P){Key(P,EKeys::Tab,IE_Pressed);},[this,Key](ALWCharacter& P){Check(P.bInventory&&!P.bMap,TEXT("Tab opens inventory"));Key(P,EKeys::Tab,IE_Released);});
 Add(TEXT("Tab closes inventory"),.2,[Key](ALWCharacter& P){Key(P,EKeys::Tab,IE_Pressed);},[this,Key](ALWCharacter& P){Check(!P.bInventory,TEXT("Tab closes inventory"));Key(P,EKeys::Tab,IE_Released);});
 Add(TEXT("M map"),.2,[Key](ALWCharacter& P){Key(P,EKeys::M,IE_Pressed);},[this,Key](ALWCharacter& P){Check(P.bMap,TEXT("M still opens map"));Key(P,EKeys::M,IE_Released);P.ClosePanels();});
 Add(TEXT("world cheats and roadside prop"),.6,[this](ALWCharacter& P){
  auto* C=Cast<ULWConsole47>(GetWorld()->GetGameViewport()->ViewportConsole);if(!RequireV2(C!=nullptr,TEXT("console installed")))return;
  P.bSafehouse=false;P.SetActorLocation(FVector(-300000,-300000,180));P.SetActorRotation(FRotator::ZeroRotator);P.GetCharacterMovement()->DisableMovement();
  auto* Chunk=GetWorld()->SpawnActor<ALWChunk>(FVector(-300000,-300000,0),FRotator::ZeroRotator);Chunk->LightingWorld=P.World;Chunk->Box(P.World,TEXT("Concrete"),FVector(0,0,-50),FVector(15000,15000,100));
  Chunk->StreetLight(P.World,FVector(1000,0,0),FRotator::ZeroRotator,false);
  Check(C->Execute47(TEXT("npctypes")).Contains(TEXT("colossus")),TEXT("NPC list includes giant enemies"));Check(C->Execute47(TEXT("vehicles")).Contains(TEXT("helicopter")),TEXT("vehicle list includes helicopter"));Check(C->Execute47(TEXT("pois")).Contains(TEXT("AIRPORT")),TEXT("POI list includes airport"));
  Check(C->Execute47(TEXT("spawnnpc zombie 0")).Contains(TEXT("Usage")),TEXT("invalid spawn count rejected"));Check(C->Execute47(TEXT("spawnvehicle nonsense")).Contains(TEXT("Unknown")),TEXT("unknown vehicle rejected"));Check(C->Execute47(TEXT("locate nonsense")).Contains(TEXT("Unknown")),TEXT("unknown POI rejected"));
  P.SetActorRotation(FRotator(0,90,0));Check(C->Execute47(TEXT("spawnnpc survivor")).Contains(TEXT("Spawned 1 / 1")),TEXT("friendly NPC spawns"));Check(C->Execute47(TEXT("spawnnpc bear")).Contains(TEXT("Spawned 1 / 1")),TEXT("enemy NPC spawns"));
  P.SetActorRotation(FRotator(0,180,0));Check(C->Execute47(TEXT("spawnvehicle dirtbike")).Contains(TEXT("Spawned")),TEXT("vehicle command spawns requested model"));P.SetActorRotation(FRotator::ZeroRotator);
  // Directly exercise the same swept path used by player, AI, and thrown vehicles.
  const FName Id(TEXT("impact_test60"));FLWVehicleRecord Rec;Rec.Model=TEXT("sedan");Rec.Position=P.GetActorLocation()+FVector(500,0,-80);Rec.Unlocked=Rec.Hotwired=true;P.World->Vehicles.Add(Id,Rec);auto* V=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,Rec.Position));
  if(RequireV2(V!=nullptr,TEXT("impact test vehicle spawned"))){V->SetActorTickEnabled(false);V->Speed=100;V->HitPedestrians(P.GetActorLocation()+FVector(1600,0,-80),FRotator::ZeroRotator);Check(Chunk->Breakables60[0].Fall<0,TEXT("low speed does not destroy lamp"));V->Speed=1300;V->HitPedestrians(P.GetActorLocation()+FVector(1600,0,-80),FRotator::ZeroRotator);Check(Chunk->Breakables60[0].Fall>=0,TEXT("vehicle sweep knocks down street lamp"));Check(P.World->PropStates.FindRef(Chunk->Breakables60[0].Id)==1,TEXT("destroyed prop state persisted"));auto* Reloaded=GetWorld()->SpawnActor<ALWChunk>(Chunk->GetActorLocation(),FRotator::ZeroRotator);Reloaded->LightingWorld=P.World;Reloaded->StreetLight(P.World,FVector(1000,0,0),FRotator::ZeroRotator,false);Check(Reloaded->Breakables60[0].Fall==1,TEXT("streamed replacement retains destruction"));bool Hidden=true;for(const auto& Ref:Reloaded->Breakables60[0].Parts)if(Ref.IsValid())Hidden&=!Ref->IsVisible();Check(Hidden,TEXT("destroyed prop stays hidden after regeneration"));Reloaded->Destroy();V->Destroy();}
  P.ObjectFocus=nullptr;P.ResidentFocus=nullptr;P.Focus=nullptr;
  P.ClearWaypoint();C->Execute47(TEXT("locate casino 5"));
 });
 Add(TEXT("hold vehicle modifier"),.2,[Key](ALWCharacter& P){P.SetActorTickEnabled(false);const FName Id(TEXT("flip_test60"));FLWVehicleRecord R;R.Model=TEXT("sedan");R.Position=P.GetActorLocation()+FVector(400,-600,-80);R.Unlocked=true;P.World->Vehicles.Add(Id,R);auto* V=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,R.Position));if(V){V->SetActorTickEnabled(false);V->SetActorRotation(FRotator(20,0,40));P.SetActorLocation(P.GetActorLocation()+FVector(0,-600,0));P.ObjectFocus=V;P.ResidentFocus=nullptr;P.CorpseFocus=nullptr;P.Focus=nullptr;}Key(P,EKeys::LeftShift,IE_Pressed);});
 Add(TEXT("Shift E recovers vehicle"),.2,[Key](ALWCharacter& P){Key(P,EKeys::E,IE_Pressed);},[this,Key](ALWCharacter& P){auto* V=Cast<ALWVehicle>(P.ObjectFocus);Check(V&&FMath::Abs(V->GetActorRotation().Roll)<1&&FMath::Abs(V->GetActorRotation().Pitch)<1,TEXT("Shift E reaches flip interaction instead of lean"));Check(!P.LeanRight40,TEXT("recovery shortcut does not lean"));Key(P,EKeys::E,IE_Released);Key(P,EKeys::LeftShift,IE_Released);P.SetActorTickEnabled(true);});
 Add(TEXT("locator completes without streaming actors"),.1,[](ALWCharacter&){},[this](ALWCharacter& P){Check(P.bWaypoint,TEXT("POI locator sets a waypoint"));});
 V2->Steps.Last().Ready=[](ALWCharacter& P){return P.bWaypoint;};V2->Steps.Last().TimeoutSeconds=45;
 return;
}
