void ALWGameMode::BuildUrbanSmoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,60,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWChunk> C;FVector Base=FVector(200000,200000,15012);};auto S=MakeShared<FState>();
 Add(TEXT("urban setup"),1,[this](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.World->EnableEncounters=false;P.Health=10000;P.Flashlight->SetVisibility(false);});
 for(int Access:{0,3,12})Add(FString::Printf(TEXT("tower access %d"),Access),2,[this,S,Access](ALWCharacter& P){
 if(S->C.IsValid())S->C->Destroy();auto* C=GetWorld()->SpawnActor<ALWChunk>();S->C=C;LWGen::FSite Site;Site.Position=FVector2D(S->Base);Site.Size=LWPlaces::Size(20);Site.Type=20;Site.Floors=12;Site.AccessibleFloors=Access;Site.Id=200000+Access;Site.Friendly=true;C->Building(P.World,Site);C->SetActorLocation(FVector(0,0,15000));for(auto& A:C->Residents)if(A)A->AddActorWorldOffset(FVector(0,0,15000));
 for(auto& Pair:C->Batches)Check(Pair.Value->GetStaticMesh()!=nullptr,TEXT("tower mesh resolves"));
 auto Floor=[&](float X,float Y,float Z){FHitResult H;FCollisionQueryParams Q;bool Hit=GetWorld()->LineTraceSingleByChannel(H,S->Base+FVector(X,Y,Z+55),S->Base+FVector(X,Y,Z-30),ECC_Visibility,Q);if(!Hit||FMath::Abs(H.ImpactPoint.Z-(S->Base.Z+Z))>=3)UE_LOG(LogTemp,Display,TEXT("URBAN_FLOOR x=%.1f y=%.1f expected=%.2f got=%.2f actor=%s component=%s"),X,Y,S->Base.Z+Z,H.ImpactPoint.Z,*GetNameSafe(H.GetActor()),*GetNameSafe(H.GetComponent()));FHitResult Ceiling;bool Obstructed=GetWorld()->LineTraceSingleByChannel(Ceiling,S->Base+FVector(X,Y,Z+20),S->Base+FVector(X,Y,Z+196),ECC_Visibility,Q);return Hit&&FMath::Abs(H.ImpactPoint.Z-(S->Base.Z+Z))<3&&!Obstructed;};
 for(int F=0;F<Access;F++)Check(Floor(300,0,F*400+18),TEXT("accessible floor has physical walking surface"));
 for(int F=0;F<Access-1;F++)for(int I=0;I<12;I++){Check(Floor(1150,-385+(I+.5f)*30,F*400+18+(I+1)*400.f/24),TEXT("ascending stair tread matches expected rise"));Check(Floor(1580,-25-(I+.5f)*30,F*400+218+(I+1)*400.f/24),TEXT("return stair tread matches expected rise"));}
 int Storage=0,Doors=0;for(auto& A:C->Residents)if(auto* O=Cast<ALWWorldObject>(A)){Storage+=O->Kind==ELWObjectKind::Container;Doors+=O->Kind==ELWObjectKind::Door;}
 Check(Access==0?Storage==0:Storage>=Access*2,TEXT("loot only populates accessible floors"));Check(Access==0?Doors==0:Doors>=Access*2,TEXT("accessible suites have usable doors"));
 LWV2Teleport(P,S->Base+FVector(0,-4500,900));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);P.Controller->SetControlRotation(FRotator(25,90,0));P.World->TimeOfDay=12;P.World->TickWeather(0,&P);
 },[this,Access](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Tower20_%d"),Access));});
 Add(TEXT("tower night interior"),2,[this,S](ALWCharacter& P){LWV2Teleport(P,S->Base+FVector(300,-500,120));P.Controller->SetControlRotation(FRotator(0,130,0));P.World->TimeOfDay=23;P.World->TickWeather(0,&P);S->C->Tick(.5f);Check(S->C->StreetLights.Num()==2,TEXT("tower creates street lamp and neon sign"));Check(S->C->StreetLights[0]->Intensity>0,TEXT("street lights activate at night"));},[this](ALWCharacter&){CaptureV2(TEXT("Tower20_Interior"));});
 Add(TEXT("generated downtown"),4,[this,S](ALWCharacter& P){if(S->C.IsValid())S->C->Destroy();bool Found=false;for(int Y=-4;Y<=4&&!Found;Y++)for(int X=-4;X<=4&&!Found;X++){TArray<LWGen::FRoad> R;TArray<LWGen::FSite> Sites;LWGen::Region({X,Y},P.World->Seed,R,Sites);int Count=0;FVector2D Center(0);for(auto& Site:Sites)if(Site.Type==20){Count++;Center+=Site.Position;}if(Count>=3){Center/=Count;LWV2Teleport(P,FVector(Center+FVector2D(-9500,-14000),3500));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);P.Controller->SetControlRotation(FRotator(-5,55,0));P.World->TimeOfDay=12.f;P.World->Stream(P.GetActorLocation(),true);P.World->TickWeather(0,&P);UE_LOG(LogTemp,Display,TEXT("URBAN20 downtown region %d %d towers=%d"),X,Y,Count);Found=true;}}Check(Found,TEXT("streamable dense city found in live seed"));},[this](ALWCharacter&){CaptureV2(TEXT("Urban20_Downtown"));});
}
