void ALWGameMode::BuildV10Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWEncounterScene> Scene;FName Id;};auto State=MakeShared<FState>();
 Add(TEXT("encounter setup"),.2,[this](ALWCharacter& P){P.NewGame();P.World->EnableEncounters=false;P.Health=10000;P.RPG.Level=20;P.RPG.Attributes.Init(5,7);P.World->TimeOfDay=13;P.World->TickWeather(0,&P);Check(ULWEncounterCatalog::Get()->Events.Num()>=50,TEXT("runtime catalog has fifty or more encounters"));});
 for(const auto& Def:ULWEncounterCatalog::Get()->Events){FName Type=Def.Id;
 Add(TEXT("encounter ")+Def.Title,.15,[this,State,Type](ALWCharacter& P){P.ClosePanels();P.World->ClearEncounterActors();P.Health=10000;P.Money=100000;P.Inventory.Empty();const auto* D=ULWEncounterCatalog::Get()->Find(Type);if(!D)return;if(!D->CostItem.IsNone()){auto Item=LWItems::Make(D->CostItem,D->Cost);LWItems::Place(P.Inventory,Item,12,12);}FVector At(18000,18000,P.World->HeightAt(FVector2D(18000,18000)));
 auto* E=P.World->SpawnEncounter(Type,At);State->Scene=E;if(!RequireV2(E!=nullptr,TEXT("encounter scene spawns")))return;State->Id=E->RecordId;Check(E->Details.Num()>3,TEXT("encounter has a dressed scene"));LWV2Teleport(P,At+FVector(0,-220,105));P.Controller->SetControlRotation(FRotator(-5,90,0));E->Use(&P);Check(P.EncounterSpeaker==E&&P.DialogueChoices.Num()>=3,TEXT("encounter opens branching choices"));Check(E->Choose(&P,0),TEXT("primary choice accepts valid resources"));
 for(ALWZombie* Z:E->Enemies)if(IsValid(Z)&&!Z->bDead){FDamageEvent Hit;Z->TakeDamage(10000,Hit,P.Controller,&P);}E->Snapshot();
 if(D->Task==ELWEncounterTask::Escort&&E->Witness){E->Witness->SetActorLocation(E->Record()->Goal);LWV2Teleport(P,E->Record()->Goal+FVector(0,100,0));}
 E->Record()->Progress=D->WorkSeconds+1;E->Tick(.1f);
 Check(E->Record()->Stage==2&&E->Record()->Rewarded,TEXT("encounter reaches a completed rewarded outcome"));Check(P.World->Containers.Contains(E->RecordId),TEXT("reward stored without requiring free inventory space"));int64 Money=P.Money;int Items=P.World->Containers.FindChecked(E->RecordId).Items.Num();E->Resolve(&P,true,TEXT("duplicate"));Check(P.Money==Money&&P.World->Containers.FindChecked(E->RecordId).Items.Num()==Items,TEXT("encounter reward is idempotent"));Check(P.World->Encounters.Completed.Contains(Type),TEXT("outcome unlocks story history"));
 },[this,Type](ALWCharacter& P){if(Type==TEXT("last_canteen")||Type==TEXT("relay_repair")||Type==TEXT("field_surgery")||Type==TEXT("private_road")||Type==TEXT("roadside_shrine"))CaptureV2(*(TEXT("Scene_")+Type.ToString()));});
 }
 Add(TEXT("persist partial combat and prevent respawn"),.3,[this,State](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();P.Health=10000;FVector At(18000,18000,P.World->HeightAt(FVector2D(18000,18000)));auto* E=P.World->SpawnEncounter(TEXT("caged_scout"),At);State->Id=E->RecordId;LWV2Teleport(P,At+FVector(0,-220,105));E->Use(&P);E->Choose(&P,0);Check(E->Enemies.Num()==3,TEXT("rescue starts with three guards"));FDamageEvent Hit;E->Enemies[0]->TakeDamage(10000,Hit,P.Controller,&P);E->Enemies[1]->Health=37;E->Snapshot();P.SaveProgress();P.LoadProgress();P.World->EnableEncounters=false;P.World->TickEncounters(1,&P);auto* Restored=P.World->LiveEncounters.FindRef(State->Id).Get();Check(Restored&&Restored->LivingEnemies()==2,TEXT("dead guards remain dead after save load"));if(Restored){Check(FMath::IsNearlyEqual(Restored->Enemies[1]->Health,37.f),TEXT("wounded guard health persists"));State->Scene=Restored;}});
 Add(TEXT("resources refusal skill choice and decline"),.2,[this,State](ALWCharacter& P){P.ClosePanels();P.World->ClearEncounterActors();P.Inventory.Empty();auto* E=P.World->SpawnEncounter(TEXT("broken_axle"),P.GetActorLocation()+FVector(0,220,-100));E->Use(&P);Check(!E->Choose(&P,0)&&E->Record()->Stage==0,TEXT("missing repair resources cannot begin"));P.RPG.Attributes[4]=1;Check(!E->Choose(&P,1),TEXT("skill check rejects insufficient intellect"));P.RPG.Attributes[4]=5;Check(E->Choose(&P,1)&&E->Record()->Stage==1,TEXT("skilled repair bypasses materials"));E->Use(&P);Check(E->Choose(&P,1)&&E->Record()->Stage==3,TEXT("active encounter can be abandoned"));State->Scene=E;});
 Add(TEXT("extortion consequences"),.2,[this,State](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();auto* E=P.World->SpawnEncounter(TEXT("last_canteen"),P.GetActorLocation()+FVector(0,220,-100));E->Use(&P);int Before=P.World->Encounters.Reputation;Check(E->Choose(&P,2),TEXT("threatening branch is available"));Check(P.World->Encounters.Reputation==Before-2&&E->LivingEnemies()==2&&!E->Record()->Rewarded,TEXT("extortion provokes guards instead of free supplies"));State->Scene=E;});
 Add(TEXT("escort physically advances and waits"),.2,[this,State](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();FVector At(24000,24000,P.World->HeightAt(FVector2D(24000,24000)));auto* E=P.World->SpawnEncounter(TEXT("lost_surveyor"),At);LWV2Teleport(P,At+FVector(0,-220,105));E->Use(&P);E->Choose(&P,0);auto* N=E->Witness.Get();if(!RequireV2(N!=nullptr,TEXT("escort traveler exists")))return;FVector Before=N->GetActorLocation();for(int I=0;I<20;I++){LWV2Teleport(P,N->GetActorLocation()+FVector(200,0,0));E->Tick(.1f);}Check(FVector::Dist2D(Before,N->GetActorLocation())>60,TEXT("escort walks along its route"));Before=N->GetActorLocation();LWV2Teleport(P,Before+FVector(2000,0,0));E->Tick(1);Check(N->GetActorLocation().Equals(Before,1),TEXT("escort waits when player falls behind"));State->Scene=E;});
 Add(TEXT("director placement and automatic scheduling"),.2,[this](ALWCharacter& P){P.World->ClearEncounterActors();P.World->Encounters=FLWEncounterState();P.ClosePanels();P.Health=10000;P.RPG.Level=10;P.World->EnableEncounters=true;P.bSafehouse=P.bIndoors=false;P.World->TimeOfDay=13;P.World->RainAmount=.7;
 Check(!P.World->EncounterLocation(ALWWorld::BunkerDoorPosition()),TEXT("director protects bunker perimeter"));Check(!P.World->EncounterLocation(FVector(0,2800,0)),TEXT("director rejects active road surface"));
 for(int I=0;I<20&&P.World->Encounters.Records.IsEmpty();I++){FVector At(1400+I*3000,2300,150);LWV2Teleport(P,At);P.World->Stream(At,true);P.Controller->SetControlRotation(FRotator(0,90,0));P.World->Encounters.Elapsed=5000+I*100;P.World->Encounters.NextAttempt=0;P.World->EncounterClock=0;P.World->TickEncounters(1,&P);}
 Check(!P.World->Encounters.Records.IsEmpty(),TEXT("production director schedules a valid roadside encounter"));P.World->EnableEncounters=false;
 });
 Add(TEXT("defense pressure and idle-time guards"),.2,[this](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();auto* E=P.World->SpawnEncounter(TEXT("camp_siege"),P.GetActorLocation()+FVector(0,220,-100));E->Use(&P);E->Choose(&P,0);float Before=E->Record()->Progress;E->Tick(1);Check(E->Record()->Progress>Before&&E->Record()->Stage==1,TEXT("defense clock advances while threats remain"));E->Record()->Integrity=0;E->Tick(.1f);Check(E->Record()->Stage==3&&!E->Record()->Rewarded,TEXT("destroyed defense cannot pay a reward"));double Clock=P.World->Encounters.Elapsed;P.bMenu=true;P.World->TickEncounters(2,&P);Check(P.World->Encounters.Elapsed==Clock,TEXT("menus do not age encounters"));P.bMenu=false;P.World->EnableEncounters=false;});
 Add(TEXT("hazard damage uses timed pulses"),.2,[this](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();P.Health=10000;P.bSafehouse=false;auto* E=P.World->SpawnEncounter(TEXT("chemical_spill"),P.GetActorLocation()+FVector(0,220,-100));E->Record()->Stage=1;LWV2Teleport(P,E->GetActorLocation()+FVector(340,320,100));float Before=P.Health;E->Tick(.01f);float After=P.Health;Check(After<Before,TEXT("entering contamination inflicts damage"));E->Tick(.01f);Check(P.Health==After,TEXT("hazard cannot damage again on next frame"));E->Tick(1.01f);Check(P.Health<After,TEXT("continued exposure damages on one-second pulse"));});
 Add(TEXT("completed scenes stream without rerolling loot"),.2,[this](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();auto* E=P.World->SpawnEncounter(TEXT("courier_return"),P.GetActorLocation()+FVector(0,220,-100));FName Id=E->RecordId;FVector At=E->GetActorLocation();E->Use(&P);E->Choose(&P,0);int Count=P.World->Containers.FindChecked(Id).Items.Num();LWV2Teleport(P,At+FVector(6500,0,150));P.World->EncounterClock=0;P.World->TickEncounters(1,&P);Check(!P.World->LiveEncounters.Contains(Id),TEXT("distant completed scene unloads"));LWV2Teleport(P,At+FVector(0,-220,100));P.World->EncounterClock=0;P.World->TickEncounters(1,&P);Check(P.World->LiveEncounters.Contains(Id)&&P.World->Containers.FindChecked(Id).Items.Num()==Count,TEXT("return restores completed scene with unchanged loot"));});
 Add(TEXT("encounter dialogue presentation"),.6,[this,State](ALWCharacter& P){P.World->ClearEncounterActors();P.ClosePanels();FVector At(18000,18000,P.World->HeightAt(FVector2D(18000,18000)));auto* E=P.World->SpawnEncounter(TEXT("relay_repair"),At);State->Scene=E;State->Id=E->RecordId;E->Record()->Seen=true;LWV2Teleport(P,At+FVector(0,-220,105));E->Use(&P);},[this](ALWCharacter&){CaptureV2(TEXT("EncounterChoices"));});
 Add(TEXT("encounter journal and expiry"),.6,[this,State](ALWCharacter& P){P.ClosePanels();auto* E=State->Scene.Get();if(E){E->Record()->Expires=P.World->Encounters.Elapsed-1;P.World->EncounterClock=0;P.World->TickEncounters(1,&P);Check(E->Record()->Stage==3,TEXT("expired opportunity records missed outcome"));}P.SwitchTab(3);P.EncounterJournal=true;P.JournalPage=0;},[this](ALWCharacter&){CaptureV2(TEXT("RoadJournal"));});
 Add(TEXT("new game clears encounter state"),.2,[this](ALWCharacter& P){P.ClosePanels();P.NewGame();Check(P.World->Encounters.Records.IsEmpty()&&P.World->LiveEncounters.IsEmpty()&&P.World->Encounters.Completed.IsEmpty(),TEXT("new survivor resets all encounter state"));});
}
