void ALWGameMode::BuildV11Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWCardTable> Table;FVector At;};auto State=MakeShared<FState>();
 Add(TEXT("tavern world placement"),.7,[this,State](ALWCharacter& P){
 P.NewGame();P.Health=10000;P.World->EnableEncounters=false;P.World->TimeOfDay=13;P.World->TickWeather(0,&P);
 TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;
 for(int Radius=0;Radius<=5;Radius++){for(int Y=-Radius;Y<=Radius;Y++)for(int X=-Radius;X<=Radius;X++)if(FMath::Max(FMath::Abs(X),FMath::Abs(Y))==Radius)LWGen::Region({X,Y},P.World->Seed,Roads,Sites);if(Sites.ContainsByPredicate([](const auto& S){return S.Type==LWPlaces::Tavern&&S.Id%4!=0;}))break;}
 const auto* Site=Sites.FindByPredicate([](const auto& S){return S.Type==LWPlaces::Tavern&&S.Id%4!=0;});if(!RequireV2(Site!=nullptr,TEXT("generated settlements include a gaming tavern")))return;
 State->At=FVector(Site->Position,140);LWV2Teleport(P,State->At+FVector(0,-600,0));P.World->Stream(P.GetActorLocation(),true);int Count=0;for(TActorIterator<ALWCardTable> T(GetWorld());T;++T){Count++;if(T->Game==0)State->Table=*T;Check(T->Body->GetStaticMesh()!=nullptr,TEXT("table body has mesh"));for(UStaticMeshComponent* Part:T->Details)Check(Part->GetStaticMesh()!=nullptr,TEXT("table detail has mesh"));}Check(Count>=3||Site->Id%4==0,TEXT("gaming tavern has three tables"));P.Controller->SetControlRotation(FRotator(-5,90,0));
 },[this](ALWCharacter&){CaptureV2(TEXT("TavernInterior"));});
 for(int Type=0;Type<3;Type++){
 Add(TEXT("card table ")+FLWCardGame::Title(Type),3.5,[this,State,Type](ALWCharacter& P){P.ClosePanels();P.Cards=FLWCardGame();auto* T=GetWorld()->SpawnActor<ALWCardTable>(State->At+FVector(0,-200,-104),FRotator::ZeroRotator);T->Setup(P.World,FName(*FString::Printf(TEXT("v11_table_%d"),Type)),Type);State->Table=T;LWV2Teleport(P,T->GetActorLocation()+FVector(0,-200,100));P.bSafehouse=false;P.Money=500;T->Use(&P);P.CardBusyUntil=0;Check(P.RPGPanel==5&&P.CardTable==T,TEXT("table opens unified card screen"));P.CardAction(TEXT("start"),20);Check(P.Cards.Game==Type&&P.Cards.Stake==20,TEXT("requested game starts"));Check(P.Money==480+P.Cards.Payout,TEXT("stake and any natural payout applied exactly once"));},[this,Type](ALWCharacter&){CaptureV2(*FLWCardGame::Title(Type));});
 Add(TEXT("resume and forfeit ")+FLWCardGame::Title(Type),.3,[this,State,Type](ALWCharacter& P){auto Copy=P.Cards;int64 Cash=P.Money;P.ClosePanels();P.SaveProgress();P.LoadProgress();P.World->EnableEncounters=false;Check(P.Cards.Deck==Copy.Deck&&P.Cards.Phase==Copy.Phase&&P.Money==Cash,TEXT("hands phase deck and credits survive real save load"));auto* T=State->Table.Get();if(!T)return;LWV2Teleport(P,T->GetActorLocation()+FVector(0,-200,100));T->Use(&P);P.CardBusyUntil=0;if(P.Cards.Active()){P.CardAction(TEXT("forfeit"));Check(P.Money==Cash&&P.Cards.Paid&&P.Cards.Payout==0,TEXT("forfeit loses existing stake with no second charge"));}int64 Final=P.Money;P.CardAction(TEXT("forfeit"));Check(P.Money==Final,TEXT("repeated forfeit cannot change balance"));P.ClosePanels();T->Destroy();});
 }
 Add(TEXT("money guards and blackjack settlement"),.5,[this,State](ALWCharacter& P){auto* T=GetWorld()->SpawnActor<ALWCardTable>(State->At+FVector(0,-200,-104),FRotator::ZeroRotator);T->Setup(P.World,TEXT("v11_economy"),0);State->Table=T;P.Cards=FLWCardGame();LWV2Teleport(P,T->GetActorLocation()+FVector(0,-200,100));T->Use(&P);P.CardBusyUntil=0;P.Money=5;P.CardAction(TEXT("start"),20);Check(!P.Cards.Active()&&P.Money==5,TEXT("unaffordable wager rejected"));P.Money=100;P.CardAction(TEXT("start"),20);P.Cards.Phase=TEXT("play");P.Cards.Paid=false;P.Cards.Payout=0;P.Cards.Hands[0].Cards={8,7};P.Cards.Hands[1].Cards={8,5};P.Cards.Deck={0};int64 Before=P.Money;P.CardBusyUntil=0;P.CardAction(TEXT("stand"));for(int I=0;I<20&&P.Cards.AutoTurn();I++){P.CardBusyUntil=0;P.CardAction(TEXT("tick"));}Check(P.Money==Before+40&&P.Cards.Paid,TEXT("winning blackjack pays exactly 1:1 plus returned stake"));P.CardBusyUntil=0;P.CardAction(TEXT("stand"));for(int I=0;I<20&&P.Cards.AutoTurn();I++){P.CardBusyUntil=0;P.CardAction(TEXT("tick"));}Check(P.Money==Before+40,TEXT("duplicate action cannot repay"));},[this](ALWCharacter&){CaptureV2(TEXT("BlackjackResult"));});
 Add(TEXT("rules screen"),.6,[](ALWCharacter& P){P.CardAction(TEXT("rules"));},[this](ALWCharacter&){CaptureV2(TEXT("TableRules"));});
 Add(TEXT("runtime playlist playback"),.4,[this](ALWCharacter& P){auto* C=ULWAudioCatalog::GetDefaultCatalog();if(!RequireV2(C!=nullptr,TEXT("audio catalog present")))return;auto Old=C->Slots.FindChecked(TEXT("CombatMusic"));auto& Slot=C->Slots.FindChecked(TEXT("CombatMusic"));Slot.Tracks={TSoftObjectPtr<USoundBase>(FSoftObjectPath(TEXT("/Game/Audio/S_MenuMusic.S_MenuMusic"))),TSoftObjectPtr<USoundBase>(FSoftObjectPath(TEXT("/Game/Audio/S_CombatMusic.S_CombatMusic")))};for(int I=0;I<6;I++){auto* A=P.World->Sound(TEXT("CombatMusic"),P.GetActorLocation(),.1f);Check(A&&A->IsPlaying()&&!A->bAllowSpatialization,TEXT("playlist track starts as 2D music"));if(A)A->Stop();}Slot=Old;});
 Add(TEXT("death and new game clear wagers"),.2,[this,State](ALWCharacter& P){P.ClosePanels();P.Cards=FLWCardGame();P.Cards.Start(1,20,15);P.Health=0;P.bDeadSaved=false;P.HandleDeath();Check(!P.Cards.Active(),TEXT("death forfeits hand"));P.NewGame();P.World->EnableEncounters=false;Check(!P.Cards.Active(),TEXT("new game clears cards"));if(State->Table.IsValid())State->Table->Destroy();});
}
