void ALWGameMode::BuildV16Smoke(ALWCharacter& Player){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 Add(TEXT("alpha menu"),2,[](ALWCharacter& P){P.bStarted=false;P.bMenu=true;},[this](ALWCharacter&){Check(LoadObject<UTexture2D>(nullptr,TEXT("/Game/Art/Textures/T_AllAmericanMeltdownAlpha"))!=nullptr,TEXT("alpha logo imported"));CaptureV2(TEXT("Menu16"));});
 Add(TEXT("female creator"),2,[this](ALWCharacter& P){P.BeginWorldSetup();P.WorldSetupClick(TEXT("createworld"));P.OpeningClick(TEXT("intro_skip"));P.OpeningClick(TEXT("body"));P.DraftIdentity.Hair=8;P.OpeningClick(TEXT("height_up"));P.OpeningClick(TEXT("weight_down"));P.OpeningClick(TEXT("rotate"));Check(P.DraftIdentity.Body==1&&P.DraftIdentity.Height>.5f&&P.DraftIdentity.Weight<.5f,TEXT("body and independent morph controls respond"));for(int I=0;I<10;I++)Check(P.World->Mesh(FName(*FString::Printf(TEXT("Hair%02dV16"),I)))!=nullptr,TEXT("hairstyle geometry imported"));},[this](ALWCharacter&){CaptureV2(TEXT("CreatorFemale16"));});
 Add(TEXT("male creator"),2,[](ALWCharacter& P){P.OpeningClick(TEXT("body"));P.DraftIdentity.Hair=2;P.PortraitYaw=0;P.OpeningClick(TEXT("shoulders_up"));},[this](ALWCharacter&){CaptureV2(TEXT("CreatorMale16"));});
 Add(TEXT("bunker and six AM"),1,[this](ALWCharacter& P){P.OpeningClick(TEXT("creator_done"));Check(P.bSafehouse&&P.World->TimeOfDay>=6&&P.World->TimeOfDay<6.01,TEXT("created survivor starts in bunker at six AM"));P.SaveProgress();float H=P.Identity.Height;P.Identity.Height=0;P.LoadProgress();Check(FMath::IsNearlyEqual(P.Identity.Height,H)&&P.Identity.Hair==2,TEXT("morphs and hairstyle survive save/load"));Check(P.SurvivorParts.Num()==7,TEXT("first person survivor body constructed"));int Bedrooms=0,Lockers=0;for(AActor* A:P.World->BunkerParts)if(auto* O=Cast<ALWWorldObject>(A)){if(O->RecordId.ToString().StartsWith(TEXT("bedroom_door_")))Bedrooms++;if(O->UseType==TEXT("locker"))Lockers++;if(O->Kind==ELWObjectKind::Container)Check(P.World->Containers.Contains(O->RecordId),TEXT("bunker storage furniture retains an accessible saved inventory"));if(O->Kind==ELWObjectKind::Stash){Check(O->GetActorLocation().Y<500,TEXT("stash moved out of corridor into storeroom"));Check(O->Body->GetStaticMesh()->GetName()==TEXT("SM_LockerV4"),TEXT("stash uses locker model"));}if(O->Kind==ELWObjectKind::BunkerExit)Check(FMath::Abs(O->GetActorLocation().X+3585+22.1)<.2,TEXT("hatch casing meets inside wall plane"));}Check(Bedrooms==10&&Lockers>=24,TEXT("all crew rooms and locker row exist"));},[this](ALWCharacter&){CaptureV2(TEXT("BunkerHall16"));});
 Add(TEXT("hatch recess"),1.5,[](ALWCharacter& P){LWV2Teleport(P,FVector(-3300,1700,-1870));P.Controller->SetControlRotation(FRotator(-5,180,0));},[this](ALWCharacter&){CaptureV2(TEXT("Hatch16"));});
 for(int I=0;I<5;I++)Add(FString::Printf(TEXT("bunker room %d"),I),1.5,[I](ALWCharacter& P){const FVector Pos[]={FVector(-1200,-360,140),FVector(1630,-1120,140),FVector(-1650,-1120,140),FVector(1650,1120,140),FVector(-1650,1120,140)};LWV2Teleport(P,FVector(-1700,1700,-2000)+Pos[I]);P.Controller->SetControlRotation(FRotator(-12,I==0?-90:I%2?180:0,0));},[this,I](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Room16_%d"),I));});
 for(int Hour:{6,12,0})Add(FString::Printf(TEXT("sky hour %d"),Hour),1.5,[this,Hour](ALWCharacter& P){if(P.bSafehouse)P.LeaveSafehouse();P.World->TimeOfDay=Hour;if(Hour==0){for(int Day=1;Day<40;Day++)if(LWGen::Hash((Day-1)*8,0,P.World->Seed,8181)%100<28){P.World->DayNumber=Day;break;}P.World->TimeOfDay=.4f;}P.World->TickWeather(0,&P);if(Hour==12)Check(P.World->SunLight->GetLightComponent()->Intensity>=3,TEXT("daylight sun has full daytime intensity"));if(Hour==0)Check(P.World->MoonLight->GetLightComponent()->Intensity<.06f,TEXT("moon lighting remains subtle"));P.Controller->SetControlRotation(Hour==0&&P.World->MoonDisc?(P.World->MoonDisc->GetComponentLocation()-P.Camera->GetComponentLocation()).Rotation():FRotator(5,0,0));},[this,Hour](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Sky16_%d"),Hour));});
 Add(TEXT("settlement defends against enemy"),.1,[this](ALWCharacter& P){
 FVector At(12000,12000,6000);auto* Guard=GetWorld()->SpawnActor<ALWResident>(At,FRotator::ZeroRotator);Guard->ConfigureResident(TEXT("defender"),TEXT("warden"),TEXT("DEFENDER"),0);Guard->SettlementId=TEXT("defense_test");Guard->SetActorTickEnabled(false);Guard->GetCharacterMovement()->DisableMovement();auto* Enemy=GetWorld()->SpawnActor<ALWZombie>(At+FVector(500,0,0),FRotator::ZeroRotator);Enemy->SetActorTickEnabled(false);Enemy->GetCharacterMovement()->DisableMovement();float Before=Enemy->Health;Check(Guard->DefendSettlement(&P)&&Enemy->Health<Before,TEXT("friendly resident acquires and damages nearby enemy"));Check(!Guard->IsTownHostile(),TEXT("defending town does not aggro player"));Guard->Destroy();Enemy->Destroy();
 });
 Add(TEXT("crew markers and XP"),1,[this](ALWCharacter& P){P.World->TimeOfDay=12;P.RPG.XP=50;P.RPG.Level=1;auto* N=GetWorld()->SpawnActor<ALWResident>(P.GetActorLocation()+FVector(1400,1800,0),FRotator::ZeroRotator);N->ConfigureResident(TEXT("marker_test"),TEXT("recruit"),TEXT("ASH"),0);N->SetActorTickEnabled(false);N->GetCharacterMovement()->DisableMovement();FLWCrewRecord R;R.Id=N->ResidentId;R.Name=TEXT("ASH");R.Following=true;P.RPG.Crew.Add(R);Check(P.RPG.Crew.Last().Following,TEXT("active companion available to map"));},[this](ALWCharacter& P){CaptureV2(TEXT("CrewXP16"));});
 Add(TEXT("town alert scope"),.5,[this](ALWCharacter& P){for(TActorIterator<ALWResident> It(GetWorld());It;++It)if(It->ResidentId==TEXT("marker_test"))It->Destroy();P.RPG.Crew.RemoveAll([](const auto& R){return R.Id==TEXT("marker_test");});P.World->TimeOfDay=12;FVector A=P.GetActorLocation()+FVector(300,0,0);auto* N=GetWorld()->SpawnActor<ALWResident>(A,FRotator::ZeroRotator);N->ConfigureResident(TEXT("test_guard"),TEXT("warden"),TEXT("GUARD"),0);N->SettlementId=TEXT("test_town");auto* Friend=GetWorld()->SpawnActor<ALWResident>(A+FVector(0,300,0),FRotator::ZeroRotator);Friend->ConfigureResident(TEXT("test_citizen"),TEXT("civilian"),TEXT("CITIZEN"),1);Friend->SettlementId=N->SettlementId;auto* Other=GetWorld()->SpawnActor<ALWResident>(A+FVector(0,600,0),FRotator::ZeroRotator);Other->ConfigureResident(TEXT("other"),TEXT("warden"),TEXT("OTHER"),0);Other->SettlementId=TEXT("other_town");N->TakeDamage(1,FDamageEvent(),P.Controller,&P);Check(N->IsTownHostile()&&Friend->IsTownHostile()&&!Other->IsTownHostile(),TEXT("player attack alerts whole town but not other settlements"));P.Talk(N);Check(P.Speaker==nullptr,TEXT("hostile settlement does not offer dialogue services"));P.SaveProgress();auto* Saved=Cast<ULWSaveGame>(UGameplayStatics::LoadGameFromSlot(TEXT("AllAmericanMeltdown_AutomationV16"),0));Check(Saved&&Saved->PropStates.FindRef(TEXT("test_town"))==1,TEXT("town hostility persists"));N->Destroy();Friend->Destroy();Other->Destroy();});
 Add(TEXT("long motorhome"),2,[this](ALWCharacter& P){FVector A(-7000,8500,0);P.World->Stream(A,true);FLWVehicleRecord R;R.Model=TEXT("rv");R.Position=FVector(A.X,A.Y,P.World->HeightAt(FVector2D(A))+75);R.Unlocked=true;R.Hotwired=true;P.World->Vehicles.Add(TEXT("rv16test"),R);auto* V=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("rv16test"),R.Position));Check(V&&V->Spec().Seats==5&&V->Spec().HalfLength>600,TEXT("twelve metre coach retains five seats"));if(V){Check(V->Wheels.Num()==6,TEXT("coach has three axles"));Check(V->Body->GetStaticMesh()->GetName()==TEXT("SM_CamperShellV17"),TEXT("new coach shell used"));LWV2Teleport(P,V->GetActorLocation()+FVector(1200,-1500,140));P.Controller->SetControlRotation((V->GetActorLocation()+FVector(0,0,120)-P.Camera->GetComponentLocation()).Rotation());}},[this](ALWCharacter&){CaptureV2(TEXT("Motorhome16"));});
 Add(TEXT("coach live-in cabin"),2,[this](ALWCharacter& P){for(TActorIterator<ALWVehicle> It(GetWorld());It;++It)if(It->RecordId==TEXT("rv16test")){LWV2Teleport(P,It->GetActorLocation()+FVector(0,-210,20));Check(It->Enter(&P,-1),TEXT("driver can board new coach"));Check(It->PlayerEye().X>LWTraffic::FrontOffset(It->Spec()),TEXT("camera sits in front cab"));It->StandInCamper();Check(It->PlayerSeat==-2,TEXT("walking cabin remains available"));It->CabinEye=FVector(LWTraffic::FrontOffset(It->Spec())-400,0,150);P.SeatYaw=180;P.SeatPitch=-10;P.TickVehicleSeat();break;}},[this](ALWCharacter&){CaptureV2(TEXT("CamperInterior16"));});
 Add(TEXT("restore and pause"),.5,[](ALWCharacter& P){if(P.Vehicle)P.Vehicle->Exit(true);P.EnterSafehouse();P.ToggleMenu();},[this](ALWCharacter&){CaptureV2(TEXT("Pause16"));});
}
