#include "LWOpening.h"
#include "Engine/Texture2D.h"
void ALWGameMode::BuildV15Smoke(ALWCharacter& P){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 Add(TEXT("main menu branding"),1,[](ALWCharacter& P){P.bStarted=false;P.bMenu=true;P.SetMenuInput(true);},[this](ALWCharacter&){Check(LoadObject<UTexture2D>(nullptr,TEXT("/Game/Art/Textures/T_AllAmericanMeltdown"))!=nullptr,TEXT("title logo imported"));CaptureV2(TEXT("MainMenu15"));});
 Add(TEXT("begin prologue without mutating save"),.5,[this](ALWCharacter& P){P.NewGame();P.Identity.Name=TEXT("EXISTING");P.SaveProgress();P.BeginWorldSetup();P.SeedText=TEXT("2030");P.WorldSetupClick(TEXT("createworld"));Check(P.OpeningMode==1&&P.OpeningScene,TEXT("new world enters prologue"));Check(P.Identity.Name==TEXT("EXISTING"),TEXT("existing survivor untouched during opening"));Check(P.World->Seed!=2030,TEXT("world settings remain staged"));});
 for(int I=0;I<9;I++)Add(FString::Printf(TEXT("cinematic shot %d"),I),.65,[this,I](ALWCharacter& P){P.OpeningShot=I;P.OpeningSince=GetWorld()->GetRealTimeSeconds()-3;P.OpeningScene->Stage(I);P.UpdateOpening();Check(P.OpeningScene->Pieces.Num()>10,TEXT("shot contains authored 3D scenery"));Check(IsValid(P.OpeningScene->Audio),TEXT("shot resolves audio cue"));},[this,I](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Prologue%02d"),I));});
 Add(TEXT("intro pause and natural completion"),8,[this](ALWCharacter& P){P.OpeningClick(TEXT("intro_pause"));double Age=P.OpeningSince;P.UpdateOpening();Check(P.OpeningPaused&&P.OpeningSince==Age,TEXT("pause freezes cinematic time"));P.OpeningClick(TEXT("intro_pause"));P.OpeningSince=GetWorld()->GetRealTimeSeconds()-19;P.UpdateOpening();Check(P.OpeningMode==2,TEXT("final shot transitions to creator"));},[this](ALWCharacter&){CaptureV2(TEXT("Creator15"));});
 Add(TEXT("creator keyboard name input"),.5,[](ALWCharacter& P){P.DraftIdentity.Name.Empty();P.NameEditing=true;Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::A,IE_Pressed,1.));},[this](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::A,IE_Released,0.));Check(P.DraftIdentity.Name==TEXT("A"),TEXT("creator accepts real keyboard name input while paused"));P.Interact();Check(!P.NameEditing&&P.OpeningMode==2,TEXT("enter finishes name without committing survivor"));});
 Add(TEXT("creator budget and appearance"),2,[this](ALWCharacter& P){Check(LWOpening::ValidAllocation(P.StartingAttributes),TEXT("default allocation uses 28 points"));P.OpeningClick(TEXT("minus_0"));P.OpeningClick(TEXT("creator_done"));Check(P.OpeningMode==2,TEXT("unspent budget cannot commit"));P.OpeningClick(TEXT("plus_1"));Check(P.StartingAttributes[0]==3&&P.StartingAttributes[1]==5,TEXT("points redistributed between categories"));for(int I=0;I<20;I++)P.OpeningClick(TEXT("minus_0"));Check(P.StartingAttributes[0]==1,TEXT("category minimum enforced"));P.OpeningClick(TEXT("reset_points"));for(int I=0;I<20;I++)P.OpeningClick(TEXT("plus_0"));Check(P.StartingAttributes[0]==4,TEXT("cannot overspend points"));P.DraftIdentity.Name=TEXT("ROWAN");P.OpeningClick(TEXT("skin"));P.OpeningClick(TEXT("hair"));P.OpeningClick(TEXT("outfit"));P.OpeningClick(TEXT("rotate"));},[this](ALWCharacter&){CaptureV2(TEXT("CreatorCustomized15"));});
 Add(TEXT("cancel is nondestructive"),.5,[this](ALWCharacter& P){P.OpeningClick(TEXT("creator_back"));Check(P.bWorldSetup&&P.OpeningMode==0&&!P.OpeningScene,TEXT("back cleans cinematic and returns to setup"));Check(P.Identity.Name==TEXT("EXISTING"),TEXT("cancel preserves old survivor"));P.WorldSetupClick(TEXT("createworld"));P.OpeningClick(TEXT("intro_skip"));Check(P.OpeningMode==2,TEXT("skip still opens creator"));P.DraftIdentity.Name=TEXT("ROWAN");P.DraftIdentity.Skin=4;P.DraftIdentity.Outfit=2;P.OpeningClick(TEXT("minus_0"));P.OpeningClick(TEXT("plus_1"));P.OpeningClick(TEXT("creator_done"));Check(P.bStarted&&!P.bMenu&&P.bSafehouse,TEXT("new survivor starts safely inside bunker"));Check(FVector::Dist(P.GetActorLocation(),ALWWorld::BunkerSpawn())<10,TEXT("spawn is bunker interior"));Check(P.World->Seed==2030,TEXT("chosen map seed committed"));Check(!P.OpeningScene&&P.OpeningMode==0,TEXT("cinematic resources cleaned"));Check(P.Identity.Name==TEXT("ROWAN")&&P.RPG.Attributes[1]==5,TEXT("identity and assigned categories applied"));},[this](ALWCharacter&){CaptureV2(TEXT("BunkerHUD15"));});
 Add(TEXT("identity save and continue"),.5,[this](ALWCharacter& P){P.SaveProgress();P.Identity.Name=TEXT("TEMP");P.Identity.Skin=0;P.RPG.Attributes.Init(1,7);P.LoadProgress();Check(P.Identity.Name==TEXT("ROWAN")&&P.Identity.Skin==4&&P.Identity.Outfit==2,TEXT("appearance and name persist"));Check(P.RPG.Attributes[0]==3&&P.RPG.Attributes[1]==5,TEXT("starting categories persist"));Check(P.bSafehouse&&P.OpeningMode==0,TEXT("continue skips creator and stays in bunker"));P.ToggleMenu();},[this](ALWCharacter&){CaptureV2(TEXT("PauseMenu15"));});
 Add(TEXT("resume compact combat HUD"),.6,[this](ALWCharacter& P){P.ToggleMenu();P.LeaveSafehouse();P.GiveItem(TEXT("rifle"));for(auto& I:P.Inventory)if(I.Definition==TEXT("rifle")){I.Slot=TEXT("Primary");P.ActiveWeaponId=I.Id;break;}P.Equip(6);P.SetWaypoint(FVector2D(P.GetActorLocation())+FVector2D(1400,500));},[this](ALWCharacter&){CaptureV2(TEXT("CompactHUD15"));});
}
