void ALWGameMode::BuildV14Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWResident> NPC;FVector Start;FGuid Gun;};auto S=MakeShared<FState>();
 Add(TEXT("V14 setup"),1,[this,S](ALWCharacter& P){P.NewGame();P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.World->TickWeather(0,&P);P.Health=10000;P.bSafehouse=false;LWV2Teleport(P,FVector(0,3000,130));P.World->Stream(P.GetActorLocation(),true);});
 Add(TEXT("weapon attachments and rarity"),3,[this,S](ALWCharacter& P){P.Inventory.Empty();auto G=LWItems::Make(TEXT("rifle"));G.Slot=TEXT("Primary");G.WeaponTier=3;G.Attachments.Add(TEXT("Optic"),TEXT("att_scope4"));G.Attachments.Add(TEXT("Light"),TEXT("att_light"));G.Attachments.Add(TEXT("Laser"),TEXT("att_laser"));G.Attachments.Add(TEXT("Grip"),TEXT("att_vertical"));P.Inventory.Add(G);S->Gun=G.Id;P.ActiveWeaponId=G.Id;P.Equip(6);Check(P.AttachmentParts.Num()==4,TEXT("four visible mounted components"));for(UStaticMeshComponent* C:P.AttachmentParts)Check(C&&C->GetStaticMesh()&&C->GetAttachParent()==P.WeaponMesh,TEXT("attachment mesh exists and follows gun"));Check(P.GunLight&&P.LaserDot,TEXT("working mounted light and laser components"));P.Controller->SetControlRotation(FRotator(0,0,0));},[this](ALWCharacter&){CaptureV2(TEXT("RifleAttachmentsV14"));});
 Add(TEXT("scope"),.5,[](ALWCharacter& P){P.bAim=true;},[this](ALWCharacter&){CaptureV2(TEXT("ScopeV14"));});
 Add(TEXT("save payload"),.3,[this,S](ALWCharacter& P){P.bAim=false;P.SaveProgress();P.LoadProgress();P.World->EnableEncounters=false;const auto* G=P.FindItem(S->Gun);Check(G&&G->WeaponTier==3&&G->Attachments.Num()==4,TEXT("save reload preserves rarity and mounts"));});
 Add(TEXT("RV model and cabin"),1,[this,S](ALWCharacter& P){P.ClosePanels();P.bSafehouse=false;LWV2Teleport(P,FVector(0,3000,130));FName Id(TEXT("v14_camper"));FLWVehicleRecord R;R.Model=TEXT("rv");R.VIN=FGuid::NewGuid();R.Position=FVector(0,3600,P.World->HeightAt(FVector2D(0,3600))+75);R.Unlocked=R.Hotwired=true;P.World->Vehicles.Add(Id,R);auto* C=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,R.Position));S->Car=C;if(!RequireV2(C!=nullptr,TEXT("RV spawned")))return;Check(C->Spec().Seats==5,TEXT("RV five seats"));Check(C->Body->GetStaticMesh()==P.World->Mesh(TEXT("CamperShellV17")),TEXT("RV uses new shell"));int Seats=0;TSet<FName> Controls;for(UStaticMeshComponent* M:C->Details){if(M->GetStaticMesh()==P.World->Mesh(TEXT("CamperSeatV14")))Seats++;for(auto Tag:M->ComponentTags)Controls.Add(Tag);}Check(Seats==5,TEXT("driver chair plus four camper passenger chairs"));for(FName Tag:{FName(TEXT("bed")),FName(TEXT("cooker")),FName(TEXT("sink")),FName(TEXT("fridge")),FName(TEXT("pantry")),FName(TEXT("wardrobe"))})Check(Controls.Contains(Tag),TEXT("habitation fixture interactable"));LWV2Teleport(P,R.Position+FVector(550,-820,130));P.Controller->SetControlRotation((R.Position+FVector(0,0,100)-P.Camera->GetComponentLocation()).Rotation());},[this](ALWCharacter&){CaptureV2(TEXT("CamperExteriorV14"));});
 Add(TEXT("RV habitation"),.6,[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;LWV2Teleport(P,C->GetActorLocation()+FVector(0,-280,100));Check(C->Enter(&P,3),TEXT("enter rear passenger seat"));C->StandInCamper();Check(C->PlayerSeat==-2,TEXT("player stands in RV aisle"));P.SeatYaw=175;P.SeatPitch=-15;P.GiveItem(TEXT("food"),2);P.Hunger=30;C->Control(TEXT("cooker"));Check(P.Hunger==100,TEXT("RV cooker consumes food"));P.Thirst=20;C->Control(TEXT("sink"));Check(P.Thirst==100,TEXT("RV sink provides water"));float Before=P.World->TimeOfDay;C->Control(TEXT("bed"));P.ChooseDialogue(0);Check(P.World->TimeOfDay!=Before,TEXT("RV bed skips time"));C->Control(TEXT("fridge"));Check(P.bInventory&&P.OpenObject,TEXT("RV fridge opens storage"));P.ClosePanels();C->Control(TEXT("cargo"));Check(P.OpenObject&&P.OpenObject->RecordId==C->RecordId,TEXT("cargo access does not reuse fridge inventory"));P.ClosePanels();P.World->TimeOfDay=12;P.World->TickWeather(0,&P);},[this](ALWCharacter&){CaptureV2(TEXT("CamperInteriorV14"));});
 Add(TEXT("walk camper and reach bed"),.5,[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;FVector Before=C->CabinEye;P.SeatYaw=180;C->CabinMove=FVector2D(1,0);for(int I=0;I<80;I++)C->TickCabinWalk(.05f);C->CabinMove=FVector2D::ZeroVector;P.TickVehicleSeat();Check(FVector::Dist(Before,C->CabinEye)>50,TEXT("player walks the cabin aisle"));Check(C->CabinEye.X>LWTraffic::FrontOffset(C->Spec())-835,TEXT("bed stops walking capsule"));FVector Bed=C->GetActorTransform().TransformPosition(FVector(LWTraffic::FrontOffset(C->Spec())-892,0,50));FRotator Look=(Bed-P.Camera->GetComponentLocation()).Rotation();P.SeatYaw=Look.Yaw-C->GetActorRotation().Yaw;P.SeatPitch=Look.Pitch;P.TickVehicleSeat();},[this,S](ALWCharacter& P){if(S->Car.IsValid()){Check(S->Car->FocusControl()==TEXT("bed"),TEXT("bed reachable through first-person interaction trace"));CaptureV2(TEXT("CamperLivingV14"));}});
 Add(TEXT("boarding and chauffeur"),1,[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;C->ChangeSeat(3);P.SeatYaw=P.SeatPitch=0;P.SetWaypoint(FVector2D(C->GetActorLocation())+FVector2D(4000,0));auto* N=GetWorld()->SpawnActor<ALWResident>(C->GetActorLocation()+FVector(0,-260,100),FRotator::ZeroRotator);S->NPC=N;N->ConfigureResident(TEXT("v14_crew"),TEXT("recruit"),TEXT("MORGAN"),0);FLWCrewRecord Crew;Crew.Id=N->ResidentId;Crew.Following=true;P.RPG.Crew.Add(Crew);Check(C->Board(N),TEXT("companion enters driver seat"));Check(C->Chauffeur==N&&N->SeatIndex==-1,TEXT("driver seat ownership"));S->Start=C->GetActorLocation();},[this,S](ALWCharacter& P){if(S->Car.IsValid()){Check(S->Car->AutoDriving,TEXT("driver starts after boarding"));CaptureV2(TEXT("CompanionDriverV14"));}});
 Add(TEXT("chauffeur moves"),5,[](ALWCharacter& P){},[this,S](ALWCharacter& P){if(S->Car.IsValid()){Check(FVector::Dist2D(S->Start,S->Car->GetActorLocation())>100,TEXT("chauffeur moves vehicle"));S->Car->RequestDriverStop();}});
 Add(TEXT("controlled stop and exit"),4,[](ALWCharacter& P){},[this,S](ALWCharacter& P){auto* C=S->Car.Get();if(!C)return;Check(FMath::Abs(C->Speed)<5&&!C->Chauffeur&&!C->AutoDriving,TEXT("F request stops and disembarks driver"));Check(P.Vehicle==C,TEXT("player remains in passenger seat"));C->Exit(true);if(S->NPC.IsValid())S->NPC->Destroy();C->Destroy();P.RPG.Crew.Empty();});
 Add(TEXT("all vehicle seat layouts"),.2,[this](ALWCharacter& P){
 P.ClearWaypoint();LWV2Teleport(P,FVector(20000,20000,5115));auto* Floor=GetWorld()->SpawnActor<ALWChunk>();Floor->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(6000,6000,20));
 for(const auto& Spec:LWTraffic::Specs()){FName Id(*(TEXT("v14_seats_")+FString(Spec.Id)));FLWVehicleRecord R;R.Model=Spec.Id;R.VIN=FGuid::NewGuid();R.Unlocked=R.Hotwired=true;R.Position=FVector(20000,20000,5075);P.World->Vehicles.Add(Id,R);auto* C=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,R.Position));if(!RequireV2(C!=nullptr,TEXT("seat fixture car spawned")))return;
 TArray<FVector> Eyes;for(int Seat=-1;Seat<Spec.Seats-1;Seat++){LWV2Teleport(P,R.Position+FVector(0,-300,80));Check(C->Enter(&P,Seat),TEXT("player can enter every seat"));Check(C->PlayerSeat==Seat,TEXT("selected seat owned by player"));FVector Eye=C->PlayerEye();for(FVector Previous:Eyes)Check(FVector::Dist(Previous,Eye)>25,TEXT("seated cameras do not overlap"));Eyes.Add(Eye);C->Exit(true);}C->Destroy();}
 Floor->Destroy();
 });
 Add(TEXT("random interior enemy placement"),.2,[this](ALWCharacter& P){
 LWV2Teleport(P,FVector(26000,26000,140));auto* C=GetWorld()->SpawnActor<ALWChunk>();LWGen::FSite Site;Site.Id=1450900;Site.Position=FVector2D(20000,20000);Site.Type=13;Site.Size=FVector2D(4000,3000);
 C->Box(P.World,TEXT("Concrete"),FVector(Site.Position,24),FVector(4000,3000,24));
 auto* Saved=P.World->SpawnTable.Get();P.World->SpawnTable=NewObject<ULWSpawnTable>(P.World);auto& Row=P.World->SpawnTable->POIs[13];Row.MinCount=Row.MaxCount=4;Row.IndoorChance=1;Row.RaiderWeight=Row.DogWeight=Row.MooseWeight=Row.TitanWeight=Row.DeathclawWeight=Row.ScorpionWeight=Row.KarenWeight=0;Row.ZombieWeight=1;P.World->SpawnTable->MaxAlive=150;
 P.World->SpawnEnemies(C,&Site,Site.Size);int Count=0;for(auto& A:C->Residents)if(auto* Z=Cast<ALWZombie>(A)){Count++;Check(Z->Kind==ELWEnemyKind::Zombie,TEXT("per-POI enemy weights obeyed"));Check(FMath::Abs(Z->GetActorLocation().X-20000)<1900&&FMath::Abs(Z->GetActorLocation().Y-20000)<1400,TEXT("random enemy is inside POI bounds"));P.World->KilledZombies.Add(Z->PersistentId);}Check(Count==4,TEXT("interior table spawns requested population"));C->Destroy();
 auto* Retry=GetWorld()->SpawnActor<ALWChunk>();P.World->SpawnEnemies(Retry,&Site,Site.Size);Check(Retry->Residents.IsEmpty(),TEXT("killed population cannot respawn on chunk reload"));Retry->Destroy();P.World->SpawnTable=Saved;
 });
 Add(TEXT("road waypoint arrival"),.2,[this](ALWCharacter& P){
 P.RPG.Crew.Empty();P.ClosePanels();LWV2Teleport(P,FVector(0,3000,140));P.World->Stream(P.GetActorLocation(),true);TArray<LWGen::FRoad> Roads;TArray<LWGen::FSite> Sites;LWGen::Gather(FVector2D::ZeroVector,P.World->Seed,Roads,Sites);
 const auto* Road=Roads.FindByPredicate([](const auto& R){return R.Width>=780&&(R.B-R.A).Size()>3200&&R.A.Size()<22000;});if(!RequireV2(Road!=nullptr,TEXT("long road fixture available")))return;
 FVector2D D=(Road->B-Road->A).GetSafeNormal(),Start=Road->A+D*750,Goal=Road->B-D*600;LWV2Teleport(P,FVector(Start,150));P.World->Stream(P.GetActorLocation(),true);
 FName Id(TEXT("v14_arrival"));FLWVehicleRecord R;R.Model=TEXT("sedan");R.VIN=FGuid::NewGuid();R.Unlocked=R.Hotwired=true;R.Position=FVector(Start,75);R.Rotation=FVector(D,0).Rotation();P.World->Vehicles.Add(Id,R);
 auto* C=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,R.Position));if(!RequireV2(C!=nullptr,TEXT("arrival car spawned")))return;
 // Remove only parked obstacles in this test lane so arrival tests steering, not a random wreck.
 for(TActorIterator<ALWVehicle> It(GetWorld());It;++It)if(*It!=C&&FVector2D::Distance(FVector2D(It->GetActorLocation()),Start)<5000)It->Destroy();
 P.SetWaypoint(Goal);Check(C->Enter(&P,0),TEXT("arrival player passenger"));auto* N=GetWorld()->SpawnActor<ALWResident>(R.Position+FVector(0,250,100),R.Rotation);N->ConfigureResident(TEXT("v14_driver_route"),TEXT("recruit"),TEXT("MORGAN"),0);FLWCrewRecord Crew;Crew.Id=N->ResidentId;Crew.Following=true;P.RPG.Crew.Add(Crew);C->Board(N);
 for(int I=0;I<2400&&(!C->DriverDismissed||C->Chauffeur);I++){C->Tick(.05f);P.TickVehicleSeat();}
 Check(C->DriverDismissed&&!C->Chauffeur&&FMath::Abs(C->Speed)<5,TEXT("arrival stops and driver exits"));Check(FVector2D::Distance(FVector2D(C->GetActorLocation()),Goal)<300,TEXT("driver reaches actual waypoint"));
 C->Exit(true);N->Destroy();P.RPG.Crew.Empty();
 C->SetActorLocationAndRotation(R.Position,R.Rotation);C->Speed=0;C->DrivePath.Empty();C->StopRequested=false;LWV2Teleport(P,R.Position+FVector(0,240,90));P.SetWaypoint(Goal);C->Enter(&P,0);
 N=GetWorld()->SpawnActor<ALWResident>(R.Position+FVector(0,-250,100),R.Rotation);N->ConfigureResident(TEXT("v14_blocked_driver"),TEXT("recruit"),TEXT("MORGAN"),0);Crew.Id=N->ResidentId;P.RPG.Crew.Add(Crew);C->Board(N);
 auto* Barrier=GetWorld()->SpawnActor<ALWChunk>();FVector BarrierAt=R.Position+FVector(D,0)*950;Barrier->Box(P.World,TEXT("Concrete"),BarrierAt,FVector(140,2200,300),R.Rotation);FVector BackAt=R.Position-FVector(D,0)*600;Barrier->Box(P.World,TEXT("Concrete"),BackAt,FVector(140,2200,300),R.Rotation);
 for(int I=0;I<1800&&(!C->DriverDismissed||C->Chauffeur);I++){C->Tick(.05f);P.TickVehicleSeat();}
 Check(FMath::Abs(C->Speed)<5&&!C->Chauffeur,TEXT("blocked road eventually stops and dismisses driver"));Check(FVector2D::DotProduct(FVector2D(C->GetActorLocation())-Start,D)<750,TEXT("driver never crosses the barricade"));
 Barrier->Destroy();C->Exit(true);N->Destroy();C->Destroy();P.RPG.Crew.Empty();
 });

}
