// Integrated runtime tests run only with -LWV4Smoke and an isolated save slot.
void ALWGameMode::BuildV4Smoke(ALWCharacter& InitialPlayer){
 V2->OriginalSensitivity=InitialPlayer.Sensitivity;V2->OriginalVolume=InitialPlayer.MasterVolume;V2->bOriginalCrust=InitialPlayer.bCrust;
 V2->OriginalPendingResolution=InitialPlayer.PendingResolution;V2->OriginalPendingWindow=InitialPlayer.PendingWindowMode;V2->bSettingsSaved=true;
 auto Add=[this](const TCHAR* Name,double Wait,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({Name,Wait,25,MoveTemp(Begin),MoveTemp(End),FLWV2Ready()});};
 auto Resident=[](ALWCharacter& P,FName Job,int Index=0)->ALWResident*{for(TActorIterator<ALWResident> I(P.GetWorld());I;++I)if(I->NpcRole==Job){if(Index--==0)return *I;}return nullptr;};
 auto Meet=[Resident](ALWCharacter& P,FName Job,int Index=0)->ALWResident*{P.ClosePanels();auto* N=Resident(P,Job,Index);if(N){LWV2Teleport(P,N->GetActorLocation()+FVector(0,-230,0));P.Controller->SetControlRotation((N->GetActorLocation()-P.GetActorLocation()).Rotation());P.Talk(N);}return N;};
 auto Furniture=[](ALWCharacter& P,FName Type)->ALWWorldObject*{for(AActor* A:P.World->BunkerParts)if(auto* F=Cast<ALWWorldObject>(A))if(F->UseType==Type)return F;return nullptr;};
 struct FState{FName CrewA,CrewB;int Points=0,Money=0;int64 XP=0;TWeakObjectPtr<ALWResident> Companion;TWeakObjectPtr<ALWWorldObject> Door;};auto State=MakeShared<FState>();
 Add(TEXT("v4 assets and settlement"),3,[](ALWCharacter& P){P.NewGame();P.Money=2000;const FVector At(LWGen::Hub(FIntPoint::ZeroValue,P.World->Seed)+FVector2D(0,-5000),115);P.World->Stream(At,true);LWV2Teleport(P,At+FVector(0,-1000,0));P.Controller->SetControlRotation(FRotator(0,90,0));},[this,Resident](ALWCharacter& P){
  Check(P.CompanionLimit()==1&&P.RPG.Crew.IsEmpty(),TEXT("fresh survivor starts with one active companion slot"));
  for(FName M:{TEXT("LockerV4"),TEXT("FridgeV4"),TEXT("StoveV4"),TEXT("RadioV4"),TEXT("WorkbenchV4"),TEXT("SinkV4"),TEXT("ToiletV4")})Check(IsValid(P.World->Mesh(M)),*FString::Printf(TEXT("new furniture %s loaded"),*M.ToString()));
  for(FName N:{TEXT("Speech0"),TEXT("Speech1"),TEXT("Speech2")})Check(IsValid(P.World->Sounds.FindRef(N).Get()),TEXT("gibberish voice slot loads"));
  for(FName R:{TEXT("merchant"),TEXT("warden"),TEXT("medic"),TEXT("recruit")})Check(Resident(P,R)!=nullptr,TEXT("friendly settlement Job generated"));
  Check(LoadObject<ULWRPGCatalog>(nullptr,TEXT("/Game/Data/DA_RPGCatalog.DA_RPGCatalog"))!=nullptr,TEXT("editable RPG catalog cooked and loaded"));CaptureV2(TEXT("01_Waystation"));
 });
 Add(TEXT("level and skills UI"),1,[this](ALWCharacter& P){P.GainXP(1600);Check(P.RPG.Level==5&&P.RPG.Points==8,TEXT("multi-level award grants skill points"));P.ToggleSkills();},[this](ALWCharacter& P){
  Check(P.RPGPanel==1&&!P.CanAct(),TEXT("skills panel gates combat"));auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());if(RequireV2(H!=nullptr,TEXT("HUD exists"))){H->NotifyHitBoxClick(TEXT("buy_perk_0"));Check(P.RPG.Perks.FindRef(TEXT("perk_0"))==1,TEXT("HUD click buys real perk"));H->NotifyHitBoxClick(TEXT("cat_3"));H->NotifyHitBoxClick(TEXT("attribute"));Check(P.RPG.Attributes[3]==2,TEXT("attribute purchase through UI"));}CaptureV2(TEXT("02_Skills"));
 });
 Add(TEXT("branching dialogue"),1,[this,Meet](ALWCharacter& P){auto* N=Meet(P,TEXT("warden"));Check(N&&P.RPGPanel==4&&!P.CanAct(),TEXT("warden opens branching conversation"));P.ChooseDialogue(0);Check(P.DialogueNode==TEXT("rumors"),TEXT("first branch selected"));P.ChooseDialogue(0);Check(P.DialogueNode==TEXT("dangers"),TEXT("nested branch selected"));P.BuildDialogue(TEXT("contracts"));},[this](ALWCharacter& P){Check(P.DialogueChoices.Num()>=5,TEXT("contract choices populated"));CaptureV2(TEXT("03_Contracts"));});
 Add(TEXT("quest acceptance and atomic supply hand-in"),.5,[this,Meet](ALWCharacter& P){
  Meet(P,TEXT("warden"));P.BuildDialogue(TEXT("quest:provisions"));P.ChooseDialogue(0);Check(P.RPG.Quests.Num()==1,TEXT("contract accepted via dialogue choice"));Check(!P.AcceptQuest(TEXT("provisions")),TEXT("duplicate contract rejected"));Check(!P.AcceptQuest(TEXT("clinic")),TEXT("prerequisite enforced"));
  P.ConsumeSupply(TEXT("water"),P.CountSupply(TEXT("water")));int Credits=P.Money;Check(!P.TurnInQuest(TEXT("provisions"))&&P.Money==Credits,TEXT("missing supply hand-in atomic"));
  auto Water=LWItems::Make(TEXT("water"),3);Check(LWItems::Place(P.Inventory,Water,12,10),TEXT("supply fixture fits inventory"));Check(P.TurnInQuest(TEXT("provisions")),TEXT("correct supplies turn in"));Check(P.CountSupply(TEXT("water"))==0&&P.Money==Credits+150,TEXT("supplies consumed and credits paid"));Credits=P.Money;const int64 XP=P.RPG.XP;Check(!P.TurnInQuest(TEXT("provisions"))&&P.Money==Credits&&P.RPG.XP==XP,TEXT("reward cannot duplicate"));Check(P.AcceptQuest(TEXT("clinic")),TEXT("completed prerequisite unlocks sequel"));
  Check(P.AcceptQuest(TEXT("shelter")),TEXT("shelter quest accepted"));P.ClosePanels();P.ToggleJournal();P.TrackQuest(TEXT("shelter"));Check(P.bWaypoint,TEXT("journal creates bunker route"));
 },[this](ALWCharacter& P){CaptureV2(TEXT("04_Journal"));});
 Add(TEXT("friendly merchant"),1,[this,Meet](ALWCharacter& P){Meet(P,TEXT("merchant"));P.ChooseDialogue(1);Check(P.bInventory&&P.OpenObject&&P.World->Containers.FindRef(P.OpenObject->RecordId).bTrader,TEXT("merchant dialogue opens actual trading grid"));Check(P.ItemsFor(2)&&P.ItemsFor(2)->Num()>0,TEXT("merchant stock exists"));},[this](ALWCharacter& P){CaptureV2(TEXT("05_Merchant"));});
 Add(TEXT("medic and passing speech"),1,[this,Meet](ALWCharacter& P){Meet(P,TEXT("medic"));P.Health=35;int Credits=P.Money;P.ChooseDialogue(1);Check(P.Health==P.MaxHealth()&&P.Money==Credits-40,TEXT("medic treatment consumes credits"));P.ClosePanels();},[this,Resident](ALWCharacter& P){auto* N=Resident(P,TEXT("medic"));Check(N&&N->SubtitleTime>0&&!N->Subtitle.IsEmpty(),TEXT("in-world speech retains subtitle"));CaptureV2(TEXT("06_PassingSpeech"));});
 Add(TEXT("hire default squad and excess recruit"),2,[this,Meet,State](ALWCharacter& P){auto* A=Meet(P,TEXT("recruit"));if(!RequireV2(A!=nullptr,TEXT("first recruit available")))return;State->CrewA=A->ResidentId;State->Companion=A;Check(P.Recruit(A),TEXT("first companion hired"));Check(!P.Recruit(A),TEXT("duplicate recruitment rejected"));auto* B=Meet(P,TEXT("recruit"),1);if(!RequireV2(B!=nullptr,TEXT("second recruit available")))return;State->CrewB=B->ResidentId;Check(P.Recruit(B),TEXT("excess recruit hired into bunker"));P.ClosePanels();Check(P.RPG.Crew.Num()==2&&P.RPG.Crew[0].Following&&!P.RPG.Crew[1].Following,TEXT("default capacity enforced"));Check(!P.SetCompanion(State->CrewB,true),TEXT("cannot exceed squad limit"));},[this,State](ALWCharacter& P){
  bool Home=false;for(TActorIterator<ALWResident> I(GetWorld());I;++I)if(I->ResidentId==State->CrewB)Home=ALWWorld::IsSafePosition(I->GetActorLocation());Check(Home,TEXT("reserve companion physically returns to bunker"));P.ToggleCrew();CaptureV2(TEXT("07_Crew"));
 });
 Add(TEXT("unlock larger squad"),1,[this,State](ALWCharacter& P){P.ClosePanels();Check(P.RaiseAttribute(3),TEXT("raise presence to squad requirement"));Check(P.BuyPerk(TEXT("perk_23")),TEXT("squad leader skill unlock"));Check(P.CompanionLimit()==2&&P.SetCompanion(State->CrewB,true),TEXT("second active companion unlocked"));},[this,State](ALWCharacter& P){
  bool Outside=false;for(TActorIterator<ALWResident> I(GetWorld());I;++I)if(I->ResidentId==State->CrewB)Outside=!ALWWorld::IsSafePosition(I->GetActorLocation())&&FVector::Dist(I->GetActorLocation(),P.GetActorLocation())<1000;Check(Outside,TEXT("home companion rejoins player outside"));
 });
 Add(TEXT("bunker rooms"),2,[this](ALWCharacter& P){P.EnterSafehouse();P.Controller->SetControlRotation(FRotator(0,0,0));},[this,Furniture,State](ALWCharacter& P){
  int Bedrooms=0;TSet<int> RoomIDs;for(AActor* A:P.World->BunkerParts)if(auto* D=Cast<ALWWorldObject>(A))if(D->RecordId.ToString().StartsWith(TEXT("bedroom_door_")))Bedrooms++;
  Check(Bedrooms==10,TEXT("ten private bedrooms have actual doors"));for(int I=0;I<10;I++){const FVector At=P.World->BedroomPosition(I);Check(ALWWorld::IsSafePosition(At),TEXT("bedroom lies inside protected volume"));FHitResult Floor;Check(GetWorld()->LineTraceSingleByChannel(Floor,At,At-FVector(0,0,220),ECC_Visibility),TEXT("bedroom has solid floor"));}
  for(FName Type:{TEXT("bed"),TEXT("locker"),TEXT("radio"),TEXT("water"),TEXT("workbench"),TEXT("cooker"),TEXT("sink"),TEXT("chair")})Check(Furniture(P,Type)!=nullptr,TEXT("bunker service furniture exists"));
  P.Health=40;Check(UGameplayStatics::ApplyDamage(&P,1000,nullptr,nullptr,nullptr)==0&&P.Health==40,TEXT("expanded shelter rejects lethal damage"));
  for(TActorIterator<ALWResident> I(GetWorld());I;++I)if(I->ResidentId==State->CrewA||I->ResidentId==State->CrewB)Check(ALWWorld::IsSafePosition(I->GetActorLocation()),TEXT("active companions enter bunker safely"));
  const auto* Q=P.RPG.Quests.FindByPredicate([](const auto& X){return X.Id==TEXT("shelter");});Check(Q&&Q->Stage==1,TEXT("real bunker entry advances visit objective"));CaptureV2(TEXT("08_BunkerHall"));
 });
 Add(TEXT("furniture gameplay and door seam"),1,[this,Furniture,State](ALWCharacter& P){
  auto* Bed=Furniture(P,TEXT("bed"));if(!RequireV2(Bed!=nullptr,TEXT("bed fixture")))return;P.Health=30;P.Stamina=10;P.Hunger=P.Thirst=100;Bed->Use(&P);Check(P.Health==65&&P.Stamina==P.MaxStamina(),TEXT("bed restores health and stamina"));
  auto* Water=Furniture(P,TEXT("water"));P.Thirst=10;Water->Use(&P);Check(P.Thirst==100,TEXT("water station restores thirst"));P.Thirst=50;Water->Use(&P);Check(P.Thirst==50,TEXT("filter cooldown prevents spam"));
  auto* Locker=Furniture(P,TEXT("locker"));LWV2Teleport(P,Locker->GetActorLocation()+FVector(-130,0,110));Locker->Use(&P);Check(P.bInventory&&P.ItemsFor(2)!=nullptr,TEXT("bunker locker container survives new game"));
  FGuid Food=LWV2FindId(P.Inventory,TEXT("food"));Check(Food.IsValid()&&LWV2MoveAuto(P,0,2,Food),TEXT("player can deposit gear in bedroom locker"));Check(LWV2MoveAuto(P,2,0,Food),TEXT("player can retrieve bedroom gear"));P.ClosePanels();
  auto* Radio=Furniture(P,TEXT("radio"));Radio->Use(&P);const auto* Q=P.RPG.Quests.FindByPredicate([](const auto& X){return X.Id==TEXT("shelter");});Check(Q&&Q->Stage==2&&!Q->Rewarded,TEXT("radio completes objective but requires turn-in"));
  for(AActor* A:P.World->BunkerParts)if(auto* D=Cast<ALWWorldObject>(A))if(D->RecordId==TEXT("bedroom_door_0")){State->Door=D;FHitResult Hit;FVector Mid=D->GetActorTransform().TransformPosition(FVector(80,0,118));Check(GetWorld()->LineTraceSingleByChannel(Hit,Mid+FVector(0,-60,0),Mid+FVector(0,60,0),ECC_Visibility)&&Hit.GetActor()==D,TEXT("closed bedroom door seals central opening"));D->Use(&P);LWV2Teleport(P,P.World->BedroomPosition(0));P.Controller->SetControlRotation(FRotator(-12,0,0));}
 },[this,State](ALWCharacter& P){if(State->Door.IsValid())Check(State->Door->DoorAngle>95,TEXT("door fully opens"));CaptureV2(TEXT("09_Bedroom"));});
 Add(TEXT("service room capture"),1,[](ALWCharacter& P){LWV2Teleport(P,FVector(-3100,2900,-1870));P.Controller->SetControlRotation(FRotator(-10,15,0));},[this](ALWCharacter& P){CaptureV2(TEXT("10_Workshop"));});
 Add(TEXT("persist RPG and crew"),2,[this,State](ALWCharacter& P){P.SetCompanion(State->CrewB,false);State->XP=P.RPG.XP;State->Points=P.RPG.Points;State->Money=P.Money;P.SaveProgress();P.RPG=FLWRPGState();P.Money=0;P.LoadProgress();},[this,State,Furniture](ALWCharacter& P){
  Check(P.RPG.XP==State->XP&&P.RPG.Points==State->Points&&P.Money==State->Money,TEXT("progression and credits survive save/load"));Check(P.RPG.Crew.Num()==2&&P.CompanionLimit()==2&&!P.RPG.Crew[1].Following,TEXT("crew assignments and perks persist"));
  int Crew=0;for(TActorIterator<ALWResident> I(GetWorld());I;++I)if(I->ResidentId==State->CrewA||I->ResidentId==State->CrewB)Crew++;Check(Crew==2,TEXT("save/load recreates crew without duplicates"));
  const auto* Q=P.RPG.Quests.FindByPredicate([](const auto& X){return X.Id==TEXT("provisions");});Check(Q&&Q->Rewarded,TEXT("quest reward claim persists"));Check(P.World->PropStates.FindRef(TEXT("bedroom_door_0"))==1,TEXT("bunker door state persists"));Check(P.World->Containers.Contains(Furniture(P,TEXT("locker"))->RecordId),TEXT("locker contents persist"));AuditV2(P,TEXT("v4 final inventory audit"));
 });
 Add(TEXT("live companion covering fire"),3,[this,State](ALWCharacter& P){
  P.LeaveSafehouse();LWV2Teleport(P,FVector(1400,0,115));P.World->Stream(P.GetActorLocation(),true);P.Health=P.MaxHealth();P.AcceptQuest(TEXT("patrol"));
  for(TActorIterator<ALWResident> I(GetWorld());I;++I)if(I->ResidentId==State->CrewA){State->Companion=*I;I->SetActorLocation(FVector(1700,220,115));I->FireTime=0;}
  TestEnemy=GetWorld()->SpawnActor<ALWZombie>(FVector(2300,220,115),FRotator(0,180,0));if(!RequireV2(TestEnemy!=nullptr,TEXT("companion combat target spawned")))return;
  P.World->ZombieCount++;TestEnemy->PersistentId=0xf0041234;TestEnemy->Health=150;TestEnemy->Stagger=600;TestEnemy->Home=TestEnemy->GetActorLocation();P.Controller->SetControlRotation(FRotator(0,10,0));
 },[this,State](ALWCharacter& P){Check(TestEnemy&&TestEnemy->Health<150,TEXT("companion live visibility trace damages hostile"));State->Money=P.Kills;TestEnemy->Health=1;CaptureV2(TEXT("11_CompanionCombat"));});
 Add(TEXT("companion kill credit and recoverable damage"),1,[](ALWCharacter&){},[this,State](ALWCharacter& P){
  Check(TestEnemy->bDead&&P.Kills==State->Money+1,TEXT("companion kill awards player exactly once"));const auto* Q=P.RPG.Quests.FindByPredicate([](const auto& X){return X.Id==TEXT("patrol");});Check(Q&&Q->Progress==1,TEXT("companion kill advances contract"));
  auto* C=State->Companion.Get();if(!RequireV2(C!=nullptr,TEXT("persistent companion combat actor valid")))return;UGameplayStatics::ApplyDamage(C,1000,nullptr,TestEnemy,nullptr);Check(C->DownTime>20&&C->Health==1&&!C->bDead,TEXT("lethal companion damage enters recovery instead of deleting recruit"));C->DownTime=.15f;
 });
 Add(TEXT("recovery and death retention"),.4,[](ALWCharacter&){},[this,State](ALWCharacter& P){Check(State->Companion.IsValid()&&State->Companion->DownTime<=0&&State->Companion->Health==150,TEXT("companion recovers from downed state"));
  const int Level=P.RPG.Level;const int Perks=P.RPG.Perks.Num();UGameplayStatics::ApplyDamage(&P,10000,nullptr,TestEnemy,nullptr);Check(P.Health==0&&P.Inventory.IsEmpty(),TEXT("death drops carried equipment"));P.Respawn();Check(P.RPG.Level==Level&&P.RPG.Perks.Num()==Perks&&P.RPG.Crew.Num()==2,TEXT("death preserves level perks and unlocked crew"));Check(P.bSafehouse&&P.Health==P.MaxHealth(),TEXT("respawn restores perk-adjusted maximum health"));
 });
 Add(TEXT("screenshots written"),1,[](ALWCharacter&){},[this](ALWCharacter&){for(const FString& File:V2->Screenshots)Check(IFileManager::Get().FileSize(*File)>10000,TEXT("runtime screenshot exists"));});
}

