// Live gameplay and persistence tests; never uses the player's save slot.
void ALWGameMode::BuildV5Smoke(ALWCharacter& InitialPlayer){
 V2->OriginalSensitivity=InitialPlayer.Sensitivity;V2->OriginalVolume=InitialPlayer.MasterVolume;V2->bOriginalCrust=InitialPlayer.bCrust;V2->OriginalPendingResolution=InitialPlayer.PendingResolution;V2->OriginalPendingWindow=InitialPlayer.PendingWindowMode;V2->bSettingsSaved=true;
 auto Add=[this](const TCHAR* N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,25,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWWorldObject> Box;FGuid VIN,Key;FVector At;int Picks;TWeakObjectPtr<ALWWorldObject> Wall;};auto S=MakeShared<FState>();
 auto Torque=[](ALWCharacter& P,bool Down){auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(EKeys::SpaceBar,Down?IE_Pressed:IE_Released,Down?1.:0.));PC->PlayerInput->ProcessInputStack({},.016f,false);};
 Add(TEXT("v5 assets and road vehicle"),3,[this,S](ALWCharacter& P){P.NewGame();P.World->Stream(FVector(2000,0,115),true);LWV2Teleport(P,FVector(2000,-700,115));FLWVehicleRecord Sedan;Sedan.Model=TEXT("sedan");Sedan.VIN=FGuid::NewDeterministicGuid(TEXT("v5_car_fixture"));Sedan.Position=FVector(2000,0,75);P.World->Vehicles.Add(TEXT("v5_car_fixture"),Sedan);S->Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("v5_car_fixture"),FVector(2000,0,75),FRotator::ZeroRotator));if(!RequireV2(S->Car.IsValid(),TEXT("sedan spawned")))return;S->VIN=S->Car->Record()->VIN;S->Car->Record()->Unlocked=false;S->Car->Record()->LockTier=4;P.Controller->SetControlRotation((S->Car->GetActorLocation()-P.GetActorLocation()).Rotation());},[this,S](ALWCharacter& P){
  for(FName M:{TEXT("SedanShellV5"),TEXT("SedanCabinV5"),TEXT("SteeringV5"),TEXT("GloveLidV5"),TEXT("WiperV5"),TEXT("SedanWheelV5")})Check(IsValid(P.World->Mesh(M)),*FString::Printf(TEXT("vehicle mesh %s loaded"),*M.ToString()));
  for(FName A:{TEXT("CarEngine"),TEXT("CarRadio"),TEXT("CarIgnition"),TEXT("CarImpact"),TEXT("CarSignal"),TEXT("PickBreak"),TEXT("LockOpen"),TEXT("WireSpark")})Check(IsValid(P.World->Sounds.FindRef(A).Get()),TEXT("new editable audio slot loaded"));
  TSet<FGuid> IDs;for(const auto& V:P.World->Vehicles){Check(V.Value.VIN.IsValid()&&!IDs.Contains(V.Value.VIN),TEXT("world vehicle VIN unique"));IDs.Add(V.Value.VIN);}Check(IDs.Num()>1,TEXT("procedural road cars generated"));int Keys=0,LockedKeys=0;for(const auto& V:P.World->Vehicles)if(V.Key!=TEXT("v5_car_fixture")){if(const auto* G=P.World->Containers.Find(FName(*(TEXT("glove_")+V.Key.ToString()))))for(const auto& Item:G->Items)if(Item.Definition==TEXT("car_key")){Check(Item.VehicleId==V.Value.VIN,TEXT("procedural glovebox key matches its own car"));Keys++;if(V.Value.LockTier>0)LockedKeys++;}}Check(Keys>0&&LockedKeys>0,TEXT("glovebox keys appear in both world loot and locked cars"));CaptureV2(TEXT("01_Sedan"));
 });
 Add(TEXT("locked container authorization"),1,[this,S](ALWCharacter& P){LWV2Teleport(P,FVector(2000,-340,115));S->Box=P.World->SpawnObject(ELWObjectKind::Container,TEXT("v5_locked_box"),FVector(2050,-440,0));auto& R=P.World->Containers.FindOrAdd(S->Box->RecordId);R.Id=S->Box->RecordId;R.Position=S->Box->GetActorLocation();R.LockTier=4;R.Unlocked=false;P.OpenContainer(S->Box.Get());Check(P.SecurityMode==1&&!P.bInventory&&!P.CanAct(),TEXT("locked storage starts picking and blocks inventory/combat"));Check(P.ItemsFor(2)==nullptr,TEXT("locked storage has no accessible inventory panel"));Check(P.SecurityTier==4,TEXT("master lock tier selected"));},[this](ALWCharacter&){CaptureV2(TEXT("02_Lockpick"));});
 Add(TEXT("pick wear and breaking"),.2,[this,S,Torque](ALWCharacter& P){P.PickAngle=P.LockSecret>0?-90:90;P.PickHealth=.1f;S->Picks=P.CountSupply(TEXT("lockpick"));Torque(P,true);for(int I=0;I<40&&P.SecurityMode;I++)P.TickSecurity(.05f);Torque(P,false);Check(P.SecurityMode==0&&P.CountSupply(TEXT("lockpick"))==S->Picks-1,TEXT("binding breaks exactly one pick"));Check(P.World->Containers.FindChecked(S->Box->RecordId).LockAttempts==1&&P.IsLocked(S->Box.Get()),TEXT("failed attempt stays locked and advances seed"));});
 Add(TEXT("successful real torque input"),.5,[this,S,Torque](ALWCharacter& P){Check(P.StartLockpick(S->Box.Get()),TEXT("retry with another pick"));P.PickAngle=P.LockSecret;Torque(P,true);for(int I=0;I<25&&P.SecurityMode;I++)P.TickSecurity(.05f);Torque(P,false);Check(!P.IsLocked(S->Box.Get())&&P.bInventory&&P.ItemsFor(2),TEXT("correct angle unlocks and opens loot grid"));P.ClosePanels();});
 Add(TEXT("tier loot and vehicle access"),.5,[this,S](ALWCharacter& P){int Locked=0;TSet<int> Tiers;for(const auto& C:P.World->Containers)if(C.Value.LockTier>0&&C.Key!=TEXT("v5_locked_box")){Locked++;Tiers.Add(C.Value.LockTier);FName Bonus=C.Value.LockTier==1?TEXT("ammo_12g"):C.Value.LockTier==2?TEXT("medkit"):C.Value.LockTier==3?TEXT("rifle"):TEXT("lmg");Check(C.Value.Items.ContainsByPredicate([&](const auto& I){return I.Definition==Bonus;}),TEXT("tier loot bonus present"));}Check(Locked>0&&Tiers.Num()>1,TEXT("procedural containers have mixed lock tiers"));
  auto Wrong=LWItems::Make(TEXT("car_key"));Wrong.VehicleId=FGuid::NewGuid();LWItems::Place(P.Inventory,Wrong,12,10);Check(!P.HasKey(S->VIN),TEXT("another car key cannot authorize this VIN"));S->Car->Use(&P);Check(P.SecurityMode==1&&!P.Vehicle,TEXT("locked car requires key or picking"));P.ClosePanels();auto Key=LWItems::Make(TEXT("car_key"));Key.VehicleId=S->VIN;S->Key=Key.Id;Check(LWItems::Place(P.Inventory,Key,12,10),TEXT("matching key fits inventory"));S->Car->Use(&P);Check(P.Vehicle==S->Car.Get()&&S->Car->Record()->Unlocked,TEXT("matching key opens driver seat"));P.Reload();Check(S->Car->EngineOn,TEXT("matching key starts engine"));P.Reload();P.Inventory.RemoveAll([&](const auto& I){return I.Id==S->Key;});
 });
 Add(TEXT("first person cabin and controls"),1,[this,S](ALWCharacter& P){P.VehicleLights();P.VehicleWipers();P.VehicleLeft();P.VehicleRadio();},[this,S](ALWCharacter& P){
  auto* C=S->Car.Get();Check(FVector::Dist(P.Camera->GetComponentLocation(),C->GetActorTransform().TransformPosition(FVector(-45,-43,53)))<2,TEXT("camera anchored inside first person driver seat"));Check(!P.CanAct()&&!P.WeaponRoot->IsVisible(),TEXT("driver cannot use hand weapons"));Check(C->Headlights&&C->Headlamps[0]->IsVisible()&&C->WipersOn&&C->Signal==-1&&C->RadioChannel==1,TEXT("dashboard controls change real components"));Check(IsValid(C->RadioAudio.Get())&&C->RadioAudio->IsPlaying(),TEXT("attached radio plays through audio system"));P.VehicleRight();Check(C->Signal==1,TEXT("right signal replaces left signal"));CaptureV2(TEXT("03_DriverSeat"));
 });
 Add(TEXT("glovebox inventory and lid"),1,[this,S](ALWCharacter& P){P.VehicleGlove();Check(P.bInventory&&P.OpenObject->RecordId==S->Car->GloveId(),TEXT("glovebox opens separate storage"));auto Key=LWItems::Make(TEXT("car_key"));Key.VehicleId=S->VIN;S->Key=Key.Id;auto& G=P.World->Containers.FindChecked(S->Car->GloveId());Check(LWItems::Place(G.Items,Key,6,4),TEXT("key fits glovebox"));Check(LWV2MoveAuto(P,2,0,S->Key)&&P.HasKey(S->VIN),TEXT("drag matching key out of glovebox"));Check(LWV2MoveAuto(P,0,2,S->Key)&&!P.HasKey(S->VIN),TEXT("stored key is not carried ignition authorization"));},[this,S](ALWCharacter&){Check(S->Car->GloveAngle>55,TEXT("glovebox lid physically opens"));CaptureV2(TEXT("04_Glovebox"));});
 Add(TEXT("hotwire UI and wrong wiring"),1,[this,S](ALWCharacter& P){P.ClosePanels();P.VehicleGlove();P.Reload();Check(P.SecurityMode==2&&!S->Car->EngineOn,TEXT("keyless ignition launches hotwire"));P.ChooseWire((P.WireOrder[0]+1)%6);Check(P.WireHeat==35&&P.WireStage==0,TEXT("wrong wire heats and resets harness"));},[this](ALWCharacter&){CaptureV2(TEXT("05_Hotwire"));});
 Add(TEXT("starter timing and bypass"),.5,[this,S,Torque](ALWCharacter& P){for(int I=0;I<3;I++)P.ChooseWire(P.WireOrder[I]);Check(P.WireStage==3,TEXT("correct wire sequence connects starter"));Torque(P,true);P.WireClock=0;P.WireHeat=99;P.TickSecurity(.05f);Check(P.WireStage==0&&P.WireHeat==25,TEXT("bad starter timing overheats and resets"));for(int I=0;I<3;I++)P.ChooseWire(P.WireOrder[I]);for(int I=0;I<30&&P.SecurityMode;I++){P.WireClock=.8f;P.TickSecurity(.05f);}Torque(P,false);Check(P.SecurityMode==0&&S->Car->Record()->Hotwired&&S->Car->EngineOn,TEXT("timed starter completes durable ignition bypass"));});
 Add(TEXT("dashboard gaze interaction"),.5,[S](ALWCharacter& P){auto* C=S->Car.Get();for(auto& M:C->Details)if(M->ComponentTags.Contains(TEXT("radio"))){FRotator R=(M->GetComponentLocation()-P.Camera->GetComponentLocation()).Rotation();P.SeatYaw=FMath::FindDeltaAngleDegrees(C->GetActorRotation().Yaw,R.Yaw);P.SeatPitch=R.Pitch-C->GetActorRotation().Pitch;}},[this,S](ALWCharacter& P){Check(S->Car->FocusControl()==TEXT("radio"),TEXT("crosshair trace reaches physical radio control"));int Before=S->Car->RadioChannel;P.Interact();Check(S->Car->RadioChannel==(Before+1)%3,TEXT("E activates focused cabin radio"));P.SeatYaw=P.SeatPitch=0;});
 Add(TEXT("swept chassis collision"),3,[this,S](ALWCharacter& P){S->At=S->Car->GetActorLocation();S->Wall=P.World->SpawnObject(ELWObjectKind::Window,TEXT("v5_collision_wall"),S->At+S->Car->GetActorForwardVector()*600+FVector(0,0,80));S->Wall->SetActorScale3D(FVector(.4,20,5));V2->Observe=[](ALWCharacter& P){P.Forward(1);};},[this,S](ALWCharacter& P){Check(FVector::Dist2D(S->At,S->Car->GetActorLocation())>100,TEXT("car approaches blocking obstacle"));Check(S->Car->GetActorLocation().X<S->Wall->GetActorLocation().X-200,TEXT("swept chassis cannot pass through solid obstacle"));V2->Observe=nullptr;P.Forward(0);S->Car->Speed=0;S->Wall->Destroy();});
 Add(TEXT("driving acceleration"),3,[this,S](ALWCharacter& P){S->At=S->Car->GetActorLocation();V2->Observe=[](ALWCharacter& P){P.Forward(1);};},[this,S](ALWCharacter& P){Check(FVector::Dist2D(S->At,S->Car->GetActorLocation())>200,TEXT("throttle physically drives car through world"));Check(FMath::Abs(S->Car->Speed)>80,TEXT("car gains road speed"));Check(!S->Car->Exit()&&P.Vehicle,TEXT("moving vehicle rejects exit"));P.VehicleGlove();Check(!P.bInventory,TEXT("moving vehicle rejects storage"));CaptureV2(TEXT("06_Driving"));V2->Observe=nullptr;P.Forward(0);});
 Add(TEXT("parking and occupied save/load"),3,[S,Torque](ALWCharacter& P){Torque(P,true);},[this,S,Torque](ALWCharacter& P){Torque(P,false);Check(FMath::Abs(S->Car->Speed)<1,TEXT("brakes stop vehicle"));S->At=S->Car->GetActorLocation();S->Car->SyncRecord();P.SaveProgress();P.LoadProgress();S->Car=P.Vehicle.Get();if(!RequireV2(S->Car.IsValid(),TEXT("save restores driver seat")))return;Check(S->Car->Record()->VIN==S->VIN&&S->Car->Record()->Hotwired&&!S->Car->EngineOn,TEXT("VIN bypass and parked transform survive load with engine off"));Check(FVector::Dist2D(S->At,S->Car->GetActorLocation())<2,TEXT("driven location restored"));Check(P.World->Containers.FindChecked(S->Car->GloveId()).Items.ContainsByPredicate([&](const auto& I){return I.Id==S->Key&&I.VehicleId==S->VIN;}),TEXT("key VIN survives nested save serialization"));P.Reload();Check(S->Car->EngineOn,TEXT("saved bypass starts without carried key"));P.Reload();Check(S->Car->Exit()&&!P.Vehicle&&P.CanAct(),TEXT("parked driver exits onto valid ground"));});
 Add(TEXT("chunk unloading and vehicle identity"),1,[this,S](ALWCharacter& P){S->Car->SetActorLocation(FVector(21000,0,75));S->Car->SyncRecord();S->At=S->Car->GetActorLocation();LWV2Teleport(P,FVector(-30000,0,115));P.World->Stream(P.GetActorLocation(),true);},[this,S](ALWCharacter& P){Check(!S->Car.IsValid(),TEXT("distant unoccupied vehicle unloads"));LWV2Teleport(P,S->At+FVector(0,-300,40));P.World->Stream(P.GetActorLocation(),true);});
 Add(TEXT("streamed car and final audit"),2,[](ALWCharacter&){},[this,S](ALWCharacter& P){int Count=0;for(TActorIterator<ALWVehicle> I(GetWorld());I;++I)if(I->RecordId==TEXT("v5_car_fixture")){Count++;Check(I->Record()->VIN==S->VIN&&I->Record()->Hotwired,TEXT("streamed car retains security state"));Check(FVector::Dist2D(I->GetActorLocation(),S->At)<2,TEXT("car respawns at moved location"));}Check(Count==1,TEXT("exactly one car after owner chunk changes"));AuditV2(P,TEXT("v5 inventory audit"));for(const FString& F:V2->Screenshots)Check(IFileManager::Get().FileSize(*F)>10000,TEXT("v5 screenshot captured"));});
}
