void ALWGameMode::BuildV6Smoke(ALWCharacter& InitialPlayer){
 BuildV5Smoke(InitialPlayer);
 auto Add=[this](const TCHAR* N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,25,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWWorldObject> Box;TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWResident> Citizen;TArray<TWeakObjectPtr<ALWResident>> Crew;FVector At;FGuid Water;int Count;};auto S=MakeShared<FState>();
 auto Key=[](ALWCharacter& P,FKey K,bool Down){auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(K,Down?IE_Pressed:IE_Released,Down?1.:0.));};
 Add(TEXT("equipment slots and container tools"),1,[this,S](ALWCharacter& P){P.NewGame();LWV2Teleport(P,FVector(2000,-300,115));P.World->Stream(P.GetActorLocation(),true);
  P.EquipCrowbar();Check(P.ActiveGun()&&P.ActiveGun()->Slot==TEXT("Primary"),TEXT("key 1 selects primary slot"));FGuid Before=P.ActiveWeaponId;P.EquipBat();Check(P.ActiveWeaponId==Before,TEXT("empty secondary does not select unrelated weapon"));auto Second=LWItems::Make(TEXT("shotgun"));Second.Slot=TEXT("Secondary");P.Inventory.Add(Second);P.EquipBat();Check(P.ActiveWeaponId==Second.Id,TEXT("key 2 selects exact secondary instance even with same weapon type in primary"));P.EquipShotgun();Check(P.ActiveGun()&&P.ActiveGun()->Slot==TEXT("Sidearm"),TEXT("key 3 selects sidearm"));P.EquipRevolver();Check(P.ActiveGun()&&P.ActiveGun()->Slot==TEXT("Melee"),TEXT("key 4 selects melee slot"));P.EquipRifle();Check(P.ActiveGun()->Slot==TEXT("Melee"),TEXT("key 7 no longer selects a weapon"));
  FName Id=TEXT("v6_tools_box");FLWContainerRecord R;R.Id=Id;R.Position=P.GetActorLocation()+FVector(80,0,-90);auto Water=LWItems::Make(TEXT("water"),2);LWItems::Place(R.Items,Water,12,12);S->Water=Water.Id;P.World->Containers.Add(Id,R);S->Box=P.World->SpawnObject(ELWObjectKind::Container,Id,R.Position);P.OpenContainer(S->Box.Get());S->Count=P.CountSupply(TEXT("water"));Cast<APlayerController>(P.Controller)->SetMouseLocation(820,160);
 });
 Add(TEXT("shift click real grid input"),.5,[Key](ALWCharacter& P){Key(P,EKeys::LeftShift,true);Key(P,EKeys::LeftMouseButton,true);},[this,S,Key](ALWCharacter& P){Key(P,EKeys::LeftMouseButton,false);Key(P,EKeys::LeftShift,false);Check(P.CountSupply(TEXT("water"))==S->Count+2,TEXT("shift click transfers and combines matching supplies"));Check(!P.ItemsFor(2)->ContainsByPredicate([&](const auto& I){return I.Id==S->Water;}),TEXT("quick transferred source removed exactly once"));Check(P.SortInventory(),TEXT("player auto sort succeeds"));AuditV2(P,TEXT("sorted inventory"));CaptureV2(TEXT("V6_Inventory"));});
 Add(TEXT("shared tab navigation"),.5,[this,S](ALWCharacter& P){auto* H=Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD());for(int I=1;I<5;I++){H->NotifyHitBoxClick(FName(*FString::Printf(TEXT("tab_%d"),I)));Check(!P.CanAct()&&(I==1?P.bMap:P.RPGPanel==I-1),TEXT("tabs switch panel and retain input gating"));}H->NotifyHitBoxClick(TEXT("tab_0"));Check(P.bInventory&&P.OpenObject==S->Box.Get()&&P.ItemsFor(2),TEXT("returning to inventory retains nearby container"));H->NotifyHitBoxClick(TEXT("tab_2"));},[this](ALWCharacter&){CaptureV2(TEXT("V6_SkillsTabs"));});
 Add(TEXT("settlement activity"),3,[this,S](ALWCharacter& P){P.ClosePanels();const FVector At(LWGen::Hub(FIntPoint::ZeroValue,P.World->Seed)+FVector2D(0,-5000),115);LWV2Teleport(P,At+FVector(0,-1400,0));P.World->Stream(At,true);P.Controller->SetControlRotation(FRotator(-5,90,0));int Civ=0;for(TActorIterator<ALWResident> N(GetWorld());N;++N)if(N->NpcRole==TEXT("civilian")&&FVector::Dist2D(N->GetActorLocation(),At)<5000){Civ++;S->Citizen=*N;}Check(Civ>=6,TEXT("settlement has six ambient residents"));if(!RequireV2(S->Citizen.IsValid(),TEXT("citizen fixture present")))return;auto* N=S->Citizen.Get();N->ActivitySpots={N->GetActorLocation()+FVector(0,450,0)};N->Activity=0;N->ActivityTime=10;S->At=N->GetActorLocation();N->Say(TEXT("Someone fixed the water pump."));P.Talk(N);Check(P.RPGPanel==0&&!P.Speaker,TEXT("ambient resident cannot open a conversation"));},[this,S](ALWCharacter&){Check(FVector::Dist2D(S->At,S->Citizen->GetActorLocation())>40,TEXT("ambient resident walks between activities"));CaptureV2(TEXT("V6_Settlement"));});
 Add(TEXT("companion passenger seating"),1,[this,S](ALWCharacter& P){P.ClosePanels();LWV2Teleport(P,FVector(2000,-300,115));P.World->Stream(P.GetActorLocation(),true);P.RPG.Crew.Empty();P.RPG.Attributes[3]=10;P.RPG.Perks.Add(TEXT("perk_23"),3);
  FLWVehicleRecord Sedan;Sedan.Model=TEXT("sedan");Sedan.VIN=FGuid::NewDeterministicGuid(TEXT("v6_car"));Sedan.Position=FVector(2000,0,75);P.World->Vehicles.Add(TEXT("v6_car"),Sedan);S->Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("v6_car"),FVector(2000,0,85)));if(!RequireV2(S->Car.IsValid(),TEXT("vehicle fixture created")))return;S->Car->Record()->Unlocked=true;S->Car->Record()->Hotwired=true;
  for(int I=0;I<4;I++){FLWCrewRecord C;C.Id=FName(*FString::Printf(TEXT("v6_crew_%d"),I));C.Name=FString::Printf(TEXT("CREW %d"),I);C.Following=true;C.Bedroom=I;P.RPG.Crew.Add(C);auto* N=GetWorld()->SpawnActor<ALWResident>(FVector(1800+I*80,240,110),FRotator::ZeroRotator);N->ConfigureResident(C.Id,TEXT("recruit"),C.Name,I);S->Crew.Add(N);}
  Check(S->Car->Enter(&P),TEXT("driver enters car with squad nearby"));P.SeatYaw=80;P.SeatPitch=-10;
 },[this,S](ALWCharacter& P){int Seated=0;TSet<int> Seats;for(auto N:S->Crew)if(N->Riding){Seated++;Seats.Add(N->SeatIndex);Check(N->GetCapsuleComponent()->GetCollisionEnabled()==ECollisionEnabled::NoCollision,TEXT("passenger cannot block chassis"));}Check(Seated==3&&Seats.Num()==3,TEXT("three distinct passenger seats filled without duplication"));Check(S->Crew.ContainsByPredicate([](auto N){return !N->Riding;}),TEXT("fourth companion remains on foot"));CaptureV2(TEXT("V6_Passengers"));});
 Add(TEXT("occupied car drives on raised asphalt"),2,[this,S,Key](ALWCharacter& P){P.SeatYaw=P.SeatPitch=0;S->At=S->Car->GetActorLocation();S->Car->Ignition();Key(P,EKeys::W,true);},[this,S,Key](ALWCharacter& P){Check(FVector::Dist2D(S->At,S->Car->GetActorLocation())>200,TEXT("fully occupied car drives without passenger or road penetration blocking it"));Key(P,EKeys::W,false);P.Forward(0);S->Car->Speed=0;
  for(auto N:S->Crew)if(!N->Riding){N->SetActorLocation(S->Car->GetActorLocation()+FVector(14000,0,0));N->TickSocial(8.1f,&P,true,3);Check(!P.RPG.Crew.FindByPredicate([&](const auto& C){return C.Id==N->ResidentId;})->Following,TEXT("outpaced companion removed from active squad"));Check(ALWWorld::IsSafePosition(N->GetActorLocation()),TEXT("outpaced companion returns to bunker"));}
  Check(S->Car->Exit(),TEXT("driver and passengers exit safely"));for(auto N:S->Crew)Check(!N->Riding,TEXT("passenger detaches on driver exit"));
 });
 Add(TEXT("loose companion following"),1,[this,S](ALWCharacter& P){for(auto N:S->Crew)if(!ALWWorld::IsSafePosition(N->GetActorLocation())){N->FollowTimer=0;N->TickSocial(.1f,&P,true,0);FVector Target=N->FollowTarget;P.Controller->SetControlRotation(FRotator(0,180,0));N->TickSocial(.1f,&P,true,0);Check(N->FollowTarget.Equals(Target,.1),TEXT("companion target does not rigidly rotate with player view"));}P.SaveProgress();P.LoadProgress();},[this](ALWCharacter& P){Check(P.RPG.Crew.Num()==4&&P.RPG.Crew.ContainsByPredicate([](const auto& C){return !C.Following;}),TEXT("inactive overflow companion persists after loading"));AuditV2(P,TEXT("v6 final inventory audit"));});
}
