void ALWGameMode::BuildV7Smoke(ALWCharacter& P0){
 V2->OriginalSensitivity=P0.Sensitivity;V2->OriginalVolume=P0.MasterVolume;V2->bOriginalCrust=P0.bCrust;V2->OriginalPendingResolution=P0.PendingResolution;V2->OriginalPendingWindow=P0.PendingWindowMode;V2->bSettingsSaved=true;
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,25,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWChunk> Fixture;TWeakObjectPtr<ALWZombie> Enemy;FVector At;float Health;};auto S=MakeShared<FState>();
 Add(TEXT("V7 setup"),1,[this,S](ALWCharacter& P){P.NewGame();P.Health=10000;P.World->TimeOfDay=12;LWV2Teleport(P,FVector(20000,20000,3115));auto* Chunk=GetWorld()->SpawnActor<ALWChunk>();S->Fixture=Chunk;Chunk->Box(P.World,TEXT("Concrete"),FVector(20000,20000,2990),FVector(24000,24000,20));
 FLWResolvedAudioSlot Audio;Check(ULWAudioCatalog::ResolveDefaultSlot(TEXT("LevelUp"),Audio),TEXT("level-up audio asset resolves"));Check(ULWAudioCatalog::ResolveDefaultSlot(TEXT("PoliceSiren"),Audio)&&Audio.Settings.bLoop,TEXT("siren loop resolves"));Check(P.AcceptQuest(TEXT("patrol")),TEXT("tracking contract accepted"));P.QuestEvent(TEXT("kill"),NAME_None,2);const auto* Quest=P.RPG.Quests.FindByPredicate([](const auto& Q){return Q.Id==TEXT("patrol");});Check(Quest&&Quest->Progress==2&&P.RPG.TrackedQuest==TEXT("patrol"),TEXT("tracked quest stores partial objective counts"));int Old=P.RPG.Level;P.GainXP(3000);Check(P.RPG.Level>Old,TEXT("experience causes level-up"));
 });
 for(const auto& Spec:LWTraffic::Specs()){
 FName Model(Spec.Id);Add(FString(TEXT("vehicle "))+Spec.Name,1.5,[this,S,Model](ALWCharacter& P){
 if(S->Car.IsValid()){P.World->Vehicles.Remove(S->Car->RecordId);S->Car->Exit(true);S->Car->Destroy();}P.ClosePanels();LWV2Teleport(P,FVector(19800,19700,3115));
 FName Id(*(TEXT("v7_")+Model.ToString()));FLWVehicleRecord R;R.VIN=FGuid::NewDeterministicGuid(Id.ToString());R.Model=Model;R.Position=FVector(20000,20000,3075);R.Unlocked=true;R.Hotwired=true;P.World->Vehicles.Add(Id,R);FLWContainerRecord Cargo;Cargo.Id=Id;Cargo.Items.Empty();P.World->Containers.Add(Id,Cargo);
 S->Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,R.Position));auto* C=S->Car.Get();if(!RequireV2(C!=nullptr,TEXT("variant spawned")))return;
 Check(P.World->Containers[Id].Width==C->Spec().CargoW&&P.World->Containers[Id].Height==C->Spec().CargoH,TEXT("cargo matches profile"));Check(C->Enter(&P),TEXT("enter variant driver seat"));C->Ignition();S->At=C->GetActorLocation();C->Throttle=1;
 TArray<ALWResident*> Riders;for(int I=0;I<C->Spec().Seats;I++){auto* N=GetWorld()->SpawnActor<ALWResident>(C->GetActorLocation()+FVector(0,250,60),FRotator::ZeroRotator);if(!N)continue;N->ConfigureResident(FName(*FString::Printf(TEXT("v7_seat_%d"),I)),TEXT("recruit"),TEXT("RIDER"),I);Check(C->Board(N)==(I<C->Spec().Seats-1),TEXT("passenger capacity enforced"));Riders.Add(N);}for(auto* N:Riders)N->Destroy();

 auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(EKeys::W,IE_Pressed,1.));PC->InputKey(FInputKeyParams(EKeys::D,IE_Pressed,1.));
 },[this,S](ALWCharacter& P){auto* C=S->Car.Get();auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(EKeys::W,IE_Released,0.));PC->InputKey(FInputKeyParams(EKeys::D,IE_Released,0.));Check(FMath::Abs(C->GetActorRotation().Yaw)>.1f,TEXT("variant turns using real steering input"));Check(FVector::Dist2D(C->GetActorLocation(),S->At)>30,TEXT("variant accelerates and drives"));C->Throttle=0;C->Speed=0;C->Control(TEXT("feature"));if(FName(C->Spec().Id)==TEXT("police")){C->Control(TEXT("siren"));C->TickFeatures(.1f);Check(C->SirenOn&&IsValid(C->SirenAudio),TEXT("police siren starts"));Check(C->EmergencyLights.Num()==2,TEXT("police red/blue lights exist"));}CaptureV2(*(FString(TEXT("Cabin_"))+C->Spec().Id));});
 Add(FString(TEXT("exterior "))+Spec.Name,.4,[S](ALWCharacter& P){auto* C=S->Car.Get();C->Exit(true);LWV2Teleport(P,C->GetActorLocation()+FVector(500,-650,190));P.Controller->SetControlRotation((C->GetActorLocation()+FVector(0,0,70)-P.GetPawnViewLocation()).Rotation());},[this,S](ALWCharacter&){CaptureV2(*(FString(TEXT("Vehicle_"))+S->Car->Spec().Id));});
 }
 Add(TEXT("mannequin aggression while watched"),1.5,[this,S](ALWCharacter& P){if(S->Car.IsValid()){S->Car->SetActorLocation(FVector(20000,26000,3075));S->Car->SyncRecord();}LWV2Teleport(P,FVector(20000,20000,3115));auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20600,20000,3115),FRotator::ZeroRotator);TestEnemy=Z;Z->ConfigureKind(ELWEnemyKind::Mannequin);Z->bAggressive=true;S->Enemy=Z;S->At=Z->GetActorLocation();P.Controller->SetControlRotation(FRotator(0,0,0));},[this,S](ALWCharacter& P){UE_LOG(LogTemp,Display,TEXT("V7_ENEMY from=%s to=%s velocity=%s mode=%d aggressive=%d safe=%d started=%d menu=%d"),*S->At.ToString(),*S->Enemy->GetActorLocation().ToString(),*S->Enemy->GetVelocity().ToString(),int(S->Enemy->GetCharacterMovement()->MovementMode),S->Enemy->bAggressive,P.bSafehouse,P.bStarted,P.bMenu);Check(S->Enemy.IsValid()&&FVector::Dist2D(S->At,S->Enemy->GetActorLocation())>120,TEXT("aggro mannequin runs while observed"));S->Enemy->SetActorLocation(P.GetActorLocation()+FVector(110,0,0));S->Enemy->AttackCooldown=0;S->Enemy->Stagger=0;float Old=P.Health;S->Enemy->TickVariant(.05f,&P);Check(P.Health<Old,TEXT("aggro mannequin attacks while observed"));S->Enemy->Destroy();});
 for(int Type=0;Type<LWPlaces::Count;Type++){
 Add(FString(TEXT("POI "))+LWPlaces::Name(Type),.7,[this,S,Type](ALWCharacter& P){if(S->Fixture.IsValid())S->Fixture->Destroy();LWGen::FSite Site;Site.Type=Type;Site.Size=LWPlaces::Size(Type);Site.Position=FVector2D(20000,20000);Site.Id=777000+Type;Site.Friendly=true;auto* Chunk=GetWorld()->SpawnActor<ALWChunk>();S->Fixture=Chunk;Chunk->Building(P.World,Site);Chunk->SetActorLocation(FVector(0,0,5000));for(auto& O:Chunk->Residents)if(IsValid(O))O->AddActorWorldOffset(FVector(0,0,5000));
 LWV2Teleport(P,FVector(Site.Position,5115)+FVector(0,-Site.Size.Y*.5+350,0));P.Controller->SetControlRotation(FRotator(-5,50,0));if(Type==9||Type==6){float CX=(Site.Size.X*.5+180)*.5,CY=-Site.Size.Y*.5+(Site.Size.Y-720)/6+80;LWV2Teleport(P,FVector(Site.Position,5115)+FVector(CX-360,CY-170,0));P.Controller->SetControlRotation(FRotator(-8,25,0));}int Storage=0;for(AActor* A:Chunk->Residents)if(auto* O=Cast<ALWWorldObject>(A)){
 Check(O->UseType!=TEXT("radio"),TEXT("POI has no random radio"));
 if(O->Kind==ELWObjectKind::Container){++Storage;TArray<UTextRenderComponent*> Labels;O->GetComponents(Labels);Check(Labels.IsEmpty(),TEXT("storage has no floating label"));Check(P.World->Containers.Contains(O->RecordId),TEXT("furniture has persistent storage"));}}
 if(Type!=15&&Type!=16)Check(Storage>0,TEXT("interior storage furniture is searchable"));
 Check(Chunk->Batches.Num()>4&&Chunk->Residents.Num()>3,TEXT("furnished POI built with interactive props"));
 if(Type>=7&&Type<=9){int Slopes=0,Gables=0;for(auto& Pair:Chunk->Batches){auto* Batch=Pair.Value.Get();if(Batch->GetStaticMesh()==P.World->Mesh(TEXT("GableV13")))Gables+=Batch->GetInstanceCount();if(Pair.Key.ToString().StartsWith(TEXT("Cube_CorrugatedV7")))for(int J=0;J<Batch->GetInstanceCount();J++){FTransform Transform;Batch->GetInstanceTransform(J,Transform,false);if(FMath::Abs(Transform.Rotator().Roll)<1)continue;Slopes++;float Side=Transform.GetLocation().Y>Site.Position.Y?1.f:-1.f;FVector Out=Transform.GetRotation().RotateVector(FVector(0,Side*100,0));Check(Out.Z<0,TEXT("roof slopes down from ridge toward eaves"));}}Check(Slopes==2&&Gables==2,TEXT("house has two roof planes and solid gable ends"));}
 if(Type==7){Check(Chunk->Batches.Contains(TEXT("SofaV13_None_C"))&&Chunk->Batches.Contains(TEXT("CoffeeTableV13_None_C")),TEXT("ranch living room contains complete furniture group"));int Beds=0;for(AActor* A:Chunk->Residents)if(auto* O=Cast<ALWWorldObject>(A))if(O->UseType==TEXT("bed"))Beds++;Check(Beds==2,TEXT("ranch has two furnished bedrooms"));TSet<FName> Kitchen;for(AActor* A:Chunk->Residents)if(auto* O=Cast<ALWWorldObject>(A))if(O->Body->GetStaticMesh())Kitchen.Add(O->Body->GetStaticMesh()->GetFName());Check(Kitchen.Contains(TEXT("SM_FridgeV4"))&&Kitchen.Contains(TEXT("SM_StoveV4"))&&Kitchen.Contains(TEXT("SM_SinkV4")),TEXT("ranch kitchen has fridge stove and sink"));}

 },[this,Type](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("POI_%02d"),Type));});}
 Add(TEXT("ranch roof exterior"),.8,[this,S](ALWCharacter& P){if(S->Fixture.IsValid())S->Fixture->Destroy();LWGen::FSite Site;Site.Type=7;Site.Size=LWPlaces::Size(7);Site.Position=FVector2D(20000,20000);Site.Id=777007;Site.Friendly=true;auto* Chunk=GetWorld()->SpawnActor<ALWChunk>();S->Fixture=Chunk;Chunk->Building(P.World,Site);Chunk->SetActorLocation(FVector(0,0,5000));for(auto& O:Chunk->Residents)if(IsValid(O))O->AddActorWorldOffset(FVector(0,0,5000));LWV2Teleport(P,FVector(21800,17900,6100));P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);P.Controller->SetControlRotation((FVector(20000,20000,5350)-P.GetPawnViewLocation()).Rotation());},[this](ALWCharacter& P){CaptureV2(TEXT("RanchRoofV13"));P.GetCharacterMovement()->SetMovementMode(MOVE_Walking);});
 Add(TEXT("ranch living room view"),.7,[](ALWCharacter& P){LWV2Teleport(P,FVector(20000,19550,5115));P.Controller->SetControlRotation(FRotator(-8,155,0));},[this](ALWCharacter&){CaptureV2(TEXT("RanchLivingV13"));});
 Add(TEXT("ranch bedroom view"),.7,[](ALWCharacter& P){LWV2Teleport(P,FVector(19825,20180,5115));P.Controller->SetControlRotation(FRotator(-12,201,0));},[this](ALWCharacter&){CaptureV2(TEXT("RanchBedroomV13"));});
 Add(TEXT("storage depletion and legacy migration"),.5,[this](ALWCharacter& P){
 LWGen::FSite Site;Site.Id=888017;Site.Type=7;Site.Size=LWPlaces::Size(7);Site.Position=FVector2D(90000,90000);Site.Friendly=true;
 FLWContainerRecord Old;Old.Id=TEXT("site_888017_0");auto Item=LWItems::Make(TEXT("water"),3);FGuid Kept=Item.Id;Old.Items.Add(Item);P.World->Containers.Add(Old.Id,Old);
 auto* C=GetWorld()->SpawnActor<ALWChunk>();C->Building(P.World,Site);FName Id;int Copies=0;
 for(AActor* A:C->Residents)if(auto* O=Cast<ALWWorldObject>(A))if(O->Kind==ELWObjectKind::Container){if(Id.IsNone())Id=O->RecordId;for(const auto& I:P.World->Containers.FindChecked(O->RecordId).Items)Copies+=I.Id==Kept;}
 Check(Copies==1&&P.World->Containers.FindChecked(Old.Id).Items.IsEmpty(),TEXT("legacy items migrate exactly once"));
 if(!Id.IsNone()){P.World->Containers.FindChecked(Id).Items.Empty();C->Destroy();C=GetWorld()->SpawnActor<ALWChunk>();C->Building(P.World,Site);Check(P.World->Containers.FindChecked(Id).Items.IsEmpty(),TEXT("empty furniture stays empty after regeneration"));}C->Destroy();
 });
 for(int Mode=0;Mode<5;Mode++)Add(FString::Printf(TEXT("weather %d"),Mode),1,[this,S,Mode](ALWCharacter& P){
 if(S->Fixture.IsValid()){S->Fixture->Destroy();S->Fixture=nullptr;}LWV2Teleport(P,FVector(1400,2300,115));P.World->Stream(P.GetActorLocation(),true);P.Controller->SetControlRotation(FRotator(0,10,0));
 for(int Period=0;Period<200;Period++){if(Period%8!=3&&Period%8!=4)continue;uint32 H=LWGen::Hash(Period,0,P.World->Seed,8181)%100;int Type=H<28?0:H<52?1:H<68?2:H<89?3:4;if(Type!=Mode)continue;P.World->DayNumber=Period/8+1;P.World->TimeOfDay=(Period%8)*3+1;break;}
 P.World->TickWeather(0,&P);Check(P.World->WeatherType==Mode,TEXT("weather mode selects deterministically"));Check((P.World->RainAmount>0)==(Mode>=3),TEXT("rain is restricted to wet weather"));
 },[this,Mode](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("Weather_%d"),Mode));});
 Add(TEXT("midnight rollover and night lighting"),1,[this](ALWCharacter& P){P.World->TimeOfDay=23.999f;int D=P.World->DayNumber;P.World->TickWeather(2,&P);Check(P.World->DayNumber==D+1&&P.World->TimeOfDay<1,TEXT("day rolls over at midnight"));Check(P.World->SunLight->GetLightComponent()->Intensity<.1f,TEXT("sun turns off at night"));P.SaveProgress();int Saved=P.World->DayNumber;P.World->DayNumber=1;P.LoadProgress();Check(P.World->DayNumber==Saved,TEXT("day count persists"));},[this](ALWCharacter&){CaptureV2(TEXT("Night"));});
 Add(TEXT("regional map"),1,[this](ALWCharacter& P){P.ClosePanels();LWV2Teleport(P,FVector(1400,2300,115));P.World->Stream(P.GetActorLocation(),true);P.ToggleMap();Cast<ALWHUD>(Cast<APlayerController>(P.Controller)->GetHUD())->MapZoom=.0015f;},[this](ALWCharacter& P){CaptureV2(TEXT("V7_Map"));});
 Add(TEXT("V7 cleanup and save"),1,[this,S](ALWCharacter& P){P.ClosePanels();if(S->Fixture.IsValid())S->Fixture->Destroy();P.SaveProgress();P.LoadProgress();const auto* Quest=P.RPG.Quests.FindByPredicate([](const auto& Q){return Q.Id==TEXT("patrol");});Check(Quest&&Quest->Progress==2,TEXT("quest progress persists"));Check(P.World->Vehicles.Contains(TEXT("v7_supercar"))&&P.World->Vehicles[TEXT("v7_supercar")].Model==TEXT("supercar"),TEXT("vehicle model persists"));});
}
