#include "LWVehicleSpec.h"
#include "LWGeneration.h"
#include "Misc/AutomationTest.h"
#if WITH_DEV_AUTOMATION_TESTS
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWV7TrafficTest,"LethalWorld.V7.VehicleProfiles",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWV7TrafficTest::RunTest(const FString&){TMap<FName,int> Counts;for(uint32 I=0;I<100000;I++)Counts.FindOrAdd(LWTraffic::Choose(I))++;TestEqual(TEXT("all eleven models selected"),Counts.Num(),11);TestTrue(TEXT("supercars rarer than work vans"),Counts[TEXT("supercar")]<Counts[TEXT("van")]/5);for(const auto& S:LWTraffic::Specs()){TestTrue(TEXT("positive physical dimensions"),S.Wheelbase>100&&S.MaxSpeed>0&&S.CargoW>0&&S.Seats>=1);TestEqual(TEXT("stationary steering cannot rotate body"),LWTraffic::YawRate(S,0,30,false),0.f);TestTrue(TEXT("reverse steering reverses yaw"),LWTraffic::YawRate(S,-300,25,false)<0);float High=LWTraffic::YawRate(S,S.MaxSpeed,30,false);TestTrue(TEXT("cornering acceleration capped by tire grip"),High*S.MaxSpeed<=980*S.Grip+.1f);}return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWV7RegionsTest,"LethalWorld.V7.RegionDiversity",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWV7RegionsTest::RunTest(const FString&){TSet<int> Types;int Sparse=0,Towns=0;for(int Y=-6;Y<=6;Y++)for(int X=-6;X<=6;X++){TArray<LWGen::FRoad> R;TArray<LWGen::FSite> S;LWGen::Region({X,Y},198706,R,S);Sparse+=S.Num()<=1;Towns+=LWGen::HasTown({X,Y},198706);for(const auto& P:S){Types.Add(P.Type);TestTrue(TEXT("valid parcel type"),P.Type>=0&&P.Type<LWPlaces::Count);for(const auto& Other:S)if(P.Id!=Other.Id)TestFalse(TEXT("buildings retain parcel separation"),LWGen::ParcelsOverlap(P,Other));}TArray<LWGen::FRoad> R2;TArray<LWGen::FSite> S2;LWGen::Region({X,Y},198706,R2,S2);TestEqual(TEXT("region is deterministic"),S.Num(),S2.Num());}for(int T=0;T<32;T++)TestTrue(TEXT("all repeatable POI types occur"),Types.Contains(T));TestTrue(TEXT("rural gaps and limited towns"),Sparse>15&&Towns<120&&Towns>15);return true;}
#endif
