void ALWGameMode::BuildV9Smoke(ALWCharacter& Initial){
 BuildV7Smoke(Initial);
 if(FParse::Param(FCommandLine::Get(),TEXT("LWPOIOnly"))){V2->Steps.RemoveAll([](const FLWV2Step& Step){return Step.Name!=TEXT("V7 setup")&&!Step.Name.StartsWith(TEXT("POI "))&&!Step.Name.StartsWith(TEXT("ranch "))&&!Step.Name.StartsWith(TEXT("storage depletion"));});return;}
 auto Add=[this](FString N,double W,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,W,30,MoveTemp(B),MoveTemp(E),FLWV2Ready()});};
 struct FState{TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWWorldObject> Chair;};auto State=MakeShared<FState>();
 Add(TEXT("V9 wet windshield"),1,[this,State](ALWCharacter& P){P.NewGame();P.Health=10000;
 for(int Period=0;Period<200;Period++){uint32 H=LWGen::Hash(Period,0,P.World->Seed,8181)%100;if(H<68||Period%8!=4)continue;P.World->DayNumber=Period/8+1;P.World->TimeOfDay=13;break;}
 P.World->TickWeather(0,&P);P.World->SurfaceWetness=.9f;P.World->UpdateWetness(0);
 FLWVehicleRecord R;R.Model=TEXT("sedan");R.VIN=FGuid::NewDeterministicGuid(TEXT("v9_glass"));R.Position=FVector(3000,2800,75);R.Unlocked=R.Hotwired=true;P.World->Vehicles.Add(TEXT("v9_glass"),R);State->Car=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,TEXT("v9_glass"),R.Position));auto* C=State->Car.Get();LWV2Teleport(P,R.Position+FVector(-200,-200,50));Check(C&&C->Enter(&P),TEXT("enter rebuilt car"));if(!C)return;
 Check(C->Body->GetStaticMesh()->GetName()==TEXT("SM_Vehicle_sedan_V9"),TEXT("vehicle uses rebuilt shell"));Check(C->Headlamps[0]->Intensity>=900000&&P.Flashlight->Intensity>=180000,TEXT("headlights and flashlight upgraded"));P.World->RainAmount=1;C->TickGlass(8);Check(C->WindshieldWater>.8f&&C->GlassWet,TEXT("rain accumulates on windshield"));C->Headlights=true;
 },[this](ALWCharacter&){CaptureV2(TEXT("V9_WetWindshield"));});
 Add(TEXT("V9 wipers clear windshield"),1,[this,State](ALWCharacter& P){if(auto* C=State->Car.Get()){C->Control(TEXT("wipers"));C->TickGlass(2);Check(C->WipersOn&&C->WindshieldWater<.05f,TEXT("wiper control clears accumulated water"));}},[this](ALWCharacter&){CaptureV2(TEXT("V9_WipersClear"));});
 Add(TEXT("V9 moisture dries and persists"),.5,[this,State](ALWCharacter& P){if(auto* C=State->Car.Get()){C->Speed=0;C->Exit(true);}P.World->SurfaceWetness=0;P.World->RainAmount=1;P.World->UpdateWetness(60);Check(P.World->SurfaceWetness>.7f,TEXT("rain builds surface moisture"));float Wet=P.World->SurfaceWetness;P.World->RainAmount=0;P.World->UpdateWetness(120);Check(P.World->SurfaceWetness>0&&P.World->SurfaceWetness<Wet,TEXT("surfaces dry gradually after rain"));P.SaveProgress();Wet=P.World->SurfaceWetness;P.World->SurfaceWetness=0;P.LoadProgress();Check(FMath::IsNearlyEqual(P.World->SurfaceWetness,Wet),TEXT("surface moisture persists"));P.World->RainAmount=0;P.World->UpdateWetness(1000);Check(P.World->SurfaceWetness==0,TEXT("puddles eventually dry completely"));});
 Add(TEXT("V9 sleeping and sitting"),.5,[this,State](ALWCharacter& P){P.EnterSafehouse();P.bSafehouse=true;P.Hunger=P.Thirst=80;float Before=(P.World->DayNumber-1)*24+P.World->TimeOfDay;Check(P.SleepInBed(),TEXT("bed permits safe sleep"));float After=(P.World->DayNumber-1)*24+P.World->TimeOfDay;Check(FMath::IsNearlyEqual(After-Before,4.f,.001f),TEXT("sleep skips four hours including midnight"));Check(P.Hunger==75&&P.Thirst==75,TEXT("sleep uses food and water"));auto* C=P.World->SpawnObject(ELWObjectKind::Furniture,TEXT("v9_chair"),P.GetActorLocation()+FVector(100,0,-88));C->SetFurniture(TEXT("chair"));State->Chair=C;C->Use(&P);Check(P.SittingChair==C&&P.GetCharacterMovement()->MovementMode==MOVE_None,TEXT("using chair seats player and disables walking"));},[this](ALWCharacter&){CaptureV2(TEXT("V9_Seated"));});
 Add(TEXT("V9 stand from chair"),.2,[this,State](ALWCharacter& P){P.Interact();Check(!P.SittingChair&&P.GetCharacterMovement()->MovementMode==MOVE_Walking,TEXT("interact stands and restores movement"));if(State->Chair.IsValid())State->Chair->Destroy();});
 Add(TEXT("V9 mannequin location rules"),.5,[this](ALWCharacter& P){
 int Watchers=0,Props=0;for(int Type=0;Type<LWPlaces::Count;Type++){LWGen::FSite S;S.Id=918000+Type;S.Type=Type;S.Size=LWPlaces::Size(Type);S.Position=FVector2D(80000+Type*10000,80000);auto* C=GetWorld()->SpawnActor<ALWChunk>();C->Building(P.World,S);
 for(AActor* A:C->Residents){if(auto* Z=Cast<ALWZombie>(A))if(Z->Kind==ELWEnemyKind::Mannequin){Watchers++;Check(Type==18,TEXT("mannequin enemies spawn only at boutique"));}if(auto* O=Cast<ALWWorldObject>(A))if(O->Kind==ELWObjectKind::MannequinDisplay){Props++;Check(O->Body->GetStaticMesh()==P.World->Mesh(TEXT("MannequinTorso")),TEXT("display and enemy use matching body mesh"));}}
 C->Destroy();}Check(Watchers>0&&Props>0,TEXT("boutique mixes watchers and display mannequins"));});
 Add(TEXT("V9 world setup"),.5,[this](ALWCharacter& P){P.BeginWorldSetup();P.WorldSetupClick(TEXT("seed"));auto* PC=Cast<APlayerController>(P.Controller);PC->InputKey(FInputKeyParams(EKeys::Seven,IE_Pressed,1.));},[this](ALWCharacter& P){Cast<APlayerController>(P.Controller)->InputKey(FInputKeyParams(EKeys::Seven,IE_Released,0.));Check(P.SeedText==TEXT("7"),TEXT("seed accepts real keyboard input while paused"));P.SeedText=TEXT("731904");P.SetupTowns=2;P.SetupPOIs=0;P.SetupTerrain=2;P.SetupDifficulty=2;CaptureV2(TEXT("V9_WorldSetup"));});
 Add(TEXT("V9 create customized world"),.5,[this](ALWCharacter& P){P.WorldSetupClick(TEXT("createworld"));P.OpeningClick(TEXT("intro_skip"));P.OpeningClick(TEXT("creator_done"));Check(P.World->Seed==731904&&P.World->TownSetting==2&&P.World->POISetting==0&&P.World->TerrainSetting==2&&P.World->Difficulty==2,TEXT("new game applies seed generation and difficulty settings"));P.SaveProgress();P.World->Seed=1;P.World->Difficulty=0;P.LoadProgress();Check(P.World->Seed==731904&&P.World->Difficulty==2&&LWGen::ParcelLevel==0,TEXT("world settings persist on load"));});
}
