#include "Components/BoxComponent.h"
void ALWGameMode::BuildVehicle49Smoke(ALWCharacter& Initial){
 struct FState{TWeakObjectPtr<ALWVehicle> Car;TWeakObjectPtr<ALWZombie> Boss;float Health=0,CarHealth=0;};auto S=MakeShared<FState>();
 auto Add=[this](FString N,double D,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,D,120,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){return true;}});};
 Add(TEXT("setup"),1,[](ALWCharacter& P){P.NewGame();P.RPG.Story.Enabled=false;P.ClosePanels();P.LeaveSafehouse();P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.World->SetActorTickEnabled(false);P.Health=10000;P.bCrust=false;P.GetCharacterMovement()->SetMovementMode(MOVE_Flying);for(TActorIterator<ALWVehicle> I(P.GetWorld());I;++I)I->Destroy();for(TActorIterator<ALWZombie> I(P.GetWorld());I;++I)I->Destroy();auto* F=P.GetWorld()->SpawnActor<ALWChunk>();F->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(40000,40000,20));for(TActorIterator<ADirectionalLight> I(P.GetWorld());I;++I){I->SetActorRotation(FRotator(-55,-40,0));I->GetLightComponent()->SetIntensity(5);}});
 for(const auto& Spec:LWTraffic::Specs()){FName Model(Spec.Id);
  Add(TEXT("driver view ")+Model.ToString(),.5,[this,S,Model](ALWCharacter& P){if(auto* C=S->Car.Get()){C->Exit(true);C->Destroy();}const FVector At(20000,20000,5075);FLWVehicleRecord R;R.VIN=FGuid::NewGuid();R.Model=Model;R.Position=At;R.Unlocked=R.Hotwired=true;R.FuelLitres=35;R.FuelLootInitialized=true;FName Id(*(TEXT("qa49_")+Model.ToString()));P.World->Vehicles.Add(Id,R);auto* C=Cast<ALWVehicle>(P.World->SpawnObject(ELWObjectKind::Car,Id,At));S->Car=C;if(!RequireV2(C!=nullptr,TEXT("car spawned")))return;C->SpawnPlacementPending=false;C->SetActorHiddenInGame(false);C->SetActorEnableCollision(true);C->SetActorTickEnabled(false);C->SetActorLocation(At);LWV2Teleport(P,At+FVector(0,-C->Spec().HalfWidth-80,10));Check(C->Enter(&P),TEXT("driver enters"));P.SeatYaw=P.SeatPitch=0;P.TickVehicleSeat();C->Speed=0;C->TickInstruments42(0);Check(FMath::IsNearlyEqual(C->GaugeNeedles42[0]->GetRelativeRotation().Roll,-130.f),TEXT("zero speed needle points to start of dial"));C->Speed=160/.0223694f;C->TickInstruments42(0);Check(FMath::IsNearlyEqual(C->GaugeNeedles42[0]->GetRelativeRotation().Roll,130.f),TEXT("full speed needle points to end of dial"));C->Speed=0;C->TickInstruments42(0);},[this,Model](ALWCharacter&){CaptureV2(*(TEXT("Driver49_")+Model.ToString()));});
 }
 Add(TEXT("flip buried bus"),1,[this,S](ALWCharacter& P){auto* C=S->Car.Get();C->Exit(true);C->Record()->Model=TEXT("bus");C->Chassis->SetBoxExtent(FVector(490,120,48));C->SetActorLocationAndRotation(FVector(20000,20000,4820),FRotator(65,0,70));LWV2Teleport(P,FVector(20000,19400,5100));auto VIN=C->Record()->VIN;Check(C->Flip49(&P),TEXT("buried tilted coach recovered"));Check(FMath::Abs(C->GetActorRotation().Pitch)<1&&FMath::Abs(C->GetActorRotation().Roll)<1&&C->GetActorLocation().Z>5000,TEXT("recovery restores upright above floor"));Check(C->Record()->VIN==VIN,TEXT("recovery preserves vehicle identity"));C->Record()->Model=TEXT("supercar");C->Chassis->SetBoxExtent(FVector(225,100,48));});
 Add(TEXT("boss grabs occupied car"),2,[this,S](ALWCharacter& P){auto* C=S->Car.Get();C->SetActorLocation(FVector(21000,20000,5075));LWV2Teleport(P,C->GetActorLocation()+FVector(0,-180,0));C->Enter(&P);P.Health=10000;S->Health=P.Health;S->CarHealth=C->Record()->Health;auto* B=GetWorld()->SpawnActor<ALWZombie>(FVector(20000,20000,5088),FRotator::ZeroRotator);B->ConfigureKind(ELWEnemyKind::Behemoth);B->SetActorTickEnabled(false);B->ThrowCooldown49=0;S->Boss=B;Check(B->TickCarAttack49(.1f,&P)&&C->Held49,TEXT("behemoth chooses occupied vehicle"));Check(!C->Flip49(&P),TEXT("held vehicle cannot be recovered"));for(int I=0;I<40;++I){C->TickThrown49(.05f);B->TickCarAttack49(.05f,&P);}Check(C->Airborne49&&!C->Held49,TEXT("windup releases occupied vehicle"));Check(P.Vehicle==C,TEXT("player stays seated during throw"));C->SetActorTickEnabled(true);},[this,S](ALWCharacter& P){Check(S->Car->GetActorLocation().X>21500,TEXT("throw carries vehicle away from boss"));});
 Add(TEXT("throw impact"),5,[](ALWCharacter&){},[this,S](ALWCharacter& P){auto* C=S->Car.Get();Check(!C->Airborne49,TEXT("thrown car lands"));Check(C->Record()->Health<S->CarHealth,TEXT("throw impact damages vehicle"));Check(P.Health<S->Health,TEXT("throw impact damages occupant"));if(P.Vehicle)C->Exit(true);S->Boss->Destroy();});
 Add(TEXT("colossus throws empty car and interrupted grab"),.5,[this,S](ALWCharacter& P){auto* C=S->Car.Get();C->SetActorTickEnabled(false);C->SetActorLocation(FVector(21000,20000,5075));C->Record()->Health=200;C->Record()->Exploded=false;C->Record()->FireRemaining=0;LWV2Teleport(P,FVector(23500,20000,5100));auto* B=GetWorld()->SpawnActor<ALWZombie>(FVector(20000,20000,5088),FRotator::ZeroRotator);B->ConfigureKind(ELWEnemyKind::Colossus);B->SetActorTickEnabled(false);B->ThrowCooldown49=0;Check(B->TickCarAttack49(.1f,&P)&&C->Held49,TEXT("colossus grabs empty vehicle"));for(int I=0;I<40;++I){C->TickThrown49(.05f);B->TickCarAttack49(.05f,&P);}Check(C->Airborne49&&FVector::DotProduct(C->FlightVelocity49.GetSafeNormal2D(),(P.GetActorLocation()-C->GetActorLocation()).GetSafeNormal2D())>.8f,TEXT("empty car aimed at player"));C->Airborne49=false;C->SetActorLocation(FVector(21000,20000,5075));Check(C->Grab49(B),TEXT("second grab"));B->bDead=true;C->TickThrown49(.05f);Check(!C->Held49&&C->Airborne49,TEXT("dead grabber releases car instead of suspending it"));B->Destroy();C->Destroy();});
}
