if(FParse::Param(FCommandLine::Get(),TEXT("LWVisual63Smoke"))){
 struct FState63{TArray<TWeakObjectPtr<ALWZombie>> NPCs;TWeakObjectPtr<ALWWorldObject> Bench;};auto State=MakeShared<FState63>();
 Add(TEXT("63 complete NPC library"),2,[this,State](ALWCharacter& P){P.NewGame();P.ClosePanels();P.bMenu=false;P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.bGod47=true;P.SetMenuInput(false);P.World->TimeOfDay=12;Cast<APlayerController>(P.Controller)->ConsoleCommand(TEXT("r.ScreenPercentage 100"));
 for(int K=0;K<15;K++){auto* N=GetWorld()->SpawnActor<ALWZombie>(P.GetActorLocation()+FVector(600+K*600,0,500),FRotator::ZeroRotator);N->ConfigureKind(ELWEnemyKind(K));N->SetActorTickEnabled(false);N->SetActorHiddenInGame(true);State->NPCs.Add(N);for(auto& C:N->Parts)Check(C->GetStaticMesh()&&C->GetStaticMesh()->GetPathName().Contains(TEXT("Models63")),TEXT("NPC part resolves rebuilt library"));}
 for(const TCHAR* N:{TEXT("TraderBody32"),TEXT("TraderHead32"),TEXT("TraderWheel32"),TEXT("SentinelTorso51"),TEXT("SentinelHead51"),TEXT("SentinelArm51"),TEXT("SentinelLeg51")})Check(P.World->Mesh(N)&&P.World->Mesh(N)->GetPathName().Contains(TEXT("Models63")),TEXT("robot and border guard revision"));
 for(const auto& A:LWArsenal62::Attachments()){const FString N=A.Id.ToString();Check(P.World->Mesh(FName(*N))&&P.World->Mesh(FName(*N))->GetPathName().Contains(TEXT("Models63")),TEXT("gunsmith attachment revision"));}
 for(const TCHAR* N:{TEXT("att_reflexV14"),TEXT("att_holoV14"),TEXT("att_scope4V14"),TEXT("att_scope8V14"),TEXT("att_lightV14"),TEXT("att_laserV14"),TEXT("att_verticalV14"),TEXT("att_angledV14")})Check(P.World->Mesh(N)&&P.World->Mesh(N)->GetPathName().Contains(TEXT("Models63")),TEXT("legacy attachment now detailed"));
 });
 Add(TEXT("63 optic bench"),3,[this,State](ALWCharacter& P){for(auto N:State->NPCs)if(N.IsValid())N->Destroy();P.Inventory.Empty();auto G=LWItems::Make(TEXT("rifle"));G.Slot=TEXT("Primary");P.Inventory.Add(G);P.ActiveWeaponId=G.Id;P.Equip(6);for(FName Id:{FName(TEXT("att_micro63")),FName(TEXT("att_tube63")),FName(TEXT("att_prism63")),FName(TEXT("att_combat63")),FName(TEXT("att_marksman63"))}){auto I=LWItems::Make(Id);LWItems::Place(P.Inventory,I,12,LWItems::InventoryHeight(P.Inventory));}auto* S=GetWorld()->SpawnActor<ALWWorldObject>(P.GetActorLocation()+FVector(100,0,0),FRotator::ZeroRotator);S->Configure(P.World,ELWObjectKind::Furniture,TEXT("bench63"));S->SetFurniture(TEXT("workbench"));State->Bench=S;P.OpenWorkbench39(S);auto* B=P.Workbench39.Get();Check(B&&B->Load(G.Id),TEXT("new sights load in workbench"));B->Tab62=1;B->Mount62=TEXT("Optic");Check(B->Available().Num()==5,TEXT("five new sights listed"));},[this](ALWCharacter& P){CaptureV2(TEXT("Visual63_Optics"));});
 for(int I=0;I<5;I++)Add(FString::Printf(TEXT("63 optic %d"),I),2,[this,I](ALWCharacter& P){const FName IDs[]={TEXT("att_micro63"),TEXT("att_tube63"),TEXT("att_prism63"),TEXT("att_combat63"),TEXT("att_marksman63")};auto* B=P.Workbench39.Get();const auto* Item=B->Draft.Bank.FindByPredicate([&](const auto& X){return X.Definition==IDs[I];});Check(Item&&B->Add(Item->Id),TEXT("new sight installs and replaces previous optic"));B->FrameAll();B->Distance*=.62;B->Center=LWMods::Position(6,TEXT("Optic"));},[this,I](ALWCharacter& P){CaptureV2(*FString::Printf(TEXT("Visual63_Sight%d"),I));});
 return;
}
