void ALWGameMode::BuildWorld26Smoke(ALWCharacter& Initial){
 auto Add=[this](FString N,double Wait,FLWV2Action B,FLWV2Action E=FLWV2Action()){V2->Steps.Add({N,Wait,120,MoveTemp(B),MoveTemp(E),[](ALWCharacter&){
#if WITH_EDITOR
 return !GShaderCompilingManager||!GShaderCompilingManager->IsCompiling();
#else
 return true;
#endif
 }});};
 struct FState {TWeakObjectPtr<ALWChunk> Floor,POI;TWeakObjectPtr<ALWZombie> Enemy;};auto S=MakeShared<FState>();
 Add(TEXT("world26 fixtures"),3,[this,S](ALWCharacter& P){P.NewGame();P.LeaveSafehouse();P.Health=10000;P.World->EnableEncounters=false;P.World->TimeOfDay=12;P.World->WeatherOverride=0;P.World->TickWeather(0,&P);auto* C=GetWorld()->SpawnActor<ALWChunk>();C->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(8000,8000,20));S->Floor=C;LWV2Teleport(P,FVector(20000,20000,5090));P.Controller->SetControlRotation(FRotator(0,0,0));});
 Add(TEXT("discovery uniqueness"),2,[this](ALWCharacter& P){const auto XP=P.RPG.XP;Check(P.DiscoverPlace(0xff123456,FVector(20700,20000,5000),TEXT("OLD CIVIL DEPOT")),TEXT("new place discovered"));Check(!P.DiscoverPlace(0xff123456,FVector(20700,20000,5000),TEXT("OLD CIVIL DEPOT")),TEXT("repeat discovery does not award XP"));Check(P.RPG.XP==XP+35,TEXT("discovery awards 35 XP once"));},[this](ALWCharacter&){CaptureV2(TEXT("World26_Discovery"));});
 Add(TEXT("fast travel"),2,[this](ALWCharacter& P){P.ToggleMap();P.SetWaypoint(FVector2D(29000,29000));Check(!P.FastTravel(),TEXT("undiscovered destination rejected"));P.SetWaypoint(FVector2D(20700,20000));P.LastCombatTime=GetWorld()->GetTimeSeconds();Check(!P.FastTravel(),TEXT("recent combat blocks travel"));P.LastCombatTime=-1000;Check(P.FastTravel(),TEXT("discovered safe destination travels"));Check(FVector::Dist2D(P.GetActorLocation(),FVector(20700,20000,0))<1500,TEXT("arrival near discovered entrance"));});
 for(int K=0;K<9;K++){
 Add(TEXT("enemy model and behavior"),2,[this,S,K](ALWCharacter& P){if(S->Enemy.IsValid())S->Enemy->Destroy();P.ClosePanels();P.LastCombatTime=-1000;LWV2Teleport(P,FVector(20000,20000,5090));P.Controller->SetControlRotation(FRotator(-3,0,0));auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20400,20000,5090),FRotator(0,180,0));S->Enemy=Z;Z->PersistentId=2600+K;Z->ConfigureKind(ELWEnemyKind(K));Z->SetActorTickEnabled(false);Z->bAggressive=true;Z->Alert=10;Z->Interest=P.GetActorLocation();
  for(auto Part:Z->Parts)Check(Part->GetStaticMesh()!=nullptr,TEXT("enemy segmented model available"));Z->DecisionClock=0;Z->TickBrain(.01f,&P);Check(Z->HasVisual,TEXT("enemy perceives visible player"));
  if(K==1)Check(Z->RaiderRounds<12,TEXT("raider fires actual magazine rounds"));
  const FVector Before=Z->Interest;P.SetActorLocation(FVector(20000,25000,5090));Z->DecisionClock=1;Z->TickBrain(.05f,&P);Check(Z->Interest.Equals(Before),TEXT("target memory does not track unseen movement"));LWV2Teleport(P,FVector(20000,20000,5090));
 },[this,K](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("World26_Enemy_%d"),K));});}
 Add(TEXT("combat counterplay"),2,[this,S](ALWCharacter& P){
 if(S->Enemy.IsValid())S->Enemy->Destroy();LWV2Teleport(P,FVector(20000,20000,5090));
 auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20100,20000,5090),FRotator(0,180,0));S->Enemy=Z;Z->SetActorTickEnabled(false);Z->Alert=10;Z->DecisionClock=0;Z->AttackCooldown=0;float HP=P.Health;Z->TickBrain(.01f,&P);Check(Z->AttackWindup>0&&P.Health==HP,TEXT("melee attack telegraphs before applying damage"));P.SetActorLocation(FVector(19500,20000,5090));Z->TickBrain(1,&P);Check(P.Health==HP,TEXT("moving out of reach evades committed melee"));
 auto* Wall=GetWorld()->SpawnActor<ALWChunk>();Wall->Box(P.World,TEXT("Concrete"),FVector(19800,20000,5120),FVector(30,800,260));Z->DecisionClock=0;Z->TickBrain(.01f,&P);Check(!Z->HasVisual,TEXT("solid wall blocks enemy perception"));Wall->Destroy();
 Z->Destroy();LWV2Teleport(P,FVector(20000,20000,5090));
 });
 Add(TEXT("dismemberment balance"),.2,[this,S](ALWCharacter& P){if(S->Enemy.IsValid())S->Enemy->Destroy();auto* Z=GetWorld()->SpawnActor<ALWZombie>(FVector(20300,20000,5090),FRotator::ZeroRotator);S->Enemy=Z;Z->SetActorTickEnabled(false);FDamageEvent Generic;Z->Dismember(Generic,&P,500);Check(Z->SeveredMask==0,TEXT("generic damage cannot randomly sever living limbs"));FPointDamageEvent E;E.HitInfo=FHitResult(Z,Z->Parts[5],Z->Parts[5]->Bounds.Origin,FVector::UpVector);Z->Dismember(E,&P,45);Check(!Z->Missing(5),TEXT("single ordinary limb hit does not sever"));Z->Dismember(E,&P,55);Check(Z->Missing(5),TEXT("focused limb damage can still sever"));Check(Z->InjurySpeed()>.5f,TEXT("single leg loss remains mobile"));Z->Destroy();});
 for(int W=5;W<=10;W++)Add(TEXT("severe weather"),2,[this,W](ALWCharacter& P){if(W==5){LWV2Teleport(P,FVector(20000,15000,300));P.Controller->SetControlRotation(FRotator(6,0,0));}P.World->WeatherOverride=W;P.bIndoors=false;P.World->TickWeather(.1f,&P);Check(P.World->WeatherType==W,TEXT("weather mode active"));Check(P.World->StormParticles!=nullptr,TEXT("weather particles created"));Check(P.World->VisibilityRange<=6000,TEXT("weather perception distance set"));if(W==6){P.World->StormOrigin=FVector(24000,15000,0);P.World->TornadoActive=true;P.World->TickWeather(.1f,&P);}},[this,W](ALWCharacter&){CaptureV2(*FString::Printf(TEXT("World26_Weather_%d"),W));});
 Add(TEXT("POI floor composition"),4,[this,S](ALWCharacter& P){P.World->WeatherOverride=0;P.World->TickWeather(.1f,&P);auto* C=GetWorld()->SpawnActor<ALWChunk>();S->POI=C;LWGen::FSite Site;Site.Type=17;Site.Size=LWPlaces::Size(17);Site.Position=FVector2D(20000,20000);Site.Id=260017;C->BuildingSurfaces=true;C->Building(P.World,Site);C->BuildingSurfaces=false;C->FlushSurfaces();C->SetActorLocation(FVector(0,0,5000));for(auto A:C->Residents)if(IsValid(A))A->AddActorWorldOffset(FVector(0,0,5000));LWV2Teleport(P,FVector(20000,18800,5125));P.Controller->SetControlRotation(FRotator(-5,75,0));Check(C->SurfaceMeshes.Num()>0,TEXT("POI uses composed non-overlapping surfaces"));},[this](ALWCharacter&){CaptureV2(TEXT("World26_PoliceFloor"));});
 Add(TEXT("cleanup"),1,[S](ALWCharacter& P){P.World->WeatherOverride=-1;if(S->Enemy.IsValid())S->Enemy->Destroy();if(S->POI.IsValid())S->POI->Destroy();if(S->Floor.IsValid())S->Floor->Destroy();});
}
