#include "LWWorkbench39.h"
#include "LWWeaponParts39.h"
#include "LWWeaponMods.h"
#include "Components/SceneCaptureComponent2D.h"
void ALWGameMode::BuildWorkbench39Smoke(ALWCharacter& Initial){
 struct FState{TWeakObjectPtr<ALWWorldObject> Bench;TWeakObjectPtr<ALWZombie> Enemy;FGuid Gun;uint32 Before=0;};auto S=MakeShared<FState>();
 auto Add=[this](const TCHAR* N,double Delay,FLWV2Action Begin,FLWV2Action End=FLWV2Action()){V2->Steps.Add({N,Delay,120,MoveTemp(Begin),MoveTemp(End),[](ALWCharacter&){return true;}});};
 Add(TEXT("Bench setup"),2,[this,S](ALWCharacter& P){P.NewGame();P.ClosePanels();P.bMenu=false;P.SetMenuInput(false);P.RPG.Story.Enabled=false;P.World->EnableEncounters=false;P.Health=10000;P.Inventory.Empty();auto G=LWItems::Make(TEXT("smg"));G.Slot=TEXT("Primary");G.WeaponTier=3;G.WeaponSkin=-1;G.Chamber=1;P.Inventory.Add(G);P.ActiveWeaponId=G.Id;P.Equip(5);S->Gun=G.Id;auto Rev=LWItems::Make(TEXT("revolver"));Rev.Cylinder.Init(1,6);LWItems::Place(P.Inventory,Rev,12,10);for(FName Id:{FName(TEXT("part_barrel_09")),FName(TEXT("part_barrel_08")),FName(TEXT("part_stock_00")),FName(TEXT("att_reflex")),FName(TEXT("att_laser"))}){auto I=LWItems::Make(Id);if(LWParts39::Find(Id)){I.WeaponTier=4;I.LegendaryModifier=TEXT("Two Shot");}LWItems::Place(P.Inventory,I,12,10);}auto* B=GetWorld()->SpawnActor<ALWWorldObject>(P.GetActorLocation()+FVector(160,0,-85),FRotator::ZeroRotator);B->Configure(P.World,ELWObjectKind::Furniture,TEXT("test_weaponbench39"));B->SetFurniture(TEXT("workbench"));S->Bench=B;S->Before=LWParts39::Fingerprint(P.Inventory);B->UseFurniture(&P);Check(P.Workbench39&&P.IsUIOpen()&&!P.CanAct(),TEXT("furniture opens bench and blocks attacks"));if(P.Workbench39){auto* Bench=P.Workbench39.Get();Check(Bench->Load(G.Id),TEXT("equipped weapon loads into draft"));Check(Bench->Meshes.Num()==Bench->Draft.Gun.Parts39.Num(),TEXT("all recipe meshes represented"));for(auto& M:Bench->Meshes)Check(M&&M->GetStaticMesh(),TEXT("part asset loads"));}P.Attack();Check(P.ActiveGun()&&P.ActiveGun()->Chamber==1,TEXT("bench click cannot shoot"));},[this](ALWCharacter& P){CaptureV2(TEXT("Workbench39_Edit"));});
 Add(TEXT("Freeform edits"),3,[this,S](ALWCharacter& P){auto* B=P.Workbench39.Get();if(!B)return;auto* Part=B->Draft.Bank.FindByPredicate([](const auto& I){return I.Definition==TEXT("part_barrel_09");});if(!Part)return;Check(B->Add(Part->Id),TEXT("cross-family part added"));B->Mode=0;B->Snapshot();B->Transform(FVector(0,14,7));const auto Pos=B->Draft.Gun.Parts39.Last().Transform.GetLocation();B->Undo();Check(!B->Draft.Gun.Parts39.Last().Transform.GetLocation().Equals(Pos),TEXT("undo reverses transform"));B->Undo(true);Check(B->Draft.Gun.Parts39.Last().Transform.GetLocation().Equals(Pos),TEXT("redo restores transform"));B->Mode=1;B->Transform(FVector(0,0,180));auto* Optic=B->Draft.Bank.FindByPredicate([](const auto& I){return I.Definition==TEXT("att_reflex");});if(Optic)B->Add(Optic->Id);auto* Laser=B->Draft.Bank.FindByPredicate([](const auto& I){return I.Definition==TEXT("att_laser");});if(Laser)B->Add(Laser->Id);B->Yaw=145;B->Distance=210;B->SetBuildName39(TEXT("DOUBLE TROUBLE"));Check(LWParts39::Fingerprint(P.Inventory)==S->Before,TEXT("preview edits do not mutate inventory"));const auto Rot=B->Capture->GetRelativeRotation();B->Yaw+=25;B->UpdateCamera();Check(!Rot.Equals(B->Capture->GetRelativeRotation()),TEXT("live orbit changes capture camera"));},[this](ALWCharacter& P){CaptureV2(TEXT("Workbench39_Custom"));});
 Add(TEXT("Apply and persistence"),2,[this,S](ALWCharacter& P){auto* B=P.Workbench39.Get();if(!B)return;Check(B->Apply(),TEXT("apply commits draft"));auto* G=P.FindItem(S->Gun);Check(G&&G->Parts39.Num()>=7&&G->CustomName39==TEXT("DOUBLE TROUBLE"),TEXT("custom assembly stored"));Check(G&&LWMods::Effect(G,TEXT("Two Shot")),TEXT("legendary part effect active"));Check(P.CustomMeshes39.Num()>=5&&P.WeaponMesh->GetStaticMesh()==nullptr,TEXT("equipped weapon uses custom geometry"));const uint32 Saved=LWParts39::Fingerprint(P.Inventory);P.SaveProgress();P.LoadProgress();Check(LWParts39::Fingerprint(P.Inventory)==Saved,TEXT("disk save/load retains assembly"));P.ClosePanels();P.OpenWorkbench39(S->Bench.Get());B=P.Workbench39.Get();if(!B)return;B->Load(S->Gun);Check(B->Dismantle(),TEXT("custom assembly dismantles in draft"));const int Parts=B->Draft.Bank.FilterByPredicate([](const auto& I){return LWParts39::Find(I.Definition)!=nullptr;}).Num();Check(Parts>=7,TEXT("dismantle recovers structural parts"));P.ClosePanels();Check(P.FindItem(S->Gun)!=nullptr,TEXT("cancel discards dismantle"));});
 Add(TEXT("Conflict guard"),1,[this,S](ALWCharacter& P){P.OpenWorkbench39(S->Bench.Get());auto* B=P.Workbench39.Get();if(!B)return;B->Load(S->Gun);P.Inventory[0].Durability-=1;Check(!B->Apply(),TEXT("external inventory changes block stale draft"));P.ClosePanels();});
 Add(TEXT("Custom live fire"),3,[this,S](ALWCharacter& P){P.ReleaseAttackInput();P.ClosePanels();P.LeaveSafehouse();P.World->TimeOfDay=12;P.World->TickWeather(0,&P);LWV2Teleport(P,FVector(20000,20000,5110));auto* F=GetWorld()->SpawnActor<ALWChunk>();F->Box(P.World,TEXT("Concrete"),FVector(20000,20000,4990),FVector(10000,10000,20));P.Controller->SetControlRotation(FRotator::ZeroRotator);P.Camera->SetWorldRotation(FRotator::ZeroRotator);P.ActiveWeaponId=S->Gun;P.Weapon=5;P.ConfigureWeaponParts();P.UpdateWeapon(.016);auto* G=P.ActiveGun();if(!G)return;G->Chamber=1;P.AttackTimer=0;P.Attack();Check(G->Chamber!=1,TEXT("custom discharge consumes action ammunition"));int FX=0;for(TActorIterator<ALWWeaponEffect> It(GetWorld());It;++It)if(It->GetOwner()==&P&&It->Mode>=3)++FX;Check(FX>=4,TEXT("multiple barrel muzzles emit visual fire effects"));Check(P.CustomMeshes39.Num()>0&&P.CustomMeshes39[0]->IsVisible(),TEXT("custom gun visible in first person"));},[this](ALWCharacter& P){CaptureV2(TEXT("Workbench39_Equipped"));});
 Add(TEXT("Capture flush"),2,[](ALWCharacter& P){});
}
