#include "Materials/MaterialInterface.h"
#include "LWMystic62.h"
#include "LWWorkbench39.h"
#include "LWWeaponParts39.h"
#include "LWWeaponMods.h"
#include "LWCharacter.h"
#include "LWWorld.h"
#include "LWWorldObject.h"
#include "Components/SceneCaptureComponent2D.h"
#include "Components/StaticMeshComponent.h"
#include "Components/PointLightComponent.h"
#include "Engine/TextureRenderTarget2D.h"
#include "Engine/World.h"
#include "Engine/StaticMesh.h"
#include "GameFramework/CharacterMovementComponent.h"
ALWWorkbench39::ALWWorkbench39(){PrimaryActorTick.bCanEverTick=true;SetRootComponent(CreateDefaultSubobject<USceneComponent>(TEXT("BenchRoot")));Capture=CreateDefaultSubobject<USceneCaptureComponent2D>(TEXT("Preview"));Capture->SetupAttachment(RootComponent);Capture->PrimitiveRenderMode=ESceneCapturePrimitiveRenderMode::PRM_UseShowOnlyList;Capture->CaptureSource=ESceneCaptureSource::SCS_FinalColorLDR;Capture->FOVAngle=40;Capture->bCaptureEveryFrame=false;Capture->bCaptureOnMovement=false;Capture->ShowFlags.SetAtmosphere(false);Capture->ShowFlags.SetFog(false);Capture->ShowFlags.SetMotionBlur(false);Capture->ShowFlags.SetTemporalAA(false);Capture->PostProcessSettings.bOverride_AutoExposureMethod=true;Capture->PostProcessSettings.AutoExposureMethod=AEM_Manual;Capture->PostProcessSettings.bOverride_AutoExposureBias=true;Capture->PostProcessSettings.AutoExposureBias=7;
 for(int i=0;i<2;++i){auto* L=CreateDefaultSubobject<UPointLightComponent>(i?TEXT("Fill"):TEXT("Key"));L->SetupAttachment(RootComponent);L->SetRelativeLocation(i?FVector(-80,110,60):FVector(60,-100,140));L->SetIntensity(i?6500:12000);L->SetAttenuationRadius(800);L->SetLightingChannels(false,false,true);L->SetCastShadows(false);}}
void ALWCharacter::OpenWorkbench39(ALWWorldObject* S){if(!S||Health<=0||Vehicle)return;ClosePanels();CancelReload();bAim=bSprint=bTrigger=false;GetCharacterMovement()->StopMovementImmediately();Workbench39=GetWorld()->SpawnActor<ALWWorkbench39>(FVector(0,0,-80000),FRotator::ZeroRotator);if(Workbench39){Workbench39->Begin(this,S);SetMenuInput(true);}}
void ALWCharacter::CloseWorkbench39(){if(Workbench39){Workbench39->Destroy();Workbench39=nullptr;}}
void ALWWorkbench39::Begin(ALWCharacter* P,ALWWorldObject* S){Player=P;Station=S;Draft.Bank=P->Inventory;Original=LWParts39::Fingerprint(P->Inventory);Target=NewObject<UTextureRenderTarget2D>(this);Target->ClearColor=FLinearColor(.015,.023,.022,1);Target->InitAutoFormat(1000,800);Capture->TextureTarget=Target;Message=TEXT("Select a weapon to customize.");Refresh();}
void ALWWorkbench39::Tick(float Dt){Super::Tick(Dt);if(!IsValid(Player)||Player->Health<=0||!IsValid(Station)||FVector::Dist(Player->GetActorLocation(),Station->GetActorLocation())>650){if(Player&&Player->Workbench39==this)Player->ClosePanels();else Destroy();return;}UpdateCamera();Capture->CaptureScene();}
void ALWWorkbench39::Snapshot(){UndoStack.Add(Draft);if(UndoStack.Num()>32)UndoStack.RemoveAt(0);RedoStack.Empty();}
void ALWWorkbench39::Undo(bool Redo){auto& From=Redo?RedoStack:UndoStack;auto& To=Redo?UndoStack:RedoStack;if(From.IsEmpty())return;To.Add(Draft);Draft=From.Pop();Refresh();Message=Redo?TEXT("Redo"):TEXT("Undo");}
void ALWWorkbench39::UpdateCamera(){Pitch=FMath::Clamp(Pitch,-85.f,85.f);Distance=FMath::Clamp(Distance,35.f,1200.f);const FVector Eye=Center+FRotator(Pitch,Yaw,0).Vector()*Distance;Capture->SetRelativeLocation(Eye);Capture->SetRelativeRotation((Center-Eye).Rotation());}
void ALWWorkbench39::Refresh(){if(Mystic62){for(auto& C:Mystic62->Drops)if(C)C->DestroyComponent();Mystic62->DestroyComponent();Mystic62=nullptr;}
 for(auto& M:Meshes)if(M)M->DestroyComponent();Meshes.Empty();Capture->ShowOnlyComponents.Empty();if(!Player||!Player->World||!Draft.Gun.Id.IsValid())return;
 const int W=LWItems::Def(Draft.Gun.Definition).WeaponIndex;
 auto AddMesh=[&](FName Name,FTransform T){auto* M=NewObject<UStaticMeshComponent>(this);M->SetupAttachment(RootComponent);M->SetStaticMesh(Player->World->Mesh(Name));M->SetRelativeTransform(T);M->SetCollisionEnabled(ECollisionEnabled::NoCollision);M->SetLightingChannels(false,false,true);M->RegisterComponent();Meshes.Add(M);Capture->ShowOnlyComponents.Add(M);return M;};
 auto* Body=AddMesh(Draft.Gun.Camo62==9?FName(*FString::Printf(TEXT("Mystic62_%02d"),W)):FName(LWArsenal62::BaseMesh(W)),FTransform::Identity);
 if(Draft.Gun.Camo62>0&&Draft.Gun.Camo62<9){auto* Mat=Player->World->Material(FName(*(Draft.Gun.Camo62>=7?FString::Printf(TEXT("Camo62_%d"),Draft.Gun.Camo62):FString::Printf(TEXT("WeaponSkin24_2_%02d"),Draft.Gun.Camo62-1))));if(Mat)for(int I=0;I<Body->GetNumMaterials();I++)Body->SetMaterial(I,Mat);}
 for(const auto& Part:LWArsenal62::MovingMeshes(W)){auto* C=AddMesh(Part.Key,FTransform(Part.Value));if(Draft.Gun.Camo62>0){const FString MatName=Draft.Gun.Camo62==9?FString::Printf(TEXT("MysticMoving62_%d"),LWArsenal62::Theme(W)):Draft.Gun.Camo62>=7?FString::Printf(TEXT("Camo62_%d"),Draft.Gun.Camo62):FString::Printf(TEXT("WeaponSkin24_2_%02d"),Draft.Gun.Camo62-1);auto* Mat=Player->World->Material(FName(*MatName));if(Mat)for(int I=0;I<C->GetNumMaterials();I++)C->SetMaterial(I,Mat);}}
 for(const auto& A:Draft.Gun.Attachments)if(LWMods::Compatible(Draft.Gun.Definition,A.Value))AddMesh(FName(*(A.Value.ToString()+(LWArsenal62::Find(A.Value)?TEXT(""):TEXT("V14")))),FTransform(LWMods::Position(W,A.Key)));
 if(Draft.Gun.Camo62==9){Mystic62=NewObject<ULWMystic62>(this);Mystic62->SetupAttachment(Body);Mystic62->RegisterComponent();Mystic62->Initialize(Player->World,W,true);for(auto& C:Mystic62->Drops)Capture->ShowOnlyComponents.Add(C);}
 UpdateCamera();
}
TArray<FGuid> ALWWorkbench39::Available()const{TArray<FGuid> Out;for(const auto& I:Draft.Bank){const auto C=LWItems::Def(I.Definition).Category;if(C==TEXT("Weapon")&&Tab62==0||C==TEXT("Attachment")&&Tab62==1&&LWMods::Mount(I.Definition)==Mount62&&LWMods::Compatible(Draft.Gun.Definition,I.Definition))Out.Add(I.Id);}return Out;}
bool ALWWorkbench39::Load(FGuid Id){if(Draft.Gun.Id.IsValid()){Message=TEXT("Apply changes or reopen the bench before selecting another weapon.");return false;}const auto* I=Draft.Bank.FindByPredicate([&](const auto& V){return V.Id==Id;});if(!I||LWItems::Def(I->Definition).Category!=TEXT("Weapon"))return false;Snapshot();Draft.Gun=*I;Draft.Bank.RemoveAll([&](const auto& V){return V.Id==Id;});Message=TEXT("Select a mount or a camo. Changes are a draft until applied.");Refresh();FrameAll();return true;}
bool ALWWorkbench39::Add(FGuid Id){const auto* I=Draft.Bank.FindByPredicate([&](const auto& V){return V.Id==Id;});if(!I)return false;if(LWItems::Def(I->Definition).Category==TEXT("Weapon"))return Load(Id);if(!Draft.Gun.Id.IsValid()||!LWMods::Compatible(Draft.Gun.Definition,I->Definition))return false;const FName Mount=LWMods::Mount(I->Definition);if(!Draft.Gun.Attachments.Contains(Mount)&&Draft.Gun.Attachments.Num()>=5){Message=TEXT("Maximum five attachments. Remove one first.");return false;}auto Next=Draft;const FName IdDef=I->Definition;Next.Bank.RemoveAll([&](const auto& V){return V.Id==Id;});const FName Old=Next.Gun.Attachments.FindRef(Mount);if(!Old.IsNone()){auto Return=LWItems::Make(Old);if(!LWItems::Place(Next.Bank,Return,12,LWItems::InventoryHeight(Next.Bank))){Message=TEXT("Make room for the replaced attachment.");return false;}}Next.Gun.Attachments.Add(Mount,IdDef);Snapshot();Draft=MoveTemp(Next);Message=LWArsenal62::Find(IdDef)?LWArsenal62::Find(IdDef)->Pros+TEXT(" / ")+LWArsenal62::Find(IdDef)->Cons:TEXT("Attachment installed in draft.");Refresh();return true;}
bool ALWWorkbench39::Detach62(){if(!Draft.Gun.Attachments.Contains(Mount62))return false;auto Next=Draft;auto I=LWItems::Make(Next.Gun.Attachments.FindRef(Mount62));if(!LWItems::Place(Next.Bank,I,12,LWItems::InventoryHeight(Next.Bank))){Message=TEXT("Make room in your inventory first.");return false;}Next.Gun.Attachments.Remove(Mount62);Snapshot();Draft=MoveTemp(Next);Refresh();return true;}
bool ALWWorkbench39::SetCamo62(int C){if(!Draft.Gun.Id.IsValid()||!LWArsenal62::Unlocked(Player,Draft.Gun.Definition,C)){Message=LWArsenal62::Challenge(Player,Draft.Gun.Definition,C);return false;}Snapshot();Draft.Gun.Camo62=C;Draft.Gun.WeaponSkin=-1;Refresh();Message=TEXT("Camo selected. Apply to keep changes.");return true;}
bool ALWWorkbench39::Remove(){return Detach62();}bool ALWWorkbench39::Action(){return false;}bool ALWWorkbench39::Dismantle(){return false;}
bool ALWWorkbench39::Apply(){if(!Player||Original!=LWParts39::Fingerprint(Player->Inventory)){Message=TEXT("Inventory changed. Close and reopen the bench.");return false;}auto Next=Draft.Bank;if(Draft.Gun.Id.IsValid()){auto G=Draft.Gun;if(!G.Slot.IsNone())Next.Add(G);else if(!LWItems::Place(Next,G,12,LWItems::InventoryHeight(Next))){Message=TEXT("Make room for the weapon.");return false;}}Player->Inventory=MoveTemp(Next);Player->ConfigureWeaponParts();Player->SyncAmmoHUD();Player->RequestSave40();Draft.Bank=Player->Inventory;Draft.Gun=FLWItemInstance();Original=LWParts39::Fingerprint(Player->Inventory);UndoStack.Empty();RedoStack.Empty();Tab62=0;Message=TEXT("Loadout applied.");Refresh();return true;}
void ALWWorkbench39::Transform(FVector){}void ALWWorkbench39::SetBuildName39(const FString&){}
FVector2D ALWWorkbench39::Project(FVector Local)const{const FVector V=Capture->GetRelativeTransform().InverseTransformPosition(Local);if(V.X<=1)return FVector2D(-100);const double T=FMath::Tan(FMath::DegreesToRadians(Capture->FOVAngle*.5));return FVector2D(.5+V.Y/(2*V.X*T),.5-V.Z/(2*V.X*T*.8));}
int ALWWorkbench39::Pick(FVector2D)const{return INDEX_NONE;}
void ALWWorkbench39::FrameAll(){FBox Box(ForceInit);for(auto& M:Meshes)if(M&&M->GetStaticMesh())Box+=M->GetStaticMesh()->GetBoundingBox().TransformBy(M->GetRelativeTransform());if(Box.IsValid){Center=Box.GetCenter();Distance=FMath::Max(65.,Box.GetExtent().Size()*3.3);}UpdateCamera();}
