#include "LWHUD.h"
#include "LWWorkbench39.h"
#include "LWWeaponParts39.h"
#include "LWWeaponMods.h"
#include "LWCharacter.h"
#include "Engine/Canvas.h"
#include "Components/SceneCaptureComponent2D.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/TextureRenderTarget2D.h"
#include "GameFramework/PlayerController.h"
static const FLinearColor BenchInk(.018,.027,.024,1),BenchText(.83,.85,.73,1),BenchGold(.94,.62,.27,1);
void ALWHUD::WorkbenchScreen39(ALWCharacter* P){auto* B=P->Workbench39.Get();if(!B)return;Rect(0,0,Canvas->ClipX/Scale,720,BenchInk);Text(TEXT("WEAPON WORKBENCH"),22,18,1.65,BenchText);Text(TEXT("RMB ORBIT   MMB PAN   WHEEL ZOOM"),290,57,.9);auto Btn=[&](FString Id,FString Label,float X,float Y,float W,bool On=false){Control55(FName(*("wb_"+Id)),Label,X,Y,W,27,On);};
 Btn(TEXT("close"),TEXT("CLOSE"),1160,16,98);Btn(TEXT("apply"),TEXT("APPLY"),1020,16,126,true);
 const TCHAR* Filters[]={TEXT("ALL"),TEXT("GUNS"),TEXT("PARTS"),TEXT("MODS")};for(int i=0;i<4;++i)Btn(FString::Printf(TEXT("filter%d"),i),Filters[i],18+i*65,64,62,B->Filter==i);
 const auto Items=B->Available();B->Page=FMath::Clamp(B->Page,0,FMath::Max(0,(Items.Num()-1)/16));for(int r=0;r<16;++r){const int i=B->Page*16+r;if(!Items.IsValidIndex(i))break;auto* I=B->Draft.Bank.FindByPredicate([&](const auto& V){return V.Id==Items[i];});if(!I)continue;const auto& D=LWItems::Def(I->Definition);const float Y=105+r*29;Rect(18,Y,250,27,FLinearColor(.055,.078,.066));Rect(18,Y,3,27,LWMods::TierColor(I->WeaponTier));Text((I->CustomName39.IsEmpty()?D.DisplayName.ToString():I->CustomName39).Left(28),26,Y+4,.85,LWMods::TierColor(I->WeaponTier));AddHitBox(FVector2D(18,Y)*Scale,FVector2D(250,27)*Scale,FName(*FString::Printf(TEXT("wb_item%d"),i)),true,10);}
 Btn(TEXT("prev"),TEXT("<"),18,580,40);Text(FString::Printf(TEXT("%d / %d"),B->Page+1,FMath::Max(1,(Items.Num()+15)/16)),78,586,.9);Btn(TEXT("next"),TEXT(">"),226,580,42);Text(TEXT("Click a gun to edit it."),18,624,.85);Text(TEXT("Click or drag parts in."),18,644,.85);
 Rect(282,92,670,536,FLinearColor(.025,.035,.033));if(B->Target)DrawTexture(B->Target,282*Scale,92*Scale,670*Scale,536*Scale,0,0,1,1,FLinearColor::White,BLEND_Opaque);
 for(int i=0;i<B->Draft.Gun.Parts39.Num();++i){const auto& Part=B->Draft.Gun.Parts39[i];const FVector2D UV=B->Project(Part.Transform.GetLocation());if(UV.X<0||UV.X>1||UV.Y<0||UV.Y>1)continue;const FVector2D V=FVector2D(282,92)+UV*FVector2D(670,536);if(i==B->Draft.Selected){Rect(V.X-4,V.Y-4,8,8,BenchGold);const FVector Axes[]={FVector(18,0,0),FVector(0,18,0),FVector(0,0,18)};const FLinearColor Colors[]={FLinearColor(1,.2,.15),FLinearColor(.25,1,.3),FLinearColor(.25,.6,1)};for(int a=0;a<3;++a){const FVector2D U=B->Project(Part.Transform.GetLocation()+Axes[a]);const FVector2D E=FVector2D(282,92)+U*FVector2D(670,536);Line(V.X,V.Y,E.X,E.Y,Colors[a],B->Axis==a?3:1);Text(FString::Chr('X'+a),E.X,E.Y,.8,Colors[a]);AddHitBox((E-FVector2D(9,9))*Scale,FVector2D(28,28)*Scale,FName(*FString::Printf(TEXT("wb_axis%d"),a)),true,20);}}}
 for(int i=0;i<3;++i)Btn(FString::Printf(TEXT("mode%d"),i),i==0?TEXT("MOVE"):i==1?TEXT("ROTATE"):TEXT("SCALE"),290+i*105,638,100,B->Mode==i);
 Btn(TEXT("snap"),B->Snap?TEXT("SNAP ON"):TEXT("SNAP OFF"),610,638,110,B->Snap);Btn(TEXT("frame"),TEXT("FRAME ALL"),734,638,135);Btn(TEXT("free"),TEXT("FREE"),878,638,68,B->Axis==3);
 Text(TEXT("ASSEMBLY"),974,66,1.1);B->PartPage=FMath::Clamp(B->PartPage,0,FMath::Max(0,(B->Draft.Gun.Parts39.Num()-1)/8));for(int r=0;r<8;++r){const int i=B->PartPage*8+r;if(!B->Draft.Gun.Parts39.IsValidIndex(i))break;const auto& Part=B->Draft.Gun.Parts39[i];FString N=(Part.Id==B->Draft.Gun.Action39?TEXT("* "):TEXT("  "))+LWItems::Def(Part.Definition).DisplayName.ToString();Btn(FString::Printf(TEXT("part%d"),i),N.Left(32),974,98+r*28,286,i==B->Draft.Selected);}
 Btn(TEXT("partprev"),TEXT("<"),974,326,40);Btn(TEXT("partnext"),TEXT(">"),1220,326,40);Text(FString::Printf(TEXT("%d PARTS"),B->Draft.Gun.Parts39.Num()),1040,332,.9);
 if(B->Draft.Gun.Parts39.IsValidIndex(B->Draft.Selected)){const auto& Part=B->Draft.Gun.Parts39[B->Draft.Selected];Text(LWMods::TierName(Part.Tier),974,366,.95,LWMods::TierColor(Part.Tier));if(!Part.Modifier.IsNone())Text(Part.Modifier.ToString().ToUpper(),974,389,.9,BenchGold);
 const FVector V=B->Mode==0?Part.Transform.GetLocation():B->Mode==1?Part.Transform.Rotator().Euler():Part.Transform.GetScale3D();for(int a=0;a<3;++a){Btn(FString::Printf(TEXT("axis%d"),a),FString::Chr('X'+a),974+a*92,420,30,B->Axis==a);Text(FString::Printf(TEXT("%.1f"),V[a]),1006+a*92,426,.8);}Btn(TEXT("minus"),TEXT("-"),974,456,40);Btn(TEXT("plus"),TEXT("+"),1020,456,40);Btn(TEXT("reset"),TEXT("RESET PART"),1070,456,190);Btn(TEXT("action"),TEXT("USE ACTION"),974,492,140);Btn(TEXT("remove"),TEXT("REMOVE"),1124,492,136);}
 if(!B->Draft.Gun.Parts39.IsEmpty()){Btn(TEXT("rename"),(B->EditingName?TEXT("> "):TEXT("NAME: "))+B->Draft.Gun.CustomName39.Left(24),974,534,286);const auto& D=LWItems::Def(B->Draft.Gun.Definition);Text((TEXT("AMMO: ")+D.AmmoType.ToString()).Left(33),974,568,.85);Text(FString::Printf(TEXT("DAMAGE x%.2f   RATE x%.2f"),LWMods::Damage(&B->Draft.Gun),1/LWMods::Interval(&B->Draft.Gun)),974,590,.85);}
 Btn(TEXT("undo"),TEXT("UNDO"),290,680,85);Btn(TEXT("redo"),TEXT("REDO"),382,680,85);Btn(TEXT("dismantle"),TEXT("DISMANTLE"),974,632,160);Btn(TEXT("repair"),TEXT("REPAIR ARMOR"),974,675,200);Text(B->Message.Left(68),480,685,.8,BenchGold);
 float MX=0,MY=0;Mouse55(MX,MY);const FVector2D Mouse(MX/Scale,MY/Scale);const FVector2D Delta=Mouse-B->LastMouse;const bool Inside=Mouse.X>=282&&Mouse.X<=952&&Mouse.Y>=92&&Mouse.Y<=628;const bool Down=PlayerOwner->IsInputKeyDown(EKeys::LeftMouseButton);
 if(Inside){if(PlayerOwner->IsInputKeyDown(EKeys::RightMouseButton)){B->Yaw-=Delta.X*.5;B->Pitch+=Delta.Y*.5;}if(PlayerOwner->IsInputKeyDown(EKeys::MiddleMouseButton)){const FRotator R=B->Capture->GetRelativeRotation();B->Center+=R.RotateVector(FVector(0,-Delta.X,Delta.Y))*(B->Distance/500);}
 if(PlayerOwner->WasInputKeyJustPressed(EKeys::MouseScrollUp))B->Distance*=.9;if(PlayerOwner->WasInputKeyJustPressed(EKeys::MouseScrollDown))B->Distance*=1.1;
 if(Down&&!B->LeftDown){const int Pick=B->Pick((Mouse-FVector2D(282,92))/FVector2D(670,536));if(Pick>=0){B->Draft.Selected=Pick;B->Snapshot();B->Dragging=true;B->DragStart=B->Draft.Gun.Parts39[Pick].Transform;B->DragOrigin=Mouse;}}
 if(B->PendingDrop&&Down&&B->Draft.Gun.Parts39.IsValidIndex(B->Draft.Selected)){
  const FVector2D UV=(Mouse-FVector2D(282,92))/FVector2D(670,536);const float Tan=FMath::Tan(FMath::DegreesToRadians(B->Capture->FOVAngle*.5));const float Depth=FVector::Dist(B->Capture->GetRelativeLocation(),B->Center);const FVector Local=B->Center+B->Capture->GetRelativeRotation().RotateVector(FVector(0,(UV.X-.5)*2*Tan*Depth,-(UV.Y-.5)*2*Tan*.8*Depth));B->Draft.Gun.Parts39[B->Draft.Selected].Transform.SetLocation(Local.GetClampedToMaxSize(295));if(B->Meshes.IsValidIndex(B->Draft.Selected))B->Meshes[B->Draft.Selected]->SetRelativeTransform(B->Draft.Gun.Parts39[B->Draft.Selected].Transform);
 }
 if(Down&&B->Dragging&&B->Draft.Gun.Parts39.IsValidIndex(B->Draft.Selected)){
  const FVector2D Drag=Mouse-B->DragOrigin;B->Draft.Gun.Parts39[B->Draft.Selected].Transform=B->DragStart;FVector V=FVector::ZeroVector;
  if(B->Axis==3){if(B->Mode==0)V=B->Capture->GetRelativeRotation().RotateVector(FVector(0,Drag.X,-Drag.Y))*(B->Distance/700);else if(B->Mode==1)V=FVector(0,Drag.Y,Drag.X)*.5;else V=FVector((Drag.X-Drag.Y)*.005);}
  else V[B->Axis]=(Drag.X-Drag.Y)*(B->Mode==0?B->Distance/700:B->Mode==1?.5:.005);
  if(B->Snap){const float Step=B->Mode==0?2:B->Mode==1?5:.05;for(int a=0;a<3;++a)V[a]=FMath::GridSnap(V[a],double(Step));}B->Transform(V);
 }}

 if(!Down){B->Dragging=false;B->PendingDrop=false;}B->LeftDown=Down;B->LastMouse=Mouse;
 if(B->EditingName){if(PlayerOwner->WasInputKeyJustPressed(EKeys::Enter)){B->EditingName=false;}else if(PlayerOwner->WasInputKeyJustPressed(EKeys::BackSpace)){B->SetBuildName39(B->Draft.Gun.CustomName39.LeftChop(1));}else{for(TCHAR C='A';C<='Z';++C)if(PlayerOwner->WasInputKeyJustPressed(FKey(FName(*FString::Chr(C)))))B->SetBuildName39(B->Draft.Gun.CustomName39+FString::Chr(C));for(TCHAR C='0';C<='9';++C){static const FName K[]={TEXT("Zero"),TEXT("One"),TEXT("Two"),TEXT("Three"),TEXT("Four"),TEXT("Five"),TEXT("Six"),TEXT("Seven"),TEXT("Eight"),TEXT("Nine")};if(PlayerOwner->WasInputKeyJustPressed(FKey(K[C-'0'])))B->SetBuildName39(B->Draft.Gun.CustomName39+FString::Chr(C));}if(PlayerOwner->WasInputKeyJustPressed(EKeys::SpaceBar))B->SetBuildName39(B->Draft.Gun.CustomName39+TEXT(" "));}}
}
void ALWHUD::WorkbenchClick39(ALWCharacter* P,FName N){auto* B=P->Workbench39.Get();if(!B)return;const FString S=N.ToString().Mid(3);if(S==TEXT("close")){P->ClosePanels();return;}if(S==TEXT("apply")){B->Apply();return;}if(S.StartsWith(TEXT("filter"))){B->Filter=FCString::Atoi(*S.Mid(6));B->Page=0;return;}if(S.StartsWith(TEXT("item"))){const auto A=B->Available();const int I=FCString::Atoi(*S.Mid(4));if(A.IsValidIndex(I)){const auto* Item=B->Draft.Bank.FindByPredicate([&](const auto& V){return V.Id==A[I];});const bool Part=Item&&LWItems::Def(Item->Definition).Category!=TEXT("Weapon");if(B->Add(A[I])&&Part)B->PendingDrop=true;}return;}if(S==TEXT("partprev")){B->PartPage--;return;}if(S==TEXT("partnext")){B->PartPage++;return;}if(S.StartsWith(TEXT("part"))){B->Draft.Selected=FCString::Atoi(*S.Mid(4));return;}if(S.StartsWith(TEXT("mode"))){B->Mode=FCString::Atoi(*S.Mid(4));return;}if(S.StartsWith(TEXT("axis"))){B->Axis=FCString::Atoi(*S.Mid(4));return;}if(S==TEXT("free"))B->Axis=3;if(S==TEXT("prev"))B->Page--;if(S==TEXT("next"))B->Page++;if(S==TEXT("undo"))B->Undo();if(S==TEXT("redo"))B->Undo(true);if(S==TEXT("snap"))B->Snap=!B->Snap;if(S==TEXT("remove"))B->Remove();if(S==TEXT("action"))B->Action();if(S==TEXT("dismantle"))B->Dismantle();if(S==TEXT("rename")){B->Snapshot();B->EditingName=!B->EditingName;}if(S==TEXT("frame")){B->FrameAll();}

 if(S==TEXT("reset")&&B->Draft.Gun.Parts39.IsValidIndex(B->Draft.Selected)){B->Snapshot();B->Draft.Gun.Parts39[B->Draft.Selected].Transform=FTransform::Identity;B->Refresh();}
 if(S==TEXT("plus")||S==TEXT("minus")){B->Snapshot();FVector D=FVector::ZeroVector;const float Step=(S==TEXT("plus")?1:-1)*(B->Mode==0?(B->Snap?2: .25):B->Mode==1?(B->Snap?15:1):(B->Snap?.1:.01));if(B->Axis==3)D=B->Mode==2?FVector(Step):FVector(Step,0,0);else D[B->Axis]=Step;B->Transform(D);}
 if(S==TEXT("repair")){auto* A=B->Draft.Bank.FindByPredicate([](const auto& I){return I.Slot==TEXT("Armor");});if(!A||A->Durability>=100){B->Message=TEXT("Equip damaged armor first.");return;}const int Cost=FMath::Max(1,4-int(P->Stat(TEXT("craft"))));int Count=0;for(const auto& I:B->Draft.Bank)if(I.Definition==TEXT("scrap"))Count+=I.Count;if(Count<Cost){B->Message=FString::Printf(TEXT("Requires %d scrap."),Cost);return;}B->Snapshot();A->Durability=FMath::Min(100,A->Durability+FMath::RoundToInt(30*(1+P->Stat(TEXT("repair")))));int Remaining=Cost;for(auto& I:B->Draft.Bank)if(I.Definition==TEXT("scrap")){const int Take=FMath::Min(Remaining,I.Count);I.Count-=Take;Remaining-=Take;}B->Draft.Bank.RemoveAll([](const auto& I){return I.Count<=0;});B->Message=TEXT("Armor repaired in draft. Apply to keep changes.");}
}
