#include "Materials/MaterialInterface.h"
#include "LWWorkbench39.h"
#include "LWWeaponParts39.h"
#include "LWWeaponMods.h"
#include "LWCharacter.h"
#include "LWWorld.h"
#include "LWWorldObject.h"
#include "Components/SceneCaptureComponent2D.h"
#include "Components/StaticMeshComponent.h"
#include "Components/PointLightComponent.h"
#include "Engine/TextureRenderTarget2D.h"
#include "Engine/World.h"
#include "Engine/StaticMesh.h"
#include "GameFramework/CharacterMovementComponent.h"
ALWWorkbench39::ALWWorkbench39(){PrimaryActorTick.bCanEverTick=true;SetRootComponent(CreateDefaultSubobject<USceneComponent>(TEXT("BenchRoot")));Capture=CreateDefaultSubobject<USceneCaptureComponent2D>(TEXT("Preview"));Capture->SetupAttachment(RootComponent);Capture->PrimitiveRenderMode=ESceneCapturePrimitiveRenderMode::PRM_UseShowOnlyList;Capture->CaptureSource=ESceneCaptureSource::SCS_FinalColorLDR;Capture->FOVAngle=40;Capture->bCaptureEveryFrame=false;Capture->bCaptureOnMovement=false;Capture->ShowFlags.SetAtmosphere(false);Capture->ShowFlags.SetFog(false);Capture->ShowFlags.SetMotionBlur(false);Capture->ShowFlags.SetTemporalAA(false);Capture->PostProcessSettings.bOverride_AutoExposureMethod=true;Capture->PostProcessSettings.AutoExposureMethod=AEM_Manual;Capture->PostProcessSettings.bOverride_AutoExposureBias=true;Capture->PostProcessSettings.AutoExposureBias=7;
 for(int i=0;i<2;++i){auto* L=CreateDefaultSubobject<UPointLightComponent>(i?TEXT("Fill"):TEXT("Key"));L->SetupAttachment(RootComponent);L->SetRelativeLocation(i?FVector(-80,110,60):FVector(60,-100,140));L->SetIntensity(i?6500:12000);L->SetAttenuationRadius(800);L->SetLightingChannels(false,false,true);L->SetCastShadows(false);}}
void ALWCharacter::OpenWorkbench39(ALWWorldObject* S){if(!S||Health<=0||Vehicle)return;ClosePanels();CancelReload();bAim=bSprint=bTrigger=false;GetCharacterMovement()->StopMovementImmediately();Workbench39=GetWorld()->SpawnActor<ALWWorkbench39>(FVector(0,0,-80000),FRotator::ZeroRotator);if(Workbench39){Workbench39->Begin(this,S);SetMenuInput(true);}}
void ALWCharacter::CloseWorkbench39(){if(Workbench39){Workbench39->Destroy();Workbench39=nullptr;}}
void ALWWorkbench39::Begin(ALWCharacter* P,ALWWorldObject* S){Player=P;Station=S;Draft.Bank=P->Inventory;Original=LWParts39::Fingerprint(P->Inventory);Target=NewObject<UTextureRenderTarget2D>(this);Target->ClearColor=FLinearColor(.015,.023,.022,1);Target->InitAutoFormat(1000,800);Capture->TextureTarget=Target;Message=TEXT("Select a weapon to edit, or add an action to start a build.");Refresh();}
void ALWWorkbench39::Tick(float Dt){Super::Tick(Dt);if(!IsValid(Player)||Player->Health<=0||!IsValid(Station)||FVector::Dist(Player->GetActorLocation(),Station->GetActorLocation())>650){if(Player&&Player->Workbench39==this)Player->ClosePanels();else Destroy();return;}UpdateCamera();Capture->CaptureScene();}
void ALWWorkbench39::Snapshot(){UndoStack.Add(Draft);if(UndoStack.Num()>32)UndoStack.RemoveAt(0);RedoStack.Empty();}
void ALWWorkbench39::Undo(bool Redo){auto& From=Redo?RedoStack:UndoStack;auto& To=Redo?UndoStack:RedoStack;if(From.IsEmpty())return;To.Add(Draft);Draft=From.Pop();Refresh();Message=Redo?TEXT("Redo"):TEXT("Undo");}
void ALWWorkbench39::UpdateCamera(){Pitch=FMath::Clamp(Pitch,-85.f,85.f);Distance=FMath::Clamp(Distance,35.f,1200.f);const FVector Eye=Center+FRotator(Pitch,Yaw,0).Vector()*Distance;Capture->SetRelativeLocation(Eye);Capture->SetRelativeRotation((Center-Eye).Rotation());}
void ALWWorkbench39::Refresh(){for(auto& M:Meshes)if(M)M->DestroyComponent();Meshes.Empty();Capture->ShowOnlyComponents.Empty();if(!Player||!Player->World)return;for(int i=0;i<Draft.Gun.Parts39.Num();++i){const auto& P=Draft.Gun.Parts39[i];auto* M=NewObject<UStaticMeshComponent>(this);M->SetupAttachment(RootComponent);M->SetStaticMesh(Player->World->Mesh(LWParts39::Mesh(P.Definition)));M->SetRelativeTransform(P.Transform);M->SetCollisionEnabled(ECollisionEnabled::NoCollision);M->SetLightingChannels(false,false,true);M->SetCastShadow(false);M->RegisterComponent();if(P.Tier>=2&&P.Skin>=0){auto* Mat=Player->World->Material(FName(*FString::Printf(TEXT("WeaponSkin24_%d_%02d"),P.Tier,P.Skin)));if(Mat)for(int j=0;j<M->GetNumMaterials();++j)if(M->GetMaterial(j)&&!M->GetMaterial(j)->GetName().Contains(TEXT("Rubber")))M->SetMaterial(j,Mat);}Meshes.Add(M);Capture->ShowOnlyComponents.Add(M);}UpdateCamera();}
TArray<FGuid> ALWWorkbench39::Available()const{TArray<FGuid> Out;for(const auto& I:Draft.Bank){const FName C=LWItems::Def(I.Definition).Category;if(I.Slot==TEXT("Loaded"))continue;if((Filter==0||Filter==1)&&C==TEXT("Weapon")||(Filter==0||Filter==2)&&C==TEXT("WeaponPart")||(Filter==0||Filter==3)&&C==TEXT("Attachment"))Out.Add(I.Id);}return Out;}
static void SaveCore39(FLWItemInstance& G){for(auto& P:G.Parts39)if(P.Id==G.Action39){P.Rounds=G.Rounds;P.Chamber=G.Chamber;P.Cylinder=G.Cylinder;P.CylinderIndex=G.CylinderIndex;}}
static void LoadCore39(FLWItemInstance& G){for(const auto& P:G.Parts39)if(P.Id==G.Action39){G.Rounds=P.Rounds;G.Chamber=P.Chamber;G.Cylinder=P.Cylinder;G.CylinderIndex=P.CylinderIndex;const auto* D=LWParts39::Find(P.Definition);const int W=D?LWItems::Def(D->Weapon).WeaponIndex:-1;if(G.Cylinder.IsEmpty()&&(W==3||W==8||W==11))G.Cylinder.SetNumZeroed(W==3?6:2);}}
bool ALWWorkbench39::Load(FGuid Id){if(!Draft.Gun.Parts39.IsEmpty()){Message=TEXT("Apply or dismantle the current project first.");return false;}const auto* I=Draft.Bank.FindByPredicate([&](const auto& V){return V.Id==Id;});if(!I||LWItems::Def(I->Definition).Category!=TEXT("Weapon"))return false;if(LWParts39::Recipe(*I).IsEmpty()){Message=TEXT("No workbench recipe is available for this weapon.");return false;}Snapshot();Draft.Gun=*I;if(Draft.Gun.CustomName39.IsEmpty())Draft.Gun.CustomName39=LWItems::Def(Draft.Gun.Definition).DisplayName.ToString().Left(26);Draft.Bank.RemoveAll([&](const auto& V){return V.Id==Id;});Draft.Gun.Parts39=LWParts39::Recipe(Draft.Gun);if(!Draft.Gun.Action39.IsValid())Draft.Gun.Action39=Draft.Gun.Parts39[0].Id;SaveCore39(Draft.Gun);Draft.Selected=0;Message=TEXT("Editing a draft. Apply to keep changes.");Refresh();FrameAll();return true;}
bool ALWWorkbench39::Add(FGuid Id){const auto* I=Draft.Bank.FindByPredicate([&](const auto& V){return V.Id==Id;});if(!I)return false;if(LWItems::Def(I->Definition).Category==TEXT("Weapon"))return Load(Id);if(Draft.Gun.Parts39.Num()>=64){Message=TEXT("The bench holds up to 64 parts.");return false;}if(!LWParts39::Find(I->Definition)&&LWItems::Def(I->Definition).Category!=TEXT("Attachment"))return false;Snapshot();auto P=LWParts39::Part(*I);Draft.Bank.RemoveAll([&](const auto& V){return V.Id==Id;});if(!Draft.Gun.Id.IsValid()){Draft.Gun=LWItems::Make(TEXT("crowbar"));Draft.Gun.CustomName39=TEXT("Custom weapon");}auto* D=LWParts39::Find(P.Definition);if(P.Transform.Equals(FTransform::Identity))P.Transform.SetLocation(D&&D->Group==TEXT("Barrel")?FVector(18,0,3):D&&D->Group==TEXT("Stock")?FVector(-14,0,0):D&&D->Group==TEXT("Grip")?FVector(0,0,-3):LWItems::Def(P.Definition).Category==TEXT("Attachment")?LWMods::Position(LWItems::Def(Draft.Gun.Definition).WeaponIndex,LWMods::Mount(P.Definition)):FVector::ZeroVector);Draft.Selected=Draft.Gun.Parts39.Add(P);if(!Draft.Gun.Action39.IsValid()&&D&&D->Group==TEXT("Action")){Draft.Gun.Action39=P.Id;LoadCore39(Draft.Gun);}LWParts39::Derive(Draft.Gun);Message=TEXT("Drag a part in the preview. Choose move, rotate or scale.");Refresh();return true;}
bool ALWWorkbench39::Remove(){if(!Draft.Gun.Parts39.IsValidIndex(Draft.Selected))return false;auto Next=Draft;SaveCore39(Next.Gun);const auto P=Next.Gun.Parts39[Next.Selected];if(P.Id==Next.Gun.Action39&&!LWParts39::ReleaseMagazine(Next.Bank,Next.Gun,Message))return false;auto I=LWParts39::Item(P);if(!LWItems::Place(Next.Bank,I,12,LWItems::InventoryHeight(Next.Bank))){Message=TEXT("Make room for the removed part.");return false;}Next.Gun.Parts39.RemoveAt(Next.Selected);Next.Selected=FMath::Min(Next.Selected,Next.Gun.Parts39.Num()-1);if(P.Id==Next.Gun.Action39){Next.Gun.Action39.Invalidate();Next.Gun.Rounds=Next.Gun.Chamber=0;Next.Gun.Cylinder.Empty();}Snapshot();Draft=MoveTemp(Next);if(Draft.Gun.Parts39.IsEmpty())Draft.Gun=FLWItemInstance();else LWParts39::Derive(Draft.Gun);Refresh();return true;}
bool ALWWorkbench39::Action(){if(!Draft.Gun.Parts39.IsValidIndex(Draft.Selected))return false;const auto* D=LWParts39::Find(Draft.Gun.Parts39[Draft.Selected].Definition);if(!D||D->Group!=TEXT("Action")){Message=TEXT("Select an action first.");return false;}if(Draft.Gun.Action39==Draft.Gun.Parts39[Draft.Selected].Id)return true;auto Next=Draft;SaveCore39(Next.Gun);if(!LWParts39::ReleaseMagazine(Next.Bank,Next.Gun,Message))return false;Next.Gun.Action39=Next.Gun.Parts39[Next.Selected].Id;LoadCore39(Next.Gun);LWParts39::Derive(Next.Gun);Snapshot();Draft=MoveTemp(Next);Message=TEXT("Action selected. Ammo and reload follow this action.");Refresh();return true;}
bool ALWWorkbench39::Dismantle(){if(Draft.Gun.Parts39.IsEmpty())return false;auto Next=Draft.Bank;Next.Add(Draft.Gun);if(!LWParts39::Dismantle(Next,Draft.Gun.Id,Message))return false;Snapshot();Draft.Bank=MoveTemp(Next);Draft.Gun=FLWItemInstance();Draft.Selected=-1;Message=TEXT("Parts recovered in the draft. Apply to keep them.");Refresh();return true;}
bool ALWWorkbench39::Apply(){if(!Player||Original!=LWParts39::Fingerprint(Player->Inventory)){Message=TEXT("Inventory changed. Close and reopen the bench.");return false;}auto Next=Draft.Bank;SaveCore39(Draft.Gun);if(!Draft.Gun.Parts39.IsEmpty()&&!LWParts39::Store(Next,Draft.Gun,Message))return false;Player->Inventory=MoveTemp(Next);if(const auto* G=Player->FindItem(Player->ActiveWeaponId)){Player->Weapon=LWItems::Def(G->Definition).WeaponIndex;Player->FireMode=(Player->Weapon==5||Player->Weapon==6||Player->Weapon==7||Player->Weapon==13)?1:0;if(G->Slot.IsNone())Player->ActiveWeaponId.Invalidate();}else Player->ActiveWeaponId.Invalidate();Player->ConfigureWeaponParts();Player->SyncAmmoHUD();Player->RequestSave40();Draft.Bank=Player->Inventory;Draft.Gun=FLWItemInstance();Draft.Selected=-1;Original=LWParts39::Fingerprint(Player->Inventory);UndoStack.Empty();RedoStack.Empty();Message=TEXT("Saved to inventory.");Refresh();return true;}
void ALWWorkbench39::Transform(FVector Delta){if(!Draft.Gun.Parts39.IsValidIndex(Draft.Selected))return;auto& T=Draft.Gun.Parts39[Draft.Selected].Transform;if(Mode==0){FVector V=T.GetLocation()+Delta;for(int i=0;i<3;++i)V[i]=FMath::Clamp(V[i],-300.,300.);T.SetLocation(V);}else if(Mode==1){T.SetRotation((FQuat(FVector::XAxisVector,FMath::DegreesToRadians(Delta.X))*FQuat(FVector::YAxisVector,FMath::DegreesToRadians(Delta.Y))*FQuat(FVector::ZAxisVector,FMath::DegreesToRadians(Delta.Z))*T.GetRotation()).GetNormalized());}else{FVector S=T.GetScale3D()+Delta;for(int i=0;i<3;++i)S[i]=FMath::Clamp(S[i],.25,3.);T.SetScale3D(S);}if(Meshes.IsValidIndex(Draft.Selected))Meshes[Draft.Selected]->SetRelativeTransform(T);}
void ALWWorkbench39::SetBuildName39(const FString& Name){Draft.Gun.CustomName39=Name.Left(26);}
FVector2D ALWWorkbench39::Project(FVector Local)const{const FVector V=Capture->GetRelativeTransform().InverseTransformPosition(Local);if(V.X<=1)return FVector2D(-100,-100);const double Tan=FMath::Tan(FMath::DegreesToRadians(Capture->FOVAngle*.5));return FVector2D(.5+V.Y/(2*V.X*Tan),.5-V.Z/(2*V.X*Tan*.8));}
int ALWWorkbench39::Pick(FVector2D UV)const{double Best=1.e30;int Index=-1;const float Tan=FMath::Tan(FMath::DegreesToRadians(Capture->FOVAngle*.5));const FVector Origin=Capture->GetRelativeLocation();const FVector Dir=Capture->GetRelativeRotation().RotateVector(FVector(1,(UV.X-.5)*2*Tan,-(UV.Y-.5)*2*Tan*.8)).GetSafeNormal();for(int i=0;i<Meshes.Num();++i){if(!Meshes[i]||!Meshes[i]->GetStaticMesh())continue;const FTransform T=Draft.Gun.Parts39[i].Transform;const FVector A=T.InverseTransformPosition(Origin),B=T.InverseTransformPosition(Origin+Dir*3000);const FBox Box=Meshes[i]->GetStaticMesh()->GetBoundingBox().ExpandBy(1);FVector Hit,Normal;float Time;if(FMath::LineExtentBoxIntersection(Box,A,B,FVector::ZeroVector,Hit,Normal,Time)&&Time<Best){Best=Time;Index=i;}}return Index;}

void ALWWorkbench39::FrameAll(){FBox Box(ForceInit);for(int i=0;i<Meshes.Num();++i)if(Meshes[i]&&Meshes[i]->GetStaticMesh())Box+=Meshes[i]->GetStaticMesh()->GetBoundingBox().TransformBy(Draft.Gun.Parts39[i].Transform);if(Box.IsValid){Center=Box.GetCenter();Distance=FMath::Max(65.,Box.GetExtent().Size()*3.3);}UpdateCamera();}
