#include "LWWeaponParts39.h"
#include "LWWeaponMods.h"
#include "LWLootTable.h"
#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Serialization/MemoryReader.h"
#include "Serialization/MemoryWriter.h"
#include "Serialization/ObjectAndNameAsStringProxyArchive.h"
#include "UObject/StrongObjectPtr.h"
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWPartsCatalog39,"LethalWorld.Workbench.CatalogAndRecipes",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWPartsCatalog39::RunTest(const FString&){TestEqual(TEXT("59 structural parts"),LWParts39::Definitions().Num(),59);TSet<FName> Unique;for(const auto& D:LWParts39::Definitions()){TestFalse(TEXT("unique catalog id"),Unique.Contains(D.Id));Unique.Add(D.Id);TestEqual(TEXT("part registered in inventory"),LWItems::Def(D.Id).Category,FName(TEXT("WeaponPart")));TestFalse(TEXT("mesh path exists"),LWItems::Def(D.Id).Mesh.IsNull());}
 for(int W=0;W<21;++W){auto G=LWItems::Make(LWParts39::WeaponId(W));G.WeaponTier=4;G.LegendaryModifier=TEXT("Toxic");G.WeaponSkin=5;G.Parts39=LWParts39::Recipe(G);TestTrue(TEXT("existing weapon has parts"),G.Parts39.Num()>=(W==19?1:2));G.Action39=G.Parts39[0].Id;LWParts39::Derive(G);FString Error;TestTrue(*FString::Printf(TEXT("valid weapon %d: %s"),W,*Error),LWParts39::Validate(G,Error));TestEqual(TEXT("recipe preserves action"),LWItems::Def(G.Definition).WeaponIndex,W);for(const auto& P:G.Parts39){TestEqual(TEXT("preserves rarity"),P.Tier,4);TestEqual(TEXT("preserves legendary effect"),P.Modifier,FName(TEXT("Toxic")));}}
 return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWPartsAmmo39,"LethalWorld.Workbench.AmmoAndRoundTrip",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWPartsAmmo39::RunTest(const FString&){for(int W=0;W<21;++W){auto G=LWItems::Make(LWParts39::WeaponId(W));G.Slot=W<2?TEXT("Melee"):W==3||W==12||W==14?TEXT("Sidearm"):TEXT("Primary");G.WeaponTier=4;G.LegendaryModifier=TEXT("Life Steal");G.WeaponSkin=7;G.Durability=63;G.Chamber=W>=2?1:0;G.Rounds=W==14?7:W==9?1:W==2?3:0;for(auto& C:G.Cylinder)C=1;const auto& Def=LWItems::Def(G.Definition);TArray<FLWItemInstance> Bank;FGuid MagId;if(!Def.MagazineType.IsNone()){auto M=LWItems::Make(Def.MagazineType);M.Slot=TEXT("Loaded");M.Rounds=3;MagId=M.Id;G.LoadedMagazine=M.Id;Bank.Add(M);}Bank.Add(G);FString Error;TestTrue(*FString::Printf(TEXT("dismantle %d"),W),LWParts39::Dismantle(Bank,G.Id,Error));auto* Core=Bank.FindByPredicate([](const auto& I){const auto* D=LWParts39::Find(I.Definition);return D&&D->Group==TEXT("Action");});TestNotNull(TEXT("action recovered"),Core);if(!Core)continue;TestEqual(TEXT("integral charges preserved"),Core->Rounds,G.Rounds);TestEqual(TEXT("chamber preserved"),Core->Chamber,G.Chamber);TestTrue(TEXT("cylinder preserved"),Core->Cylinder==G.Cylinder);if(MagId.IsValid()){auto* M=Bank.FindByPredicate([&](const auto& I){return I.Id==MagId;});TestTrue(TEXT("mag released with original identity and rounds"),M&&M->Rounds==3&&M->Slot.IsNone());}
 auto Custom=LWItems::Make(G.Definition);Custom.Action39=Core->Id;Custom.CustomName39=TEXT("Round trip");Custom.Rounds=Core->Rounds;Custom.Chamber=Core->Chamber;Custom.Cylinder=Core->Cylinder;for(const auto& I:Bank)if(LWParts39::Find(I.Definition)){auto P=LWParts39::Part(I);P.Transform=FTransform(FRotator(13,122,45),FVector(-20,42,12),FVector(.8,1.2,2));Custom.Parts39.Add(P);}Bank.RemoveAll([](const auto& I){return LWParts39::Find(I.Definition)!=nullptr;});TestTrue(TEXT("custom assembly stores"),LWParts39::Store(Bank,Custom,Error));auto* Stored=Bank.FindByPredicate([&](const auto& I){return I.Id==Custom.Id;});TestNotNull(TEXT("stored weapon"),Stored);if(!Stored)continue;const int Price=LWMods::Price(*Stored);TestTrue(TEXT("custom weapon has combined part price"),Price>0);auto Before=Stored->Parts39;TestTrue(TEXT("custom disassembles"),LWParts39::Dismantle(Bank,Custom.Id,Error));for(const auto& Part:Before){auto* I=Bank.FindByPredicate([&](const auto& V){return V.Id==Part.Id;});TestTrue(TEXT("part identity/transform/finish retained"),I&&I->WeaponTier==Part.Tier&&I->LegendaryModifier==Part.Modifier&&I->WeaponSkin==Part.Skin&&I->PartTransform39.Equals(Part.Transform)&&I->Durability==63);}}
 return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWPartsAtomic39,"LethalWorld.Workbench.AtomicFailures",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWPartsAtomic39::RunTest(const FString&){TArray<FLWItemInstance> Bank;auto G=LWItems::Make(TEXT("lmg"));G.Slot=TEXT("Primary");Bank.Add(G);for(int i=0;i<120;++i){auto Fill=LWItems::Make(TEXT("scrap"));if(!LWItems::Place(Bank,Fill,12,10))break;}const uint32 Before=LWParts39::Fingerprint(Bank);FString Error;TestFalse(TEXT("full inventory refuses disassembly"),LWParts39::Dismantle(Bank,G.Id,Error));TestEqual(TEXT("failed dismantle is atomic"),LWParts39::Fingerprint(Bank),Before);G.Parts39=LWParts39::Recipe(G);G.Action39=G.Parts39[0].Id;TestFalse(TEXT("duplicate weapon cannot be stored"),LWParts39::Store(Bank,G,Error));TestEqual(TEXT("failed store is atomic"),LWParts39::Fingerprint(Bank),Before);Bank.Empty();Bank.Add(LWParts39::Item(G.Parts39[0]));TestFalse(TEXT("cannot embed an unconsumed item"),LWParts39::Store(Bank,G,Error));const auto Duplicate=G.Parts39[0];G.Parts39.Add(Duplicate);TestFalse(TEXT("duplicate embedded identity rejected"),LWParts39::Validate(G,Error));G.Parts39.Pop();G.Parts39[0].Transform.SetScale3D(FVector(-1));TestFalse(TEXT("invalid transform rejected"),LWParts39::Validate(G,Error));return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWPartsEffects39,"LethalWorld.Workbench.FreeformEffectsAndSerialization",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWPartsEffects39::RunTest(const FString&){auto G=LWItems::Make(TEXT("smg"));G.Parts39=LWParts39::Recipe(G);G.Action39=G.Parts39[0].Id;const FName Effects[]={TEXT("Two Shot"),TEXT("Life Steal"),TEXT("Toxic"),TEXT("Rapid Fire"),TEXT("Recoil Free"),TEXT("Explosive")};for(FName E:Effects){auto I=LWItems::Make(TEXT("part_barrel_09"));I.WeaponTier=4;I.LegendaryModifier=E;auto P=LWParts39::Part(I);P.Transform=FTransform(FRotator(0,180,0),FVector(-30,20,10));G.Parts39.Add(P);}auto Laser=LWParts39::Part(LWItems::Make(TEXT("att_laser")));G.Parts39.Add(Laser);LWParts39::Derive(G);FString Error;TestTrue(TEXT("cross-family assembly with backwards launch tubes accepted"),LWParts39::Validate(G,Error));for(FName E:Effects)TestTrue(TEXT("all distinct legendary effects active"),LWMods::Effect(&G,E));TestEqual(TEXT("duplicate effects do not increase two shot"),LWMods::Shots(&G),2);TestTrue(TEXT("attachment detected"),LWMods::Has(&G,TEXT("att_laser")));TestTrue(TEXT("recoil free active"),LWMods::Recoil(&G)==0);const auto Barrels=LWParts39::Barrels(G);TestEqual(TEXT("every barrel contributes a muzzle"),Barrels.Num(),7);TestTrue(TEXT("backwards barrel faces backwards"),Barrels.Last().GetRotation().GetForwardVector().X<-.99);TArray<uint8> Bytes;{FMemoryWriter W(Bytes);FObjectAndNameAsStringProxyArchive A(W,false);A.ArIsSaveGame=true;FLWItemInstance::StaticStruct()->SerializeItem(A,&G,nullptr);}FLWItemInstance Loaded;{FMemoryReader R(Bytes);FObjectAndNameAsStringProxyArchive A(R,true);A.ArIsSaveGame=true;FLWItemInstance::StaticStruct()->SerializeItem(A,&Loaded,nullptr);}TestEqual(TEXT("save/load exact fingerprint"),LWParts39::Fingerprint({G}),LWParts39::Fingerprint({Loaded}));return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FLWPartsLoot39,"LethalWorld.Workbench.PartsInLoot",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FLWPartsLoot39::RunTest(const FString&){TStrongObjectPtr<ULWLootTable> T(NewObject<ULWLootTable>());TSet<FName> Found;bool Legendary=false;for(int i=0;i<3000;++i)for(const auto& I:T->Roll(TEXT("trader"),i,.9f))if(LWParts39::Find(I.Definition)){Found.Add(I.Definition);if(I.WeaponTier==4&&!I.LegendaryModifier.IsNone())Legendary=true;}TestEqual(TEXT("all 59 parts obtainable"),Found.Num(),59);TestTrue(TEXT("parts can roll legendary effects"),Legendary);return true;}
#endif
