"""Offline authored chapters 2–4. Uses the same narrative schema as the opening."""
import runpy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ns=runpy.run_path(str(ROOT/'Tools/author_campaign76_opening.py'))
D=ns['D'];D['cast'].clear();D['scenes'].clear();D['stages'].clear()
b,c,a,scene,stage,person=[ns[k] for k in ['b','c','a','scene','stage','person']]
for args in [('della','Della Voss',True),('hank','Hank Corwin'),('rook','Captain Elias Rook'),('imani','Sergeant Imani Bell',True),('tomas','Tomas Paredes'),('hannah','Hannah Pike',True),('orrin','Orrin Lake'),('simon','Simon Weller'),('ruth','Ruth Weller',True)]:person(*args)
scene('rome_intro',[
 b('della','If you are here for a ride, get in line. If you are here for Tomas, come here.'),
 b('della','That tag is ours. We loaded the sealed consignments. I did not see the people inside until the third run. Then the Directorate stopped letting my crews near their wagons.'),
 b('lena','The same dispatch number appears on my emergency ledger. You were being paid with diverted public stock.',needs=['!dead_lena']),
 b('della','Paid? They brought antibiotics. My crane operator was dying. I am not proud enough to call that easy.'),
 b('della','We need the terminal working to reach the northern station. Hank has the switch key. He wants his stranded cargo released before he puts his crew under another suspended load. Talk to him. Then lock the crane, drain the lift pit, and test the gate. In that order.')],next='rome_crew')
scene('hank_terms',[b('hank','The crate with the green strap belongs to three farms. Della has it under lien. They miss the planting window, we miss meals.'),b('della','They owe us two engine rebuilds. If debts vanish whenever someone needs the cargo, I cannot keep crews fed.')],[
 c('Release the farm cargo against a written labor schedule.','hank_shared',effects=['crew_ready','farm_schedule','trust_della+=1','freehold_supply+=1']),
 c('Pay the 80-credit lien. The cargo goes free.','hank_paid',needs=['credits>=80'],effects=['spend:80','crew_ready','freehold_supply+=1','trust_hank+=2']),
 c('Back Della: cargo remains until the debt is worked.','hank_lien',effects=['crew_ready','toll_debt','trust_della+=2','trust_hank-=2'])])
scene('hank_shared',[b('hank','I will put my name on the schedule. Put hers beside it. Nobody gets to pretend a signature only binds the poor.'),b('della','Fine. Two crews, three days. Here is the key.')],next='rome_repair')
scene('hank_paid',[b('della','Eighty clears it. You should have asked which of those farms can pay you back.'),b('hank','They can feed people. Some debts ought to stay that simple.')],next='rome_repair')
scene('hank_lien',[b('hank','Then I work. You can tell those farmers why.'),b('della','I will tell them myself. We keep a terminal or lose all three farms next winter.')],next='rome_repair')
scene('cargo_open',[b('hank','The lock is cut. That is clothing, not machine packing.'),b('','Among the bags: a water-board identification card for Tomas Paredes, a blue child\'s glove labeled LUIS, and a ring engraved R + S. The bags have processing tags. They were removed from travelers.'),b('della','I know two of those names. We are not selling this lot. Photograph the tags and put every bag back in its own sack.'),b('lena','The weights in my ledger make sense now. They called the belongings surplus, so nobody had to record a person losing them.',needs=['!dead_lena'])],next='rome_control')
scene('rome_vote',[b('della','Northbound freight can move again. The question is who signs a load out. One desk is quick. Three desks catch a mistake. Three desks can also spend a week arguing while medicine spoils.'),b('hank','A crew seat, a farm seat, her seat. Recorded tariffs. That is what I want.'),b('della','Or hand the keys to Corwin. He has asked often enough. He would open the gates and run out of spares before the thaw.')],[
 c('Della controls dispatch, with a public tariff ledger.','rome_della',effects=['canal_control=1','logistics=2','trust_della+=2','canal_prices=2']),
 c('Negotiate shared dispatch: crews, farms, and Della each hold a key.','rome_shared',needs=['farm_schedule'],effects=['canal_control=2','logistics=1','coalition+=1','canal_prices=1']),
 c('Give Hank and the cargo owners control. Remove the toll desk.','rome_hank',effects=['canal_control=3','logistics=1','trust_della-=3','canal_prices=0','spares_shortage'])])
scene('rome_della',[b('della','You will pay the published price like everyone else. But a medical wagon never waits behind luxury cargo. Write that first.'),b('hank','I will keep a second copy of the ledger. You can count on that.')],next='guard_arrive')
scene('rome_shared',[b('della','Hank takes nights. Farms appoint someone who can count. If this deadlocks, all three of us answer for it.'),b('hank','Fair. You have a seat at the table when it does, traveler. Not ownership of it.')],next='guard_arrive')
scene('rome_hank',[b('hank','Gate opens tonight. First run carries food, nobody pays to get their own blankets back.'),b('della','The spare parts will not arrive out of gratitude. Remember I said that when the winch stops.')],next='guard_arrive')
stage('rome_arrive','lockstock','rome','Lock, Stock','Meet Della Voss at the canal freight terminal.','della hank mara lena',arrival='rome_intro')
stage('rome_crew','lockstock','rome','Lock, Stock','Resolve the cargo lien with Hank and Della.','della hank mara lena',[a('talk_hank','Negotiate the stranded farm cargo',[-200,170,0],scene='hank_terms',mesh='')])
stage('rome_repair','lockstock','rome','Lock, Stock','Secure the crane, drain the pit, and restore the loading gate.','della hank',[
 a('crane_lock','Engage the crane maintenance lock',[-330,180,0],mesh='ControlPanel52',work=5,effects=['crane_locked'],needs=['!crane_locked']),
 a('pit_drain','Drain the lift pit',[290,170,0],mesh='Scrap52',work=6,effects=['pit_drained'],needs=['crane_locked','!pit_drained']),
 a('freight_gate','Test the freight gate under crew supervision',[0,300,0],mesh='RelayConsole52',work=5,effects=['terminal_working'],needs=['pit_drained'])],needs=['terminal_working'],next='rome_cargo')
stage('rome_cargo','watercarries','rome','What the Water Carries','Inspect the misdeclared processing shipment.','della hank lena',[a('tagged_bags','Open the misdeclared shipment',[220,50,0],scene='cargo_open',mesh='Crate',effects=['belongings_catalogued','evidence_belongings','journal:Tomas Paredes and the Wellers appear on Rome processing tags. Their belongings were removed before transfer.'])])
stage('rome_control','watercarries','rome','What the Water Carries','Resolve control of the reopened terminal.','della hank',[a('talk_della','Decide the dispatch arrangement',[0,150,0],scene='rome_vote',mesh='')])

scene('guard_intro',[b('rook','Captain Elias Rook. The ward is through there. Keep your voice down; they have finally slept.'),b('imani','We hold the supply corridor. It is why the clinic has oxygen. It is also why I need two more drivers than I have.'),b('rook','Directorate medicines keep this hospital open. They ask us to escort their transfers. You have questions about one. Help Imani check the next convoy. Stay with the patients, and do not let a rifle settle a paperwork dispute.')],next='guard_convoy')
scene('convoy_restraints',[b('tomas','Do not close that door. My hands are tied to the seat.'),b('imani','Driver, where is the medical restraint order? ...That is a cargo receipt.'),b('tomas','They said Elena and Luis were following. Nobody will tell me where they are.'),b('rook','I am halting the movement. Sergeant, check every transport. Nobody leaves until we know who authorized this.')],[
 c('Unfasten the restraint and move Tomas to the ward.','convoy_release',effects=['tomas_released','trust_imani+=2','evidence_restraints']),
 c('Keep the transport intact and copy the holding-facility route.','convoy_follow',effects=['transport_traced','evidence_restraints','trust_tomas-=1'])])
scene('convoy_release',[b('tomas','My ring is at home. Tell her that if she does not believe it is me.'),b('imani','I will book him as a patient under my own name. Whatever command thinks of that, it will have to say to me.')],next='guard_holding')
scene('convoy_follow',[b('tomas','You are letting them take me so you can follow? Then do not lose the road.'),b('imani','I copied the axle number. If the convoy turns off, you will know which one it is.')],next='guard_holding')
scene('holding_records',[b('','Transfer annex duty book: incoming families separated by trade category. Medical objections returned unsigned. Freight receipts use a presidential authentication series issued after September 2028.'),b('lena','This series was supposed to be retired. It proves someone can issue orders through that system. It does not prove who is alive.',needs=['!dead_lena']),b('imani','Rook saw the first restraint complaint six weeks ago. His initials are on the response: maintain escort pending clarification.')],next='guard_confront')
scene('rook_confront',[b('rook','I saw the complaint. I asked for clarification. They sent oxygen and another order. I kept the first and obeyed the second.'),b('imani','You could have stopped a transport. You stopped this one when there were witnesses.'),b('rook','Yes. Do not soften that for me. Tell me what you need changed now.')],[
 c('Work with him privately: release the annex detainees and cut Directorate escorts.','rook_private',effects=['guard_control=1','rook_cooperates','guard_support=2','coalition+=1']),
 c('Publish the signed complaint. Let the ward and guard elect new command.','rook_public',effects=['guard_control=2','imani_leads','guard_support=1','evidence_public','trust_rook-=2']),
 c('Conceal the complaint in exchange for continued access.','rook_conceal',effects=['guard_control=3','directorate_access','guard_support=0','leverage+=1'])])
scene('rook_private',[b('rook','I will sign the release in front of the ward. Private does not mean invisible.'),b('imani','I will verify the cells myself. Cooperation is useful. Forgiveness can wait.')],next='hill_arrive')
scene('rook_public',[b('imani','The vote is for me. I wanted a shift change, not a command. First order: no transfer without the traveler\'s consent recorded by someone outside the escort.'),b('rook','I will turn over the route codes. You do not have to keep me to use them.')],next='hill_arrive')
scene('rook_conceal',[b('rook','Access is not absolution. I know what you are holding.'),b('imani','The book did not vanish because you closed it. I kept the names of the people still there.')],next='hill_arrive')
stage('guard_arrive','escort','guard','Escort Duty','Meet Rook and Imani at the functioning corridor hospital.','rook imani mara',arrival='guard_intro')
stage('guard_convoy','escort','guard','Escort Duty','Inspect the waiting transport and its patient manifest.','rook imani tomas',[a('convoy_manifest','Check the restraint order',[230,100,0],scene='convoy_restraints',mesh='Dossier52')])
stage('guard_holding','transit','holding','Missing in Transit','Enter the transfer annex and recover its duty book.','imani lena',[
 a('annex_release','Release the detained travelers',[-260,160,0],mesh='Keys52',work=3,effects=['annex_released','civilian_rescues+=2'],needs=['!annex_released']),
 a('annex_book','Copy the signed duty book',[260,160,0],scene='holding_records',effects=['evidence_authentication'])])
stage('guard_confront','orders','guard','Orders from Above','Confront Rook with the annex duty book.','rook imani',[a('talk_rook','Confront Rook',[0,150,0],scene='rook_confront',mesh='')])

scene('hill_weather',[b('hannah','Shut the outer door behind you. Wind is coming straight through.'),b('mara','We heard a distress call on the approach. Same words, every forty seconds.',needs=['!dead_mara']),b('hannah','A recording can still mean trouble. Look before you take the cut-through. Fresh tire ruts go in. None come out. Whoever is calling has not asked once about the weather.'),b('hannah','Take the maintenance shelter first. Dry socks, a fire, someone checking the roof. Then decide which road deserves your life.')],next='hill_beacon')
scene('beacon_observe',[b('','From the maintenance overlook, the antenna cable runs to a vehicle battery behind the cut-through. Two lookouts trade positions each time the recorded call begins.'),b('hannah','There. You can disconnect the aerial from this side without putting anyone in that lane. Or warn the next travelers. A fight is an option, not an obligation.')],[
 c('Disconnect the beacon and mark the safe detour.','beacon_safe',effects=['beacon_disabled','trust_hannah+=2','wilderness_routes']),
 c('Broadcast a warning, leaving the ambushers exposed.','beacon_warn',needs=['comms'],effects=['beacon_warning','wilderness_routes','communications_restored']),
 c('Drive the ambushers away and open the direct road.','',stage='hill_fight',effects=['beacon_fight'])])
scene('beacon_safe',[b('hannah','A quiet road is a result. You do not have to fill it with bodies to prove you did something.')],next='freehold_arrive')
scene('beacon_warn',[b('hannah','I hear the road watch repeating you. Good. Let the lie travel slower than the warning for once.')],next='freehold_arrive')
scene('freehold_table',[b('orrin','Forty sacks until thaw. Twenty-three mouths already. You bring nine more, you have thirty-two people hungry later.'),b('hannah','And nine people dead now if I close the door. They have a welder, a midwife, and seven people who should not need a useful job to be let inside.'),b('mara','We can count both the food and the people. Neither number becomes kinder if we stop saying it.',needs=['!dead_mara']),b('hannah','The canal farms can cover some of the difference if their shipment got through. Otherwise, we need a ration agreement or somewhere else warm enough to go.')],[
 c('Bring in all nine; use the released canal farm shipment.','freehold_supply',needs=['freehold_supply'],effects=['freehold_refuge=2','coalition+=1','trust_hannah+=2','winter_food=2']),
 c('Share the winter ration and convert the reserved lodging into a refuge.','freehold_ration',effects=['freehold_refuge=1','coalition+=1','trust_hannah+=1','winter_food=1']),
 c('Arrange guarded onward travel instead of permanent admission.','freehold_travel',effects=['freehold_refuge=3','civilian_rescues+=1','trust_hannah-=1'])])
scene('freehold_supply',[b('orrin','I saw the sacks. That changes the arithmetic. It does not make me glad I said no.'),b('hannah','You can help me move the spare beds. Let them hear the answer from both of us.')],next='witness_arrive')
scene('freehold_ration',[b('orrin','Everyone cuts back. Including the people making the speech.'),b('hannah','Including me. The reserved rooms become family rooms. We will need the boarded windows sealed before nightfall.')],next='freehold_refuge')
scene('freehold_travel',[b('hannah','I will take them to the next shelter. I will remember why I had to. Keep a lamp on until we have all come back.')],next='witness_arrive')
scene('weller_intro',[b('simon','I maintained command links. I did not choose targets. I tell myself that a lot.'),b('ruth','Tell them the other part. The part you say in your sleep.'),b('simon','An authenticated order after the news said Richardson was dead. An instruction to preserve continuity personnel and deny a surrender channel. I heard it. I kept the acknowledgement tape.'),b('simon','I am not leaving Ruth and the children. They hid me when an old colleague came asking. Do not offer me safety that makes them pay for it.')],[
 c('Travel together. I will put the whole family on the evacuation request.','weller_travel',effects=['witness_travels','witness_family','testimony','trust_simon+=2']),
 c('Record the testimony and leave the family at the sheltered Freehold.','weller_tape',needs=['freehold_refuge>=1'],effects=['testimony','witness_sheltered','witness_family']),
 c('Hand Simon to the Directorate in exchange for access.','weller_warning')])
scene('weller_travel',[b('ruth','Then help me pack enough food for all of us. We are not a document with feet.'),b('simon','The tape is in the labeled tin. I will carry it myself until we meet whoever is receiving us.')],next='watertown_arrive')
scene('weller_tape',[b('simon','I will give you the recording and a signed account. If anyone can get a message back, tell me what the outside records say. I need to know which parts I remember correctly.')],next='watertown_arrive')
scene('weller_warning',[b('ruth','He trusted you because Hannah sent you. If you hand him over, the rest of us cannot stay here. Understand that before you say another word.')],[c('Confirm the surrender. This betrays Simon and exposes his family.','weller_surrender',effects=['witness_surrendered','directorate_access','trust_hannah-=4','civilian_harm+=2','testimony=0']),c('Withdraw the threat.','weller_intro')])
scene('weller_surrender',[b('simon','There is a duplicate acknowledgement at the hospital archive. I am telling you that because someone ought to use it. It is not forgiveness.'),b('ruth','Look at me. Do not watch the door while I am talking to you. You know what you are doing.',gesture='stop',pause=1.5)],next='watertown_arrive')
stage('hill_arrive','wrongturn','tughill','Wrong Turn','Reach the Tug Hill maintenance shelter before following the distress call.','hannah mara',arrival='hill_weather')
stage('hill_beacon','wrongturn','tughill','Wrong Turn','Watch the cut-through before approaching the repeated distress call.','hannah',[
 a('dry_shelter','Seal the shelter draft and warm the traveling group',[-260,170,0],mesh='Scrap52',work=7,effects=['shelter_prepared'],needs=['!shelter_prepared']),
 a('observe_beacon','Observe the distress-beacon approach',[320,-280,0],scene='beacon_observe',mesh='Keys52',work=4)])
stage('hill_fight','wrongturn','tughill','Wrong Turn','Clear the ambush approach, then disable its transmitter.','hannah',[a('silence_beacon','Disconnect the false distress beacon',[320,-280,0],next='freehold_arrive',mesh='RelayConsole52',needs=['enemies_clear'],effects=['beacon_disabled'])],enemies=4)
stage('freehold_arrive','table','freehold','A Place at the Table','Join the winter ration meeting.','hannah orrin mara',arrival='freehold_table')
stage('freehold_refuge','table','freehold','A Place at the Table','Make the reserved lodging habitable for the incoming families.','hannah orrin',[
 a('refuge_window','Seal the winter-room window',[-300,170,0],mesh='Scrap52',work=6,effects=['refuge_sealed'],needs=['!refuge_sealed']),
 a('refuge_beds','Prepare the spare bedding',[280,170,0],next='witness_arrive',mesh='MedicalCase52',work=4,needs=['refuge_sealed'],effects=['refuge_ready'])])
stage('witness_arrive','heardit','witness','The Man Who Heard It','Speak to Simon and Ruth Weller at the sheltered cabin.','simon ruth hannah mara',arrival='weller_intro')
(ROOT/'Data/Campaign76/02_Canal_Guard_Freeholds.json').write_text(json.dumps(D,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
