"""Build bounded per-POI soft-reference bundles from assets used by the native builders."""
from pathlib import Path
import re
r=Path(__file__).resolve().parents[1];src=r/'Source/LethalWorld'
assets={}
for folder in ['Content/Art/Meshes','Content/Art/Models63','Content/Art/Interiors65','Content/Materials']:
 for p in (r/folder).glob('*.uasset'):
  key=p.stem.removeprefix('SM_').removeprefix('M_')
  assets[key]='/Game/'+str(p.relative_to(r/'Content').with_suffix('')).replace('\\','/')+'.'+p.stem
assets['Cube']='/Game/Art/Meshes/SM_UnitCube.SM_UnitCube'
assets['Sphere']='/Engine/BasicShapes/Sphere.Sphere';assets['Cylinder']='/Engine/BasicShapes/Cylinder.Cylinder'
def collect(files):
 out=set()
 for f in files:
  text=(src/f).read_text(encoding='utf-8-sig')
  for name in re.findall(r'TEXT\("([A-Za-z0-9_]+)"\)',text):
   if name in assets:out.add(assets[name])
 return out
base=collect(['LWWorld.cpp','LWRoadBuilding33.cpp','LWUrban.cpp','LWWorldObject.cpp','LWEnemies.cpp','LWZombie.cpp','LWVehicleSpec.h','LWVehicle.cpp','LWVehicleDetail42.cpp','LWLuxuryRV66.cpp','LWCamper.cpp','LWElectric74.cpp','LWWeather.cpp','LWAviationSky84.cpp','LWVehicleExplosion68.cpp'])
base.update(path for name,path in assets.items() if '/Models63/' in path or name.startswith('Vehicle42_') or name.endswith('42'))
common=collect(['LWPOI.cpp','LWInteriors65.cpp','LWFurniture.cpp','LWResident.cpp','LWPOISurvivors.cpp'])
# Character submeshes are assembled from suffixes, so add their small revised mesh bundle explicitly.
common.update(path for name,path in assets.items() if name.endswith('32') and any(x in name for x in ['Resident','Zombie','Raider']))
groups={0:base,1:common,2:collect(['LWCanadaBuilding68.cpp','LWBorder51.cpp','LWBorderGuard51.cpp'])|common}
files={69:['LWNewYorkBuildings69.cpp','LWDestiny71.cpp','LWSyracuseBuildings73.cpp'],21:['LWCasino.cpp'],32:['LWLandmarkBuilding.cpp','LWExpansion57.cpp','LWAirfields84.cpp','LWAircraftCabin84.cpp'],20:['LWUrban.cpp'],5:['LWPOIV18.cpp'],22:['LWDungeonBuilding.cpp','LWDungeon.h'],33:['LWLandmarkBuilding.cpp'],53:['LWUnderground.cpp','LWDungeonBuilding.cpp','LWDungeon.h'],58:['LWPOIExpansion.cpp','LWShoppingMall65.cpp'],64:['LWExpansion57.cpp']}
for typ,names in files.items():groups[typ]=common|collect([n for n in names if (src/n).exists()])
lines=['// Generated by Tools/build_stream_assets68.py; these are soft references, not permanent loads.','static void AddWarmBundle68(int Group,TSet<FSoftObjectPath>& Out){',' switch(Group){']
for group,paths in groups.items():
 lines+=[' case '+str(group)+':']
 lines+=['  Out.Add(FSoftObjectPath(TEXT("'+p+'")));' for p in sorted(paths)]
 lines+=['  break;']
lines+=[' }','}']
(src/'LWStreamAssets68.inl').write_text('\n'.join(lines)+'\n')
print({k:len(v) for k,v in groups.items()})
