"""Compile authored campaign data into native tables. No runtime file/network IO.
Author-only material lives in Docs/Campaign76 and is never included by this tool.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def text(s):return 'TEXT('+json.dumps(str(s),ensure_ascii=True)+')'
def arr(values):return '{'+','.join(text(x) for x in values)+'}'
def vec(v):return 'FVector('+','.join(str(float(n)) for n in v)+')'
def scalar(v):return str(float(v))+'f'
def build():
    data={'stages':[],'scenes':[],'cast':[]}
    for path in sorted((ROOT/'Data/Campaign76').glob('*.json')):
        d=json.loads(path.read_text(encoding='utf-8'))
        for k in data:data[k]+=d.get(k,[])
    for kind in data:
        ids=[x['id'] for x in data[kind]];assert len(ids)==len(set(ids)),('duplicate',kind)
    stages={s['id'] for s in data['stages']};scenes={s['id'] for s in data['scenes']};people={p['id'] for p in data['cast']}
    def ref(v,pool):assert not v or v in pool,('missing reference',v)
    # Check the combined graph, including conversations that continue into other
    # conversations. A valid individual JSON file is not enough for a campaign.
    stage_by={s['id']:s for s in data['stages']};scene_by={s['id']:s for s in data['scenes']}
    reached=set();read=set()
    def walk_stage(id):
        if not id or id in reached:return
        ref(id,stages);reached.add(id);s=stage_by[id]
        walk_stage(s.get('next'));walk_scene(s.get('arrival'))
        for a in s['actions']:walk_stage(a.get('next'));walk_scene(a.get('scene'))
    def walk_scene(id):
        if not id or id in read:return
        ref(id,scenes);read.add(id);s=scene_by[id];walk_stage(s.get('next'))
        for c in s['choices']:walk_stage(c.get('stage'));walk_scene(c.get('next'))
    walk_stage('bell_lights')
    assert reached==stages,('unreachable stages',sorted(stages-reached))
    assert read==scenes,('unreachable scenes',sorted(scenes-read))
    out=['// Generated by Tools/campaign76.py. Edit Data/Campaign76/*.json.']
    out+=['const TArray<FLWC76Person>& LWCampaign76::Cast(){static const TArray<FLWC76Person> D={']
    for p in data['cast']:out+=['{'+','.join([text(p['id']),text(p['name']),str(p.get('female',False)).lower(),text(p['voice'])])+'},']
    out+=['};return D;}','const TArray<FLWC76Scene>& LWCampaign76::Scenes(){static const TArray<FLWC76Scene> D=[](){TArray<FLWC76Scene> V;']
    for s in data['scenes']:
        ref(s.get('next',''),stages);out+=['{FLWC76Scene S;S.Id='+text(s['id'])+';S.Next='+text(s.get('next',''))+';']
        for b in s.get('beats',[]):
            ref(b.get('who',''),people)
            out+=['S.Beats.Add({'+','.join([text(b.get('who','')),text(b['text']),arr(b.get('needs',[])),text(b.get('gesture','')),text(b.get('cue','')),vec(b.get('move',[0,0,0])),scalar(b.get('pause',0))])+'});']
        for c in s.get('choices',[]):
            ref(c.get('next',''),scenes);ref(c.get('stage',''),stages)
            out+=['S.Choices.Add({'+','.join([text(c['text']),text(c.get('next','')),text(c.get('stage','')),arr(c.get('needs',[])),arr(c.get('effects',[]))])+'});']
        out+=['V.Add(MoveTemp(S));}']
    out+=['return V;}();return D;}','const TArray<FLWC76Stage>& LWCampaign76::Stages(){static const TArray<FLWC76Stage> D=[](){TArray<FLWC76Stage> V;']
    for s in data['stages']:
        ref(s.get('arrival',''),scenes);ref(s.get('next',''),stages)
        for p in s.get('cast',[]):ref(p,people)
        out+=['{FLWC76Stage S;S.Id='+text(s['id'])+';S.Mission='+text(s['mission'])+';S.Site='+text(s['site'])+';S.Title='+text(s['title'])+';S.Goal='+text(s['goal'])+';S.Cast='+arr(s.get('cast',[]))+';S.Arrival='+text(s.get('arrival',''))+';S.Next='+text(s.get('next',''))+';S.Needs='+arr(s.get('needs',[]))+';S.Enemies='+str(s.get('enemies',0))+';S.Duration='+str(float(s.get('duration',0)))+';']
        for a in s.get('actions',[]):
            ref(a.get('scene',''),scenes);ref(a.get('next',''),stages)
            out+=['S.Actions.Add({'+','.join([text(a['id']),text(a.get('scene','')),text(a.get('next','')),text(a['label']),text(a.get('mesh','Dossier52')),vec(a.get('at',[0,0,0])),arr(a.get('needs',[])),arr(a.get('effects',[])),str(float(a.get('work',0)))])+'});']
        out+=['V.Add(MoveTemp(S));}']
    out+=['return V;}();return D;}']
    (ROOT/'Source/LethalWorld/LWCampaign76Data.inl').write_text('\n'.join(out)+'\n',encoding='utf-8')
    print('CAMPAIGN76',len(stages),'stages',len(scenes),'scenes',sum(len(s.get('beats',[])) for s in data['scenes']),'dialogue beats',len(people),'characters')
if __name__=='__main__':
    import sys,runpy
    if '--author' in sys.argv:
        for name in ['opening','north','canada','return','finale']:
            runpy.run_path(str(ROOT/f'Tools/author_campaign76_{name}.py'))
        runpy.run_path(str(ROOT/'Tools/refine_campaign76.py'))
        runpy.run_path(str(ROOT/'Tools/author_campaign77.py'))
        runpy.run_path(str(ROOT/'Tools/campaign76_roads.py'))
    build()
