"""Single source for the 50 part definitions, compiled fallback catalog and mesh authoring."""
import json
from pathlib import Path
r=Path(__file__).resolve().parents[1]
weapons=['crowbar','bat','shotgun','revolver','sniper','smg','rifle','lmg','doublebarrel','missile_launcher','minigun','sawedoff','desert_eagle','m4','taser','flamethrower']
names=['Crowbar hook','Bat striking head','Pump shotgun action','.357 revolver frame','Sniper receiver','SMG receiver','Combat rifle receiver','LMG receiver','Double-barrel action','Missile launcher chassis','Minigun drive unit','Sawed-off action','.50 pistol frame','M4 receiver','Taser power module','Flamethrower valve body']
parts=[]
def add(id,name,group,size,weapon='',damage=0,handling=0,speed=0,price=45,muzzle=(0,0,0)):
 parts.append(dict(id=id,name=name,group=group,mesh='WP39_'+id.removeprefix('part_'),size=size,weapon=weapon,damage=damage,handling=handling,speed=speed,price=price,muzzle=muzzle))
for i,(w,name) in enumerate(zip(weapons,names)):
 add(f'part_action_{i:02}',name,'Action',[32 if i>=2 else 38,10 if i in [7,9,10,15] else 7,10],w,.015,0,0,70+i*8)
barrels=['Pump barrel and fore-end','.357 barrel','Precision rifle barrel','SMG barrel shroud','Combat rifle gas barrel','LMG heavy barrel','Twin shotgun barrels','Launch tube','Six-barrel rotor','Short twin barrels','.50 pistol barrel','M4 gas barrel','Taser electrodes','Flame nozzle']
lengths=[60,20,75,28,48,64,58,68,70,26,16,48,14,58]
for i,(name,length) in enumerate(zip(barrels,lengths),2):add(f'part_barrel_{i:02}',name,'Barrel',[length,10 if i in [8,9,10,11] else 6,8],damage=.035 if i in [4,7,9,10] else .02,handling=.015 if i==4 else 0,price=50+i*5,muzzle=(length,0,0))
for i,name in enumerate(['Adjustable carbine stock','Fixed rifle stock','Folding skeleton stock','Padded survival stock','Pump shotgun stock','Walnut break-action stock','Precision cheek-rest stock','Heavy support stock']):add(f'part_stock_{i:02}',name,'Stock',[32,8,14],handling=.025+i*.002,speed=-.004 if i==7 else .005,price=35+i*4)
for i,name in enumerate(['Ribbed pistol grip','Revolver walnut grip','Angled shoulder grip','Large pistol grip','Steel crowbar handle','Wrapped bat handle']):add(f'part_grip_{i:02}',name,'Grip',[10,6,18] if i<4 else [30,4,4],handling=.025,speed=.008,price=24+i*3)
for i,name in enumerate(['Tubular feed assembly','Six-chamber cylinder','Detachable-magazine well','Break-action hinge','Belt feed and cover','Sealed pressure coupling']):add(f'part_feed_{i:02}',name,'Feed',[18,9,11],speed=.025,price=40+i*7)
assert len(parts)==50
(r/'Data/WeaponParts39.json').write_text(json.dumps(parts,indent=2))
def text(s):return 'TEXT('+json.dumps(s)+')'
def vec(a):return 'FVector('+','.join(str(x) for x in a)+')'
lines=['// Generated by Tools/define_weapon_parts39.py. Source: Data/WeaponParts39.json.']
for p in parts:lines.append('Out.Add({'+','.join([text(p['id']),text(p['name']),text(p['group']),text(p['mesh']),text(p['weapon']),vec(p['size']),vec(p['muzzle']),str(p['damage'])+'f',str(p['handling'])+'f',str(p['speed'])+'f',str(p['price'])])+'});')
(r/'Source/LethalWorld/LWPartDefinitions39.inl').write_text('\n'.join(lines).replace(',0f',',0.f')+'\n')
