"""Build the complete spoken script, immutable casting, and native chatter pools.

This step is offline. Paid generation is a separate command with a hard ledger cap.
The old six profiles/recordings remain intact; the budgeted general cast uses four
new voices. Named legacy-story casting is retained without re-enabling that story.
"""
import json, re, hashlib
from pathlib import Path
import dialogue59 as d

SRC = d.ROOT / 'Source/LethalWorld'
DATA = d.ROOT / 'Data/Dialogue75.json'
def strings(code):
    return [json.loads('"'+s+'"') for s in re.findall(r'TEXT\("((?:[^"\\]|\\.)*)"\)', code)]
def source(name): return (SRC/name).read_text(encoding='utf-8-sig')
def story_id(name):
    for n in ('mara','inez','elsie','voss','tessa','jonah','tomas','rusk','mercer'):
        if n in name.lower(): return 'story_'+n
    if 'collector' in name.lower(): return 'choir_collector'
    if 'sergeant' in name.lower(): return 'heroes_sergeant'
    return 'narrator'

def build():
    reg=d.registry()
    additions=[('M04','Eric','cjVigY5qzO86Huf0OWal',False),
               ('F04','Matilda','XrExE9yKIg1WjnnlVkGX',True),
               ('M05','Bill','pqHfZKP75CvOlQylNhV4',False),
               ('F05','Alice','Xb7hH8MSUJpSbSDYk0k2',True)]
    for ident,name,voice,female in additions:
        p={'id':ident,'name':name,'voice_id':voice,'female':female,
           'model_id':'eleven_flash_v2_5', 'voice_settings':{
           'stability':.55,'similarity_boost':.8,'style':0,'use_speaker_boost':True,'speed':1.0}}
        old=next((v for v in reg['profiles'] if v['id']==ident),None)
        if old: assert old==p, 'Never overwrite a published voice profile'
        else: reg['profiles'].append(p)
    reg['assignment_version']=2
    reg['active_procedural_profiles']=['M04','M05','F04','F05']
    reg['procedural_replacements']={'M01':'M04','M02':'M05','M03':'M04','F01':'F04','F02':'F05','F03':'F04'}
    reg['cast'].update(choir_collector='M03',heroes_sergeant='M01')
    d.save(d.REG,reg)
    groups=json.loads(DATA.read_text(encoding='utf-8'))['groups']
    native=['// Generated by Tools/dialogue75.py from Data/Dialogue75.json.']
    for group,lines in groups.items():
        for text in lines:
            ident=group+'_'+hashlib.md5(d.normalize(text).encode()).hexdigest()[:12]
            native.append('{TEXT('+json.dumps(ident)+'),TEXT('+json.dumps(group)+'),TEXT('+json.dumps(text)+')},')
    (SRC/'LWDialogue75Defaults.inl').write_text('\n'.join(native)+'\n',encoding='utf-8')
    shared={t for lines in groups.values() for t in lines}
    shared.update(r['text'] for r in json.loads((d.OUT/'starter.json').read_text())['lines'])
    shared.update(e['intro'] for e in json.loads((d.ROOT/'Data/Encounters.json').read_text()))
    # These are speech assignments only, not dialogue buttons, item names or HUD prose.
    for name in ('LWPlayerRPG.cpp','LWCanada68.cpp'):
        for m in re.finditer(r'DialogueText=(TEXT\("(?:[^"\\]|\\.)*"\))',source(name)):
            shared.update(strings(m[1]))
    for m in re.finditer(r'Quest\((TEXT\("[^"\n]*"\),TEXT\("[^"\n]*"\),TEXT\("[^"\n]*"\))',source('LWRPG.cpp')):
        shared.add(strings(m[1])[2])
    # Explicit voiced counterparts for changing settlement and quest UI values.
    for name in ('LWSettlementLife.cpp','LWEncounterScene.cpp'):
        for m in re.finditer(r'->Say\((TEXT\("(?:[^"\\]|\\.)*"\))\)',source(name)):
            shared.update(strings(m[1]))
    shared.update([
        'Let us go over the settlement accounts.',
        'Who would you like to station here?',
        'Leave your goods with us. Collect the proceeds when they sell.'
    ])
    rows={}
    oldrows={r['key']:r for r in json.loads((d.OUT/'starter.json').read_text())['lines']}
    def add(profile,text):
        text=d.normalize(text)
        if not text or text=='...static...': return
        k=d.line_key(profile,text)
        rows[k]=oldrows.get(k,{'key':k,'profile':profile,'text':text,'file':k+'.wav'})
    for profile in reg['active_procedural_profiles']:
        for text in sorted(shared): add(profile,text)
    # Preserve cast identities for retained (currently disabled) chapter scenes.
    for line in source('LWStoryScenes.cpp').splitlines():
        if 'Shot(TEXT(' in line:
            who,text=strings(line)[:2]; add(reg['cast'][story_id(who)],text)
    s=source('LWStory.cpp')
    speech=next(line for line in s.splitlines() if 'Speech=A==TEXT("mara")?' in line)
    speechtexts=[t for t in strings(speech) if len(t)>50]
    for profile,text in zip(('F01','M01','F02','F01'),speechtexts): add(profile,text)
    follow='The roads still connect the towns. What has broken is trust. Follow the evidence, keep supplies in reserve, and don\'t confuse a uniform with a promise.'
    for p in ('F01','M01','F02'): add(p,follow)
    add('F01','Thank you. The trauma supplies are in the pharmacy. The raiders left their paperwork there, too.')
    add('F03','Give up your weapons. Come with us. Now.')
    manifest={'schema':1,'lines':list(rows.values())}
    d.save(d.OUT/'complete75.json',manifest)
    ledger=json.loads((d.OUT/'usage.json').read_text())
    remaining=[r for r in rows.values() if ledger.get(r['key'],{}).get('state')!='complete']
    report={'shared_texts':len(shared),'new_companion_lines':sum(len(v) for k,v in groups.items() if k.startswith('companion_')),
            'new_settler_lines':sum(len(v) for k,v in groups.items() if k.startswith('settler_')),
            'new_raider_lines':sum(len(v) for k,v in groups.items() if k.startswith('raider_')),
            'clips':len(rows),'remaining_clips':len(remaining),'remaining_characters':sum(len(r['text']) for r in remaining),
            'estimated_flash_credits':sum((len(r['text'])+1)//2 for r in remaining),'credit_cap':15000}
    d.save(d.ROOT/'Saved/Dialogue75Plan.json',report)
    print(json.dumps(report,indent=2))
if __name__=='__main__': build()
