from pathlib import Path
r=Path('Source/LethalWorld')
def e(n,a,b):
 p=r/n;s=p.read_text();assert a in s,(n,a);p.write_text(s.replace(a,b))
e('LWStory.cpp','People.FindRef(TEXT("story_mara").Get())','People.FindRef(TEXT("story_mara")).Get()')
e('LWStory.cpp','ClearActors(bool All){Transport=nullptr;Fire.Empty();','ClearActors(bool All){if(Transport)Transport->DestroyComponent();Transport=nullptr;for(auto& F:Fire)if(F)F->DestroyComponent();Fire.Empty();')
e('LWStory.cpp','S==0||S==20||S==27','S==0||S==20||S==26||S==27')
e('LWStoryScenes.cpp',' }else if(S==27){',' }else if(S==26){\n  Shot(TEXT("Director Elias Mercer"),TEXT("I gave these people a country when all you offered was a campfire. A nation needs one voice, one will, and someone prepared to punish disobedience."),FVector(-600,-600,240),FVector(-400,-400,200),FVector(0,100,150),10);\n  Shot(TEXT("Mara"),TEXT("You put children in cells and called it a census. We are done asking permission to exist."),FVector(400,-2800,180),FVector(200,-2700,170),FVector(-250,-2350,145),8);\n  Shot(TEXT("Director Mercer"),TEXT("Then let history record your choice. Seal the court. Fire on anyone who stands with them."),FVector(0,-500,180),FVector(0,-300,180),FVector(0,100,150),8);\n }else if(S==27){')
e('LWStoryScenes.cpp','if(S==-3){RestorePrison();Player->SaveProgress();return;}Advance();','if(S==-3){RestorePrison();Player->SaveProgress();return;}if(S==26){for(auto& E:Enemies)if(IsValid(E))E->SetActorTickEnabled(true);Player->SaveProgress();return;}Advance();')
e('LWStoryScenes.cpp',' const int Area=',' for(auto& E:Enemies)if(IsValid(E))E->SetActorTickEnabled(false);\n const int Area=')
e('LWStoryScenes.cpp','  State().Flags.Add(TEXT("mercy_burned"));','  State().Flags.Add(TEXT("mercy_burned"));\n  Transport=NewObject<UStaticMeshComponent>(this);Transport->SetupAttachment(RootComponent);Transport->SetStaticMesh(World->Mesh(TEXT("Vehicle_boxtruck_V9")));Transport->SetWorldLocation(Base+FVector(-250,-2050,35));Transport->SetCollisionEnabled(ECollisionEnabled::NoCollision);Transport->RegisterComponent();\n  for(int K=0;K<10;K++){auto* F=NewObject<UStaticMeshComponent>(this);F->SetupAttachment(RootComponent);F->SetStaticMesh(World->Mesh(TEXT("IntroFlameV15")));F->SetMaterial(0,World->Material(TEXT("IntroFire")));F->SetWorldLocation(Base+FVector((K%2?1:-1)*2300,-700+(K/2)*650,90));F->SetWorldScale3D(FVector(2,2,4));F->SetCollisionEnabled(ECollisionEnabled::NoCollision);F->RegisterComponent();Fire.Add(F);}\n  World->Sound(TEXT("FuelExplosion"),Base+FVector(2200,0,50),.55f);')
e('LWSpawnTable.cpp','if(IsSafePosition(At)||Player&&','if(LWStory::Reserved(FVector2D(At))||IsSafePosition(At)||Player&&')
# Story POI discovery markers use known names and remain hidden until visited.
e('LWMapHUD.cpp','        DrawRoute(HUD, View, P, Mini);','        for(int StoryIndex=0;StoryIndex<9;StoryIndex++){int64 Id=0xEF320000u+StoryIndex;if(!P.RPG.KnownPlaces.Contains(Id))continue;FVector2D Point=View.Plot(LWStory::Site(StoryIndex));if(!View.Bounds.Contains(Point,10))continue;HUD.Rect(Point.X-5,Point.Y-5,10,10,Amber);if(!Mini&&HasMouse&&(Point-Mouse).Size()<20)Hover=LWStory::SiteName(StoryIndex);}\n        DrawRoute(HUD, View, P, Mini);')
# Map click snaps chapter icons to their real entrances.
e('LWMapHUD.cpp','for(const auto& Site:S)if(P->RPG.KnownPlaces','for(int StoryIndex=0;StoryIndex<9;StoryIndex++)if(P->RPG.KnownPlaces.Contains(int64(0xEF320000u+StoryIndex))&&(View.Plot(LWStory::Site(StoryIndex))-Mouse).Size()<18)Goal=FVector2D(P->RPG.KnownPlaces[int64(0xEF320000u+StoryIndex)]);\n            for(const auto& Site:S)if(P->RPG.KnownPlaces')
